### ISSUE TITLE
Clipboard history doesn't work

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#100]
The title, basically. `clipman pick --tool "wofi" --max-items=30 --histpath="~/.local/share/clipman.json"`, a bind declared in /etc/sway/definitions (which is against convention probably? Shouldn't it be in /etc/sway/modes/default?), doesn't work properly because:
1. clipman isn't installed by default in the OS
2. Even if it is installed, as far as I understand there is no exec to watch for clipboard history, because the abeforementioned command says `nothing to show: no data available`.
3. I'm preparing a PR to switch to lbonn's rofi fork to switch from wofi, and because this bind uses wofi and also doesn't work anyway.

It's a question on whether to fix (move it to modes, add exec to store clipboard history, make it work with rofi's fork, though it probably will be a part of my PR), or to delete it completely and maybe reimplement it later

**Comment by boredland** [comment]
in favor of removing first.
