### ISSUE TITLE
If on Manjaro Testing Branch or error while loading shared libraries: libdate-tz.so.2.4.1

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#101]
If you are on the testing branch you will find that waybar will crash every time your screen turns off for any reason.  To fix this you need to replace waybar with waybar-git from the AUR.  

For more info: https://github.com/Alexays/Waybar/issues/1158

**Comment by Mathew-D** [comment]
It seems they are also removing the bluetooth module from waybar.

**Comment by boredland** [comment]
> need to install the git version manually and remove /usr/bin/waybar

As I see it, waybar-git has a provides for waybar. In my opinion that should make it solve the "waybar" dependency of the settings package. So it should allow you to replace one by the other and due to waybar-git conflicting waybar, it should be even forcing you to..

**Comment by Mathew-D** [comment]
I though it would too but as soon as I tried to install waybar-git pamac said I had to uninstalled waybar and desktop-setting-sway.  It seems to work now though.

**Comment by boredland** [comment]
very strange.. pacman works in mysterious ways

**Comment by Mathew-D** [comment]
I would not upgrade chrono-date to 3.0.1-1 as it seems to break waybar even the git version.  I had to downgrade to 3.0.0-2 and use the git version.

**Comment by Mathew-D** [comment]
fixxed
