### ISSUE TITLE
Add/Remote and firefox error

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#102]
When you click on a link in the Add/Remove Software app from manjaro it says Firefox is not responding and will not open the link.  If we add MOZ_DBUS_REMOTE=1  to /etc/environment it fixes the error.

Here is more info:  https://mastransky.wordpress.com/2020/03/16/wayland-x11-how-to-run-firefox-in-mixed-environment/
I know it says put it in: ~/.bashrc  but I am not sure sway reads that.

**Comment by boredland** [comment]
> but I am not sure sway reads that

Relatively sure it doesn't

**Comment by Mathew-D** [comment]
That is why I put mine in /etc/environment and it fixed the error.

**Comment by boredland** [comment]
But.. does sway even need to read it? You can try and add it to .profile (https://www.github.com/Manjaro-Sway/desktop-settings/tree/sway/community%2Fsway%2Fetc%2Fskel%2F.profile) - I'd be surprised if that wasn't enough.

**Comment by Mathew-D** [comment]
I still get the error when I take it out of the /etc/environment I just checked. If I go into terminal and from run printenv MOZ_DBUS_REMOTE=1 shows up but I still get the error when I click on a link in Add / Remove from wofi

**Comment by boredland** [comment]
That's sad, and puts in question some other variables we have in .profile :-D

**Comment by Mathew-D** [comment]
When I switch to rofi it doesn't error.  It seems wofi doesn't run them but with rofi using foot it works fine.

**Comment by boredland** [comment]
`~/.config/environment.d/*.conf` could be a better place to put stuff then.
 https://www.freedesktop.org/software/systemd/man/environment.d.html

**Comment by boredland** [comment]
so should we add it to .profile then? or environment?

**Comment by Mathew-D** [comment]
With the switch to foot and rofi the .profile should be fine.
