### ISSUE TITLE
Script that can be removed

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#103]
In /usr/share/sway/scripts  we don't need:
autoname-workspaces.py  as we are using sworkstyle
I don't think we use:
inactive-windows-transparency.py  and jsonreplace.sh

**Comment by boredland** [comment]
And the jq dependency can be dropped from the settings package.

**Comment by boredland** [comment]
inactive-window-transparency.py and autoname-workspaces.py are being inserted from upstream:
https://github.com/swaywm/sway/tree/master/contrib
