### ISSUE TITLE
How to upgrade manjaro-sway-settings?

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#104]
I like new settings, but my work laptop works on 5.3.0-8. The current is 5.5.0-8.

```shell
yay -Syyu
[sudo] password for ak: 
...
:: Starting full system upgrade...
warning: manjaro-sway-settings: local (5.3.0-8) is newer than community (1.0.0-1)
:: Searching AUR for updates...
 -> manjaro-sway-settings: local (5.3.0-8) is newer than community (1.0.0-1)
 -> Missing AUR Packages:  libnm-glib
 there is nothing to do

~ 27s
❯ yay -S manjaro-sway-settings
warning: downgrading package manjaro-sway-settings (5.3.0-8 => 1.0.0-1)
resolving dependencies...
^C
Interrupt signal received

~ 11s
❯ sudo pacman -Sy manjaro-sway-settings                                              
warning: downgrading package manjaro-sway-settings (5.3.0-8 => 1.0.0-1)
resolving dependencies...
looking for conflicting packages...

Packages (3) fzf-0.27.2-1  sway-launcher-desktop-1.4.0-1  manjaro-sway-settings-1.0.0-1

Total Download Size:   1.06 MiB
Total Installed Size:  3.34 MiB
Net Upgrade Size:      3.15 MiB

:: Proceed with installation? [Y/n] ^C
Interrupt signal received
```

**Comment by boredland** [comment]
`pacman -S manjaro-sway/manjaro-sway-settings` should do

**Comment by Mathew-D** [comment]
If you want it to be automatic,  you would need move the manjaro-sway db higher in /etc/pacman.conf.  If you move it above the community you will not have this problem again.  For example my order is:

[core]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[extra]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist

[manjaro-sway]
SigLevel = Optional TrustAll
Server = https://packages.manjaro-sway.download/$arch

[community]
SigLevel = PackageRequired
Include = /etc/pacman.d/mirrorlist
`

**Comment by andrius** [comment]
> `pacman -S manjaro-sway/manjaro-sway-settings` should do

Did it, thank you. But then I can't see the workspace number:

![image](https://user-images.githubusercontent.com/26776/126275527-2be5f829-9fa0-4615-a98f-ca58c08d2a36.png)

**Comment by boredland** [comment]
This may be due to us switching from string numbers like "1" etc to real numbers for workspace names. Did you restart after the upgrade?

**Comment by boredland** [comment]
If not you may send a window to ws 1 (super+shift+1) and check if that one has the right number.

**Comment by Mathew-D** [comment]
Oh I see what he means... When there is an application open it shows the icon that matches what programs are running now instead of the numbers.  This way you don't have to remember what is run.

**Comment by Mathew-D** [comment]
If you remove sworkstyle the numbers should come back as that is the program and auto-renames the workspaces with the correct images of the programs you are opening.

**Comment by andrius** [comment]
Sure I've restarted; @Mathew-D if I'll remove sworkstyle I guess only numbers would return? In any case on my freshly installed Dell with yesterday's version, I do get both numbers and icons, curious what's missing... quick scanning of settings do not show anything suspicious

**Comment by andrius** [comment]
A comment to the @boredland on waybar. I work on microsoft surface go2, it is tiny laptop, that perfectly works with sway. In the office space I just use 27" monitor, but if I work from home, the main issue with the waybar is tiny space. With the default settings there is literally no space even for icons, I used to customize it a lot to fit into my workflow.
Is there any option to add some profile support or something like that?

**Comment by boredland** [comment]
Yes, there is "include" support coming to waybar, that, as I get it will allow that.

**Comment by Mathew-D** [comment]
@andrius If you uninstall sworkstyle you will just get numbers.   I am not sure what version your dell is running as I never got both auto icons and numbers.  Only 1 or the other. There might be a way but I don't see it in sworkstyle config.

**Comment by andrius** [comment]
Photo because it's a fresh install ![image](https://user-images.githubusercontent.com/26776/126284487-2002112d-6ef0-4e61-bca7-853ea8c4aa0e.jpeg)

**Comment by Mathew-D** [comment]
Can you check what version of manjaro-sway-settings it is running.

**Comment by andrius** [comment]
It should be this version https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202107190232

**Comment by andrius** [comment]
0.5.6-14

**Comment by Mathew-D** [comment]
I am sorry I don't know right now maybe @boredland  or @FallenChromium can help as it is 4:30am here I need to get to sleep.

**Comment by boredland** [comment]
> Photo because it's a fresh install ![image](https://user-images.githubusercontent.com/26776/126284487-2002112d-6ef0-4e61-bca7-853ea8c4aa0e.jpeg)

That is, as I see it, how it is supposed to look.

**Comment by Mathew-D** [comment]
Try this:
nano ~/.config/waybar/config

Then find: 
   "sway/workspaces": {
        "all-outputs": false,
        "disable-scroll": true,
        "format": "{name}"
  },
and put // in front of format then reload sway config and see if that does what you want.

**Comment by FallenChromium** [comment]
In my commit to migrate to sworkstyle I've set it up in a way that both numbers and name of the workspace are shown, for example, 
![image](https://user-images.githubusercontent.com/43214067/126294346-b2999260-a43b-44ad-9008-3a60d63a2b23.png)
Did you make any changes to ~/.config/waybar/config?

**Comment by boredland** [comment]
> In my commit to migrate to sworkstyle I've set it up in a way that both numbers and name of the workspace are shown, for example, 
> ![image](https://user-images.githubusercontent.com/43214067/126294346-b2999260-a43b-44ad-9008-3a60d63a2b23.png)
> Did you make any changes to ~/.config/waybar/config?

I think it looks the same for him..

**Comment by FallenChromium** [comment]
As far as I understand @Mathew-D's suggestion helped (see the emote). Closing the issue then? @andrius, what did you end up doing?
