### ISSUE TITLE
cleanup screenshot mode

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#106]
I've decided to open this issue out of frustration that I have when using these modes. First of all I shall say that I really like the idea and the ease-of-use, it's actually very neat, but there are serveral problems with them, I think:
1. These modes aren't "minor" (they don't include the normal mode), which means that when I use them, I cannot use any hotkeys to switch desktops\workspaces\use launcher and many other things I might actually want to do when recording a video, for example
2. Escape is the exit key from the mode, but it's an exit key for basically everything, so, for example, when I want to quit my launcher after starting the record, I actually stop recording instead.
3. In screenshot mode, when you press Area button for example, you can call it several times in a row, which will lead to a faded image. Basically it's a debate if after the screenshot command is executed should we proceed to normal mode or stay in screenshot mode.
4. PrintScreen, the key which most users are very used to isn't mapped. I think it will be nice to make an alternative, mode-less bind at least for making a screenshot with PrintScr, because it's a habit, and this key is made for this anyway :D. On my old setup, I've had these binds for screenshots, maybe it will be a useful starting point (please note I wrote this before encountering Manjaro Sway, so it's not using all the cool possibilities that are available). /usr/share/sway/scripts/grimshot can be used instead as a more universal and consistent solution:
```
#Copy whole screenshot to clipboard
bindsym --to-code Print exec grim - | wl-copy

#Save to HOME
bindsym --to-code Ctrl+Print exec grim ~/Documents/screenshot-"$(date +%s)".png

#Take a screenshot of a window to the clipboard
bindsym --to-code $mod+Print exec grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | wl-copy

#Take a screenshot of the window and save it at HOME
bindsym --to-code Ctrl+$mod+Print exec grim -g "$(swaymsg -t get_tree | jq -r '.. | select(.focused?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')" ~/Documents/screenshot-"$(date +%s)".png

# Take a screenshot of selected region and save to clipboard
    bindsym --to-code Shift+Print exec grim -g "$(slurp)" - | wl-copy

# Take a screenshot of selected region and save at HOME
    bindsym --to-code Ctrl+Shift+Print exec grim -g "$(slurp)" ~/Documents/screenshot-"$(date +%s)".png
```

**Comment by boredland** [comment]
I hate the screenshot modes and barely ever use them. They're just copied from the sway edition as far as I remember.

**Comment by FallenChromium** [comment]
Perhaps we could move this functionality to rofi, it would be a nice alternative because it's still easy to use, but it doesn't block keybindings and depend on theming\bar. As an alternative, for the most used screenshot and record modes we can do keybinds that will not depend on rofi either.

**Comment by boredland** [comment]
I'd appreciate a screenshot on "print" button however.

**Comment by boredland** [comment]
@all-contributors please add @FallenChromium for a good and clean idea how to do this
