### ISSUE TITLE
After the recent upgrade, volume up and down indicators are black

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#108]
From now I can see only a black rectangle; it seems that wob.sh does not work (snippets from sway configs)

```shell
❯ bash /usr/share/sway/scripts/wob.sh $(amixer sset Master 5%+ | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1) '#0000ff'

~
❯ bash /usr/share/sway/scripts/wob.sh $(amixer sset Master 5%+ | sed -En 's/.*\[([0-9]+)%\].*/\1/p' | head -1)          
```

**Comment by boredland** [comment]
Hi there! Those are multiple problems actually:

1. wob changed its syntax from argb to the more common rgba, but I intoduced a bug within (fix is on the way)
2. we didn't yet adapt wob.sh to it, since that is part of a bigger undertaking. If you want a quick fix: put the FF behind the color parameters in `/usr/share/sway/scripts/wob.sh`

**Comment by boredland** [comment]
hmhm. apparently it doesn't work with putting the FF behind. Having a look...

**Comment by boredland** [comment]
a quick fix is to just remove the color parameters in wob.sh

**Comment by boredland** [comment]
Little update: wob 0.22 is working as it should. So My initial comment about putting the 'FF' behind the color value is valid again.

**Comment by FallenChromium** [comment]
It should be resolved after [dynamic theming](https://github.com/Manjaro-Sway/desktop-settings/pull/26) will be merged.

**Comment by boredland** [comment]
should be fixed in manjaro-sway-settings 6.0.0 - reopen if you've remaining issues.

**Comment by hakanyi** [comment]
> Little update: wob 0.22 is working as it should. So My initial comment about putting the 'FF' behind the color value is valid again.

Bumped into this issue as volume buttons are not working for me atm. wob is version 0.11 after fresh install and updates.

**Comment by boredland** [comment]
1st please update to wob 1.2: 

`pacman -S manjaro-sway/wob`

2nd make sure you have the newest settings package: 

`pacman -S manjaro-sway/manjaro-sway-settings`

**Comment by hakanyi** [comment]
`pacman -S manjaro-sway/wob` solves it (now version 0.12), thanks!
