### ISSUE TITLE
add conky-style on-screen text to hint for help menu

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#110]
the current help-button is merely a workaround. 
[nwg-wrapper](https://github.com/nwg-piotr/nwg-wrapper) should replace it.

Text: `$mod + ? -  Help Menu`

- [ ] add nwg-wrapper to sway config as startup-if-exists
- [ ] add nwg-wrapper as optional dependency to settings package
- [ ] remove help button from waybar

**Comment by Mathew-D** [comment]
Getting it to open and display isn't that hard.. what I find hard to get it to close it.... lol.

**Comment by boredland** [comment]
Oh really. Never tried nwg-wrapper, but I thought it would work very similar to conky. That doesn't sound good...

**Comment by boredland** [comment]
@Mathew-D I am not 100% sure we are talking about the same thing here. I wanted to display just a string on the background. I just tested this and for me I looks like I hoped it would (conky style). What did you try to achieve?

**Comment by Mathew-D** [comment]
I just tried running the example code they gave.  The message was always behind every window and once it was opened I couldn't get it to go away.  I only ran the code with terminal to see what it would do.
