### ISSUE TITLE
screen lock does not working

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#111]
After the upgrade to the 6.x version today and reboot, screen lock from the wlogout menu does not working (swaylock alone does work). I did check wlogout cofig and reinstalled both wlogout and swaylock, but that did not helped

**Comment by Mathew-D** [comment]
I use my own locking that is why I didn't see the error right away.  It seems to be a quote thing.  Can you try:
sudo nano /etc/sway/definitions
and change $locking to 

set $locking swaylock --daemonize --color "$selection-color" --inside-color "$selection-color" --inside-clear-color "$text-color" --ring-color "$color2" --ring-clear-color "$color11" --ring-ver-color "$color13" --show-failed-attempts --fade-in 0.2 --grace 2 --effect-vignette 0.5:0.5 --effect-blur 7x5 --ignore-empty-password --screenshots --clock

If that works can you tell me and I will push out the fix to everyone. It seems like it wanted the colors in ""

**Comment by Mathew-D** [comment]
I am going to close this as the new commit should fix this issue. https://github.com/Manjaro-Sway/desktop-settings/commit/098998956b5189ee4e11d4ebf1c235a79820ebda
