### ISSUE TITLE
Some `/etc/sway/*` configs missing

### ISSUE THREAD

**Issue by chesedo** [Manjaro-Sway/manjaro-sway#112]
My system updated in the morning. In the afternoon my computer lost power, but on the reboot my sway config had errors. For example `$waybar_position` could no longer be found.

Upon investigation I discovered that `/etc/sway/` now only contains the following files while my config is trying to include `/etc/sway/definitions`:
```
$ tree /etc/sway
/etc/sway
├── config
└── config.d
    └── 50-systemd-user.conf

1 directory, 2 files
```

I am not sure whether it was the update or incorrect reboot that caused the issue?

**Comment by chesedo** [comment]
I just remember, I also tried to customize my theme using the 'Customize Look and Feel' app

**Comment by chesedo** [comment]
I think I found it. Those files come from the `manjaro-sway-settings` package. So I tried to reinstall it. However, it gives a warning about `cannot resolve "termite"`... I removed termite earlier today too :man_facepalming: Now the question is how to get `termite` back?

`sudo pacman -S termite` gives me `target not found: termite`

**Comment by Mathew-D** [comment]
The sway-setting needs to come from the right database. Try pacman -S manjaro-sway/manjaro-sway-settings

**Comment by chesedo** [comment]
That did the trick. Thanks @Mathew-D

**Comment by manfred3000** [comment]
> `sudo pacman -S termite` gives me `target not found: termite`

Termite has been [abandoned](https://github.com/thestinger/termite/) - I'd recommend using [foot](https://codeberg.org/dnkl/foot) instead.

**Comment by boredland** [comment]
yeah, that is where we went with the settings =>v6

**Comment by chesedo** [comment]
I've already jumped to alacritty. Hence the uninstall. On a side note, installing from the `manjaro-sway` db seems to have changed a lot of config. Probably because `community` is still on 1.0 and it seems the distro defaults to `community`?

**Comment by boredland** [comment]
> I've already jumped to alacritty. Hence the uninstall. On a side note, installing from the `manjaro-sway` db seems to have changed a lot of config. Probably because `community` is still on 1.0 and it seems the distro defaults to `community`?

The built images use the latest versions from our repo. Sadly the Manjaro tooling doesn't allow us to prioritize our repo over community for the built image.
