### ISSUE TITLE
"Connect to socket" errors during system boot 

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#113]
The error sounds like this:

~~~bash
[wlr] [libseat] [libseat/backend/seatd.c:70] Could not connect to socket /run/seatd.sock: no such file or directory
~~~

The problem is fixed by adding a line to the `/etc/environment` file 

~~~bash
LIBSEAT_BACKEND=logind
~~~

Wlroots have ditched the dependency on logind and relied on libseat for desktop management.

**Comment by boredland** [comment]
@all-contributors please add @MuratovAS for finding a bug and providing a solution for this
