### ISSUE TITLE
How to extract and use the iso.z01 file

### ISSUE THREAD

**Issue by enricofadly** [Manjaro-Sway/manjaro-sway#117]
I know its kinda stupid question but how to use the iso.z01, because its new to me and Im always straight download the iso file from manjaro sites (gnome), and i wanna to try sway but idk to find the iso files.

**Comment by boredland** [comment]
You have to download both, .zip and .z01. depending on your archiving application it already has support for you extracting the file using the .zip. if not, you can join them: https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux#40481

**Comment by enricofadly** [comment]
> You have to download both, .zip and .z01. depending on your archiving application it already has support for you extracting the file using the .zip. if not, you can join them: https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux#40481

Thanks for the quick response sir, i'll try it , 

keep up the good work sir !
