### ISSUE TITLE
Мodified Script Sunset.sh, adding a widget in Waybar 

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#118]
I was modified by the script for working with Wlsunset.
Added features:
1. Widget Waybar, allowing you to turn on and disable "night mode", as well as visualize the current state.
2. Configuration file, and auto creation mechanism
3. Ability to not use location
4. Checking the correctness of the answer from FreeGeoip.App

P.S. I do not have experience in participating in such big projects as Manjaro. Is I doing correctly by sending trouble through "Issues"? 

Changed files:
`~/.config/waybar/config`
Do not forget to register this seen in Style.css and in the section "Modules-Right" 
~~~json
    "custom/sunset": {
	"interval": 2,
        "tooltip": false,
        "return-type": "json",
        "format" : "{icon}",
        "format-icons": {
            "on": "ﯦ" ,
            "off": "ﯧ" 
        },
        "exec": "/bin/sh /usr/share/sway/scripts/sunset.sh",
	"on-click": "swaymsg exec /usr/share/sway/scripts/sunset.sh 'toggle'",
    },
~~~

`/usr/share/sway/scripts/sunset.sh`
~~~bash
#!/bin/sh
#Checks if a configuration file exists, if necessary creates 
function checkConfig(){
	if [ ! -f "$HOME/.config/wlsunset/config" ];
	then 
		mkdir -p $HOME/.config/wlsunset
echo 'temp_low="4000"
temp_high="6500"
sunrise="07:00"
sunset="23:00"
duration="900"
location="off"
' >> $HOME/.config/wlsunset/config
	fi
}

#Startup function
function onSunSet(){
	checkConfig
	source $HOME/.config/wlsunset/config

	if [ ${location} = "on" ]; 
	then
		CONTENT=$(curl -s https://freegeoip.app/json/)
		longitude=$(echo $CONTENT | jq .longitude)
		latitude=$(echo $CONTENT | jq .latitude)
		if [ -e $longitude ];
		then
			echo location ERROR: freegeoip.app
			longitude='65'
			latitude='60'
		else
			echo location OK:  $latitude $longitude
		fi	
		wlsunset -l $latitude -L $longitude -t $temp_low -T $temp_high -d $duration &
	else
		wlsunset -t $temp_low -T $temp_high  -d $duration -S $sunrise -s $sunset &
	fi

}

#Accepts managing parameter 
case $1'' in
	'off')
   	pkill wlsunset
	;;

	'on')
	onSunSet
	;;

	'toggle')
   	if pkill -0 wlsunset
	then
		pkill wlsunset
	else
		onSunSet
	fi
    ;;
esac

#Returns a string for Waybar 
if pkill -0 wlsunset
then
	class="on"
else
	class="off"
fi	

printf '{"alt":"%s"}\n' "$class"
~~~

You should also change the file `/etc/sway/config.d/99-autostart-applications.conf`
~~~bash
'[ -x "$(command -v wlsunset)" ] && $HOME/.config/sway/scripts/sunset.sh "on"'
~~~

**Comment by boredland** [comment]
thats a fine idea! I would not go the the script to bootstrap the config file but rather move it to the skel. see pr.

**Comment by MuratovAS** [comment]
I looked at your "Pull Request", noticed inaccuracy.
You have added a module code, but did not add a module directly to the panel.
You must also add several lines:

`sway/etc/skel/.config/waybar/config`
~~~bash
......
"modules-right": [
"custom/sunset",
......
~~~

`sway/etc/skel/.config/waybar/style.css`
~~~bash
......
/* Each module */
#custom-sunset,
......
~~~
P. S. I apologize for the inconvenience, in the future I will do my own "Pull Request".

**Comment by boredland** [comment]
@all-contributors please add @MuratovAS for writing code to enhance our sunset script
