### ISSUE TITLE
Widget for Waybar, allowing you to manage multimedia.

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#124]
Widget for Waybar, allowing you to manage multimedia.
In most WM, this feature is implemented by means of notifications.
It is based on MPRIS D-BUS Interface, is not attached to a specific player. This is implemented through the [playerctl](https://github.com/altdesktop/playerctl) program.

Scenario of use: The music is played in the background, in my case in Firefox. Suddenly there is a call to a cell phone. I need to respond urgently. Looking for a tab with audio players usually take a long time. This module will allow you to do in one click. As well as will allow the playback as quickly.

The widget tried to make the most compact. If you completely turn off the audio player, the widget will automatically hide from the panel.

`sway/etc/skel/.config/waybar/config`
~~~json
  "custom/playerctl": {
	"interval": 1,
	"tooltip": true,
	"return-type": "json",
	"format" : "{icon}",
	"format-icons": {
		"Playing": "喇",
		"Paused": ""
	},
	"exec": "status=$(playerctl status) && title=$(playerctl metadata title) && artist=$(playerctl metadata artist) && echo {'\"alt\"':'\"'$status'\"', '\"tooltip\"':'\"'$title - $artist'\"'}",
	"on-click": "playerctl play-pause",
	"on-click-right": "playerctl next",
	"on-scroll-up": "playerctl position 10+", 
	"on-scroll-down": "playerctl position 10-", 
  },
~~~
`sway/etc/skel/.config/waybar/config`
~~~json
"modules-right": [
....
	"custom/playerctl",
....
~~~
`sway/etc/skel/.config/waybar/style.css`
~~~css
/* Each module */
....
#custom-playerctl,
....
~~~

**Comment by boredland** [comment]
I think I like the idea. But is it that different from https://github.com/Alexays/Waybar/wiki/Module:-MPD ?

**Comment by MuratovAS** [comment]
The "Waybar / Module: MPD" module is Front-End for MPD Server.
MPD Server already independently reproduces audio from a file or network stream.

Playerctl Command-Line Utility, Front-End. Allows you to connect to various players, using the MPRIS universal interface. Including MPD. It supports VLC, MPV, Rhythmbox, Web Browsers, Cmus, MPD, Spotify and Others.

My solution is more versatile and lightweight. Does not limit the user in choosing a player.
It allows you to manage even YouTube, directly from the browser, without third-party applications.
