### ISSUE TITLE
Shell comments are invisible with default theme

### ISSUE THREAD

**Issue by skunkfox** [Manjaro-Sway/manjaro-sway#125]
Title says it all. If I open up kitty and zsh and start typing when I enter a comment the color of the comment is invisible in the default theme (black on black).
![20210801_10h38m44s_grim](https://user-images.githubusercontent.com/88281387/127776872-29a2c7bf-387a-4366-b7e6-6a3f126a56dd.png)

**Comment by boredland** [comment]
confirmed for foot too!

**Comment by FallenChromium** [comment]
Doesn't happen for me with a powerlevel10k theme for zsh, so not a coloring issue. Can someone try some other edition of Manjaro? It may be that it's broken in the `manjaro-zsh-settings`, so not our scope
![image](https://user-images.githubusercontent.com/43214067/127777862-95a01f75-e1f2-4ff8-b69c-7c8311545ae9.png)

**Comment by Mathew-D** [comment]
@FallenChromium what gnome theme are you running?  As I am having the same thing in gnome-terminal when I tell it to use the gnome theme.

**Comment by FallenChromium** [comment]
It doesn't happen when I've reset my whole config (copied it from skel), so not a GTK thing either. foot doesn't take any colors from a GTK theme by the way, it's all defined in the foot.ini
![image](https://user-images.githubusercontent.com/43214067/127783441-ccb26a06-9544-45c3-8346-bfc44d0362e7.png)

**Comment by Mathew-D** [comment]
I am using the default zsh from the install and this I what I get. The comment is the same color as the background of the check mark on the right.
![2021-08-01T15:52:43,077332020-04:00](https://user-images.githubusercontent.com/44036272/127783617-72654b77-c33b-4f60-94e0-4b5a69a431c0.png)

**Comment by aimixess** [comment]
Hello,
As a workaround, you can put : ZSH_HIGHLIGHT_STYLES[comment]='fg=blue' in you .zshrc.
