### ISSUE TITLE
Nwg-wrapper theming

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#128]
Just so this is not forgotten: aiming for the i3 conky, so we should adapt css to resemble that a bit:
![conky](https://news-cdn.softpedia.com/images/news2/manjaro-linux-16-06-rc-i3-community-edition-ships-with-linux-kernel-4-4-9-lts-504309-4.jpg)

**Comment by MuratovAS** [comment]
I am now working on a script forming a list of hot keys.
It is capable of Parsing configuration files and form something very similar to the help. On your photo I see something like that.
If this is a useful project, let me know. 
A small example of work. The script is still far from completion. 
![2021-08-03T23:58:30,185954317+05:00](https://user-images.githubusercontent.com/50487552/128071003-b4a214c7-e265-4062-8b5e-8cb19718ddee.png)

**Comment by boredland** [comment]
Hm, that does sound exactly what I aimed for with the sbdp tool I built for the help. It's written in typescript and thus not very efficient. If you've got something more efficient, I would probably prefer that. It's not about theming though...
