### ISSUE TITLE
Issues with new lock menu

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#129]
I love it - interface get unified. But now it does not self-terminate, if I press control-key-Shift-e, then l to lock, and enter a password in a while, menu is still there, I have to press Esc after the unlock

**Comment by FallenChromium** [comment]
Oh, I see, thanks for the feedback! I'll make a PR to fix it.

**Comment by FallenChromium** [comment]
Please check it when the PR will get merged :)
