### ISSUE TITLE
replace partition installation . manjaro-sway-2021.08.04 release

### ISSUE THREAD

**Issue by tomas0430** [Manjaro-Sway/manjaro-sway#132]
Installation fails on bootlaoder script. python error FileNotFound ;bootloader etc. left with empty grub console after install. Any idea how to fix it?

**Comment by boredland** [comment]
I have no idea what that is about, where does that bootloader script fail? during install?

**Comment by boredland** [comment]
just did a plain new install in a vm without any issues.

**Comment by aimixess** [comment]
Hi, I also encounter this problem, at the end of installation, the python script is unable to find bootx64.efi in /tmp and installer stop.

**Comment by boredland** [comment]
Since sway edition is not maintaining the calamares installer, I doubt I am of any help here. I suggest searching in the manjaro.org forums: https://forum.manjaro.org/

**Comment by boredland** [comment]
the issue may have been related to a bug in the iso_build action https://github.com/manjaro-gnome/download/issues/15. the image that is being build now (should be available in 30m) should thus work for you. let me know if that changed.

**Comment by tomas0430** [comment]
Yeah! It's working now without a glitch.No more bootloader error with this release 2021.08.15. Very happy.Thanks for your work.
