### ISSUE TITLE
Cannot log back in after system upgrade

### ISSUE THREAD

**Issue by FilBot3** [Manjaro-Sway/manjaro-sway#135]
I am running `manjaro-sway-21.0-210428-linux510` in a GNOME Boxes instance backed by libvirtd on Pop!_OS 21.04 for a host. I can get Manjaro Sway to install and be useable, but after I encounter issue https://github.com/Manjaro-Sway/manjaro-sway/issues/69#issuecomment-875770572 and perform a `sudo pacman -Syyu`, I reboot, and then I cannot login as my user I defined at install, nor the manjaro default user. I then have to delete the VM and start over or revert to an earlier snapshot.

This was caused by me trying to reload my sway config, but MOD+SHIFT+c seemingly not working so I tried to reboot as listed in issue https://github.com/Manjaro-Sway/manjaro-sway/issues/136 .

**Comment by boredland** [comment]
https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-log-in-inside-a-virtual-machine

**Comment by FilBot3** [comment]
the `manjaro`/`manjaro` un/pw isn't letting me in with the latest release in GNOME Boxes. I am unable to get the point where I can enable 3D Acceleration.

**Comment by boredland** [comment]
3d acceleration of your virtualization solution, nothing related to the "inside" of your vm.

**Comment by FilBot3** [comment]
I don't see the option. Normally I would for my other VMs.
![image](https://user-images.githubusercontent.com/3039509/129226459-cb5bb3fb-bd3e-4562-bd8d-98cc48c58edb.png)

**Comment by FilBot3** [comment]
This is just the LiveCD beginning part. I haven't been able to install anything.

**Comment by boredland** [comment]
ya, i know. this issue is known. thats why it is in the issues 🤷🏼

**Comment by FilBot3** [comment]
My apologies, I'm not trying to come off as combative. Hard to express this through text.

**Comment by boredland** [comment]
already documented: https://github.com/Manjaro-Sway/manjaro-sway/issues/56
