### ISSUE TITLE
MOD+SHIFT+? not showing help plus a number of other keyboard shortcuts

### ISSUE THREAD

**Issue by FilBot3** [Manjaro-Sway/manjaro-sway#136]
I recently installed Manjaro Sway `manjaro-sway-21.0-210428-linux510` into a GNOME Boxes back by libvirtd instance on a Pop!_OS 21.04 host. However, a few of the keyboard shortcuts do not seem to be working as expected. I can open the terminal with MOD+Enter, I can click on the menu in the top left hand corner. WHen I open a few terminals, I cannot MOD+[h/j/k/l] between any of the panes, however, the MOD+[arrow-up/down/left/right] work. I tried to modify the `~/.config/sway/config.d/00-user-config` file to reset the vim navigation bindings using

```plaintext
set $left h
set $down j
set $up k
set $right l
```

Then attempted to press MOD+SHIFT+c and nothing seemingly happened. Then I did MOD+SHIFT+e, which I rebooted, then encountered issue https://github.com/Manjaro-Sway/manjaro-sway/issues/135 . I also saw that the [SUPPORT.md](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-list-the-predefined-shortcuts) shows this, but wasn't working for me.

**Comment by boredland** [comment]
`manjaro-sway-21.0-210428-linux510` sounds massively outdated. check [here](https://github.com/Manjaro-Sway/manjaro-sway/releases) for sth. newer.

**Comment by FilBot3** [comment]
The download link from the https://manjaro.org/download/#sway is pointing to an older version of this ISO then. It may need to be updated.

**Comment by boredland** [comment]
> I cannot MOD+[h/j/k/l]

where did you come up with that one?

**Comment by FilBot3** [comment]
I thought it was part of the default configuration for sway

* https://github.com/swaywm/sway/blob/master/config.in#L12-L15

**Comment by boredland** [comment]
we don't have it... afaik. i'll download and try in gnome boxes. help should work though.

**Comment by FilBot3** [comment]
When downloading the latest `.zip`, I encountered this error when attempting to unzip it.
```bash
➜  Downloads unzip manjaro-sway-21.1.0-210812-linux510.iso.zip 
Archive:  manjaro-sway-21.1.0-210812-linux510.iso.zip
warning [manjaro-sway-21.1.0-210812-linux510.iso.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
file #1:  bad zipfile offset (local header sig):  4
```

Then I tried the `.z01` file since it seemed like it would be the file I need, but I'm not sure what file format a `.z01` is. 

```bash
➜  Downloads unzip manjaro-sway-21.1.0-210812-linux510.iso.z01 
Archive:  manjaro-sway-21.1.0-210812-linux510.iso.z01
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of manjaro-sway-21.1.0-210812-linux510.iso.z01 or
        manjaro-sway-21.1.0-210812-linux510.iso.z01.zip, and cannot find manjaro-sway-21.1.0-210812-linux510.iso.z01.ZIP, period.
```

**Comment by boredland** [comment]
https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-unzip-the-multi-part-zip-zip--z01

**Comment by boredland** [comment]
(if you have a graphical archive manager, installing p7zip will likely work too)

**Comment by FilBot3** [comment]
I was able to get the files unarchived using the command provided. I'm attempting to install, but not having luck logging in now.
