### ISSUE TITLE
sha1sum mismatch

### ISSUE THREAD

**Issue by press5** [Manjaro-Sway/manjaro-sway#137]
Hello, 

This may not be the right place to post this (and if it's not, I apologize in advance) but it looks like the download for sway [at manjaro](https://manjaro.org/downloads/community/sway/) doesn't match the sha1sum provided on the page ( `b7e8a7e51953e07965155d2f92916dba0bc518a65339c9253642f35156ca3500` ), instead I get `5cdad62cd38537071a7226c7cc161536cfa87a37`. 

the macOS archive tool doesn't recognize it as a valid zip file; The Unarchiver does, but the sha1sum does not match.

**Comment by press5** [comment]
the macOS archive tool doesn't recognize it as a valid zip file; The Unarchiver _does_, but the sha1sum does not match.

**Comment by boredland** [comment]
What did you check the sha1sum against? the zip or the iso inside the zip?

**Comment by press5** [comment]
I tried both, to be sure: 

```
$ sha1sum manjaro-sway-21.0-210428-linux510.iso
5cdad62cd38537071a7226c7cc161536cfa87a37  manjaro-sway-21.0-210428-linux510.iso
$ sha1sum manjaro-sway-21.0-210428-linux510.iso.zip
50577c354582a881c90c494baf4fd94001e8371d  manjaro-sway-21.0-210428-linux510.iso.zip
```

**Comment by boredland** [comment]
I mean: that image is massively outdated and we have to find a way to get rid of that kind of links on the manjaro page (I did not put it there!). But sampling the latest image here in our github releases, everything is in order:

```
$ cat Downloads/manjaro-sway-21.1.0-210818-linux510.iso.sha1
02fb2bb04d07b170b7bca6fc7b0dee6cdcab9e4f  manjaro-sway-21.1.0-210818-linux510.iso
$ sha1sum Downloads/manjaro-sway-21.1.0-210818-linux510.iso 
02fb2bb04d07b170b7bca6fc7b0dee6cdcab9e4f  Downloads/manjaro-sway-21.1.0-210818-linux510.iso
```

**Comment by press5** [comment]
@boredland  I was so concerned about the download being broken or tampered with that I didn't notice it was out of date!  Thank you. I will use the latest image from this repo. Since my intent was to make you aware of the potentially bad link at Manjaro, I think this can be closed now, since I have a working iso now and thus am happy. :) 

Thank you for replying so quickly; please have a good rest of the week and stay safe!
