### ISSUE TITLE
Broken SWORKSTYLE in the Manjaro-Sway repository 

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#138]
good day
After the last update, problems with SWORKSTYLE package began.
To solve the problem, moved to version from AUR 
![2021-08-19T12:06:55,290451913+05:00](https://user-images.githubusercontent.com/50487552/130030627-f4964391-bfa4-45b2-ab4d-676324e836d1.png)

**Comment by boredland** [comment]
Hi! I'll look into it. When did this occur for you? For me it works nicely.. Did you restart sworkstyle after the update?

**Comment by MuratovAS** [comment]
This happened 18.08.21. After the update it took the system to restart. After that, I noticed that SWORKSTYLE does not work. I tried to run it and got a mistake like a screen shot.

**Comment by boredland** [comment]
ah, I think I know whats going on. you have the old `.config/sworkstyle/config.toml` present with the comment section in the beginning. apparently my mapping function cant deal with that yet. good find!

**Comment by MuratovAS** [comment]
Really. Removed comments "#" and string "[Matching]" earned.

Its useful to note. I used to use such structures, they stopped working. 
```
'/(?i)Youtube.*librewolf/' = ''
'/(?i)Github.*librewolf/' = ''
'librewolf' = ''
```

**Comment by boredland** [comment]
Sworkstyle has no unit tests, I will try and add some.

**Comment by boredland** [comment]
I think pkgrev 5 should now only try to replace lines starting with `'`. hope that fixes it. It does for me..
