### ISSUE TITLE
Doesn't start in VMware - Asked to enter username on Live CD

### ISSUE THREAD

**Issue by press5** [Manjaro-Sway/manjaro-sway#139]
Hi folks, 

Using VMWare Fusion Pro 12.1.2 with the live iso `manjaro-sway-21.1.0-210820-linux510.iso` it seems login with manjaro/manjaro is impossible:

![image](https://user-images.githubusercontent.com/43304339/130272628-7ad1e9b4-4109-4db2-9302-70d0870c5219.png)

**Comment by boredland** [comment]
You should not even be seeing that prompt. Will have a look later.

**Comment by press5** [comment]
Thank you. Let me know if you need more information.

**Comment by boredland** [comment]
from your screenshot, there may be other things going wrong. I tested with gnome boxes and clearly had the behaviour from https://github.com/Manjaro-Sway/manjaro-sway/issues/56. So I'll fix that up and hope this makes it better for you too.

**Comment by boredland** [comment]
I can't really wrap my head around this. why would there be a basic login shell on tty2 and why are the credentials not valid. this is booting straight from the live cd?

**Comment by boredland** [comment]
hmmm. I am getting greetd in vmware, like in gnome boxes (can"t loging before setting the variable mentioned in #56 though):
![image](https://user-images.githubusercontent.com/4662748/130316783-e1ff58b1-aa4d-417f-964d-f18f9feb61b4.png)

**Comment by press5** [comment]
@boredland this is booting straight from the iso image, yes.

**Comment by press5** [comment]
I see a new ISO generated from #56 - will try that and report back. 

thank you again :)

**Comment by press5** [comment]
![image](https://user-images.githubusercontent.com/43304339/130323912-41bd3770-0b20-423d-afc2-bbd78457c555.png)

@boredland if this ever gives up or finishes I'll let you know what happens. :)

**Comment by press5** [comment]
After playing with this a little more I get the loop behavior if I boot with the opensource option (in hindsight, this kind of makes sense) regardless of the state of 3D acceleration in VMWare. 

If I select the proprietary drivers with 3D off, I get the behavior I reported last night (login on tty2, manjaro/manjaro doesn't work). Proprietary drivers & 3D on, it seems to loop here for a while:

![image](https://user-images.githubusercontent.com/43304339/130324908-928f7dd1-2890-4132-af4c-a2440a1c0896.png)

Eventually we get to the point where it starts the greeter service (below), but at this point the VM appears to go unresponsive. 

![image](https://user-images.githubusercontent.com/43304339/130324997-71cd8278-001f-4198-a504-0702102facb3.png)

**Comment by boredland** [comment]
For me it doesn't work in VMware either. In Gnome Boxes / Qemu it now works even without 3d acceleration.

**Comment by boredland** [comment]
seems to be an upstream issue in sway on vmware, at least there's people experiencing that in void linux too:
https://github.com/swaywm/sway/issues/5834

**Comment by boredland** [comment]
the iso works fine with vbox and the 3d accelerated graphics adapter by the way, so this seems to be a vmware issue only:
![image](https://user-images.githubusercontent.com/4662748/130350525-79005090-269a-42fb-9906-dd2d0d2d296a.png)

**Comment by boredland** [comment]
closing in favor of a comment in the readme caveats section
