### ISSUE TITLE
Installer fails when trying to use existing LVM2 partitions

### ISSUE THREAD

**Issue by bkuri** [Manjaro-Sway/manjaro-sway#144]
I've tried multiple times with the same result. I ask for a manual partition mode, select LUKS, leave other existing partitions alone, pick a `/boot/efi` partition (outside of my volume group), I get an error stating that I didn't select `/boot/efi` (even though I just did), add the rest of my details (name, password, etc), click on Next and I get an error.

After digging a bit deeper it seems like the installer "forgets" my existing VG right before the installation process actually starts, and even typing the command `vgchange -ay` right before I click on the `Next` button doesn't fix it.

LVM is a hard requirement for me, since I've used it for years and I'm very hesitant to venture into btrfs or other similar schemes in case something goes wrong in the future.

Thanks!

**Comment by boredland** [comment]
Hi! I don't see how this may be related to sway edition and think this could be a calamares bug. Will try to reproduce anyhow.

**Comment by bkuri** [comment]
@boredland much appreciated! I can post it elsewhere if it's more appropriate, though.

**Comment by boredland** [comment]
I guess forum.manjaro.org would be the right place.

**Comment by bkuri** [comment]
@boredland I checked that URL and there seems to be very little movement in regards to calamares. I guess that their [issues page](https://github.com/calamares/calamares/issues) might be a better choice, but I need a bit more time to see if this LVM stuff has already been reported.

Then again, I would rather just forgo the calamares install and just do it using the CLI. Do you know if this is possible using the manjaro-sway live cd? TIA!

**Comment by bkuri** [comment]
FWIW I found a temporary workaround by following [these instructions](https://github.com/calamares/calamares/issues/1564#issuecomment-846321060) from a fellow LVM user.

**Comment by boredland** [comment]
> Then again, I would rather just forgo the calamares install and just do it using the CLI. Do you know if this is possible using the manjaro-sway live cd? TIA!

me too! there actually is some work going on recently: https://github.com/yochananmarqos/manjaroinstall

**Comment by bkuri** [comment]
Nice! Looking forward to it.

Loving this distro so far, btw. Keep up the good work!
