### ISSUE TITLE
custom definitions not working

### ISSUE THREAD

**Issue by bhartshorn** [Manjaro-Sway/manjaro-sway#145]
Hi, I'm attempting to follow the customization section in the FAQ by adding definitions. I cannot figure out why they are not being applied. I have confirmed that I have the latest settings package and it's copied into my config directory. 

.config/sway/definitions.d/custom.conf
``` 
set $left h
set $down j
set $up k
set $right l

set $waybar_position bottom
```

.config/sway/config
```
# Default config for sway
#
# Copy this to ~/.config/sway/config and edit it to your liking.
#
# Read `man 5 sway` for a complete reference.

# styles - set the folder for your theme defination file
set $theme /usr/share/sway/themes/matcha-green

#theme variables
include $theme/definitions

# global variables
include /etc/sway/definitions

# user variables
include $HOME/.config/sway/definitions.d/*.conf

include /etc/sway/inputs/*
include /etc/sway/outputs/*

# enable modes
include /etc/sway/modes/*

# only enable this if every app you use is compatible with wayland
# xwayland disable

# include additional configs e.g. to autostart applications
include /etc/sway/config.d/*

# user config
include $HOME/.config/sway/config.d/*.conf
```

Note that this file from `config.d` *is* applied correctly.

config.d/01-user.conf
```
# input "*" equals all input methods
# to specify settings for a specific input method, use its identifier instead.
# query the connected input methods: `swaymsg -t get_inputs`

input * {
    # use capslock as win/super key
    # use both shift keys as capslock
    xkb_options caps:super,shift:both_capslock_cancel
    
}
```

**Comment by boredland** [comment]
what are you trying to achieve? the left/right/.. variables you set are only ever used in the "resize" mode and are identical in our /etc/sway/definitions ...

as for the waybar position: it doesn't respect the setting in sway. you have to put it into `.config/waybar/config.jsonc`:

```json
{
    "include": [
        "/usr/share/sway/templates/waybar/config.jsonc"
    ],
    "position": "bottom"
}
```

**Comment by bhartshorn** [comment]
Ah, so it probably is working fine. With left/right/etc I was trying to use hjkl for switching/moving windows. Knowing what you just mentioned I should be able to fix that.

As for bar position, that might warrant an update to docs and the README in `definitions.d`, that's where I got the info. 

I'll close up this issue after I make sure I can get hjkl working. Thanks for your time.

**Comment by boredland** [comment]
I think adding this to config.d/ should fix ya up:
```
## Navigation // Move focus // $mod + ↑h ↓j ←k →l ##
$bindsym $mod+h focus left
$bindsym $mod+j focus down
$bindsym $mod+k focus up
$bindsym $mod+l focus right

## Navigation // Move focused window // $mod + Shift + ↑h ↓j ←k →l ##
$bindsym $mod+Shift+h move left
$bindsym $mod+Shift+j move down
$bindsym $mod+Shift+k move up
$bindsym $mod+Shift+l move right
```

**Comment by boredland** [comment]
> might warrant an update to docs and the README in definitions.d
removed that and added a not about how it really works to the SUPPORT.md

**Comment by bhartshorn** [comment]
Is it worth adding something like the following to the default config? This seems like a common modification, but maybe I'm mistaken..

```
$bindsym $mod+$left focus left
$bindsym $mod+$right focus right
...
```

Anyway, I'm fixed up. Thanks for your time!
