### ISSUE TITLE
changing wallpaper error

### ISSUE THREAD

**Issue by AOSXAP** [Manjaro-Sway/manjaro-sway#146]
I was trying nitrogen to change wallpaper but it doesn't seem to work? how do u actually change the wallpaper? went through the config files but couldn't find?

Thx

**Comment by boredland** [comment]
hard so say what goes wrong for you if you don't tell me what you tried so far, but it should be as easy as adding a defintion (f.e. to `~/.config/definitions.d/01-wallpaper.conf`) like so:

```
set $background /usr/share/backgrounds/manjaro-sway/gruvbox-light-manjarosway-3840x2160.png
```

**Comment by boredland** [comment]
this is by the way documented in `~/.config/sway/definitions.d/README.md`

**Comment by AOSXAP** [comment]
> this is by the way documented in `~/.config/sway/definitions.d/README.md`

Oh thanks , i missed that file sorry !

Btw your project is amazing!
