### ISSUE TITLE
greetd breaks on Raspberry Pi after updating packages, preventing sway login

### ISSUE THREAD

**Issue by dansalvato** [Manjaro-Sway/manjaro-sway#151]
Several users have reported that first boot works fine after installing Manjaro Sway onto their Raspberry Pi, but after updating packages, a reboot gets them stuck at a blinking cursor.

I was able to fix it by commenting out the `[initial_session]` section of the greetd config (`/etc/greetd/config.toml`). So my current speculation is that some package is either returning this section to the config, or some package is signaling to greetd that it's a first-time session. Either way, something is causing greetd to attempt to use the nonexistent `oem` user as defined in `initial_session`.

If it helps, Raspberry Pi Imager lists its available Manjaro Sway build as having been released on 2021-08-22, so the problem could be specific to updating from a nightly build around that time to now.

**Comment by Mathew-D** [comment]
I think you have the wrong spot as this is for the PC version where I think you need the arm version for Raspberry Pi. https://gitlab.manjaro.org/manjaro-arm

**Comment by dansalvato** [comment]
Forgive me if I'm misunderstanding, but I'm pretty sure that the ARM version is built from this repo as well, given the download page ([here](https://manjaro.org/download/#raspberry-pi-4-sway)) credits Andreas Gerlach as the "Edition Maintainer". But I understand if ARM is not officially supported. I'll try to reproduce this bug, as well as #152, on an x86 platform.

**Comment by Mathew-D** [comment]
From what I understand, we started with coping some of the code from the ARM version to make this on for x86.  For arm sway I would try this link:  https://forum.manjaro.org/c/arm/sway/85 

If you look here: https://github.com/Manjaro-Sway/manjaro-sway/issues/42  you will see that boredland talks about them being two different versions.

**Comment by dansalvato** [comment]
Well shoot, I had no idea the two were fully divergent/independent projects. Thanks for clearing that up!
