### ISSUE TITLE
What's the name of the login screen manjaro-sway uses?

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#153]
I changed something and now I see diminute text on the login screen.

**Comment by Mathew-D** [comment]
manjaro-sway uses greetd

**Comment by Zeioth** [comment]
Thank you for your answer. Actually I found by chance it's tuigreet: https://github.com/apognu/tuigreet

Now I just have to figure out where it's called from so I can pass the arguments.

**Comment by Mathew-D** [comment]
Maybe this will help:
cat /etc/greetd/config.toml                                                                                                                                                         ✔ 
[terminal]
vt = "next"

[default_session]
command = "tuigreet --remember --time --issue --asterisks --cmd sway"
user = "greeter"%                                                                                                                                                                                   

~  ls -la /etc/systemd/system   
lrwxrwxrwx  1 root root   38 Jun 20 18:22 display-manager.service -> /usr/lib/systemd/system/greetd.service

cat /usr/lib/systemd/system/greetd.service                                                                                                                                         
[Unit]
Description=Greeter daemon
After=systemd-user-sessions.service plymouth-quit-wait.service
After=getty@tty1.service
Conflicts=getty@tty1.service

[Service]
Type=simple
ExecStart=greetd
IgnoreSIGPIPE=no
SendSIGHUP=yes
TimeoutStopSec=30s
KeyringMode=shared
Restart=always
RestartSec=1
StartLimitBurst=5
StartLimitInterval=30

[Install]
Alias=display-manager.service

**Comment by Zeioth** [comment]
Woah thanks, I actually found Tuigreet it's been called from 
`/etc/greetd/config.toml`

Now I just need to discove how to change the font size. I tried with `GRUB_GFXMODE=800x600`
And by editting 
`/etc/greetd/styles.css`

But neither of them seem to have effect over tuigreet.

**Comment by Zeioth** [comment]
Ok found it:

You have to run
`sudo vim /etc/vconsole`

Now just use the font you like. For example:

```
# requires sudo pacman -S terminus-font
FONT=ter-132n
```
