### ISSUE TITLE
Rofi un-themed

### ISSUE THREAD

**Issue by xfalcox** [Manjaro-Sway/manjaro-sway#155]
After updating my old install, and running the whole skel thing, my rofi appear to be unthemed:

![image](https://user-images.githubusercontent.com/1385470/133658795-38bac85d-4bb8-4cf2-bfd9-27ccdb3ade16.png)

Weirdly, doing the manual variable replacement by hand and running 

```
rofi -show combi -combi-modi "drun,run" -terminal $term -ssh-command  "{terminal} {ssh-client} {host} [-p {port}]" -run-shell-command "{terminal} {cmd}" -show-icons -font "Roboto 11" -lines 10 -width 35 -color-normal "#141a1b, #eeeeee, #141a1b, #16a085, #eeeeee" -color-window "#141a1b, #282a2b"
```

results in the same thing...

**Comment by Mathew-D** [comment]
Rofi changed it theming style in 1.7.  We are currently working on it... but you can try:

set $menu rofi -show combi -combi-modi "drun,run" -terminal $term -ssh-command  "{terminal} {ssh-client} {host} [-p {port}]" -run-shell-command "{terminal} {cmd}" -show-icons -font "Roboto 11" -lines 10 -width 35 -theme-str "* {lightbg:  $background-color; background:  $background-color; lightfg:  $accent-color; foreground:  $text-color; ac:  $accent-color;}"

In your ~/.config/sway/definitions.d/00-user-define.conf 
As I think that will give you back the look you had.. I don't run the normal rofi look so I can't be 100% sure... Can you let me know if it does look the way it did.

**Comment by xfalcox** [comment]
That did work!

![image](https://user-images.githubusercontent.com/1385470/133676935-310ef48c-29a9-4c3a-aaf7-c1a5b35e1e21.png)

**Comment by Mathew-D** [comment]
Should be fixxed with the new desktop settings package.
