### ISSUE TITLE
It's time to bake in Nvidia 470 support for Sway (update readme)

### ISSUE THREAD

**Issue by pythonInRelay** [Manjaro-Sway/manjaro-sway#157]
Nvidia has finally moved to GDM. For this reason, Sway should be updated to support and use Nvidia's 470 drivers. At the very least the readme should be edited here and possible support given so people can finally get the benefit of using the proprietary drivers. At current the readme on the repo here says that they are not supported, which is no longer true.

https://www.itsfoss.net/nvidia-470-driver-now-works-with-wayland-composer-sway/

https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-470-74-production-branch-release/189679

https://9to5linux.com/nvidia-470-74-graphics-driver-brings-support-for-linux-kernel-5-14-firefox-improvements

https://www.gamingonlinux.com/2021/09/nvidia-47074-for-linux-is-out-fixing-up-memory-usage-for-direct3d-12-with-vkd3d-proton

Let's discuss the following going forward. I feel like this could result in a proper long-term stable release of Manjaro Sway.

**Comment by boredland** [comment]
I mean: we should probably still communicate the potential problems - it still only will work with the latest stable kernel, not lts. since I don't own any nvidia graphics: what steps would we need to take, if any?

**Comment by boredland** [comment]
> proper long-term stable release of Manjaro Sway

Manjaro is a rolling release distribution. There is no such thing as a long-term stable release, in my eyes there shouldn't even be any point-releases and I think the named releases mostly exist for marketing reasons.

**Comment by boredland** [comment]
> I meant regarding stable -build- images, the same way that Manjaro has for their other DEs.

I don't see what the benefit would be, other than people needing to install a bunch of package updates after they downloaded the iso.

**Comment by boredland** [comment]
> perhaps opening up testing support and feedback for future pull requests

to what are you referring? the `desktop-settings`?

**Comment by pythonInRelay** [comment]
> > perhaps opening up testing support and feedback for future pull requests
> 
> to what are you referring? the `desktop-settings`?

Yes mostly. In any case, as I said I will test it myself and see how the experience is, especially with multiple monitor support.

**Comment by boredland** [comment]
we have a "testing" mode for the settings already. Just install the "manjaro-sway-settings-git" package and you'll receive the pre-release updates.
