### ISSUE TITLE
How to install manjaro-sway

### ISSUE THREAD

**Issue by JuanVqz** [Manjaro-Sway/manjaro-sway#159]
Hi! I just want to try manjaro-sway but I got an error when making the `completed.zip`

I found I can join `.zip.z01` and `.zip`just doing `cat file.zip.z01 file.zip > completed.zip`and it works but when I wanted to extract it as `.iso` it fails, any suggestion how can I test `manjaro-sway`?

thank you, if here is not the best way to publish sorry!
![asd](https://user-images.githubusercontent.com/7331511/134589870-acc831b0-c615-405f-94b1-4b30265718bd.png)

**Comment by jyooru** [comment]
Running this command worked for me:
```bash
zip -FF manjaro-sway-21.1.0-210923-linux514.iso.zip --out out.zip && unzip out.zip
```
