### ISSUE TITLE
Scratchpad doesn't remember window size when moving to another monitor

### ISSUE THREAD

**Issue by Zeioth** [manjaro-sway/manjaro-sway#160]
**How to reproduce**:

* Send a window to the scratchpad.
* Move the cursor to another monitor and bring back the window from scratchpad.
* The size of the window changed, and is now super small.

This issue only seem to happen in multi monitor setups. If you always work in the same monitor, it does't happen.

https://x0.at/R4rM.png
https://x0.at/Dls8.png

Any idea about what is causing this?

**Comment by boredland** [comment]
since we're using [just the default sway scratchpad](https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/etc/sway/modes/scratchpad), I would kindly ask you to ask them directly - at least I can confirm this being a problem sometimes. right now I have very similar resolutions on my second monitor, so for me its not a big issue.

**Comment by Zeioth** [comment]
Thank you for confirming the issue.

Posted on Sway's GitHub
https://github.com/swaywm/sway/issues/6561

**Comment by Zeioth** [comment]
Also please, let me know about any help I can bring to the project. There's something are you struggling with currently?

**Comment by Zeioth** [comment]
I actually noticed, the windows change to the same size windows do in float mode. I'm gonna search the way to change the default size for floating windows in manjaro-sway (if you know the answer, will be very appreciated)

**Comment by Mathew-D** [comment]
for_window [app_id="gedit"] floating enable, resize set 1200 800

That resizes the widow when it opens to that float size, it might help you on your way.

**Comment by boredland** [comment]
i guess setting this for all floating windows is just:

```
for_window [floating] resize set 1200 800
```

**Comment by Zeioth** [comment]
Lo luck, seem to be an sway bug actually.

Those sentences do work when the app open for the first time. But after changing screen and restoring from scratchpad, that happen.

**Comment by l-j-g** [comment]
I dont have this issue, at least i can't replicate.

In .config/foot/foot.ini I have set: 
`font = monospace:pixelsize=18`

Do this fix your issue? 
Do the issue only occur on foot applications?

**Comment by boredland** [comment]
No response, no support..
