### ISSUE TITLE
The wob version included in manjaro-sway is outdated and has some bugs

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#161]
Just's letting you know the version included in manjaro-sway crashes when volume is higher than 100. This have been fixed in both wob from the official repos and wob-git.

My manjaro-sway is about 1 month old so maybe you already fixed it. Anyway. Cheers!

**Comment by boredland** [comment]
I think we have the latest version in our repos. May I ask what version of wob you have on your machine?

**Comment by Zeioth** [comment]
0.11 has the issue.
0.12 solved it.

Closing the issue.

**Comment by Zeioth** [comment]
r
