### ISSUE TITLE
Unable to unlock on single display (laptop)

### ISSUE THREAD

**Issue by Dennisvw99** [Manjaro-Sway/manjaro-sway#171]
I am unable to unlock from hibernation if I am on my single main laptop display, I cannot type in my password (the screen just stays blurry). However, I can unlock if I am connected to external monitors. I have this problem just out of the box by install.

**Comment by boredland** [comment]
So just for me to try to reproduce:

- you are on your laptop
- you lock your screen & it becomes blurred
- you start typing your password, but no visual reaction on the screen?

**Comment by Dennisvw99** [comment]
Correct
