### ISSUE TITLE
upgrading to sway in manjaro i3

### ISSUE THREAD

**Issue by AntouanK** [Manjaro-Sway/manjaro-sway#179]
Hi there.

I know it's probably not the right place to ask this question, but I'm trying to see how I can install sway in my existing manjaro i3 installation ( don't want to install everything from scratch until I test sway )

I got the new nvidia drivers, 495. 
And I installed `sway-git`.
But, in the lightdm greeter screen, when I select "sway" and try to log in, it goes blank and then takes me back to the lightdm greeter screen.

Not sure how to fix it. Any ideas on what might be wrong?

Also, can I install manjaro-sway and keep all my existing .config, etc? Or do I have to go for a clean installation?

Thank you :pray:

**Comment by c02y** [comment]
There is a package called `manjaro-i3-settings`, a package like `manjaro-sway-settings` can be provided.

I'm guessing sway edition is not ready yet, and manjaro-sway iso is just for testing?

**Comment by boredland** [comment]
we have got such a package, but those packages name a conflict with others. I am not sure we should change that though.
