### ISSUE TITLE
Some applications opening additional terminal

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#18]
Tested with inkscape

**Comment by boredland** [comment]
problem is (i hope) identified and only relevant for certain applications:
https://github.com/Biont/sway-launcher-desktop/issues/25#issuecomment-756849604
keeping this issue open - creating a pr to work with the edgier cases shouldn't be too hard.

**Comment by boredland** [comment]
we'll be switching to wofi, however for sway launcher desktop I created a pr https://github.com/Biont/sway-launcher-desktop/pull/35

**Comment by masteor** [comment]
I have the same problem with the far2l application-it opens a separate window, but the mc runs in the same terminal window, can I do something about it?

**Comment by boredland** [comment]
> I have the same problem with the far2l application-it opens a separate window, but the mc runs in the same terminal window, can I do something about it?

are you using sway launcher desktop or wofi? (we switched inbetween)

**Comment by boredland** [comment]
no reaction. should work at least in wofi.
