### ISSUE TITLE
How to restart installer?

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#185]
I have canceled the installer and tried to restart it with `Super-D` and then selecting the installer, but nothing happens.

**Comment by boredland** [comment]
ya, visudo and wayland don't play nice (or at least that was a problem in the past). just do `sudo -E calamares` on the command line.

**Comment by xeruf** [comment]
Please add that to the FAQ :)

**Comment by boredland** [comment]
👍🏼 done
