### ISSUE TITLE
Update foot

### ISSUE THREAD

**Issue by hakanyi** [Manjaro-Sway/manjaro-sway#186]
Would it be possible to update the foot (terminal) package? 
How are package updates handled in general? Thanks!

**Comment by Mathew-D** [comment]
Should be fix now just do an update.   Most of the packages are updated by workflow but something seem to stop that one and should be good now.  I just got 1.9.2 from the update.

**Comment by boredland** [comment]
ya, the workflow had issues / got archived due to inactivity for 60 days (a gh policy)
