### ISSUE TITLE
"Support" for NVIDIA Driver >=470 isn't working

### ISSUE THREAD

**Issue by Jerrody** [Manjaro-Sway/manjaro-sway#187]
So, I tried to use Manjaro Sway with proprietary Nvidia Driver, but Sway after installing the driver sends me to hell. But at GitHub page says that Nvidia Driver >=470 are supported by Sway.

After rebooting I get:
use command _--my-next-gpu-wont-be-nvidia_ as always gets man when tries to use the proprietary driver.
So, nothing changed. What's wrong?

Specs:
Processor - Xeon E3-1220 (4 cores, 4 threads)
GPU - NVIDIA GTX 1650 SUPER 4GB
RAM - 12GB

**Comment by boredland** [comment]
> GitHub page says that Nvidia Driver >=470 are supported by Sway

not ours, I think:

> nvidia's 470 drivers and the 5.14 Kernel have just added sway support for proprietary drivers and are known to cause problems.

**Comment by Jerrody** [comment]
> 
> 
> > GitHub page says that Nvidia Driver >=470 are supported by Sway
> 
> not ours, I think:
> 
> > nvidia's 470 drivers and the 5.14 Kernel have just added sway support for proprietary drivers and are known to cause problems.

So, in this case. Need just to wait for when this crap will be fixed. Right?

**Comment by boredland** [comment]
There are recent very promising developments, so I don't think is looks as grim as it did half a year ago. Refer [here](https://github.com/Manjaro-Sway/manjaro-sway/issues/165) if you want to discuss this further and look for pointers.

**Comment by Jerrody** [comment]
> 
> 
> There are recent very promising developments, so I don't think is looks as grim as it did half a year ago. Refer [here](https://github.com/Manjaro-Sway/manjaro-sway/issues/165) if you want to discuss this further and look for pointers.

Roger that.
