### ISSUE TITLE
Config error on fresh install

### ISSUE THREAD

**Issue by branylagaffe** [Manjaro-Sway/manjaro-sway#189]
I installed the daily build from yesterday (1.11.2021), and sway immediately report an error in the configuration's file [96-waybar-config.conf line 4](https://github.com/Manjaro-Sway/desktop-settings/blob/c606b8f6c6962b2afd26641394bee9fc408a6277/community/sway/etc/sway/config.d/96-waybar-config.conf#L4).

**Comment by boredland** [comment]
so.. when you start after the install you get this?

**Comment by boredland** [comment]
just installed the latest image in a VM and did not get any errors...

**Comment by branylagaffe** [comment]
I tried again today with the same build, no issue in a VM then tried again bare-metal.
1. I kept the US keymap before booting, and it ran perfectly
2. Tried again after selecting the CH keymap and couldn't complete the installation because of the post-install script while copy the file from /etc/skel to elsewhere.

**Comment by branylagaffe** [comment]
I don't know if i'm having some sort of edge case where the installation randomly crash or not. I don't know if i want to look further
