### ISSUE TITLE
choosing languages in the install wont scroll on ultrawides

### ISSUE THREAD

**Issue by matthiasdebernardini** [Manjaro-Sway/manjaro-sway#19]
Title, I could use the arrow keys and get it but just wanted to point this out. It's not a problem with other installers of manjaro.

**Comment by boredland** [comment]
hi! thanks for you feedback what is your exact display resolution? perhaps I have a change to reproduce this. just to be safe: you did not install inside qemu, but on a real machine, right?

**Comment by matthiasdebernardini** [comment]
Yes, real machine on my desktop PC. Resolution 2560x1440, it’s an ultra wide. The problem was with that scrolling menu everything else worked fine.

Best Regards,
Matthias

On Jan 9, 2021, at 18:36, Jonas Strassel <notifications@github.com> wrote:

﻿

hi! thanks for you feedback what is your exact display resolution? perhaps I have a change to reproduce this. just to be safe: you did not install inside qemu, but on a real machine, right?

**Comment by kblcuk** [comment]
Fwiw when I was installing on real machine (Lenovo X1e), the language menu was rendered 3/4 outside of the screen. I still could use keyboard and arrows to pick it though, so I wonder if this issue is about Calamares-based installation, or something else :thinking:

**Comment by boredland** [comment]
problem could be, that we're starting the installer non-floating so it probably does behave differently (stretches) in a non-windowed mode.

**Comment by boredland** [comment]
iirc fixed with the new calamares style - closing, but feel free to reopen if persists. in the long term we would like to look into a arch-installer fork.
