### ISSUE TITLE
add matcha theme to qt apps

### ISSUE THREAD

**Issue by vncsna** [Manjaro-Sway/manjaro-sway#190]
I would like to contribute with an "activation" of papirus-dark-maia theme for qt apps, but I don't know where and how. My idea is to install the `qt5-styleplugins` package and then add the following configs:

`~/.gtkrc-2.0`
```
gtk-icon-theme-name = "Papirus-Dark-Maia"
gtk-theme-name = "Matcha-dark-sea"
gtk-font-name = "Cantarell 11"
```

`~/.config/qt5ct/qt5ct.conf`
```
[Appearance]
color_scheme_path=/usr/share/qt5ct/colors/airy.conf
custom_palette=false
standard_dialogs=default
style=gtk2

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x16\0\x44\0\x65\0j\0\x61\0V\0u\0 \0S\0\x61\0n\0s@(\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
general=@Variant(\0\0\0@\0\0\0\x16\0\x44\0\x65\0j\0\x61\0V\0u\0 \0S\0\x61\0n\0s@(\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x14\0\0\a\x7f\0\0\x4K\0\0\0\0\0\0\0\x14\0\0\x2\xde\0\0\x2t\0\0\0\0\x2\x4\0\0\a\x80\0\0\0\0\0\0\0\x14\0\0\a\x7f\0\0\x4K)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
```
This last one is just to change the style option to gtk2 on Qt5 Settings.  
It's possible to visualize the effect opening Manjaro Settings.

**Comment by boredland** [comment]
hm, I tried this and it did not seem to change a lot/anything for me. then again: I already seem to have had both of these files, but don't know where they came from.

**Comment by boredland** [comment]
this is what manjaro-settings-manager looks for me on stock manjaro sway: 
![image](https://user-images.githubusercontent.com/4662748/149164140-e169c31a-eaa3-415e-b652-075fbad0c348.png)

**Comment by nnuel** [comment]
![2022-01-13T10:04:51,517520366+01:00](https://user-images.githubusercontent.com/4148154/149299303-6b5c0a40-8865-409a-bb79-df1fa5b28b6c.png)

Also here it shows white and I had it with other QT apps though. I don't think I have touched any QT settings or install any packages, so it is about as default.

**Comment by boredland** [comment]
@nnuel you can try and install `manjaro-sway-settings-git` and then
then:
```
cp -rf /etc/skel/.gtkrc-2.0 ~/
cp -rf /etc/skel/.config/qt5ct/qt5ct.conf ~/.config/qt5ct/qt5ct.conf
```

**Comment by nnuel** [comment]
Thanks, I could see that nothing was there in the personal config. So I had to do a `mkdir .config/qt5ct` in order for the second command to work. Then it looked dark, but slightly different and then I remembered that I had installed Kvantum manager, as I had seen that being installed before, or saw other people use it.

Not sure if it is exactly the same, but at least it's the dark mode, and that already goes a long way in making it look similar. 
![2022-01-13T10:46:06,210349272+01:00](https://user-images.githubusercontent.com/4148154/149306120-3f6c39d2-990d-4fe7-a7ff-d04f232f970a.png)

**Comment by boredland** [comment]
this is how it is supposed to look. what exactly did you have to do to make it look like that?

**Comment by nnuel** [comment]
```
cp -rf /etc/skel/.gtkrc-2.0 ~/
mkdir ~/.config/qt5ct
cp -rf /etc/skel/.config/qt5ct/qt5ct.conf ~/.config/qt5ct/qt5ct.conf
```

I did install Kvantum manager, as it was removed with one of the updates, but I am doing this from memory. 
There I selected `Matchama-Dark`, and I am not sure if I did much else.

Not sure if I did anything else. But if anything comes to mind, I will share here.

**Comment by boredland** [comment]
I wonder if one really needs to select anything in kvantum manager or if that should be set by qt5ct.conf already. Will try as soon as https://github.com/manjaro/manjaro-iso-action/pull/27 is fixed.
