### ISSUE TITLE
Release torrent's don't work

### ISSUE THREAD

**Issue by actualdankcoder** [Manjaro-Sway/manjaro-sway#191]
If you attempt to download the newer releases via the torrent, there will be no seeders

**Comment by boredland** [comment]
true. we should either make them work or remove them.

**Comment by xeruf** [comment]
Also, they only download the first part of the archive, making them truly useless. Since you seem to rely on github anyways, just let them handle the traffic and remove the torrents ^^

**Comment by boredland** [comment]
put up a PR to remove those.
