### ISSUE TITLE
Obsolete foot and foot-terminfo

### ISSUE THREAD

**Issue by hakanyi** [Manjaro-Sway/manjaro-sway#193]
New releases are available on AUR but not in manjaro-sway -- do Github workflows need updating again? 

Note that 1) this issue is also blocking an `ncurses` update, and 2) you may want to add a `TERM=foot-extra` to `foot.ini` in order to continue using foot's terminfo after the update. 
See the latest comments here: https://aur.archlinux.org/packages/foot/

**Comment by boredland** [comment]
should we be targetting tmux? I guess for most users, defaulting to `xterm-256color` would be just fine, wouldn't it?

**Comment by hakanyi** [comment]
I think it's fine to simply use the `ncurses` terminfo, see also here:https://codeberg.org/dnkl/foot/src/branch/master/INSTALL.md#other. In that case, `foot-terminfo` is not needed anymore and should be uninstalled.

For `ssh`ing, the alias in the default `.zshrc` is to use `xterm-256color` anyways.

**Comment by boredland** [comment]
on the other hand: there is no real harm, according to that readme. and a couple of addons for the tmux'ers among us. I'll just merge your patch.

**Comment by hakanyi** [comment]
Thanks! `foot-extra` seems to be incompatible with `manjaro-zsh-config`, though:
```
/usr/share/zsh/manjaro-zsh-config:bindkey:86: cannot bind to an empty key sequence
/usr/share/zsh/manjaro-zsh-config:bindkey:87: cannot bind to an empty key sequence
```

I recommend reverting that change (and hence keep using `ncurses` terminfo) for now.

**Comment by Zeioth** [comment]
I updated the system and now foot is throwing this error when I open it:

    /usr/share/zsh/manjaro-zsh-config:bindkey:86: cannot bind to an empty key sequence
    /usr/share/zsh/manjaro-zsh-config:bindkey:87: cannot bind to an empty key sequence
zeioth@zeioth-pc Linux 5.14.18-1-MANJARO x86_64 21.2.0 Qonos
    /home/zeioth/.zshrc:bindkey:295: cannot bind to an empty key sequence
    /home/zeioth/.zshrc:bindkey:296: cannot bind to an empty key sequence
    ~ >

**Comment by boredland** [comment]
I am confused. On my machine 

```
/usr/share/zsh/manjaro-zsh-config:bindkey:86: cannot bind to an empty key sequence
/usr/share/zsh/manjaro-zsh-config:bindkey:87: cannot bind to an empty key sequence
```

occurs only as soon as I uninstall foot-terminfo

**Comment by hakanyi** [comment]
This is how I reproduced the error after observing it for the first time:
1. Override `term` in `~/.config/foot/foot.ini` to `term=foot`, then run `foot` (not as a client, but a separate instance) -- observe that everything's working fine
3. Revert back to `term=foot-extra`, run `foot` and observe the error

**Comment by boredland** [comment]
```
$ pacman -Q foot
foot 1.10.0-3
$ pacman -Q foot-terminfo
foot-terminfo 1.10.0-1
$ cat .config/foot/foot.ini
include=/usr/share/sway/templates/foot.ini

# rename to foot.ini and add your custom foot overrides hereafter
# font=RobotoMono Nerd Font Mono:size=11
dpi-aware=true
term=foot-extra
```

**Comment by hakanyi** [comment]
I could've sworn I tested before uninstalling `foot-terminfo` :D 
Anyways, re-installing `foot-terminfo` and reverting to `term=foot-extra` seems to be resolving the issue for me similar to @boredland.

That still leaves this, though:
> I tried with:
> 
> ```
> yay -S foot-git foot-terminfo-git
> ```
> 
> With the same result.

In case it helps debugging, to add to the above:
```
$ yay -Q manjaro-zsh-config
manjaro-zsh-config 0.22-2
```

**Comment by boredland** [comment]
soo... this issue is nearly resolved, isn't it? `term=foot-extra` is part of the defaut ini now and no changes are required from the users perspective.
Only remainder: adding foot-terminfo to the settings package dependencies.

**Comment by hakanyi** [comment]
Agreed. Thanks a lot and sorry for the confusion!

**Comment by Zeioth** [comment]
My prev issue still remain, I'll research what's going on after work.

**Comment by boredland** [comment]
Ah, sorry I thought it was the same issue.

**Comment by Zeioth** [comment]
Hey sorry for the delay:

I fixed the issue by adding this line to ~/.config/foot/foot.ini

    term=foot-extra

The new foot is supposed to get the value of term from ncurses by default (or that's what AUR says), but doesn't seem the case for me.  Ready to be closed.

**Comment by Mathew-D** [comment]
Doesn't /usr/share/sway/templates/foot.ini already have that line?

**Comment by Zeioth** [comment]
I checked and yes it does. Most likely this was caused by my local config:

``` bash
# I was using include in foot.ini like
~/.config/foot/base.ini → foot.ini
# instead of 
/usr/share/sway/templates/foot.ini → foot.ini
```

This is something I usually do to avoid breaking changes from upstream but this time backfired.
Thank you.
![screenshot_2021-11-22_22-45-37_600619753](https://user-images.githubusercontent.com/3357792/142939724-f7c0e19d-27ae-476c-a51f-bd94afa1dde6.png)
