### ISSUE TITLE
[Minor issue] on tuigreet: --remember doesn't work with the version in the repo

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#194]
Under /etc/greetd/config.toml we have the line

    command = "tuigreet --remember --time --issue --asterisks --cmd sway"

Just letting you know that the argument --remember doesn't do anything with the version of the package included in manjaro-sway repos. I installed 'yay -S greetd-tuigreet-git', reboot, and now show the latest logged user.

So updating it to the newest version should fix it.
Cheers.

**Comment by Zeioth** [comment]
Tested on yesterday's build.

**Comment by Zeioth** [comment]
yay -S greetd-tuigreet-bin also fixes it, so it's probably safest as it is an stable version.

**Comment by boredland** [comment]
guess the rebase on aur is just stuck, haven't been using passwort login for a long time (fprintd), so I had no chance to really test this.

**Comment by boredland** [comment]
updated greetd and tuigreet. would be interesting if it work for you now!

**Comment by Zeioth** [comment]
Thank you for the fast response!!

I've done 

    sudo pacman -Syyu
    sudo pacman -S sudo pacman -S greetd greetd-tuigreet

Restarted the computer a couple times, and I can confirm it works as expected now!
