### ISSUE TITLE
changing gui fonts is too hard

### ISSUE THREAD

**Issue by l-j-g** [Manjaro-Sway/manjaro-sway#196]
Changing the GUI font is pretty difficult due to hard configuration to use Roboto 11 in assorted configuration files. 

Some files i have identified so far that need to be changed are: 

/usr/share/sway/templates/waybar 
/etc/sway/definitions/ 
/usr/share/sway/templates /foot.ini

ect. 

I'm aware the distro has been setup to reference user configs set in .config,  to prevent overwrite during updates however its pretty tedious to find and check the syntax for all of the possible files - 

Wouldn't it make more sense to reference monospace in font-config in these files. 
Then if the user wants to change a different font they would only need to change the fonts.conf.

If you agree. that this is the way, I would be willing to prepare a pull request, all though i am a bit of a n00b. 

rgds

**Comment by Mathew-D** [comment]
Most of the font name and size is setup in the theme definitions files: (/usr/share/sway/themes/matcha-green/definitions)

set $gui-font Roboto 11
set $term-font RobotoMono Nerd Font 14

Those vars will change MOST of the font setup for sway.  There are a few spots that seem to be missed
/etc/sway/definitions (only the clipboard uses hard coded the rest of the file comes from the theme)

The following I don't know how we would change it to use the vars from the theme.
/usr/share/sway/templates/waybar/style.css ( font-family: "RobotoMono Nerd Font", "Roboto Mono", sans-serif;) 
/usr/share/sway/templates/foot.ini  (font=RobotoMono Nerd Font Mono:size=8)

**Comment by Mathew-D** [comment]
Also if you want to change the theme which would include the fonts from the default I would change the 
set $theme /usr/share/sway/themes/matcha-green
in the ~/.config/sway/config to point to a new theme setup.  matcha-green is the default theme but if you copy it somewhere else and change that var to the new copy you can change most of the look of sway from there.
