### ISSUE TITLE
Qt Applications: Menu doesn't respond

### ISSUE THREAD

**Issue by mireiner** [Manjaro-Sway/manjaro-sway#197]
For Qt applications (newly installed) the menu doesn't respond. When clicking on a menu item with the mouse, no dropdown menu appears. This was tested with KWrite, Kate, Dolphin or Krusader and the latest manjaro-sway-21.1.0-211123-linux515.iso

**Comment by mireiner** [comment]
I have installed on hard disk. But have no experience with Sway. May be I am doing something wrong?

I have installed on hard disk so far:
1. Manjaro/Sway
2. EndeavourOS/Sway Community Edition
3. Calam-arch-installer (vanilla-arch) with Sway installed by me.

All three installations are showing the same Qt application menu error. The only unusual thing is, that I use the refind boot manager.

But refind boots also Vanilla-Arch with KDE-Plasma and Vanilla-Arch with Gnome 41 Desktop on other partitions of my multi-boot hard drive. And on them Qt programs run flawlessly. All Vanilla-Arch installations run on Linux kernel 5.15.4-arch1-1 x86_64.

No idea why the Qt menu problem occurs with me and not with you?

**Comment by boredland** [comment]
I only tried Kate. I'll try later on a fresh live iso, perhaps that helps...

**Comment by mireiner** [comment]
I have found the cause. It is the GUI scaling. 

I have a monitor with 2560x1440 resolution. If following is added to ~/.config/sway/config.* :

output DP-1 mode 2560x1440 pos 2560,0 scale 1.5
or
output DP-1 mode 2560x1440 pos 2560,0 scale 2

the menus no longer respond in KDE and some Qt applications doesn't work anymore.

Is there any workaround for this problem?

**Comment by boredland** [comment]
If that is right, you surely are not alone. Have you checked issues at sway? I currently have only scaling 1 and 2, so no fractions. I Think I remember issues when people had two digit decimals.

**Comment by mireiner** [comment]
I got the menu problem also with integer scaling 2. Will check for reported sway issues now. This issue here can be closed.

Off-topic, but by the way: The language settings set in the installer (German for me) are not applied in the Manjaro Sway installation. The keyboard stays "US" and the weekdays of the clock the same.

Good luck!

**Comment by boredland** [comment]
Hi there! I started working on a patched version of calamares, the installer, a while back, but had no time to continue yet. In short: we'd need our own keyboard module for it. It's doable. Or we disable the keyboard module so people aren't led to think this could work out of the box.

**Comment by mireiner** [comment]
Found a solution. Just define the scaling in ~/.config/sway/config:

output * scale 1.5

And the menu problem is gone. No need to explicitly specify the monitor output and the resolution etc..
