### ISSUE TITLE
Open new terminal on cwd

### ISSUE THREAD

**Issue by fraunos** [Manjaro-Sway/manjaro-sway#198]
Hi,
I think this is a cool feature, there's a script - swaycwd that can be used with foot like this
`foot -D $(swaycwd)`
and then the new terminal has the same working path, which is handy imo.
I added this myself to /usr/share/sway/scripts/foot.sh, but I'm not sure if it is the best place, plus I have no idea how to add dependencies to the install, otherwise I would open a PR already :p

**Comment by boredland** [comment]
same as what? the already opened foot terminal? Sounds neat!

**Comment by boredland** [comment]
ah, I see. its the tiniest of bash [scripts](https://github.com/qiu-x/swaycwd). we could just copy it to our scripts dir for example. that would be another or a replacement for our current terminal keybind?

**Comment by fraunos** [comment]
@boredland  I'm using a version from AUR, which is based on an idea from a Reddit thread
https://aur.archlinux.org/packages/swaycwd/ https://aur.archlinux.org/cgit/aur.git/tree/swaycwd?h=swaycwd
https://www.reddit.com/r/swaywm/comments/ayedi1/opening_terminals_at_the_same_directory/ei7i1dl/
