### ISSUE TITLE
Restoring HOME

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#199]
I setup a new Manjaro Sway installation but did not properly set it up. Then I deleted the partition that contained my home directory, thinking it was not that important, as I needed the space.
Now when I boot, Sway shows an error and I have no idea how to do anything.

Through https://github.com/Manjaro-Sway/manjaro-sway/issues/174 I found https://github.com/Manjaro-Sway/desktop-settings.
Will installing `manjaro-sway-settings` suffice to restore the relevant files?

**Comment by boredland** [comment]
No, you need to [copy in your dotfiles](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-do-i-upgrade-the-config-after-an-update)

**Comment by xeruf** [comment]
Thanks! I did `cp -rf /etc/skel/.??* ~` and it worked :)

In the live ISO, basic key combinations where listed in the bottom left, was this part of the wallpaper or some option? How can I get that back?

**Comment by boredland** [comment]
Thats available via a shortcut, given you have nwg-wrapper on your machine. Then it should be Super + ?

**Comment by xeruf** [comment]
Thanks, works flawlessly :)
