### ISSUE TITLE
Update tuigreet

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#200]
The currently packaged version is quite outdated and missing crucial features, see https://github.com/apognu/tuigreet/issues/48#issuecomment-988361369

**Comment by Mathew-D** [comment]
I am running the current version from manjaro and when I run tuigreet -v, I get:
tuigreet 0.7.1 (x86_64-unknown-linux-gnu)

So when you update manjaro it will update to 0.7.1

**Comment by xeruf** [comment]
Sure, but for that I need to set up an AUR helper. It would be nice to prepackage it so it is also available in the live ISO.

**Comment by boredland** [comment]
The only explanation could be that theanjaro repos contain an outdated version. Manjaro Sway has had the current version for ages.

**Comment by boredland** [comment]
You don't need an aur helper. The Manjaro Sway repo does have that version. See https://packages.manjaro-sway.download/x86_64/greetd-tuigreet-0.7.1-1-x86_64.pkg.tar.zst

**Comment by xeruf** [comment]
Well, after updating my manjaro-sway system I still don't have power options. I will check again. But why not simply update the packaged version?

**Comment by boredland** [comment]
well, it is not us, its manjaro upstream who have that super old version. for now, just install `manjaro-sway/greetd-tuigreet`. I will ping them to remove it from the community repo so our version will be pulled in releases.

**Comment by xeruf** [comment]
Ah, thank you :)

**Comment by xeruf** [comment]
Yes, I had to manually run `sudo pacman -Syu manjaro-sway/greetd-tuigreet`, simple system update didn't cut it. 
Can't you configure the image so it includes your version? Or prompt upstream to update?

**Comment by boredland** [comment]
> Or prompt upstream to update?

As I wrote: asked upstream to drop it so our version is the only one. I could specify that our build should take our version during build, but this would lead to a constant and annoying warning in pacman that upstream has a different version.

**Comment by xeruf** [comment]
I get that warning anyways after upgrading ^^ but why should upstream drop it rather than updating it, making your separate version obsolete?

**Comment by boredland** [comment]
soo, it is gone from community and tonights build will have the latest version. and it should show as an update for all others.

**Comment by xeruf** [comment]
thank you very much for all the quick assistance :)
