### ISSUE TITLE
Increase shortcut help font size

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#201]
I am very eager to learn Sway, but the shortcut reference is so small I can hardly read it on my 4k monitor :/ any way to adjust that?

**Comment by boredland** [comment]
I've got a 4k screen too and can read it just fine. That is the problem with things that relate to the resolution - they vary depending on you physical screen size etc. You can try and add a font size inside the css of nwg-wrapper: `.config/nwg-wrapper/style.css` You can display the menu in a terminal too:  just run `.config/nwg-wrapper/help.sh`

**Comment by xeruf** [comment]
thank you! The issue in my case might be that I have my monitors arranged vertically

**Comment by xeruf** [comment]
setting `font-size: 40px` worked nicely :)
