### ISSUE TITLE
Enable TRIM by default

### ISSUE THREAD

**Issue by Zeioth** [Manjaro-Sway/manjaro-sway#202]
I noticed manjaro doesn't do this by default. Since most hard disks nowadays are SSD/Nvme, this might be a good idea maybe. It increases performance and make disks last longer.

Currently it can be manually enabled like:

    sudo systemctl enable fstrim.timer

**Comment by boredland** [comment]
imo we could enable that by default.

**Comment by boredland** [comment]
ehm, just wanted to do that just to discover this should be enabled by default in our distro:
https://github.com/Manjaro-Sway/iso-profiles/blob/b7bb079d3bcc74c3113334f3633e10e2d94d0413/community/sway/profile.conf#L37

Let me know if this is broken or sth, but I think this is already done.
