### ISSUE TITLE
feature request: fahrenheit option for weather module

### ISSUE THREAD

**Issue by bdefore** [manjaro-sway/manjaro-sway#203]
changing all of the instances of 'FeelsLikeC' in weather.py to 'FeelsLikeF' allow me to have the tray module use fahrenheit instead. would be nice to parameterize this for users, maybe setting a `$measurement-scale` in config? i'd recommend not applying this across modules though since many like me would prefer celsius for hardware temperature readings even as fahrenheit is more natural for weather.

**Comment by boredland** [comment]
Fahrenheit is used in afaik exactly one country of the earth, so not a priority for me tbh. Would accept a contribution though.

**Comment by bdefore** [comment]
i admit it's an arcane legacy. unfortunately, even though it's one large holdout country, i expect it's preferable for a substantial portion of the userbase of manjaro-sway. i could cook up a PR but it's also low priority for me.

for anyone following and for accuracy sake, the weather.py also has cases of `maxtempC`, `mintempC`, and `temp_C`, each of which have equivalents suffixed with 'F' instead. there's also a few places where imperial system users might prefer miles to kilometers, which are more straightforward to substitute (Kmph -> Miles)

https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/usr/share/sway/scripts/weather.py
example weather api response: https://wttr.in/?format=j1

**Comment by YannickLehr** [comment]
> there's also a few places where imperial system users might prefer miles to kilometers, which are more straightforward to substitute (Kmph -> Miles)
> 
https://www.youtube.com/watch?v=GDUt-Kbxqsg

**Comment by boredland** [comment]
It should be in the manjaro-sway-settings-git package. For users with appropriate LC_MEASUREMENT setting, this shouldn't be a breaking change.
