### ISSUE TITLE
replace blueberry with rofi-bluetooth

### ISSUE THREAD

**Issue by bdefore** [manjaro-sway/manjaro-sway#204]
to reproduce:
- open blueberry by clicking tray icon
- click an available device to connect to, another modal will pop up with details about it
- click the parent modal
- submodal hides behind parent, unreachable and parent becomes unresponsive

workaround: killing the blueberry process

**Comment by boredland** [comment]
better workaround:

- move the blueberry window (Super +  Shift + Arrows)
- stash the blueberry window (Super + Shift + - ), do whatever, unstash the blueberry window (Super + -)

**Comment by boredland** [comment]
Did you have sth else in mind? What would have been your expected behavior?

**Comment by bdefore** [comment]
ideally the parent two models don't become unresponsive in this case. one
not receiving clicks and the other trapped beneath.

**Comment by boredland** [comment]
that is not sway related, I think. As I understand it, blueberry makes the primary window "unclickable" as soon as a device window opens.

**Comment by boredland** [comment]
Perhaps we can indidicate in waybar how many instances of a window are open.

**Comment by bdefore** [comment]
perhaps there's a bug (in blueberry?) that the primary window is clickable when a device window is open.

**Comment by boredland** [comment]
good point. it is at least fishy that you can't move the inactive main window. at least we should make sure this is different elsewhere. quick fix would be to disable the auto-floating for blueberry (perhaps it is possible to only enable it for the device window?).

**Comment by bdefore** [comment]
disabling auto-floating would be a degraded experience. perhaps also surprising to me is that Super - Shift - Q does not quit blueberry in this state.

**Comment by boredland** [comment]
or: we find a nicer bluetooth management tool. sth similar to nmtui would be amazing.

**Comment by hakanyi** [comment]
It's obviously not a TUI, but [rofi-bluetooth](https://github.com/nickclyde/rofi-bluetooth) that uses `bluetoothctl` works pretty well for me. That project is inspired by [networkmanager-dmenu](https://github.com/firecat53/networkmanager-dmenu) which I'm also using.

**Comment by boredland** [comment]
i mean, it is worth a try then, isn't it. we have rofi anyway.

- [ ] add rofi bluetooth to package repo
- [ ] call it in waybar
- [ ] drop blueberry

**Comment by boredland** [comment]
while I added to our repo now, I think we'd probably want to change it in a way to support our rofi theme. or is that working out of the box somehow?

**Comment by hakanyi** [comment]
We could make it accept rofi arguments (with defaults) and then define the command similar to how the app launcher is set up in sway's `definitions`.
The out-of-the-box way would be to compile the theme into rofi's config (which I know is not super straight forward).

**Comment by boredland** [comment]
Since rofi bluetooth is just a simple script, we could probably just contribute a PR [there](https://github.com/nickclyde/rofi-bluetooth/blob/893db1f2b549e7bc0e9c62e7670314349a29cdf2/rofi-bluetooth#L302) to support either additional params or a custom rofi command.

**Comment by boredland** [comment]
:tada: 

[recording_20220831-134448.webm](https://user-images.githubusercontent.com/4662748/187671077-635e9832-8f65-4769-9605-5aed30298a7e.webm)
