### ISSUE TITLE
feature request: battery indicator on top bar

### ISSUE THREAD

**Issue by tychi-nflx** [Manjaro-Sway/manjaro-sway#205]
Excellent work on this distro! I've been using it happily for about a month now as a daily driver.

The only quality of life improvement that I think would be nice out of the box is a battery indicator on the top bar. My laptop has died on me a few times while working because I wasn't aware on how dire my current situation was.

I know this is something I should be able to configure and will get to it eventually, but wanted to share since I think for newer users this missing feature could be a deal breaker for adoption.

**Comment by boredland** [comment]
what would you like on it to be improved? right now it just starts shimmering orange when battery-life is down to 30%. My personal experience is, that this just is to early and I think "oh well, it will be good for another two hours" so I end up with is (nearly) dying. so probably we can just lower that threshold?

**Comment by tychi-nflx** [comment]
The whole bar shimmers orange or a battery icon turns orange. I haven't seen either so far. The icons on my bar in order currently:

weather, keyboard layout, clipboard, cpu, memory, temp, wifi, bluetooth, zzz, audio, brightness, lightbulb.

if there was an orange battery icon (or the whole bar turning orange) at 30% that'd be perfect, i just haven't seen that for this month so far.

for additional context (not sure if this matter) running https://frame.work with an i5, 16gb memory, 250gb hdd.

**Comment by boredland** [comment]
ah, no. then there is def. sth wrong. this is how it "should" look on a notebook:

![image](https://user-images.githubusercontent.com/4662748/146453356-d57dc2d2-8410-41b9-8808-ddd97304481d.png)

iirc, the waybar battery module searches for the battery level on dev `BAT0` by default.

what is the output of ` ls /sys/class/power_supply/BAT*/capacity` on your machine?

**Comment by tychi-nflx** [comment]
ahh, that'll probably be it then, looks like I'm getting BAT1 back from that `ls`.

`/sys/class/power_supply/BAT1/capacity`

where should I go to update that?

(also big thanks for helping debug and doing so this quickly :)

**Comment by boredland** [comment]
hm. I think we can fix that on our side. Apparently we set it to BAT0 and thus are overriding the auto-detect 😊

**Comment by boredland** [comment]
you can give `pacman -Syyu manjaro-sway-settings-git` a try for the newest development version. for me nothing changed, which is a good sign..

**Comment by tychi-nflx** [comment]
yesss, this works now, thanks so much! do you have a link for donations for your work?

**Comment by boredland** [comment]
glad to hear it works! we did not yet see the need to accept donations ourselves and are not really developing (a lot) of software, mere configuring it. BUT we have this little section about [important upstream projects one could donate to](https://github.com/Manjaro-Sway/manjaro-sway#conations).

**Comment by Mathew-D** [comment]
The battery module now loads even if you are on a desktop

**Comment by boredland** [comment]
@Mathew-D s issue is documented [here](https://github.com/Alexays/Waybar/issues/972) already.

**Comment by boredland** [comment]
We could think about sth like this for battery alerts: https://www.reddit.com/r/swaywm/comments/rhrj9e/low_battery_alerts/hoscueg?utm_medium=android_app&utm_source=share&context=3
