### ISSUE TITLE
No builds

### ISSUE THREAD

**Issue by bittin** [Manjaro-Sway/manjaro-sway#209]
Hello!

Got no Manjaro Sway builds end of December last year and start of January this year

**Comment by boredland** [comment]
Hi! This is due to me accidentally firing tons of requests against one of my applications with my hosting provider - basically I launched a DDOS attack on myself by accident. Currently clarifying how I can get the things back online, shouldn't be long.

**Comment by boredland** [comment]
Its clarified

**Comment by boredland** [comment]
https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202201011255

**Comment by bittin** [comment]
nice

**Comment by bittin** [comment]
No builds for a couple of days now

**Comment by nnuel** [comment]
> No builds for a couple of days now

IIRC it's been set to building once a week.

**Comment by bittin** [comment]
@nnuel oh did not know that, thanks for the information

**Comment by boredland** [comment]
Ya, after a year of development, I feel it is not changing often enough to have daily builds and we trigger rebuilds automatically when the iso-profile changes.
