### ISSUE TITLE
Brightness buttons seem to take single increment steps, instead of bigger ones.

### ISSUE THREAD

**Issue by nnuel** [manjaro-sway/manjaro-sway#212]
It takes about a minute to go from lowest brightness to highest brightness. 

Not sure if it is related to this latest commit: [Brightness RAW](https://github.com/Manjaro-Sway/desktop-settings/commit/f8c508450b607b17f23f01d4e770008e1f589854)

It was working before and I doubt I dabbled with the settings myself, but that could very well be. 
New to the sway-edition and I think it's great and very easy to work with, once I understand what parts do what. 

Also: Is there a specific place where manjaro-sway discussions are centered or are they meant to take place here on github?
Not sure if there is an IRC or a Discord or the Manjaro forum. 

I am working on a GPU %-indicator module for the waybar, which I have sort of working for the dGPU, and working now on the intel iGPU, mostly as a learning project, but an indicator of whether the dGPU is running/rendering would be helpful as a minimal icon.

**Comment by nnuel** [comment]
Yes, it takes about 8 or 9 presses of the brightness down button, for it to register as a 1% decrease.

**Comment by hakanyi** [comment]
Same here.
The weird thing is that the latest commit is not yet available to me. Had to test this by manually updating my config to reflect the latest commit.

**Comment by boredland** [comment]
this surely is related to the latest commit (and not released yet afaik). it is hard to find a solution that suits everyone due to how "[light](https://man.archlinux.org/man/community/light/light.1.en)" works. 
It had the additional parameter "T" that allows an increase by percentage so perhaps we should use that instead. See my thoughts so far [here](https://github.com/Manjaro-Sway/desktop-settings/pull/86).

**Comment by hakanyi** [comment]
I think `light -A 5` is already interpreted as percentage: 

> Increase backlight brightness by 5 percent
https://github.com/haikarainen/light

**Comment by nnuel** [comment]
Cheers, I didn't even know about that command, as I am new to most of this. 
I will most likely make a bindsym to quickly go to max brightness and one for minimum brightness, and from there I can go to the slower and more fine-tuned scrolling. 

Thanks for linking the 'light' page, will have a read through that next.

A small update on the iGPU % indicator, there's most likely a bug in the JSON output of 'intel_gpu_top', so it can only give the initial value, but can't update like the values of htop can, due to a missing bracket. So I hope that can get fixed relatively soon, so I could further work on that module for waybar. The radeon (AMD) one works, but the code could use some polishing, as I copied it from another redditor. 

Eventually, both the iGPU and dGPU indicators could use the same value, and make use of the tooltip.

**Comment by boredland** [comment]
this works, as long as the scale of your device is so, that 5% of your scale is greater than 1 single increment on your scale. If your scale is 1-15 (which it is on a lot of devices according to arch wiki), then 5% is lower than 1. And then upping it by 5% wont do anything.

**Comment by nnuel** [comment]
Clear, so we need to find a way that works for both?

In the meantime, I have added these two bindsyms that just go to min/max the brightness.

```
bindsym shift+XF86MonBrightnessDown exec light -S 1
bindsym shift+XF86MonBrightnessUp exec light -S 100
```

Probably this needs some check as to what the minimal step is, percentage-wise. But the 100 must clearly work for all the other devices, I would think.

**Comment by boredland** [comment]
What would do: dynamically calculating the minimum percentage needed and taking it if its bigger than e.g. 5%. That should be possible.

**Comment by nnuel** [comment]
So, not sure if you'd have to both check 'intel_backlight' and 'acpi_video0', but the former gives me:

```cat /sys/class/backlight/intel_backlight/max_brightness
937```

which seems to make sense with the roughly 9 presses for a 1% increase.

On the [wiki](https://wiki.archlinux.org/title/backlight#ACPI) here they mention the 15 value, like you said:

```cat /sys/class/backlight/acpi_video0/max_brightness
15
```

So we should do a check there, but I am not sure if we can make the `backlight/$VARIABLE/max_brightness. Because you'd need to check for the correct device/driver thingy. 

But once that is done, I think it can work as intended.

**Comment by nnuel** [comment]
Maybe rawmode should work. And if the `max_brightness > 15` or 20, then go for percentages, and if lower go for the raw steps. I like the extra granularity, but as a first interaction, it seems really to be broken, but with the SHIFT bindsyms, it works rather well for my usecase at least, so I will keep that. 

But in general 15 or 20 stepped brightness works much better and intuitive.

**Comment by boredland** [comment]
there hopefully are be better ways, but how about:

```bash
MAX_BRIGHTNESS=$(light -O && light -S 100 && light -r -G && light -I)
FIVE_PERCENT=$( printf "%.0f\n" $(( MAX_BRIGHTNESS * 0.05 )) ) 
BRIGHTNESS_RAW_STEP=$( [ $FIVE_PERCENT -ge 1 ] && echo $FIVE_PERCENT || echo 1  )
```

**Comment by boredland** [comment]
if that percentage works, it should be really easy to add this add a little script that gets called.

**Comment by hakanyi** [comment]
@boredland Note that the max raw value can be obtained by `light -Mr`. 
See https://github.com/haikarainen/light/issues/128

**Comment by boredland** [comment]
very good find. so, imo we can determine it using this:
```bash
 printf "%.0f\n" $(( $(light -Mr) * 0.05 )) | grep -Eo '[1-9]{1}[0-9]{0,3}' || echo 1
```

**Comment by hakanyi** [comment]
This will do it as well as `light -r -A` does tolerate floats.
```bash
echo $(( $(light -Mr) * 0.05 < 1 ? 1 : $(( $(light -Mr) * 0.05 )) ))
```

**Comment by boredland** [comment]
you may try this as for example .config/sway/config.d/04-brightness.conf:

```bash
set $brightness_step bash -c 'echo $(( $(light -Mr) / 100 * 5 < 1 ? 1 : $(( $(light -Mr) / 100 * 5 )) ))'
set $brightness_up light -r -A $($brightness_step) 
set $brightness_down light -r -U $($brightness_step)

$unbindsym XF86MonBrightnessUp
$unbindsym XF86MonBrightnessDown

$bindsym XF86MonBrightnessUp exec $brightness_up && $onscreen_bar $(light -G | cut -d'.' -f1)
$bindsym XF86MonBrightnessDown exec $brightness_down && $onscreen_bar $(light -G | cut -d'.' -f1)
```

**Comment by nnuel** [comment]
Yes, this works great! in 20 steps for me in the test file. 
The only thing that would make it more optimal, would to go with the lowest possible value before going fully dark. So more granularity between 0-5%. As that's where each value matters more than let's say 95-100%. I will have a think on how to implement that, but it's been helpful to see how this all works. I didn't know about the onscreen_bar, but another smaller bug is the muted microphone, that only fills up half the bar, instead of the full bar.

Will see if I can fight the right code for this and whether this is also device specific. Either it can be made 100 as in full, or you could show the strength of the microphone input from the pulseaudio.

**Comment by boredland** [comment]
We can set the minimal value to 1 on boot using `light -N 1`. The other point I don't really get tbh.

This is how the audio bar looks for me:

https://user-images.githubusercontent.com/4662748/148132664-fa88c635-21cf-4da0-b20d-ab42fa4ccf28.mp4

**Comment by nnuel** [comment]
Ah, in that case it works as intended. It might have been that I had set my mic to 50% and therefor it looked like it was either zero or one, and then stuck in the middle. 

So it already did show the strength of the mic, I just hadn't checked or wasn't aware.

**Comment by xeruf** [comment]
For whatever reason, this does not work for me on a framework laptop:
```sh
❯ brightnessctl
Device 'intel_backlight' of class 'backlight':
	Current brightness: 1 (0%)
	Max brightness: 96000
# Lots of brightness-up-presses (Fn+F8)
❯ brightnessctl
Device 'intel_backlight' of class 'backlight':
	Current brightness: 1 (0%)
	Max brightness: 96000
```

**Comment by boredland** [comment]
well, there may be a rounding issue :/ here you can see which is the minimal step: https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/sway/definitions#L37

would be interesting what that is on your machine.

**Comment by xeruf** [comment]
Looks all fine and dandy:
```sh
❯ echo $(( $(light -Mr) / 100 * 5 < 1 ? 1 : $(( $(light -Mr) / 100 * 5 )) ))
4800
❯ bash -c 'echo $(( $(light -Mr) / 100 * 5 < 1 ? 1 : $(( $(light -Mr) / 100 * 5 )) ))'
4800
❯ light -S 1
❯ light
1.00
❯ brightness_step=4800
❯ light -r -A $brightness_step
❯ light
6.00
```

Maybe the key itself is not recognised correctly?

**Comment by xeruf** [comment]
Aha, `showkey` does not show the keys indeed ^^

**Comment by boredland** [comment]
oh, damn.

**Comment by xeruf** [comment]
Alright, it's a device issue ;)
https://community.frame.work/t/12th-gen-not-sending-xf86monbrightnessup-down/20605/13

So you can close this

**Comment by boredland** [comment]
ah, cool this is going to be tackled in the driver!
