### ISSUE TITLE
autotiling stoped working

### ISSUE THREAD

**Issue by durito28** [Manjaro-Sway/manjaro-sway#213]
Hi,
my sway had a large update yesterday, and now autotiling isn't working.
Has anyone an idea how i can fix it

autotiling -h

Traceback (most recent call last):
File "/usr/bin/autotiling", line 33, in <module>
sys.exit(load_entry_point('autotiling==1.6', 'console_scripts', 'autotiling')())
File "/usr/bin/autotiling", line 22, in importlib_load_entry_point
for entry_point in distribution(dist_name).entry_points
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
return Distribution.from_name(distribution_name)
File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for autotiling

**Comment by hakanyi** [comment]
This might be due to a recent python 3.9 -> 3.10 update. Try to rebuild with yay or pacman, or, for your convenience, follow the instructions given by the most recent Manjaro (stable) [forum post](https://forum.manjaro.org/t/stable-update-2022-01-02-kernels-systemd-kde-frameworks-mesa-xorg-server-wine-python-3-10/97104).

**Comment by boredland** [comment]
I guess we could just rebuild it, as it should use python3.10 now by default. Let's give that a try.

**Comment by boredland** [comment]
as with all python updates since the beginning of time, this seems to be a nightmare. So for some reason it is on python 3.9 in the container and fails because it didn't find wheel: https://github.com/Manjaro-Sway/autotiling/runs/4706436868?check_suite_focus=true

**Comment by boredland** [comment]
soo, after updating the underlying builder image, this should ™️  work now. let me know if it doesn't after an update in ~5minutes.

**Comment by durito28** [comment]
Everything works, thanks for the quick support!!!
And a huge thank you to everyone for this great distro (the best Linux system I've ever used)

**Comment by nnuel** [comment]
Ah, so that is what this was, I got it working with the `exec_always autotiling`, as I thought I had broken something. Commented the line now and autotiling still works. 

Fully agree with @durito28's comment!
