### ISSUE TITLE
Nwg-wrapper not working

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#216]
Fresh install, iso downloaded today. `nwg-wrapper` is installed, config-files work, `.config/nwg-wrapper/help.sh` provides the correct output.
But `SUPER+?` does not show the shortcut help. How can I debug this?

**Comment by boredland** [comment]
nwg wrapper is a python package, so I guess the package is broken due to the major 3.10 release of python being the default now. I will try and iterate the pkgrel and check if I just works before I dig deeper.

**Comment by boredland** [comment]
flashfocus is broken too.

**Comment by boredland** [comment]
you can try `pacman -Syyu` in a few minutes.

**Comment by boredland** [comment]
confirmed both are working after the update.

**Comment by xeruf** [comment]
My savior at hand immediately as usual, enabling me to deliver the fresh laptop with Manjaro Sway to my friend this morning in perfect condition :)

I personally use plain Arch, but this distribution really shines when it comes to bringing in newbies, so I am starting to deploy it on all machines of friends who want full control of their computer even when new to Linux (the casuals get Zorin ;) ). Your responsive support is the icing on the cake of this awesome software stack, reminding me that I finally have to migrate from my hacky KDE Plasma tiling extension to Sway.

The company I work for actually embraces openness (currently I am setting up computers for the company, and the first conversion was the computer of the boss himself ^^) and has a server rack in Frankfurt, so maybe we can meet up sometime?

**Comment by boredland** [comment]
> rack in Frankfurt, so maybe we can meet up sometime

Chances are high that I don't live too far away (I can see the boxy server buildings from my terrace). Sure, get in touch!
