### ISSUE TITLE
Changing sworkstyle icon for 'foot' and 'nvim'

### ISSUE THREAD

**Issue by nnuel** [Manjaro-Sway/manjaro-sway#217]
I am trying to change the 'foot' terminal icon to change in waybar by changing this to the `.config/sworkstyle/config.toml'. The reason being as it is more minimal and works better as a small icon than the default one.

```
'foot' = ''
'/foot/' = ''
'/NVIM/'        = ''
```

It changes, and Neovim also shows the proper vim icon instead of vimeo. However, it gets overruled by the default value in the package, and there doesn't seem to be a way to fix this in the user config file, but it needs a change in the package of sworkstyle.

Not sure if the nerd font will load properly in github, otherwise I will send the direct links.

**Comment by nnuel** [comment]
This is the hex and class of the vim icon, it gets rendered as a B in github, but shows correctly on Sworkstyle.

e62b
nf-custom-vim

if I change the 'foot' app-id, then all the terminals will show the new icon, but it seems that app_id overrules the title setting, that scans for partials. 

So I can either have the new icon for all terminals, also the curses. Or I can have the old terminal icon and a newer vim icon, but I can't seem to be set both correctly,  because the 'foot' app-id is set in the defaults and there's no way to change that.

**Comment by boredland** [comment]
Hi there! I have no strong opinions on that. Please just put up a PR against this file here: https://github.com/Manjaro-Sway/sworkstyle/blob/master/static/default_config.toml Those are the manjaro sway overrides.

**Comment by nnuel** [comment]
I will do, never made a pull request, so bear with me for a bit, if I don't use the right conventions or something goes wrong.

**Comment by nnuel** [comment]
Alright, I think I was succesful, not sure if I both needed to make a fork and also a new branch in that fork. I expect that only the fork would have sufficed.
