### ISSUE TITLE
alacritty doesn't start from mod+enter

### ISSUE THREAD

**Issue by antonwnk** [Manjaro-Sway/manjaro-sway#225]
Thanks a lot for the great experience your distro has given me so far!
I'm having issues with getting alacritty to start when called from the sway shortcut. It is running just fine called from the launcher and from a different terminal.

I know it's actually set as the default, but foot always comes up even after installing alacritty. I tried setting the term variable in the user  files under either ~/.config/sway/config.d/ or ~/.config/sway/definitions.d/ but to no avail.

I also tried to replace foot with alacritty in  /etc/sway/definitions and that stopped foot from starting when running mod+enter but still didn't cause alacritty to start.

Finally, I can rebind other things in my user config, so I know that's working well.

**Comment by Mathew-D** [comment]
There are two var you need to setup in ~/.config/sway/definitions.d/ to change to default term.  The term var changes the mod+shift+enter and the term_cwd change the mod+enter key.  As you can see below I changed mine to gnome-terminal 
##Change terminal
set $term gnome-terminal
set $term_cwd $term

**Comment by boredland** [comment]
@antonwnk closing since solution sounds good. feel free to reopen if it does not work. please have a look into our [faq](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md) section

**Comment by antonwnk** [comment]
yes, it was that absolutely, haha🤦 quite a silly thing to miss.
thanks for the help~!!

**Comment by xeruf** [comment]
Can't find it in the FAQ, and the suggested solution is inadequate: The default terminal for both commands should be set just by overriding $term. Now I had to copy over the definition of $term_cwd, which is brittle...

**Comment by boredland** [comment]
hi there! as probably not all terminal emulators work the same, will have to provide overrides for these two:

``` 
set $term /usr/share/sway/scripts/foot.sh
set $term_cwd $term -D "$(swaycwd 2>/dev/null || echo $HOME)"
```

I just tried the solution proposed by @Mathew-D.

```
set $term gnome-terminal
set $term_cwd $term
```

For me this worked flawlessly.

**Comment by xeruf** [comment]
@boredland the solution works, but you loose the feature from the original config - preserving the working directory.

**Comment by boredland** [comment]
yes, to keep that functionality, you have to read the gnome-terminal  (or whatever terminal you use) manpages.

for gnome-terminal this should work:

```
set $term gnome-terminal
set $term_cwd $term --working-directory "$(swaycwd 2>/dev/null || echo $HOME)"
```
