### ISSUE TITLE
Grimshot scripts no longer in the place where it should be.

### ISSUE THREAD

**Issue by nnuel** [Manjaro-Sway/manjaro-sway#229]
It coincided around the time that I installed Sway-git, because of a newer version that would more easily let me toggle the waybar, in a way that it only showed when I pressed the mod button, as an addition to the more permanent toggle of Mod + Shift + B.

Only soon after I discovered that my screenshot functionality broke, but I am not sure if it still works for others.

![image](https://user-images.githubusercontent.com/4148154/149854379-593f9021-056f-43f6-9234-665d498c43ce.png)

and

![image](https://user-images.githubusercontent.com/4148154/149854568-a4094d02-c905-48af-8f5b-bfd2191683a2.png)

Also on Github it doesn't seem to be there, so maybe it didn't use grimshot for a while then.
Or is this something that gets installed there as soon as the AUR package is installed?

**Comment by boredland** [comment]
grimshot is installed by the sway and by the sway-git package. So the question is more how you removed it...

**Comment by nnuel** [comment]
Yes, reinstalled and everything worked. I would guess then with switching to sway-git. I might change back to the normal one, once 1.7 is stable and see if it gets back.

It must have been with installing the git version that removes grimshot. 
So if I understand correctly, sway installs a standard script of grimshot in the /usr/share/sway/scripts/grimshot location and that's why it is not here in the repo?
