### ISSUE TITLE
Can't open new terminal if current terminal is in path with whitespace

### ISSUE THREAD

**Issue by Galbar** [Manjaro-Sway/manjaro-sway#230]
If I'm in `$HOME/.local/share/Flavio Tordini/Minitube`, When I press `$mod+Enter` nothing happens.

If I'm in `$HOME/Downloads`, When I press `$mod+Enter` a new terminal is opened with cwd being `$HOME/Downloads`.

I sounds like some quotes are missing somewhere but I'm not familiar enough with all the scripts to figure out where.

**Comment by boredland** [comment]
can you try "$mod+shift+Enter" while I search for a proper solution?

**Comment by Galbar** [comment]
yes, `$mod+shift+Enter` works, although it opens the terminal at `$HOME` (adding info, not complaining :sweat_smile: )

Thanks for looking into this. I'll try to familiarize myself with the scripts better, hopefully next time I can offer a patch :smile:.

**Comment by boredland** [comment]
Escaping that path is much harder (for me) than I initially thought, or I am overseeing sth.

**Comment by aboettger** [comment]
Very interesting problem, not even that works.

```
set $term_cwd $term -D '$HOME/foo bar'
```

**Comment by aboettger** [comment]
Fixed

```
set $term_cwd $term -D "$(swaycwd 2>/dev/null || echo $HOME)"
```

and in `/usr/share/sway/scripts/foot.sh`

```
# wrapper script for foot

USER_CONFIG_PATH="${HOME}/.config/foot/foot.ini"

if [ -f "$USER_CONFIG_PATH" ]; then
    USER_CONFIG=$USER_CONFIG_PATH
fi

foot -c "${USER_CONFIG:-"/usr/share/sway/templates/foot.ini"}" "$@" &
```

**Comment by boredland** [comment]
thanks so much! probably will put that into a PR over the next days if nobody else is ;)
