### ISSUE TITLE
"Error opening terminal: foot."

### ISSUE THREAD

**Issue by PLK2** [Manjaro-Sway/manjaro-sway#236]
On my RockPro64 running 5.16.2-4-Manjaro Arm
Opened a new terminal.
SSH'd into a separate Debian server as sudo user.
Attempted "sudo nano ..."
Received error message:
"Error opening terminal: foot."

Did the above on my macOS Terminal without any issues.

Any ideas on the problem?

**Comment by boredland** [comment]
while this is an issue with the arm edition apparently. I guess this may be realted to a wrong terminfo. But its weird anyhow. Please go to the manjaro forums for assistance regarding the ARM edition.

**Comment by PLK2** [comment]
Ah, will do. Thanks!
