### ISSUE TITLE
Configure display manager

### ISSUE THREAD

**Issue by kishikaisei** [Manjaro-Sway/manjaro-sway#237]
I couldn't find what display manager is being used, and I want to configure it so it gets the `--my-next-gpu-wont-be-nvidia` by default.
As much as I want to use the `nouveau` drivers, I can't because of blender and davinci resolve and all.
And is there a way to make it that there is not warning when running the proprietary drivers as well?

**Comment by boredland** [comment]
it is configured in `/etc/greetd/config.toml`, but that flag shouldn't be necessary as soon as sway 1.7 is launched.
