### ISSUE TITLE
Installation on 1 GB ram

### ISSUE THREAD

**Issue by MrArtemSid** [Manjaro-Sway/manjaro-sway#239]
Set minimal ram size in calamares to 0.7 instead of 1.0 to be able to install Manjaro sway on 1 gb ram pc

**Comment by boredland** [comment]
is this a request what? manjaro is an open source project. the manjaro version of calamares is [maintained](https://gitlab.manjaro.org/applications/calamares) in the manjaro gitlab. if you want to contribute (and be it by opening an issue) then it should be there. But I can only recommend to make a compelling argument there, instead a demand. I certainly am not taking "demand" seriously in an open source project.

**Comment by boredland** [comment]
I just remembered [this](https://github.com/manjaro/release-plan/issues/88) issue some days ago, that at least it isn't as simple as disabling the limit, as you eventually will require a swap to deal with the excess ram.

**Comment by MrArtemSid** [comment]
I just told about the problem. Default calamares ram limit (1.0) doesn't allow installing manjaro on 1 GB PC. I didn't made a commit or something due to lack of time, sry. I was able to install Manjaro XFCE on 1 GB of ram by changing value from 1.0 to 0.7, didn't manage to install Manjaro Sway, because calamares didn't open next time(idk why, would check later if u need), but seems like Manjaro Sway uses less ram than xfce, so installation on 1 GB ram should be fine

**Comment by MrArtemSid** [comment]
> I just remembered [this](https://github.com/manjaro/release-plan/issues/88) issue some days ago, concluding that at least it isn't as simple as disabling the limit, as you eventually will require a swap to deal with the excess ram.

By the way, why no one uses zram in installation time, like half of ram?

**Comment by MrArtemSid** [comment]
I tried, it was showing something like failed to find display or something

**Comment by boredland** [comment]
Then you didn't run it with `sudo -E`.

**Comment by MrArtemSid** [comment]
Hmm, I'll check tomorrow, thanks

**Comment by MrArtemSid** [comment]
Yeah, worked, thanks you.
