### ISSUE TITLE
strange mouse behaviour in virtual machines

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#24]
it feels like the mouse is one "line" off - no idea why

**Comment by JudahGoldstein** [comment]
are you running in a VM? I know vBox and gnome-boxes both have mouse issues with Wayland. in my experience changing resolutions sometimes fixes it.

**Comment by boredland** [comment]
I think its probably due to `spice-vdagent` not running...

**Comment by Zeioth** [comment]
Maybe it's only on my end, but spice-vdagent was not installed by default, I had to do pacman -S manually.

**Comment by boredland** [comment]
tbh, I did not take a very close look at this in recent times. does it work with the agent installed? as I see it, non of the other iso profiles specify it.

**Comment by boredland** [comment]
stale...
