### ISSUE TITLE
Missing xdg-user-dirs package in miminal iso image

### ISSUE THREAD

**Issue by fraunos** [Manjaro-Sway/manjaro-sway#241]
Hi,
I just installed manjaro-sway-21.1.0-minimal-220130-linux516.iso clean and noticed recording mode doesn't work. The issue was a missing package - xdg-user-dirs, which was needed for `/usr/share/sway/scripts/recorder.sh` script.
I installed it manually and it started working.
Is this on purpose for minimal version?

**Comment by boredland** [comment]
Na, not on purpose. I guess most people don't use the minimal edition, so it didn't come up yet. Would you like to update iso profiles accordingly?

**Comment by fraunos** [comment]
Sure! I have no idea how and where, but I'll take a look in the evening :)

**Comment by fraunos** [comment]
I noticed clipboard history not working too - should I fix this too for minimal iso? @boredland

**Comment by boredland** [comment]
tyvm! as I wrote there: both probably don't belong in a "minimal" image, but since it would be more difficult to remove them in a non-breaking way, I think your solution is very much fine for now.
