### ISSUE TITLE
Where does the /etc/sway/config file come from?

### ISSUE THREAD

**Issue by hakanyi** [Manjaro-Sway/manjaro-sway#244]
Sorry if it's a dumb question, but where does the `/etc/sway/config` file come from that's floating around in my `/etc/sway/` folder? It contains, for example, the line `set $term alacritty` which is definitely obsolete.
Got my attention due to [this forum post](https://forum.manjaro.org/t/which-config-file-do-i-use-edit/101259)

**Comment by boredland** [comment]
it is part of the official [distribution package](https://archlinux.org/packages/community/x86_64/sway/) of sway, that for most parts just extracts the official release, that build it from [this](https://github.com/swaywm/sway/blob/master/config.in) template. But is is not loaded in our default entrypoint (~/.config/sway/config).

Feel free to open, if you have further questions.
