### ISSUE TITLE
unable to create events in khal

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#245]
The default khal installation coming with manjaro-sway is broken. It is not possible to create new events unless they are all-day events.

The first time you focus any input field for start or end time a warning is displayed:

`/usr/lib/python3.10/site-packages/khal/khalendar/khalendar.py:153: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html`

If you opened khal from swaybar this warning message will obscure the whole UI and render it unusable.

When you try to save an event an exception occurs:

`AttributeError: '_PytzShimTimezone' object has no attribute '_tzinfos'`

And the event is **not** saved.

Probably due to this issue: https://github.com/pimutils/khal/issues/1092

Above issues mentions downgrading `python-tzlocal` as a potential workaround. So maybe manjaro-sway should install the downgraded package version by default?

**Comment by boredland** [comment]
manjaro downgraded to v 2.1 of tzlocal too:
![Uploading image.png…]()
