### ISSUE TITLE
Pamac-manager error in command-line

### ISSUE THREAD

**Issue by nnuel** [Manjaro-Sway/manjaro-sway#248]
When I start pamac-manager from the command-line I got a lot of GTK errors, which were partly because of me switching themes. But This GDK-error is something that remains and I saw someone on the [ARM forum](https://forum.manjaro.org/t/error-when-running-pamac-manager-especially-remotely/79550) that had the same issue.

```
> pamac-manager
(pamac-manager:129635): Gdk-CRITICAL **: 13:32:57.147: gdk_window_set_cursor: assertion 'GDK_IS_WINDOW (window)' failed
```

Anyone able to reproduce this error on their system? I think I should make a fresh USB iso, so I can do some more testing and comparing versus the base install.

**Comment by nnuel** [comment]
https://forum.manjaro.org/t/pamac-manager-stopped-working/95249/13

Another user getting this error, so I suppose it is manjaro-wide.

**Comment by Zeioth** [comment]
You probably want to report this on [pamac's git ](https://gitlab.manjaro.org/applications/pamac/). They are the responsible ones for that part of the system.

**Comment by Mathew-D** [comment]
That error comes from the gdk theme that is being used.  Some of the themes are still trying to use things that were removed from gdk.  I would do as @Zeioth said any report it to the pamac package or to the maintainer of the gdk theme you are using.

**Comment by simon-bueler** [comment]
Closing this issue, feel free to reopen when there is still an issue.
