### ISSUE TITLE
Question regarding Missing AUR Packages:  kvantum-theme-matchama

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#250]
Hello,

If I run `yay -Syyu`, I do receive message about missing AUR package; Matcha green in the `/usr/share/sway/themes/matcha-green/definitions` also does include property for kvantum-theme: `set $kvantum-theme Matchama-Dark`... question: which package includes Matchama-Dark theme used by manjaro-sway?

```shell
yay -Syyu                                     
:: Synchronizing package databases...
 core                               168.9 KiB   832 KiB/s 00:00 [###################################] 100%
 extra                             1901.3 KiB  6.63 MiB/s 00:00 [###################################] 100%
 community                            7.0 MiB  8.58 MiB/s 00:01 [###################################] 100%
 multilib                           174.0 KiB  4.25 MiB/s 00:00 [###################################] 100%
 manjaro-sway                        21.2 KiB   176 KiB/s 00:00 [###################################] 100%
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> ferdi-nightly-bin: local (5.7.0-1) is newer than AUR (5.6.3.nightly.16-1)
 -> Missing AUR Packages:  kvantum-theme-matchama
 there is nothing to do
```

**Comment by boredland** [comment]
that theme has been dropped upstream. you can just remove it. I did not have time to test out alternatives extensively, but it seems [matcha-dark](https://github.com/Manjaro-Sway/desktop-settings/commit/697cb5d3b076fc9d2eb303af80fc6a5caa15639a) is a good fit. The package you'd need is [kvantum-matcha](https://github.com/Manjaro-Sway/iso-profiles/commit/72bbb13bdab1dec8412cdcb332f13540e3f3f407)

**Comment by l-j-g** [comment]
@boredland  

re: font settings would you be open to setting a global monospace font through Fontconfig?

**Comment by boredland** [comment]
I do not think I understand the question. What would that mean?

**Comment by boredland** [comment]
Seems not to be urgent.

**Comment by l-j-g** [comment]
Apologies, its not urgent. 
Not not sure if this is relevant to the original question. [Fontconfig](https://wiki.archlinux.org/title/font_configuration) would let you to define a global alias for fonts that could be used across applications e.g. sway, foot, vs code

for example to alias 'monospace' to 'RobotoMono Nerd Font Mono'.  This would make it easier to maintain a consistent font across the system and make it easier to maintain that consistent font in non-sway applications e.g. VS Code, as you would just need to reference the font 'monospace'

As per #196 Currently there is there are some hard coded fonts used in the config: 
- /usr/share/sway/templates/waybar/style.css ( font-family: "RobotoMono Nerd Font", "Roboto Mono", sans-serif;)
- /usr/share/sway/templates/foot.ini (font=RobotoMono Nerd Font Mono:size=8)

it would require finding all of the places where fonts have been hard coded and also references to $gui-font and $term-font in sway and changing them to 'monospace' (or what ever we decide to call the font)
