### ISSUE TITLE
Fix screensharing for discord ect. 

### ISSUE THREAD

**Issue by l-j-g** [Manjaro-Sway/manjaro-sway#251]
Hello, 

I believe on the default configuration screen-sharing for applications such as discord is broken. I suggest we work on a patch to make this operational as it is possible and a pretty important feature.

It was a bit finicky for me to get it fully operational working though.  I cannot remember exactly what will be required on a default installation as I have made some modifications to my installation  -

Is pipewire used by default?  Potentially all that will be required is: 

- Add `xdg-desktop-portal-wlr` as a requirement: 

- Add `exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway` to /etc/sway/config.d/50-systemd-user.conf

I was able to getting it working through Firefox - The native discord app seems to have issues because it is based on chrome/electron and needs to be launched with flags to work properly (still wasnt able to get it working with flags) - there is a possible flatpak solution?

**Comment by Mathew-D** [comment]
I though we had xdg-desktop-portal-wlr already installed by default.  As I already had it.  I have used screen sharing in Brave lots of times in the last few months without issue.
To get it to work in chrome like browsers just go to:
`chrome://flags/#enable-webrtc-pipewire-capturer`
and turn that flag on.  It was listed on the FAQ page.    As for native apps I haven't tried so I can't say much.

**Comment by l-j-g** [comment]
If this works out of the box (for firefox) and chrome (with whats in the FAQ) this can be deleted - it didn't for me, maybe I didnt integrate an upstream change.

**Comment by Mathew-D** [comment]
Can someone else try their system and let us know please.

**Comment by boredland** [comment]
no reaction.

**Comment by worldofgeese** [comment]
I suggest we re-open this as screensharing does not work using Zoom from either the AUR or Flatpak.

To reproduce first attempt workarounds:
`cat $HOME/.config/zoomus.conf`:
```
...
enableWaylandShare=true
...
```

If using Flatpak, run Zoom with `flatpak run --env=XDG_CURRENT_DESKTOP=GNOME us.zoom.Zoom`. If using the AUR Zoom, `XDG_CURRENT_DESKTOP=GNOME zoom`.

Start a new meeting then atttempt any form of screensharing:

https://user-images.githubusercontent.com/59834693/220579501-361ae44e-3581-401a-8918-992076667e8f.mp4

Zoom will not screenshare.

Zoom does support other video sources, like OBS but OBS unfortunately also does not expose a `Screen Capture (Pipewire)` source to the user when attempting to add as a new source, which means it's not detecting the Pipewire output:

https://user-images.githubusercontent.com/59834693/220580548-ce1aec75-4db4-43ba-8392-ff6868c8145e.mp4

**Comment by boredland** [comment]
Well, this issue was not about the zoom app, but about chromium based applications using the `xdg-desktop-portal-wlr`, for example the zoom webapp, ms teams, google meet, jitsi etc. Those still work fine. I didn't know that the zoom linux app now is supposed to work with wayland.

**Comment by boredland** [comment]
Well, reading on about it, it seems this this works only with super hacky workarounds, if even. If you find a solution, feel free to open a new ticket. 

The current solution for applications that have web apps: use them.

If they have both, it might be worth mentioning, that some have better sound and camera on their native apps - I don't know why. If so, it might be worth joining through the webapp only to share the screen.

**Comment by boredland** [comment]
For discord, by the way, I am using "webcord", which works nicely for me. I [asked](https://github.com/SpacingBat3/WebCord/issues/382) them if they would add support for a .flags file like we have for other chromium/electron based applications.

**Comment by worldofgeese** [comment]
Have you tried OBS? My hunch is something funky is going on with Pipewire since OBS isn't picking up on it as a valid source.

**Comment by boredland** [comment]
OBS seems to grab a pipewire source. Something is off with the dimensions tho, it only covers some part from the upper left corner.
