### ISSUE TITLE
Question: what is the difference between the "normal" and "unstable" versions and how do you switch between them?

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#252]
The ["official" Manjaro Sway download page](https://manjaro-sway.download/) now lists two sets of downloads, a "normal" one and one with "unstable" in the file names.

What exactly is the difference between the two? How would I know which version I am using? And how would I switch back to "normal" (stable) if I am on unstable?

The reason for my question: 2 months ago I installed sway from the download page and back then there was no "unstable" as far as I remember. I then just regularly updated using `pacman -Syu`.

Now I am experiencing [crashes with sway 1.7](https://github.com/swaywm/sway/issues/6851).

Could it been that I ended up on the "unstable" branch without knowing?
If yes, is there a way to switch back?

**Comment by boredland** [comment]
This notation refers to the Branches in the Manjaro repositories. 

Unstable: arch repos with some customizations

Testing: soon to be released packages.

If you did not switch branches un purpose you will be on stable then.

Here is how to switch them:
https://wiki.manjaro.org/index.php/Switching_Branches
Switching back is possible, but means that you will have "Unstable" packages until you are on par with stable repos again.

In am using unstable and stable in parallel on different devices. I rarely feel any difference but have updates popping up on the unstable on every day.

**Comment by heapifyman** [comment]
Thank you for the explanation. 🙏🏽
