### ISSUE TITLE
No easy way to change wallpaper

### ISSUE THREAD

**Issue by RajrupDasid** [Manjaro-Sway/manjaro-sway#254]
Today I download Sway minimal to try it 
but ended up a breaking system 
Why? because I don't know why it's much complicated that i3?
feh wallpaper change is not working and even tried from root not working if i copy /etc/sway/config to .config/sway
it's broke my sway menu bar
why there is no proper document or made some simple to do this ?

**Comment by boredland** [comment]
na, its just as easy as with i3, you just did sth. pretty bad (enabled the sway default cfg).

I added a hint to our [faq](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-change-the-wallpaperbackground-image).

**Comment by RajrupDasid** [comment]
yeah I read and configured 
and yes it's really easy of course after your help
sometime easy things just looks very complicated !
by the way one more help is required from you
how to enable screen sharing in firefox ?

**Comment by boredland** [comment]
hm. it should ™️  work out of the box. it does for me:
![image](https://user-images.githubusercontent.com/4662748/156995475-3ab8754d-2858-4f0d-ab5a-10b78f6ef935.png)

**Comment by boredland** [comment]
ah, you installed minimal. minimal is missing all the packages marked as "extra" [here](https://github.com/Manjaro-Sway/iso-profiles/blob/sway/community/sway/Packages-Desktop). That includes `xdg-desktop-portal-wlr`

**Comment by RajrupDasid** [comment]
@boredland  yes sir , I have installed minimal sir
I will try to configure it 
By the way thanks sir and thanks for help sir
