### ISSUE TITLE
Installer stuck after "started authorization manager" on VirtualBox

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#260]
### Issue:
Trying to install latest ISO on VirtualBox, after the "Started Authorization Manager" there is no visual updates. Ubuntu installer works on the same VirtualBox

### And question:
I want to install manjaro sway in headless mode on VPS, to access it with wayvnc. Initial idea were to export image to the hosting: https://www.vultr.com/docs/import-a-server-to-vultr-vps/, but I could just install it with pacman. Is there any guideline on how to install manjaro sway over regular archlinux (including video-drivers for the headless mode)?

**Comment by andrius** [comment]
Update:
I followed another guide: https://www.vultr.com/docs/requirements-for-uploading-an-os-iso-to-vultr and followed installation steps, so it is easier with vultr. But my question above is still open ;)

![image](https://user-images.githubusercontent.com/26776/159578807-57812f44-7f64-4ee6-9454-ccdbdaceb039.png)

**Comment by boredland** [comment]
Regarding the OP: No, there is no guide on how to install over archlinux and honestly I don't think that would be a good idea. It could, however, work with another manjaro edition (like gnome). You'd first need to install all the packages as listed [here](https://raw.githubusercontent.com/Manjaro-Sway/iso-profiles/sway/community/sway/Packages-Desktop). Afterwards you'd need to create the files according to our [desktop-overlay](https://github.com/Manjaro-Sway/iso-profiles/tree/sway/community/sway/desktop-overlay). It should ™️ be possible to create a little bash script doing both. Would you be interested in that?

Regarding the whole topic: I have no experience at all with those kinds to automated installs. I know them tho, for example if you install Windows or Ubuntu in Gnome Boxes, that seems to work pretty well. I have no idea how to cater that to be honest. I you guys have any insights as to what we'd have to do from an OS side, we eventually could provide for this.

**Comment by boredland** [comment]
^^ updated my initial comment with some more information across the several different questions you had. please next time try to create separate issues for different topics, as I don't really understand if/how the virtualbox and the VPS topic are connected.

**Comment by boredland** [comment]
closing due to no reaction and not any focus of mine.

**Comment by stevo-knievo** [comment]
I have the same issue.
Trying to install manjaro-sway-21.3.2-221023-linux515.iso ISO on VirtualBox, but after the "Started Authorization Manager" there are no visual updates. Other distros are working fine.

Host Fedora 36 + VirtualBox 7.0

**Comment by theychx** [comment]
I had the same problem using gnomeboxes/kvm on a pop-os 22.04 host.

Turning on 3D accel. in guest prefrences in gnomeboxes fixes the problem for some reason.

**Comment by berenddeboer** [comment]
No success for me either. It keeps staing a start job is running to initialise Pacman keyring, but that never succeeds, so you can't login.

**Comment by berenddeboer** [comment]
Success with using gnome-boxes, instead of virtualbox.
