### ISSUE TITLE
make idle timeout configurable

### ISSUE THREAD

**Issue by eterps** [Manjaro-Sway/manjaro-sway#261]
[sway]idle timeout is currently hardcoded to 240 seconds, any thoughts yet how to make that configurable?

**Comment by boredland** [comment]
sure, good idea. should work just like this:

```
set $idle_seconds 240
set $idle swayidle -w \
    timeout $idle_seconds 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout 300 'exec $locking' \
    timeout 600 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'playerctl pause' \
    before-sleep 'exec $locking'
```

so you can put `set $idle_seconds 60` into a user config after that. Perhaps, while we're at it, we could do the same for the locking timeout and dmps-timeout?

**Comment by boredland** [comment]
please install manjaro-sway-settings-git and take this on a test ride.
