### ISSUE TITLE
Show nwg-wrapper shortcut help on all monitors

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#264]
When looking for the shortcut help, I currently have to find the correct screen, which is kinda hard if I don't already know the shortcuts ^^
I see no harm in putting it on all screens.

**Comment by boredland** [comment]
Any idea how to do this with nwg-wrapper?

**Comment by xeruf** [comment]
From a quick glance at the help, call it once for each monitor with the `--output` option, which should not be hard from `swaymsg -t get_outputs`.

**Comment by boredland** [comment]
- [ ] update nwg-wrapper to current version
- [ ] use a quit signal so we can stop all instances more intelligently
- [ ] start instances for all outputs

**Comment by boredland** [comment]
I upgraded to newest nwg-wrapper and use the "new" signal api for toggling visibility while iterating through the displays. I am on on a multi-output setup rn, so please give manjaro-sway-settings-git a spin!
