### ISSUE TITLE
Question: Which calendar app is being used?

### ISSUE THREAD

**Issue by miltkall** [Manjaro-Sway/manjaro-sway#265]
Many thanks for your great efforts on maintain manjaro-sway 👌🏿!

Since last week the terminal calendar used from sway crashes when clicking on:
![image](https://user-images.githubusercontent.com/7304125/162602101-d8bf9049-ff49-4a18-a35a-61664e3dead0.png)

Unfortunately it closes so fast, that I am not able to check the cmd executed. It is a python app/script for sure, yet I do not know which one. Could you maybe provide so more infos/hints? 🙏🏿 

I know that it is not a manjaro-sway issue, yet I do not know where to ask the question.

Many thanks 👏🏿

**Comment by boredland** [comment]
its "khal". On my machine it starts..

**Comment by jyotiradityatiwary** [comment]
You can reproduce this error by running `LC_TIME=en_IN khal calendar`. (The last line of output says "unsupported locale'

However, I noticed that running `LC_TIME=en_IN.utf8 khal calendar` works properly without any errors.

en_IN is the default locale set if you set timezone as Asia/Kolkata during installation. Can manjaro installer be modified to set locale as en_IN.utf8 instead?

**Comment by boredland** [comment]
so.. what is `cat /etc/locale.conf` for you?

**Comment by leadermik** [comment]
In my case using the `timedatectl set-timezone {{timezone}}` did not update the `/etc/timezone` (remained to its old value). 

By manually setting the `/etc/timezone` to the correct timezone actually solved the problem.

Thanks for your time and efforts @boredland ! 😃

**Comment by jyotiradityatiwary** [comment]
> so.. what is `cat /etc/locale.conf` for you?

```
LANG=en_IN
LC_ADDRESS=en_IN
LC_IDENTIFICATION=en_IN
LC_MEASUREMENT=en_IN
LC_MONETARY=en_IN
LC_NAME=en_IN
LC_NUMERIC=en_IN
LC_PAPER=en_IN
LC_TELEPHONE=en_IN
LC_TIME=en_IN
```

**Comment by leadermik** [comment]
Here 
![image](https://user-images.githubusercontent.com/7304125/164184834-891aa796-aa51-4f75-a462-2775ec337cb6.png)
