### ISSUE TITLE
change default shell to fish

### ISSUE THREAD

**Issue by ehsanghorbani190** [Manjaro-Sway/manjaro-sway#266]
Hi :D i want to change my default shell to fish, i used `chsh` command as root and as my user,with and without `-s` flag, it just doesn't work(i tried logging out and restarting after that, and it doesn't work too)! `$SHELL` is always equal to `/usr/bin/zsh`. and nothing changes it. i also checked `/etc/passwd` file and my user's shell is set to fish there, but i always get zsh after opening a new terminal,

**Comment by Mathew-D** [comment]
Take a look at ~/.profile

**Comment by ehsanghorbani190** [comment]
> Take a look at ~/.profile

Thanks! Solved the problem.
