### ISSUE TITLE
Change default applications

### ISSUE THREAD

**Issue by ehsanghorbani190** [Manjaro-Sway/manjaro-sway#267]
Hi :D i would like to change default applications to launch files from PCManFM or CLI with `open` command. for example i would like to open all of my videos with mpv player instead of MPlayer. how can i do that ?

**Comment by boredland** [comment]
No idea what "open" is, but for me it is working using right-click on a file, "Open With" > "Open With" > selecting the tool and checking the box to keep this as a default. Isn't that what you aim for?

**Comment by ehsanghorbani190** [comment]
@boredland 
i meant `xdg-open`, for example , `open myVideo.mp4` will open it with MPlayer. i found what you said and it works, but there should be a config for managing this, what if i remove PCManFM? how do i set to open a file type with a specific program then ?

**Comment by boredland** [comment]
So you want a dedicated tool to configure xdg mime, am I getting this right? In the past I always used the file manager for that, so I have no particular ideas...

**Comment by ehsanghorbani190** [comment]
@boredland that's exactly what i'm looking for, thanks! :D

**Comment by boredland** [comment]
this would be a gui editor for this: https://aur.archlinux.org/packages/mime-editor
