### ISSUE TITLE
Configure dex for xdg-autostart

### ISSUE THREAD

**Issue by uthr** [Manjaro-Sway/manjaro-sway#268]
Since this distro is supposed to be newbie-friendly (right?) and have a "just works" feel, it would be nice to support xdg autostart out of the box too, see https://github.com/swaywm/sway/issues/1423

Since I had an issue with activitywatch starting to early, I now have this in my config, which I guess could be standard:

    exec "gdbus wait --session org.kde.StatusNotifierWatcher && dex --autostart"

See https://www.reddit.com/r/swaywm/comments/o35hwq/how_do_i_execute_programs_that_require_the_tray/
It waits for the tray to start and then executes all autostart applications in the XDG paths.

**Comment by boredland** [comment]
Hi there! I added dex to the optional dependencies and added that line to our autostart script.
