### ISSUE TITLE
USB support on System76 Lemur Pro

### ISSUE THREAD

**Issue by tylerchilds** [Manjaro-Sway/manjaro-sway#270]
Hey :) I've been really loving manjaro-sway on the frame.work and raspberry pi 400 (different project?)

I ended up popping it onto my Lemur Pro a few days ago and just tried my USB ports for the first time. The flash drive I usually recover my data from wasn't recognized at all and my PS4 controller glows on and glows off, so I know something happens when a device is connected.

Are there any commands I can run to try and troubleshoot this issue?

(thanks again for the support a few months back getting the battery data wired up :)

**Comment by boredland** [comment]
> frame.work

that is an x86 device, so you'll probably have used this edition too.

>  flash drive I usually recover my data from wasn't recognized at all

so.. it didn't show up in pcmanfm? or what did you expect to happen?

> PS4 controller glows on and glows off, so I know something happens

I have no idea what would be supposed to happen when you connect it.

**Comment by tylerchilds** [comment]
>  it didn't show up in pcmanfm?
Correct, it doesn't show up in pcmanfm. 

My PS4 controller does connect now and show up in `lsusb` though. I'm thinking maybe just my flash drive is incompatible?

**Comment by boredland** [comment]
So your usb drive does not show up in lsusb? Could you check dmesg? Either way: since we use the same kernel as regular manjaro, this should imo not be a sway-specific issue.

**Comment by tylerchilds** [comment]
It looks like my flash drive has stopped working on all machines. It was just unfortunate timing that the first failure happened to be when I went to restore data on a fresh install. Sorry for the churn.
