### ISSUE TITLE
can't boot this in QEMU

### ISSUE THREAD

**Issue by Ryder17z** [Manjaro-Sway/manjaro-sway#271]
![image](https://user-images.githubusercontent.com/2000703/166106538-7fc50441-3d34-4ddc-943e-5d4f0d36bebd.png)
manjaro-sway-21.2.4-220424-linux515.iso
 
It just hangs here. 

Latest unstable on the other hand does a similar thing as issue #139 describes. if a correct login is entered, an error flies by and your almost immediately thrown back to the login prompt. The output it gives is:
`Rolling back to kms_swrast`
`Missing required Wayland interface`

If it matters, the host OS is Manjaro XFCE 21.2.6

**Comment by boredland** [comment]
no reaction.

**Comment by boredland** [comment]
This may be a problem with hardware rendering not available in qemu. I will add the environment variable to allow software rendering to the iso, perhaps that helps.

**Comment by boredland** [comment]
in gnome boxes, for me it only works using this flag rn. don't exactly know why tho, as I definitely remember it working without not too long ago:
![image](https://user-images.githubusercontent.com/4662748/170863202-4cf5781d-053d-415a-94a0-28b74bcf2519.png)

**Comment by Ryder17z** [comment]
> Changing the video settings of the machine from virtio to qxl

Yes. that works, but it should be added to the readme as well.

**Comment by mmahmoudian** [comment]
I wish this was somehow fixed or at least a proper error was produced. But for those who are using virtmanager:

![image](https://user-images.githubusercontent.com/390889/221169766-796a13b4-86ab-4146-b917-9778b23a6905.png)

**Comment by boredland** [comment]
[this](https://www.reddit.com/r/swaywm/comments/plcq6r/comment/hcd21yq/?utm_source=share&utm_medium=web2x&context=3) might get you a better performance.
