### ISSUE TITLE
waybar disappears after update to 0.9.13-1

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#279]
Waybar disappears after updating to version `0.9.13-1`. Also when using the default config.jsonc and default style.css.

Workaround: downgrade to version `0.9.12-2`

**Comment by Mathew-D** [comment]
Can you tell me if you are on the stable or the testing channel of Manjaro please.

**Comment by heapifyman** [comment]
I'm currently on the testing channel.

**Comment by Mathew-D** [comment]
I am on the Testing channel and had waybar disappear as well but I went the other way and upgraded to the waybar-git from the AUR to fix the problem for now.  Also I had to rename the style.css.example in my ~/.config/waybar to just style.css to reset the color afterwards.
It seems to be a Manjaro package problem.

**Comment by heapifyman** [comment]
> upgraded to the waybar-git from the AUR to fix the problem for now

If I do that the bluetooth icon disappears from the waybar.

> Also I had to rename the style.css.example in my ~/.config/waybar to just style.css to reset the color afterwards.

I did not have to do that.

**Comment by Mathew-D** [comment]
> > upgraded to the waybar-git from the AUR to fix the problem for now
> 
> If I do that the bluetooth icon disappears from the waybar.
I don't use the bluetooth so I keep forgetting that the AUR seems to forget to add the blue tooth module.  
You have to add the --auto-features=enabled option to the PKGBUILD file.  So change:
    meson --prefix=/usr "${srcdir}/build"
to 
    meson --auto-features=enabled --prefix=/usr "${srcdir}/build" 
and that should add back the Bluetooth module back.

**Comment by Mathew-D** [comment]
To get the manjaro package fixed the best place would be https://forum.manjaro.org/

**Comment by mbledkowski** [comment]
I have the same problem

**Comment by boredland** [comment]
> Would it help to file an issue at https://bugs.archlinux.org/ or is there any other better place?

We're actually pulling waybar from the arch packages. After installing the current version from arch, I have the same issue, this ominous error is preventing startup:

```

** (waybar:345224): ERROR **: 21:27:55.030: 
unhandled exception (type std::exception) in signal handler:
what: argument not found

[1]    345224 trace trap (core dumped)  DEBUG=true waybar
wc: write error
```
the problem is a [breaking change in the bluetooth module](https://github.com/Alexays/Waybar/issues/1574). I will update the config on our end.

**Comment by boredland** [comment]
Soo, it seems the new config works with the previous waybar version too, as to my testing. So I am releasing a new version of manjaro-sway-settings asap.

**Comment by mbledkowski** [comment]
I love you, everything works as expected now <3

**Comment by bdefore** [comment]
@boredland i updated manjaro sway today and encountered this issue but it was unclear that it was already resolved on your end. when breaking changes like this occur that require replacing something in local config it would be very helpful if the releases section of github identified it. waybar config is something i've modified so i'm not in the habit of copying it over from the manjaro sway base after each update. thanks for your work on this!

**Comment by boredland** [comment]
Hi! I made a [major bump](https://github.com/Manjaro-Sway/desktop-settings/releases/tag/11.0.0) due to that. It should only have broken after that update if you 

1. opted out completely from our waybar config
2. configured an override and overrode the bluetooth module with your own (not compatible) code

**Comment by boredland** [comment]
You can easily opt into our modules, if you haven't, by adding the include line into you userspace waybar configuration:
```
"include": [
        "/usr/share/sway/templates/waybar/config.jsonc"
 ],
```

You can still override all modules and set their order etc. like you used to.

**Comment by bdefore** [comment]
Looks like I don't have that in my local config. I'll add that in thanks.
