### ISSUE TITLE
Improve readabillity of waybar - black font on green background

### ISSUE THREAD

**Issue by fraunos** [Manjaro-Sway/manjaro-sway#280]
Hi,
I did small corrections to waybar CSS - personally I wanted more vertical space, so I set it to auto height and reduced the font-size, but then noticed the white on green text is barely visible.
What do you guys think of changing the font colors? It would look kinda like this:

![image](https://user-images.githubusercontent.com/6673521/170831374-364c6c41-1f46-4dae-868f-af9a7711d81d.png)
![image](https://user-images.githubusercontent.com/6673521/170831464-652248ba-1e08-4dd9-8ca8-e59ceb2ea8b7.png)

**Comment by boredland** [comment]
I think this looks really good. I'd be open for a change once in a while and the current style was mostly plagiarized from the arm and the i3 edition. What do other @Manjaro-Sway/maintainers think?

**Comment by Mathew-D** [comment]
Doesn't hurt to try something new.  I am game.

**Comment by fraunos** [comment]
Cool!
