### ISSUE TITLE
Live manajaro-sway iso not working

### ISSUE THREAD

**Issue by thyeun** [Manjaro-Sway/manjaro-sway#281]
Step that 
1. Using sway iso version ```manjaro-sway-21.2.4-220529-linux515.iso```
2. After using ```balenaEtcher``` to make it into usb and boot up.
3. Boot up with BIOS, only see a word ```GRUB``` and wont proceed.

Anyone can advised what issue on this?

**Comment by AdriandMartin** [comment]
I've tried it (using UEFI instead of BIOS), and although it booted, I got this error:
![imagen](https://user-images.githubusercontent.com/22200464/171291163-71565c5b-f296-43e1-a6f5-aa0042dafc02.png)

And then, in the live session, the wallpaper didn't load

**Comment by thyeun** [comment]
@AdriandMartin So, can we agree that the live iso having issue?

As UEFI and BIOS also facing issue

**Comment by boredland** [comment]
that doesn't look like a sway, but like a manjaro issue :-/ will try and have a look later...

**Comment by thyeun** [comment]
@AdriandMartin thanks, will try it out. if that is a Manjaro build issue, meaning that all iso will affected than. :)

**Comment by thyeun** [comment]
Just try out ```manjaro-sway-21.2.4-220508-linux515.iso```, still facing the same issue, as you can see from the below picture.

![Screenshot_2022-06-01_17:35:20](https://user-images.githubusercontent.com/1939446/171374936-a6a3f1fe-c66a-45ff-8235-6013b300d066.png)

**Comment by AdriandMartin** [comment]
Does the [GRUB screen](https://forum.manjaro.org/uploads/default/original/3X/5/d/5ddc2c283c53eae8d1f9b20d4702346c13d52a7f.jpeg) appears before it happens?

**Comment by thyeun** [comment]
@AdriandMartin Once boot into live usb, it directly appear ```GRUB``` and stuck there.

**Comment by AdriandMartin** [comment]
I noticed that I have an old computer with BIOS at home, so I've tried one of the ISOs on it. Although at the first moment I got the same screen as in your photo, then it disappeared and the GRUB screen was shown. Just for ensuring, is it a 64 bits computer?

**Comment by thyeun** [comment]
@AdriandMartin Not really sure 64 bit or 32 bit, it is a very very old laptop, but how long it stay on the GRUB screen? My one stay until more than 2 hours and still not move forward.

**Comment by AdriandMartin** [comment]
Just a few seconds, no so long. I told you about 64 bits because it's the only Intel architecture currently supported, although I think that, if it was the problem, the own GRUB should report about it and not getting stuck that way

**Comment by thyeun** [comment]
@AdriandMartin Agree with you for not stuck that way, i got no issue at all from others distro, it only happen on Manjaro.

if it is related with 64 bits architecture, than i got no luck to try Manjaro out. :( and thanks for helping me out on this issue.

**Comment by thyeun** [comment]
Try out i3, still same :(

**Comment by thyeun** [comment]
@AdriandMartin So, what is the different of Manjaro iso with others distro iso? 99% others distro, i got no issue, it only happen to Manjaro iso, i can confirm, there are some specific build on Manjaro iso, that cause me facing this issue.

> Well, at least we can affirm that it's not a specific problem of this distro

**Comment by AdriandMartin** [comment]
Many of the main distributions have its own scripts to build their ISOs (some are, e.g., [Debian](https://salsa.debian.org/live-team/live-build), [Arch Linux](https://gitlab.archlinux.org/archlinux/archiso), [Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports), [Puppy Linux](https://github.com/puppylinux-woof-CE/woof-CE), [Android](https://android.googlesource.com/platform/build/soong/), ...), and that's the case of [Manjaro Linux](https://gitlab.manjaro.org/tools/development-tools/manjaro-tools#3-buildiso), which also allows automatizing the process using [GitHub Actions](https://github.com/manjaro/manjaro-iso-action)
> Note that it's not the only way distros are built, because others like [LocOS](https://www.youtube.com/watch?v=rWQea9bQYWk) and [Bodhi Linux](https://sourceforge.net/projects/bodhibuilder/) use tools to modify existing ISOs

In these scripts it's specified how the software is built (or if it's already packaged, where it's taken from) and configured, so although I'm not completely sure, what makes sense to me is that the Manjaro's scripts makes some changes, maybe on the GRUB package (either in building or in configuring it) or perhaps into another closely related package, which makes their ISOs doesn't work properly in your hardware

**Comment by thyeun** [comment]
@AdriandMartin thanks for your explanation. than Manjaro will be big no no from me. Will try others distro with sway.

**Comment by AdriandMartin** [comment]
You are welcome. Remember that you can always use the Sway's configuration files provided by this distro, because they are platform-independent as they will be interpreted by Sway

**Comment by boredland** [comment]
I would suspect, that you have an EFI-compatible laptop and try to boot grub instead. Is there a efi prompt when you boot and press F9 ? Does it contain an entry for manjaro?
