### ISSUE TITLE
`sunset.sh` calls geoip API twice but wouldn't one call be enough?

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#282]
In [sunset.sh](https://github.com/Manjaro-Sway/desktop-settings/blob/b85c93b364191d6443215755ddd6a24abfcb08e7/community/sway/usr/share/sway/scripts/sunset.sh#L23) the geoip API is called twice - once for longitude and then again for latitude.

As far as I understand, the response to the first call already will contain both latitude and longitude. So wouldn't it be enough to call the API only once, store the response and then extract latitude and longitude from the response using `jq`?

**Comment by boredland** [comment]
does it work if you first initialize the GEO_CONTENT= variable (empty) outside of the function? i am not sure how bash variable scopes work.

**Comment by boredland** [comment]
hi! I think [this](https://github.com/Manjaro-Sway/desktop-settings/commit/75f0a90fc677c3cbad669c138d492f5cdb5e3471) should work now
