### ISSUE TITLE
No background and no onscreen helper on fresh install/live disk

### ISSUE THREAD

**Issue by CrumbsTrace** [Manjaro-Sway/manjaro-sway#283]
I decided to install this distribution again after trying out some other distributions for a while. This distribution worked well for me in the past but unfortunately I seem to be having some problems with the current iso. 

No background seems to be rendering at all, instead displaying a full gray solid background. Attempting to override $background does not have any effect here. Another issue is that the onscreen help for shortcuts does not seem to be showing up either, I have confirmed that .config/nwg-wrapper/help.sh is still present, Super + ? does not seem to help either. 

I seem to be having this problem both on a fresh install and when booting from a live disk

If it matters, I have a dual monitor setup, neither the background nor the helper are showing up on either display
![image](https://user-images.githubusercontent.com/45168144/171929639-af7c11bf-ec52-4184-aff8-d9a50b3d8c14.png)

**Comment by boredland** [comment]
So, when starting the live disk I get the onscreen-menu, but can reproduce the background missing:

![image](https://user-images.githubusercontent.com/4662748/172025623-aeef0035-3c7d-4ba4-bd98-e37ac15dd78d.png)

When I try to set the background using swaymsg, nothing changes.

**Comment by AdriandMartin** [comment]
I've tried [the last ISO built](https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202206050322), and the problem still happens. When a terminal is opened in the live session, the following error messages appear:
![2022-06-05T17:57:17,485871072+02:00](https://user-images.githubusercontent.com/22200464/172059318-5596c6dc-4919-4131-8e40-cdcbe0f81461.png)

Moreover, `swaybg` command is not found. It seems to be something related to privileges

**Comment by CrumbsTrace** [comment]
I installed swaybg and reloaded and the background immediately appeared

**Comment by boredland** [comment]
good find, so we need to install swaybg manually now, as it appears.

**Comment by AdriandMartin** [comment]
Yes but, as far as I'm concerned, `swaybg` comes with the distro, so it should be already included in the ISO (or at least it was in the previous releases)

**Comment by boredland** [comment]
ya, the reason is just, that swaybg [had been made](https://github.com/archlinux/svntogit-community/commit/98b34d7f00db817003e04de396ffc01e82229c43) an optional dependency in the sway package.

I explicitly added it to our iso profile and to the dependencies of manjaro-sway-settings.

**Comment by boredland** [comment]
new version has been created. I hope that fixes things!?

**Comment by AdriandMartin** [comment]
It seems only the full version has `swaybg` preinstalled, the minimal requires the available update to be installed for getting it

**Comment by boredland** [comment]
well, apparently the iso was built before I bumped the settings-package. thats unfortunate, but will heal itself.
