### ISSUE TITLE
/usr/share/sway/scripts/help.sh fails if multiple displays are connected

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#285]
With an external monitor connected via HDMI to a laptop the help text does not appear on any of the screens.

Running `/usr/share/sway/scripts/help.sh` manually will result in the following error: `nwg-wrapper: error: unrecognized arguments: HDMI-A-1`.

The full output is:
```
++ swaymsg -t get_outputs --raw
++ jq -r '.[].name'
+ OUTPUTS='eDP-1
HDMI-A-1'
+ VISIBILITY_SIGNAL=30
+ QUIT_SIGNAL=31
+ [[ '' == \-\-\t\o\g\g\l\e ]]
+ pkill -f -31 nwg-wrapper
+ for o in "${OUTPUTS}"
+ nwg-wrapper -o eDP-1 HDMI-A-1 -sv 30 -sq 31 -s help.sh -p left -a end
usage: nwg-wrapper [-h] [-s SCRIPT | -t TEXT] [-c CSS] [-o OUTPUT] [-p POSITION] [-a ALIGNMENT] [-j JUSTIFY] [-mt MARGIN_TOP] [-mb MARGIN_BOTTOM] [-ml MARGIN_LEFT] [-mr MARGIN_RIGHT] [-l LAYER] [-si] [-sl SIG_LAYER] [-sv SIG_VISIBILITY] [-sq SIG_QUIT] [-sr SIG_REFRESH] [-r REFRESH]
                   [-v]
nwg-wrapper: error: unrecognized arguments: HDMI-A-1
```

It appears that storing multiple display names in `OUTPUTS` is not working as expected.

This could be fixed by:

a) replacing `for o in "${OUTPUTS}"; do` with `for o in $(echo "${OUTPUTS}"); do` or
b) removing variable `OUTPUTS` altogether, and replacing `for o in "${OUTPUTS}"; do` with `for o in $((swaymsg -t get_outputs --raw | jq -r '.[].name'); do`

Personally, I think option b) is the cleaner solution.

@boredland I could create a PR for that if you agree.

**Comment by boredland** [comment]
Sure! Would be super happy about it!
