### ISSUE TITLE
Link to wrong settings file in SUPPORT.md

### ISSUE THREAD

**Issue by ochsma** [Manjaro-Sway/manjaro-sway#294]
Hey there,
I spotted a small issue in the `SUPPORT.md` file. 
It's mentioning adding some definitions into the `~/.config/sway/config.d/02-directional.conf` file for `sway`.
I think it was supposed to be the `~/.config/sway/definitions.d/02-directional.conf` file.

I spotted it while trying out the config in the wrong folder mentioned in the `SUPPORT.md` file.

The line in question can be found [here](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md?plain=1#L254).

**Comment by boredland** [comment]
you may be right. I find it hard to distinguish between "definition" and "config" in a lot of cases tbh. Will change it.
