### ISSUE TITLE
Problem when downloading img via github link

### ISSUE THREAD

**Issue by jewel943** [Manjaro-Sway/manjaro-sway#295]
Due to the time-limited download link of github,I can't download an img completely.And curl doesn't work.So I hope to have an download link of mega cloud drive or google cloud drive or any other working solution,thanks

**Comment by boredland** [comment]
Hi! This is a point I did not have on my plate to be honest. I will have a look so we can upload the images to some kind of CDN.

**Comment by boredland** [comment]
Hi there! I think I may have found a relatively elegant solution to this: github pages. Will keep you posted, but [so far this looks pretty amazing](https://github.com/Manjaro-Sway/manjaro-sway/runs/8080794215?check_suite_focus=true).

**Comment by boredland** [comment]
https://manjaro-sway.download/ now has direct links to the most recent downloads as well as a link to a torrent file.
