### ISSUE TITLE
Systems freezes 5.15/5.17/5.18&brtfs/ext4

### ISSUE THREAD

**Issue by ziombra** [Manjaro-Sway/manjaro-sway#296]
Hi, all!

I currently have a bug on my Dell Latitude 7480/i5/16/1080p/
A system freeze occurs, during which, e.g. When watching some YouTube, the sound changes in about ~0.5-1 second or also cases when clicking on the touchpad with the right button on the sensor. Caps Lock also starts flashing about ~10 seconds before you have to physically shut down the laptop. Accordingly, the keyboard, touchpad/mouse, and display do not respond, but the keyboard backlight works. No graphical errors when freezing. There are general ones like the one above, but on an ongoing basis, that I can't solve either.
I've been using Manjaro/Sway for almost a year. The bug itself began to appear with ~autumn updates. It can occur randomly, without any reason or specific actions.

When changing kernel 5.17-5.15-5.18 the bug did not disappear, I use manjaro-sway-21.2.4-220626_(stable or unstable branch equally)_. Also changed FS - brtfs->ext4.
A similar situation in #275 

There were no such bugs on the website of the laptop manufacturer either.
After switching to Fedora/openSUSE/Debian, no such errors were found.
Could this be a system error or a kernel problem?

Thank you.

**Comment by boredland** [comment]
I just had something similar when plugging in my usb-c docking station and had it before when trying to resume from standby. Is your root partition encrypted?

**Comment by boredland** [comment]
I am 99% sure we don't do anything special in manjaro sway, so without further information I deem this an upstream issue, and close it to be tracked in https://github.com/Manjaro-Sway/manjaro-sway/issues/275
I'd recommend you to ask for help in the manjaro forums.
