### ISSUE TITLE
Wondering about desktop-settings

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#298]
is this supposed to be in the public config? Then it should be documented somehow, I have no idea what this program is about, sounds a bit like timewarrior?
```sh
# zeit tracking
set $zeit_list zeit list --only-projects-and-tasks --append-project-id-to-task | \
    rofi -dmenu -font "$gui-font" -p "Select task to track" -lines 10 -width 35 -theme-str $rofi_theme | \
    /usr/share/sway/scripts/zeit.sh track && \
    pkill -RTMIN+10 waybar
```

Are issues about https://github.com/Manjaro-Sway/desktop-settings supposed to be tracked here, as issues are disabled over there?

**Comment by boredland** [comment]
> is this supposed to be in the public config? Then it should be documented somehow, I have no idea what this program is about, sounds a bit like timewarrior?

[exactly](https://github.com/mrusme/zeit)! we probably should have a section about tools we have preinstalled and what their purpose is. would you like to give this a start? we use this repo for documentation, so either add a new section to SUPPORT.md or the readme. I have no strict preference.

**Comment by xeruf** [comment]
then the readme of https://github.com/Manjaro-Sway/desktop-settings should link back here. Unfortunately I am quite caught up at the moment.

**Comment by boredland** [comment]
> the readme of https://github.com/Manjaro-Sway/desktop-settings should link back

ah, the reason we're not modifying the readme or anything there is, that this repo rebases onto the upstream and I want to avoid conflicts.

so, as a compromise I added this issue tracker as a repo url.
