### ISSUE TITLE
Allow vim-style and arrow key bindings in sway config

### ISSUE THREAD

**Issue by xeruf** [Manjaro-Sway/manjaro-sway#299]
I would deem it sensible to enable both vim-style (hjkl) and arrow key bindings for moving focus and resizing and so on by default, as the keys aren't used by something else anyways and I as a vim user use both from time to time.

**Comment by boredland** [comment]
I am certainly no opposed to it, as you're not the first to look for vim-bindings. BUT: right now it is configured so you can [override the keybinds easily](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-use-wasd-for-directional-navigation). With your proposal this would mean we'd have to duplicate all the defintions in which we use $up $down $left or $right to be using hjkl too. Or did you have something else in mind?

**Comment by xeruf** [comment]
yes, we have to duplicate them, as is already done in the default `/etc/sway/config` at least on my system.
The way they do it there, arrow keys always work and vim-style keys work additionally if the variables are set.

**Comment by boredland** [comment]
ok, I'd propose we add it like this then:

```
set $left_alt h
set $down_alt j
set $up_alt k
set $right_alt l
```

and duplicate every place where we use $left etc. which should be around four places (resize 10px, resize 50px, move, focus). wdyt?

**Comment by xeruf** [comment]
Hm, I don't see why we wouldn't do it like sway does by default:
Hardcode arrow keys in addition to the variables.

**Comment by boredland** [comment]
I mean, both is fine. Having both as variables gives ppl. the option to combine other variants, like wasd & hjkl etc.,  which clearly will be an edge case, so you're probably correct.

**Comment by xeruf** [comment]
I don't see how anyone used to vim-style would ever go back to wasd ^^ I dunno, I guess this is bikeshedding at this point though

**Comment by boredland** [comment]
added the alternative bindings, for me they seem to work just fine!
