### ISSUE TITLE
lock does not work because swaylock is called with non-exising command line parameters by default

### ISSUE THREAD

**Issue by felixniemeyer** [Manjaro-Sway/manjaro-sway#300]
Hi there, 

thanks for your great work, really appreciate it!

### problem description 
I noticed that the default value for `$locking` calls swaylock with a bunch of parameters that swaylock does not support. 
Here is the default $locking command string from _/etc/sway/definitions_ :
```
set $locking swaylock --daemonize --color "$selection-color" --inside-color "$selection-color" --inside-clear-color "$text-color" --ring-color "$color2" --ring-clear-color "$color11" --ring-ver-color "$color13" --show-failed-attempts  --grace 2 --effect-vignette 0.5:0.5 --effect-blur 7x5 --ignore-empty-password --screenshots --clock
```

It uses the following parameters that `swaylock -h` doesn't list: 
- fade-in 
- grace
- effect-vignette
- effect-blur
- screenshots 
- clock

Consequently, when calling lock by `windows+shift+e` and then "l" for lock, nothing happens. 

### workaround
A workaround is to override `$locking` in _.config/sway/definitions.d/lockfix.conf_ like this:
```
set $locking swaylock --daemonize --color "$selection-color" --inside-color "$selection-color" --inside-clear-color "$text-color" --ring-color "$color2" --ring-clear-color "$color11" --ring-ver-color "$color13" --show-failed-attempts  --ignore-empty-password 
```
There I have simply stripped off all the unsupported command line params. 
But this also means there is no blurred screenshot like I know from manjaro i3 version. 

### expected behaviour
I wish swaylock would work with out of the box with the default sway config + a nice visual appearance with a blurred desktop screenshot :-)

I hope this report helps to improve manjaro sway edition.

Felix

**Comment by boredland** [comment]
I am using swaylock on a daily basis, are you using the version from our repos (swaylock-effects).

**Comment by felixniemeyer** [comment]
I installed  manjaro sway from (I think) the official manjaro sway iso. 
```
swaylock --version
swaylock version 1.6
```
But I don't have a swaylock-effects package installed
```
pacman -Qs swaylock
local/swaylock 1.6-2
    Screen locker for Wayland
```
I think I did not change anything after installing manjaro sway from the iso. 

Maybe the manjaro sway iso comes with swaylock (without -effects) but with a config that needs swaylock-effects.

**Comment by boredland** [comment]
hi @felixniemeyer, did you download the minimal image? If so, in 20/30 minutes there should be a new release to try.

**Comment by felixniemeyer** [comment]
Hi @boredland 
I have replaced swaylock with swaylock-effects via pacman.
Now everything works fine and looks good!

I don't want to try reinstalling my system right now, if this is, what youre asking me to do^^ but the line that adds swaylock-effects to the requirements looks good. 

I hope me reporting this was helpful in the sense that others who install manjaro sway form the minimal image get a working lock out of the box. 

Thank you!

**Comment by boredland** [comment]
ah, you're right. that would be rather complicated. great to hear things work on your end now!
