### ISSUE TITLE
Dragging and Dropping Between Folders Uses Outdated Paths

### ISSUE THREAD

**Issue by skunkfox** [Manjaro-Sway/manjaro-sway#301]
Let's say I have two instances of PCManFM open. I am dragging and dropping files between two folders. However if I rename the directory path of one of the folders, dragging and dropping breaks. This is a serious usability issue.

Let me show you what I mean. I have one folder open, the path is "/home/fox/Downloads/Alex Voice Project/God of War Samples". It is filled with ogg audio files.

I have a second folder open in a new window, the path is: "/home/fox/Downloads/Alex Voice Project/Voice References/Talking". I can drag and drop into this folder.

But let's say, in the "Talking" window, I want to rename the path. In that second window, I go up a folder and rename the "Talking" folder to "Atreus Talking" so now the path reads: "/home/fox/Downloads/Alex Voice Project/Voice References/Atreus Talking". I jump back into the "Atreus Talking" folder and try to drag and drop from the "God of War Samples" folder in the first window to the "Atreus Talking" folder in the second window.

Now I get a popup error: "Error when getting information for file “/home/fox/Downloads/Alex Voice Project/God of War Samples/4409039.ogg”: No such file or directory". That's bizarre, because I haven't even touched the source folder for "God of War Samples". If I kill both windows with PCManFM, and re-open them, I can then drag and drop like normal.

I am posting this bug here, instead of on the PCManFM git repo, because until recently I was using Gentoo (love Manjaro: Sway Edition too much to not switch back) and I wasn't experiencing this issue with PCManFM as far as I can tell. But if you guys think I should post this bug with them then let me know.

**Comment by boredland** [comment]
I am not sure this is something we could solve on our end. We just pull the Manjaro package and they afaik are pulling the untouched arch package.

**Comment by skunkfox** [comment]
> I am not sure this is something we could solve on our end. We just pull the Manjaro package and they afaik are pulling the untouched arch package.

I will go ahead and see if I can reproduce it on other distros and then submit a bug with them. For now you can close this thread.
