### ISSUE TITLE
update rofi-wayland

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#303]
Hello, can you run the update action for rofi-wayland as they are up to version 1.75 and we are still 1.7.0

thanks

**Comment by boredland** [comment]
ideas what might be going on [here](https://github.com/Manjaro-Sway/rofi-wayland/runs/8057255529?check_suite_focus=true#step:3:1138)?

**Comment by Mathew-D** [comment]
That is very interesting as if I download and run the PKGBUILD file on my system it builds with no errors.  It must be something with the action itself but I have no idea what.  Sorry I couldn't be more help as I haven't used actions on github before.

**Comment by boredland** [comment]
It might be a dependency missing, there is present on our systems.

**Comment by boredland** [comment]
seems that rofi package got disowned. questionable if we should stick with rofi. the previous maintainer suggested [fuzzel](https://codeberg.org/dnkl/fuzzel), which I never heard of.

**Comment by Mathew-D** [comment]
I looked at it... you can't even open an app with the mouse at all. The package in AUR might be disowned but the rofi itself is still getting updates regularly.

**Comment by boredland** [comment]
Found the underlying issue (privilege escalation in docker) and should work now.
