### ISSUE TITLE
Calamares installer crashes on startup

### ISSUE THREAD

**Issue by upa58** [Manjaro-Sway/manjaro-sway#304]
Hello,

I downloaded the image `manjaro-sway-21.3.2-220828-linux515.iso` and booted from it. When I tried to start the installer, it immediately crashes:
```
$ sudo -E calamares
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
19:40:13 [1]: void bail(const QString&, const QString&)
    ERROR: FATAL in "/usr/share/calamares/branding/manjaro/branding.desc" 
     Slideshow file /usr/share/calamares/branding/manjaro/slideshow/SlideShow.qml does not exist or is not a valid QML file.
```
I was able to fix this issue by manually editing the file `/usr/share/calamares/branding/manjaro/slideshow/SlideShow.qml` in line 202 to point to the existing file `show.qml`. When I ran the installer afterwards again, I got an other error:
```
$ sudo -E calamares
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
19:49:03 [1]: void bail(const QString&, const QString&)
    ERROR: FATAL in "/usr/share/calamares/branding/manjaro/branding.desc" 
     Image file /usr/share/calamares/branding/manjaro/logo_small.svg does not exist.
```
In total there are 4 referenced files in `/usr/share/calamares/branding/manjaro/slideshow/SlideShow.qml` which do not exist in the filesystem. After replacing all of them, the installer seems to work normally.

**Comment by boredland** [comment]
This has to be a very recent issue. I installed two days ago using last weeks iso without an issue.

**Comment by boredland** [comment]
Update: seems to be [fixed upstream](https://gitlab.manjaro.org/packages/extra/calamares/-/commit/433f018892daf73ac1b203e094a15a3862661082) already. Will try to create a new issue soonish, can you try with last weeks image?

**Comment by upa58** [comment]
Yes, I just tried last weeks image `manjaro-sway-21.3.2-220821-linux515.iso`: No errors.
Even the Calamares installer starts up immediately after boot (which did not happen with yesterdays release).

**Comment by boredland** [comment]
New image should be available (due to some hick-ups even multiple). You could try if that fits the bill!

**Comment by upa58** [comment]
I confirm that the current release `manjaro-sway-21.3.2-220830-linux515.iso` is not affected by the issue anymore.

Thank you for the quick fix!
