### ISSUE TITLE
Failed to connect to boredland.github.io port 443: Connection refused

### ISSUE THREAD

**Issue by 1337omega** [Manjaro-Sway/manjaro-sway#31]
Downloaded the latest iso. after installation i tried to install some stuff and got this error

**Comment by boredland** [comment]
hi! I'm restructuring a lot right now, so the address of the custom package repo changed. you can update that yourself in `/etc/pacman.conf` (should be in the end of the file). Replace the boredland-entry with:
```
[manjaro-sway]
SigLevel = Optional TrustAll
Server = https://packages.manjaro-sway.download/
```

**Comment by 1337omega** [comment]
it worked

**Comment by boredland** [comment]
sorry for the extra work. you'll need to change the line again to `Server = https://packages.manjaro-sway.download/$arch`

**Comment by 1337omega** [comment]
i tried it with the line but got a connection timout

**Comment by boredland** [comment]
can you give me some logs? for me https://packages.manjaro-sway.download/ doesn't time out...

**Comment by 1337omega** [comment]
So i tried today again after i commented out Boredland this is the result.

`Synchronizing package databases...
https://packages.manjaro-sway.download/x86_64/boredland.db: Could not connect: Connection refused
Failed to prepare transaction:
could not find database
Warning: subfinder: local (807.615d480-1) is newer than community (2.4.5-1)
Failed to prepare transaction:
could not find database
Transaction cancelled.`

pacman.conf:

`[boredland]
SigLevel = Optional TrustAll
Server = https://packages.manjaro-sway.download/$arch
`


off topic.. why do i need to reboot after installing something. every time.

**Comment by boredland** [comment]
`boredland.db` means that you did only replace the url line. please replace the whole "repo" block as stated earlier. how it is now in your conf, it searches for the wrong repo in the right place:
```
[manjaro-sway]
SigLevel = Optional TrustAll
Server = https://packages.manjaro-sway.download/$arch
```

> off topic.. why do i need to reboot after installing something. every time.

you shouldn't what do you mean with that?
