### ISSUE TITLE
iso not starting properly in qemu/kvm

### ISSUE THREAD

**Issue by boredland** [manjaro-sway/manjaro-sway#318]
there currently are several issues starting in qemu/kvm:

- source update takes forever
- some issue with the guest drivers not loading during boot
- my cursor was upside down?
- tbd

**Comment by daiaji** [comment]
In fact, it seems that the performance of the qxl graphics card is not enough to use Sway. When I use virtio vga gl, everything seems to be relieved, but my mouse is still upside down.🙃
![Screenshot_20221011_225312](https://user-images.githubusercontent.com/25875791/195125480-17449874-eca1-489b-9db5-63bd6f6595c8.png)

**Comment by boredland** [comment]
those are great finding! I guess we should be able to base a fix on this!

**Comment by daiaji** [comment]
https://github.com/swaywm/sway/issues/6581
Found a related issue, what do you think?

**Comment by boredland** [comment]
so to wrap this up:

- we need to ensure spice-vdagent is installed in the live image
- we need to ensure spice-vdagent is started in the live image

**Comment by munoz0raul** [comment]
Hi Any suggestion for that: https://github.com/swaywm/sway/issues/6581

**Comment by boredland** [comment]
I tried this using todays image with Gnome Boxes and enables hardware acceleration with mixed results:

1. the cursor is not inverted
2. the cursor is at the right position

BUT the cursor is slooooow:

[recording_20230209-163547.webm](https://user-images.githubusercontent.com/4662748/217859753-7e38a389-12c8-49ec-83dd-a4c582e4a151.webm)

We still have `WLR_NO_HARDWARE_CURSORS=1` in our `.profile` - that might cause that issue.

**Comment by daiaji** [comment]
> I tried this using todays image with Gnome Boxes and enables hardware acceleration with mixed results:
> 
>     1. the cursor is not inverted
> 
>     2. the cursor is at the right position
> 
> 
> BUT the cursor is slooooow:
> recording_20230209-163547.webm
> 
> We still have `WLR_NO_HARDWARE_CURSORS=1` in our `.profile` - that might cause that issue.

Indeed, it is exceptionally sluggish, especially when opening Firefox, but I am unsure as to the cause.
