### ISSUE TITLE
Workspace change disabled when using deattached web apps

### ISSUE THREAD

**Issue by arkaitz-dev** [manjaro-sway/manjaro-sway#320]
When I use a deattached (from web browser --Brave in my case, but perhaps also with Chrome--), the workspace changing is disabled. As an example, whenever I open in a deattached web app Whatsapp, Protonmail, Reddit or whatever you use, I can't change workspace unless I use the mouse to select in the sway-bar the workspace I want to go to. It also happens that I can't open new apps/windows in that workspace (where the app is opened/been used). Is like the windows key gets disabled for some unknown reason whenever a new web app window is opened in a workspace.

**Comment by boredland** [comment]
I can reproduce this. It's like the chrome apps gain all focus, when you use chrome apps (chrome://apps). Weird.

**Comment by boredland** [comment]
Seems to be a [known](https://www.reddit.com/r/swaywm/comments/vuhr75/why_does_chromium_with_app_now_grab_complete/) problem.

I will add 

```
# Don't allow applications to inhibit shortcuts, i.e. grab total control of the
# keyboard. Chrome currently abuses this by enabling it for all "--app=..."
# shortcuts.

seat * shortcuts_inhibitor disable
```

to our sway config.

**Comment by boredland** [comment]
@all-contributors please add @arkaitz-dev for reporting a bug
