### ISSUE TITLE
electron-flags.conf: electron does not start with all parameters in one line

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#322]
With the recently introduced (via [this commit](https://github.com/manjaro-sway/desktop-settings/commit/997111f69f5faff46a44bb49a9ede7bd87c4fa5f)) `electron-flags.conf` one-liner, `electron` and `slack` (an electron app) throw an error, for example:
```
[3711:0912/180359.169645:FATAL:platform_selection.cc(45)] Invalid ozone platform: wayland --enable-features=WaylandWindowDecorations
[1]    3711 trace trap (core dumped)  **slack**
```
Works fine with params in separate lines. Please consider reverting that commit. Thanks!

**Comment by boredland** [comment]
I think that means that it works, but that slack-electron has a severe issue.

**Comment by Mathew-D** [comment]
sounds like the electron version that slack is using doesn't support wayland so you were using xwayland

**Comment by boredland** [comment]
Na, I guess he is using slack-electron from the aur and that one indeed does not play well with one-liner config. Reverted it, lets see if issues pop up again, but so far it looks good on my machine. Can't recall what was causing issues before.

**Comment by boredland** [comment]
Oh man... now I know why I changed it. google-chrome-beta now isn't picking up anything but the first line :1st_place_medal:

**Comment by boredland** [comment]
I'd propose to have two configs: "electron" multi line and "chrome" single line. symlinks for each and then hope for the best. What a bs that they don't speak the same language in terms xD
