### ISSUE TITLE
Sway window split indicator not visible by default

### ISSUE THREAD

**Issue by upa58** [manjaro-sway/manjaro-sway#325]
When changing split mode in Sway (`$mod+e layout toggle split`) there is no visible change. This is confusing, since you cannot see which split mode is currently active. (At first I even thought that the keybinding is not working at all.)

This is due to the used sway theme, in which the color for the Indicator is identical to the Child Border color (`§color12`):

`/usr/share/sway/themes/matcha-green/definitions`:
```
# Property Name         Border  BG      Text    Indicator Child Border
client.focused          $color5 $color12 $color0 $color12 $color12
```

I suggest highlighting the color of the indicator (as in the original Sway configuration).

**Comment by boredland** [comment]
would love to hear some feedback in https://github.com/manjaro-sway/desktop-settings/pull/129
