### ISSUE TITLE
How to change this border color

### ISSUE THREAD

**Issue by mioscape** [manjaro-sway/manjaro-sway#329]
I wonder how to change this border colour (Brightness Bar, Volume Bar & Notification Bar)

I want to match it with Catppuccin Color Scheme

![image](https://user-images.githubusercontent.com/43681888/191192101-c7a04f00-9cda-4f68-bad6-594b189d37c1.png)
![image](https://user-images.githubusercontent.com/43681888/191192361-7f2032ee-acde-49ba-b7fe-c308a0daa26e.png)

**Comment by boredland** [comment]
You can create and load a custom theme. I will make this a bit easier then it is now, but roughly:

Create a copy of the theme: https://github.com/manjaro-sway/desktop-settings/tree/sway/community%2Fsway%2Fusr%2Fshare%2Fsway%2Fthemes%2Fmatcha-green

And point to it by editing your .config/sway/config

**Comment by mioscape** [comment]
> You can create and load a custom theme. I will make this a bit easier then it is now, but roughly:
> 
> Create a copy of the theme: https://github.com/manjaro-sway/desktop-settings/tree/sway/community%2Fsway%2Fusr%2Fshare%2Fsway%2Fthemes%2Fmatcha-green
> 
> And point to it by editing your .config/sway/config

Which variable do i need to change. I did change the configuration, but no luck

**Comment by mioscape** [comment]
Any solution?

**Comment by boredland** [comment]
Yes, it is super easy:

```
cp /usr/share/sway/themes/matcha-green)/definitions ~/.config/sway/definitiond.d/theme.conf
```

do your customization in `~/.config/sway/definitiond.d/theme.conf`.

**Comment by boredland** [comment]
I would keep this ticket open, as we should document that in our Support.md

**Comment by mioscape** [comment]
> I would keep this ticket open, as we should document that in our Support.md

Uhh sorry, its changed. I thought the colors changed without rebooting the device. 

![image](https://user-images.githubusercontent.com/43681888/191721708-bb10f837-bfba-4b9a-be8a-4f0d3c62ce25.png)

**Comment by boredland** [comment]
> I edit the file immediately in /usr/share/sway/themes/matcha-green/definitions, I'll move it to ~/.config

please do that, as it will ensure this endures updates.

**Comment by boredland** [comment]
keeping open to make sure we document this properly.

**Comment by mioscape** [comment]
> > I edit the file immediately in /usr/share/sway/themes/matcha-green/definitions, I'll move it to ~/.config
> 
> please do that, as it will ensure this endures updates.

It's working

![image](https://user-images.githubusercontent.com/43681888/191722951-1679f2bd-7d4b-4d05-810e-dd1bfa2351fb.png)
![image](https://user-images.githubusercontent.com/43681888/191723032-e663bb81-d8cb-43c6-a2d4-b42e8da11d1d.png)

**Comment by robin-thoene** [comment]
Hey,

I know this is closed but I have a similar issue. I can not get the Volume and Brightness bar to change the color.

My current theme is located under `.config/sway/themes/custom/definitions` and looks like this:

```
# some global theme specific variables
set $gtk-theme Dracula
set $icon-theme Dracula
set $cursor-theme xcursor-breeze
set $gui-font JetBrainsMono Nerd Font 11
set $term-font JetBrainsMono Nerd Font 11
set $gtk-color-scheme prefer-dark
set $kvantum-theme Dracula

set $color0  #141a1b
set $color1  #282a2b
set $color2  #3B758C
set $color3  #41535B
set $color4  #43a5d5
set $color5  #d6d6d6
set $color6  #f8f8f2
set $color7  #ffffff
set $color8  #Cd3f45
set $color9  #db7b55
set $color10 #e6cd69
set $color11 #9fca56
set $color12 #bd93f9
set $color13 #55b5db
set $color14 #a074c4
set $color15 #8a553f

#$color0
set $background-color $color0
#$color6
set $text-color $color6
#color1
set $selection-color $color1
#color12
set $accent-color $color12

# Basic color configuration using the Base16 variables for windows and borders.
# Property Name         Border  BG       Text    Indicator Child Border
client.focused          $color5 $color12 $color0 $color6   $color12
client.focused_inactive $color1 $color1  $color5 $color3   $color1
client.unfocused        $color1 $color0  $color5 $color6   $color1
client.urgent           $color8 $color8  $color0 $color9   $color8
client.placeholder      $color0 $color0  $color5 $color0   $color0
client.background       $color7
```

The dracula theme I installed from here `https://github.com/dracula/gtk`. This is applied, I can verify by opening gtk / kvantum styled applications.

The theme is imported in my config `.config/sway/config`

```
# Default config for sway
#
# Copy this to ~/.config/sway/config and edit it to your liking.
#
# Read `man 5 sway` for a complete reference.

# styles - set the folder for your theme definition file
set $theme ~/.config/sway/themes/custom

# theme variables
include $theme/definitions

# global variables
include /etc/sway/definitions

# user variables
include $HOME/.config/sway/definitions.d/*.conf

include /etc/sway/inputs/*
include /etc/sway/outputs/*

# enable modes
include /etc/sway/modes/*

# only enable this if every app you use is compatible with wayland
# xwayland disable

# include additional configs e.g. to autostart applications
include /etc/sway/config.d/*

# user config
include $HOME/.config/sway/config.d/*.conf
```

Which seems to be applied, because for example the notification is themed with the correct color ($color12 -> #bd93f9)

Thanks in advance for any feedback / help.

**Comment by mioscape** [comment]
> Hey,
> 
> I know this is closed but I have a similar issue. I can not get the Volume and Brightness bar to change the color.
> 
> My current theme is located under `.config/sway/themes/custom/definitions` and looks like this:
> 
> ```
> # some global theme specific variables
> set $gtk-theme Dracula
> set $icon-theme Dracula
> set $cursor-theme xcursor-breeze
> set $gui-font JetBrainsMono Nerd Font 11
> set $term-font JetBrainsMono Nerd Font 11
> set $gtk-color-scheme prefer-dark
> set $kvantum-theme Dracula
> 
> set $color0  #141a1b
> set $color1  #282a2b
> set $color2  #3B758C
> set $color3  #41535B
> set $color4  #43a5d5
> set $color5  #d6d6d6
> set $color6  #f8f8f2
> set $color7  #ffffff
> set $color8  #Cd3f45
> set $color9  #db7b55
> set $color10 #e6cd69
> set $color11 #9fca56
> set $color12 #bd93f9
> set $color13 #55b5db
> set $color14 #a074c4
> set $color15 #8a553f
> 
> #$color0
> set $background-color $color0
> #$color6
> set $text-color $color6
> #color1
> set $selection-color $color1
> #color12
> set $accent-color $color12
> 
> # Basic color configuration using the Base16 variables for windows and borders.
> # Property Name         Border  BG       Text    Indicator Child Border
> client.focused          $color5 $color12 $color0 $color6   $color12
> client.focused_inactive $color1 $color1  $color5 $color3   $color1
> client.unfocused        $color1 $color0  $color5 $color6   $color1
> client.urgent           $color8 $color8  $color0 $color9   $color8
> client.placeholder      $color0 $color0  $color5 $color0   $color0
> client.background       $color7
> ```
> 
> The dracula theme I installed from here `https://github.com/dracula/gtk`. This is applied, I can verify by opening gtk / kvantum styled applications.
> 
> The theme is imported in my config `.config/sway/config`
> 
> ```
> # Default config for sway
> #
> # Copy this to ~/.config/sway/config and edit it to your liking.
> #
> # Read `man 5 sway` for a complete reference.
> 
> # styles - set the folder for your theme definition file
> set $theme ~/.config/sway/themes/custom
> 
> # theme variables
> include $theme/definitions
> 
> # global variables
> include /etc/sway/definitions
> 
> # user variables
> include $HOME/.config/sway/definitions.d/*.conf
> 
> include /etc/sway/inputs/*
> include /etc/sway/outputs/*
> 
> # enable modes
> include /etc/sway/modes/*
> 
> # only enable this if every app you use is compatible with wayland
> # xwayland disable
> 
> # include additional configs e.g. to autostart applications
> include /etc/sway/config.d/*
> 
> # user config
> include $HOME/.config/sway/config.d/*.conf
> ```
> 
> Which seems to be applied, because for example the notification is themed with the correct color ($color12 -> #bd93f9)
> 
> Thanks in advance for any feedback / help.

In my case, i need to re-apply the theme every time booted to linux

**Comment by robin-thoene** [comment]
Isn't that already the case when setting this theme in the config file?

**Comment by robin-thoene** [comment]
I found this in `/etc/sway/definitions`:

```
set $onscreen_bar /usr/share/sway/scripts/wob.sh "$accent-color" "$background-color"
```

this seems to be the line that is responsible for setting the bar colors. However, I already override these two colors in m theme, but the bar still stays green.

**Comment by boredland** [comment]
Hi there! @robin-thoene and I investigated a little yesterday evening. Apparently nothing ever refreshed the `wob` config and we had a problem with the order of things, as the global definitions are being loaded first, and nothing did override the `$onscreen_bar` variable. This one is being released as `manjaro-sway-settings-git`, feedback welcome! https://github.com/manjaro-sway/desktop-settings/commit/fe92adb84c5465663c6d21e0f52356b742d3522a

**Comment by robin-thoene** [comment]
What I am now as well experiencing after reboot with our/my updated solution is that the primary color is no longer applied to the notifications and the dmenu

![image](https://github.com/manjaro-sway/manjaro-sway/assets/110201991/bf686507-8da6-445e-8e36-d4bcaa071dd0)
![image](https://github.com/manjaro-sway/manjaro-sway/assets/110201991/474a5b02-b6ae-4edd-86bc-7d7114d873b5)

**Comment by boredland** [comment]
With said patch, this worked nicely for me:

1. Install `darcula-gtk-theme` (aur) and `dracula-kde-theme-git` (aur).
2. Add `.config/sway/definitions.d/theme.conf`:
```
# dracula
# needed packages: darcula-gtk-theme dracula-kde-theme-git
# some global theme specific variables
set $gtk-theme Dracula
set $icon-theme Papirus-Dark-Maia
set $cursor-theme Dracula-cursors
set $gui-font Roboto 11
set $term-font JetBrainsMono NF 14
set $gtk-color-scheme prefer-dark
set $kvantum-theme Dracula-purple-solid

set $color0  #141a1b
set $color1  #282a2b
set $color2  #3B758C
set $color3  #41535B
set $color4  #43a5d5
set $color5  #d6d6d6
set $color6  #f8f8f2
set $color7  #ffffff
set $color8  #Cd3f45
set $color9  #db7b55
set $color10 #e6cd69
set $color11 #9fca56
set $color12 #bd93f9
set $color13 #55b5db
set $color14 #a074c4
set $color15 #8a553f

#$color0
set $background-color $color0
#$color6
set $text-color $color6
#color1
set $selection-color $color1
#color12
set $accent-color $color12

# Basic color configuration using the Base16 variables for windows and borders.
# Property Name         Border  BG       Text    Indicator Child Border
client.focused          $color5 $color12 $color0 $color6   $color12
client.focused_inactive $color1 $color1  $color5 $color3   $color1
client.unfocused        $color1 $color0  $color5 $color6   $color1
client.urgent           $color8 $color8  $color0 $color9   $color8
client.placeholder      $color0 $color0  $color5 $color0   $color0
client.background       $color7
```

If y'all can confirm this working, we could even add this one to `/usr/share/sway/themes/`

**Comment by boredland** [comment]
> Hey @boredland.
> 
> big thank you again for the investigation yesterday!
> 
> What I am now as well experiencing after reboot with our/my updated solution is that the primary color is no longer applied to the notifications and the dmenu

Have to `skel`-ed the new `.config/sway/config`?

**Comment by robin-thoene** [comment]
What do you mean exactly with `to skel`?

**Comment by boredland** [comment]
> What do you mean exactly with `to skel`?

Copy the file from `/etc/.skel` - either manually or via the `skel` command.

**Comment by robin-thoene** [comment]
No luck so far. I executed the skel command and installed `dracula-kde-theme-git`. For some reason yay can not find `darcula-gtk-theme` on my machine.

I installed GTK and Kvantum theme manually before using the Dracula documentation and in my old version where I explicitly set the `$theme` var to my theme the notification cards and the dmenu where styled correct.

**Comment by boredland** [comment]
Just tried it on another machine and it worked like a charm... Updated the theme.conf to also use the icon-theme.

**Comment by robin-thoene** [comment]
I will investigate this after work and copy your `theme.conf` as well. Maybe there is a difference in that.

**Comment by boredland** [comment]
Maybe. Also I think the foot-theme needs some adaption. Perhaps you already figured that one out?

**Comment by robin-thoene** [comment]
Still no luck, even using your theme.conf, but I can not try out using the AUR package darcula-gtk-theme as yay has an error when I try to install it:

`No AUR package found for darcula-gtk-theme`

**Comment by boredland** [comment]
> Still no luck, even using your theme.conf, but I can not try out using the AUR package darcula-gtk-theme as yay has an error when I try to install it:
> 
> `No AUR package found for darcula-gtk-theme`

Oh, I just misspelled ;)

**Comment by boredland** [comment]
closing as we now have some stock themes that demo how theming could be done. its a rofi script `Manjaro Sway Theme` that will allow you to apply them.
