### ISSUE TITLE
Keyboard layout / variant for the login

### ISSUE THREAD

**Issue by jessybreyne** [manjaro-sway/manjaro-sway#332]
On a fresh installation, I chose the French keyboard in us variant (qwerty). But at login, I have azerty variant. I deduce that the variant is not taken at the login.

I fixed the problem by putting the us keymap in /etc/vconsole.conf. I do not know if it is possible to take into account the variant during the installation.

**Comment by boredland** [comment]
Hi there! There have been multiple discussions about this in the past - please have a look into our [SUPPORT.md](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#why-do-my-keyboard-settings-from-the-installer-have-no-effect). There are hints how to configure your keyboard too.
