### ISSUE TITLE
install manjaro calamares not work 

### ISSUE THREAD

**Issue by eyes1971** [manjaro-sway/manjaro-sway#336]
calamares need libboost 1.79 

but libboost 1.80 is in manjaro-sway.iso

**Comment by boredland** [comment]
Which image did you download? Stable or latest?

**Comment by AdriandMartin** [comment]
I had this problem with the latest release, @eyes1971 are you referring to that?
![ManjaroSwayCalamaresIssue](https://user-images.githubusercontent.com/22200464/196143666-05a6a5b5-1c4d-4b05-afc9-bd02d5ac6307.png)

**Comment by boredland** [comment]
hm, but calamares has not been updated:
https://gitlab.manjaro.org/packages/extra/calamares/-/blob/master/PKGBUILD

**Comment by AdriandMartin** [comment]
Wow, I see. So why does pamac report about an update? And where does it come from if the package wasn't updated?

**Comment by boredland** [comment]
Can you try the "stable" image instead? Latest may always have incompatible things inside. While this works most of the time, there is no way of knowing.

**Comment by khanxbahria** [comment]
I used the [manjaro-sway-21.3.2-221016-linux515.iso.zip](https://github.com/manjaro-sway/manjaro-sway/releases/download/202210160422/manjaro-sway-21.3.2-221016-linux515.iso.zip) but same issue. I tried updating Calameres to 3.2.61-5 as well, but the manjaro live installer fails on last step.

**Comment by AdriandMartin** [comment]
I couldn't find a release tagged as "stable", do you refer to the non-latest ISOs in [the webpage](https://manjaro-sway.download/)

**Comment by ovidius72** [comment]
same problem

**Comment by boredland** [comment]
I the packaging on our end, so it should :tm: pick the upstream version of calamares. I asked with the manjaro team, how come there is a different version of the package in the repos then in its source :-/

**Comment by boredland** [comment]
Soo, new images should be out. Please give me feedback if that didn't do the trick!
