### ISSUE TITLE
Weird font after fresh installation

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#340]
Just installed manjaro sway (the unstable iso) on my new laptop and encountered this unfamiliar default font (firefox and rofi at least): 
![image](https://user-images.githubusercontent.com/33870649/198730518-6779741c-fb44-433c-98c0-aa1ffc475b8e.png)

How can I change this to the manjaro sway default font? Thanks!

**Comment by boredland** [comment]
Thats strange. We didn't change sth. in that department, but it certainly looks like the monospace font is being used everywhere for you.
seems we did set it in the [gtk settings](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/skel/.gtkrc-2.0#L4). Would you mind trying out another font there and if thats helping in your case?

**Comment by boredland** [comment]
in the theme, we [properly differentiate](https://github.com/manjaro-sway/desktop-settings/blob/2d564e28639f3fcb50871e1c5a97e5daa5b0fc28/community/sway/usr/share/sway/themes/matcha-green/definitions#L9) between terminal/monospace and others. don't understand yet whats going wrong there.

**Comment by Tamriel** [comment]
I had this font bug as well, and installing the following solved it:
`sudo pacman -S calibre chromium digikam grsync intellij-idea-community-edition keepassxc mediainfo-gui meld musescore pdfpc sigil soundkonverter texlive-fontsextra texlive-genericextra texlive-htmlxml texlive-latexextra texlive-pictures texlive-science languagetool ocrfeeder mkvtoolnix-gui pavucontrol mp3splt-gtk posterazor bookworm telegram-desktop numlockx libreoffice-still libreoffice-still-de code evince youtube-dl nautilus sushi pdfarranger lib32-libcups adobe-source-sans-pro-fonts quodlibet font-manager ttf-opensans ttf-ms-fonts ttf-sil-fonts`
I don't know which of the packages solved it, but one did.

**Comment by boredland** [comment]
My bet would be on ttf-opensans. Let me know, so we can add it as a dependency of our settings package!

**Comment by boredland** [comment]
added ttf opensans and triggered a new release.

**Comment by hakanyi** [comment]
Thanks all, ttf opensans doesn't help, unfortunately (in fact, I didn't have that package installed on my old laptop until the update today), so feel free to remove it as a dependency.
The roboto font is simply missing and I could install it via `ttf-roboto`, but that package isn't installed on my old laptop either. It seems to be hiding in some other package that's not yet a dependency of the settings package?

**Comment by boredland** [comment]
I mean, we could add that roboto package, but that is not installed separately on my machine. I currently can't check what provides that font, but my guess is that it is being shipped alongside something chrome/electron like (Telegram, Chrome, Slack). Will take a look as soon as possible.

**Comment by hakanyi** [comment]
Good pointer, thanks! 
`ttf-liberation` (shipped with Chromium, for example) seems to be the culprit, can you confirm?

**Comment by boredland** [comment]
Yes, I have that package! That seems likely.

**Comment by tve** [comment]
I'm also having font issues. Below is screen shot of how github looks in vivaldi (all monospaced fonts). It looke fine in firefox. I assume FF is Wayland native which Vivaldi isn't (I believe I have to enable the wayland mode explicitly).

![image](https://user-images.githubusercontent.com/39480/201456578-2b8018a0-f8a8-4237-953a-b280f24e70fc.png)

**Comment by boredland** [comment]
> I'm also having font issues. Below is screen shot of how github looks in vivaldi (all monospaced fonts). It looke fine in firefox. I assume FF is Wayland native which Vivaldi isn't (I believe I have to enable the wayland mode explicitly).
> 
> ![image](https://user-images.githubusercontent.com/39480/201456578-2b8018a0-f8a8-4237-953a-b280f24e70fc.png)
> 

Hi! This is a different problem. You have to add a -flags.conf file for Vivaldi.

**Comment by tve** [comment]
> Hi! This is a different problem. You have to add a -flags.conf file for Vivaldi.

Your right, I had to go to vivaldi://flags/#ozone-platform-hint and switch it to 'auto'. Does that point to a problem with the X11 fonts, though?

**Comment by boredland** [comment]
Nah, thats just an issue with vivaldi not starting in wayland mode. I [added](https://github.com/manjaro-sway/desktop-settings/commit/e30aa7203c57d3267451e8174057a29ba69ff2ca) symlink to the chrome flags to our default skel.
