### ISSUE TITLE
Is there an alternative to KDE Connect in the sway ecosystem?

### ISSUE THREAD

**Issue by daiaji** [manjaro-sway/manjaro-sway#341]
KDE Connect is really convenient.
Although I couldn't experience it on a virtual machine due to some compatibility glitches between QEMU/KVM virtual machines and sway, the rough experience of running a live CD on bare metal seemed satisfactory.
Also, I want to bind the side buttons b10 and b11 of the mouse. The native button bindings of sway should be able to bind these special buttons, right?

**Comment by boredland** [comment]
Hi there! Historically there have been issues using kde connect and sway and afaik there is no wayland/wlroots ecosystem solution I know of.

Regarding your mouse: you could use [wshowkeys](https://git.sr.ht/~sircmpwn/wshowkeys) to demonstrate if your keys are being picked up by wayland.

**Comment by daiaji** [comment]
> Hi there! Historically there have been issues using kde connect and sway and afaik there is no wayland/wlroots ecosystem solution I know of.

too painful.😭

**Comment by boredland** [comment]
Well I tried and kde connect works okay-ish out of the box. I couldn't get phone input to work, but clipboard share worked, multimedia controls worked, receiving input from linux worked...

**Comment by boredland** [comment]
Well, I can only recommend to try out kde-connect or gsconnect (chrome, firefox) and have a look if to fit the bill.

**Comment by daiaji** [comment]
> Well, I can only recommend to try out kde-connect or gsconnect (chrome, firefox) and have a look if to fit the bill.

[Valent](https://github.com/andyholmes/valent) has been performing admirably, and there is also an available [AUR package](https://aur.archlinux.org/packages/valent-git).

It appears that it doesn't rely on GNOME, but rather utilizes the GTK library. 

Perhaps it might be worthwhile to consider incorporating Valent into the software repository for Manjaro-Sway?

Unfortunately, due to virtual performance constraints, I am unable to conduct further testing of Valent.

However, it successfully accomplishes tasks such as connecting with KDE Connect on an Android device and synchronizing clipboards.

It seems, however, that remote file access is not achievable.

**Comment by boredland** [comment]
Thanks for investigating. Will try it myself and add it to the repo as soon as possible.

**Comment by boredland** [comment]
When using the AUR package: does controlling via the mouse work for you? For me it doesn't and I wonder if there is a daemon or something I missed to start.

**Comment by boredland** [comment]
ah, pointer controls are a work in progress on the portal end: https://github.com/emersion/xdg-desktop-portal-wlr/pull/263

**Comment by daiaji** [comment]
Honestly, it's nice that Valent can decouple from GNOME and only use some GNOME graphics libraries, and that it's available in Alpha.

**Comment by daiaji** [comment]
> When using the AUR package: does controlling via the mouse work for you? For me it doesn't and I wonder if there is a daemon or something I missed to start.

To be honest, there really seems to be a lack of a service, at least on kde, there is a default open kde-connect service, or any other automatic startup solution?

**Comment by boredland** [comment]
> any other automatic startup solution

Valent has a autostart file which is fine as such. It has no tray-indicator, there seems to be one via gnome extensions.

**Comment by daiaji** [comment]
> > any other automatic startup solution
> 
> Valent has an autostart file which is fine as such. It has no tray-indicator, there seems to be one via gnome extensions.

sway should have something similar.

**Comment by boredland** [comment]
We could make a waybar module. Don't know what we want to show there tho and if we'd like to have some actions other than opening `valent`.

```
gdbus call --session \ 
           --dest "ca.andyholmes.Valent" \
           --object-path "/ca/andyholmes/Valent" \
           --method
"org.freedesktop.DBus.ObjectManager.GetManagedObjects"
```

returns the list of devices:

```
({objectpath '/ca/andyholmes/Valent/Device/0660b6e71d9a7448': {'ca.andyholmes.Valent.Device': {'State': <uint32 3>, 'Id': <'0660b6e71d9a7448'>, 'IconName': <'phone-symbolic'>, 'Name': <'Pixel 6'>}}},)
```

I guess we could write a little python cli for it what returns 0 if at least one device is connected and work from there?

**Comment by daiaji** [comment]
![Screenshot_20231228_115724](https://github.com/manjaro-sway/manjaro-sway/assets/25875791/19b86b4c-877b-431e-83e2-f088faa1e185)

Basically, after connecting to the device, the tray icon will expand to display the signal strength and battery level of the connected device
Then there are some plugin functions.
The blank area below the icon will display notifications for connecting devices.

**Comment by boredland** [comment]
Well, I don't think we could reach this level of features with waybar. That being said, individual information can be easily pulled from dbus:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/17a0ccbb-734f-4747-a885-a7f1be5be293)

```
 'notification.send',
 'unpair',
 'share.open',
 'runcommand.execute',
 'notification.close',
 'sms.fetch',
 'telephony.mute-call',
 'share.view',
 'clipboard.push',
 'share.uris',
 'battery.state',
 'clipboard.pull',
 'sftp.browse',
 'share.text',
 'notification.reply',
 'pair',
 'sms.messaging',
 'connectivity_report.state',
 'presenter.remote',
 'ping.message',
 'notification.action',
 'notification.cancel',
 'ping.ping',
 'presenter.pointer',
 'contacts.fetch',
 'mousepad.event',
 'share.cancel',
 'share.uri',
 'findmyphone.ring',
 'share.chooser'
```

I'd propose we start with a waybar icon that shows "disconnected" if at least one of the paired devices is disconnected. Then we could add a tooltip showing the 'connectivity_report.state',
and the 'battery.state' per devices in a list (similar to what we have for the weather icon).

**Comment by boredland** [comment]
Added a first version of the script. This is what it looks now:

[recording_20231228-152144.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/cd35c3fc-554a-4120-9df2-c9ab8268fc2e)

**Comment by boredland** [comment]
Basic version is implemented and released. There may be bugs and some of the parsing is brittle. If issues occur, we'll probably have to make it a bit more robust.

**Comment by boredland** [comment]
@all-contributors please add @daiaji for having a great idea
