### ISSUE TITLE
Welcome dialog for sway beginners

### ISSUE THREAD

**Issue by Tamriel** [manjaro-sway/manjaro-sway#342]
After installation I would love to see a welcome screen which says:

To add keyboard  shortcuts and autostart applications, edit `~/.config/sway/config`.
To adjust the status bar, copy and edit the following config files:
```
cp  ~/.config/waybar/config.jsonc.example ~/.config/waybar/config.jsonc
cp  ~/.config/waybar/style.css.example ~/.config/waybar/style.css
```

**Comment by boredland** [comment]
or perhaps we offer a "configuration hints" shortcuts in our list of shortcuts that just opens our SUPPORT.md file in the browser? wdyt?

**Comment by Tamriel** [comment]
Great!

**Comment by boredland** [comment]
why closing it? this was just an idea, nothing implemented yet!

**Comment by Tamriel** [comment]
You are right, sorry!

**Comment by Tamriel** [comment]
Will this shortcut be visible on the desktop now?
And is it possible to remove that list of shortcuts from the desktop?

**Comment by boredland** [comment]
if you want to get rid of it permanently, just [remove](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-disable-the-help-onscreen-menu-permanently) it. otherwise there is ctrl+shift+? for toggling its visibility.

**Comment by Tamriel** [comment]
Removing that file had no effect.
This view shall be disabled:
![Untitled](https://user-images.githubusercontent.com/5037153/198853427-8a6e141e-305e-4d3a-b5c1-1948e414c3c8.png)

**Comment by Tamriel** [comment]
I did work now, after a restart :smiley: :+1:
