### ISSUE TITLE
"unable to invoke grim" when saving a screenshot

### ISSUE THREAD

**Issue by Tamriel** [manjaro-sway/manjaro-sway#343]
This notification appears after I press print, then shift+p. The screenshot is not saved as a file.

**Comment by boredland** [comment]
As this sounds very strange, one question beforehand: are using the x86 version or are you on arm?

**Comment by Tamriel** [comment]
x86

**Comment by Tamriel** [comment]
Mh, somehow it works now! Sorry for bothering.
