### ISSUE TITLE
Weird keyboard layout behaviour

### ISSUE THREAD

**Issue by EmptyLungs** [manjaro-sway/manjaro-sway#344]
With such sway configuration keyboard toggle works well, but after reloading sway config it stops working, only US layout is available:
```
input "1:1:AT_Translated_Set_2_keyboard" {
    xkb_options ctrl:nocaps,grp:alt_shift_toggle
    xkb_switch_layout next
    xkb_layout us,ru
    xkb_numlock disabled
}
```

When I'm trying to modify config from shell it returns errors:
```
> sway input "1:1:AT_Translated_Set_2_keyboard" xkb_layout us,ru
< [ { "success": true }, { "success": false, "parse_error": true, "error": "Unknown\/invalid command 'ru'" } ]
```

I've tried to escape comma, but there's another error happened:
```
[ { "success": false, "parse_error": false, "error": "Failed to compile keymap: Couldn't find file \"symbols\/us\\\" in include paths" } ]
```

<details>
  <summary>Output of swaymsg -t get_inputs</summary>

```
Input device: ThinkPad Extra Buttons
  Type: Keyboard
  Identifier: 6058:20564:ThinkPad_Extra_Buttons
  Product ID: 20564
  Vendor ID: 6058
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: ETPS/2 Elantech TrackPoint
  Type: Mouse
  Identifier: 2:14:ETPS/2_Elantech_TrackPoint
  Product ID: 14
  Vendor ID: 2
  Libinput Send Events: enabled

Input device: ETPS/2 Elantech Touchpad
  Type: Touchpad
  Identifier: 2:14:ETPS/2_Elantech_Touchpad
  Product ID: 14
  Vendor ID: 2
  Libinput Send Events: enabled

Input device: AT Translated Set 2 keyboard
  Type: Keyboard
  Identifier: 1:1:AT_Translated_Set_2_keyboard
  Product ID: 1
  Vendor ID: 1
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Integrated Camera: Integrated C
  Type: Keyboard
  Identifier: 5967:9305:Integrated_Camera:_Integrated_C
  Product ID: 9305
  Vendor ID: 5967
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Sleep Button
  Type: Keyboard
  Identifier: 0:3:Sleep_Button
  Product ID: 3
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Lid Switch
  Type: Switch
  Identifier: 0:5:Lid_Switch
  Product ID: 5
  Vendor ID: 0
  Libinput Send Events: enabled

Input device: Power Button
  Type: Keyboard
  Identifier: 0:1:Power_Button
  Product ID: 1
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Video Bus
  Type: Keyboard
  Identifier: 0:6:Video_Bus
  Product ID: 6
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled

Input device: Power Button
  Type: Keyboard
  Identifier: 0:1:Power_Button
  Product ID: 1
  Vendor ID: 0
  Active Keyboard Layout: English (US)
  Libinput Send Events: enabled
```

</details>

**Comment by boredland** [comment]
I think I might know what causes this.

**Comment by andrius** [comment]
I have similar issue; in my case the file name is `~/.config/sway/config.d/90-keyboard.conf`. However I can't switch layout with console too: 

```sh
❯ swaymsg input '*' xkb_layout "us"                   

~
❯ swaymsg input '*' xkb_layout "us,lt"
Error: Unknown/invalid command 'lt'

~
❯ swaymsg input '*' xkb_layout "us,ru"
Error: Unknown/invalid command 'ru'
```

**Comment by boredland** [comment]
Would you mind giving `~/.config/sway/config.d/01-keyboard.conf` a try? Our "there is a custom keyboard config?" detection is not very smart right now. We probably should find a nicer way...

**Comment by EmptyLungs** [comment]
> Would you mind giving `~/.config/sway/config.d/01-keyboard.conf` a try? Our "there is a custom keyboard config?" detection is not very smart right now. We probably should find a nicer way...

I have tried to put this configuration to `~/.config/sway/config` and `~/.config/sway/config.d/keyboard.conf`, both with the same result.
But it works with filename you suggested!

**Comment by boredland** [comment]
Well, the idea currently is, that we consume the xdg keyboard settings if we can't find a custom config. That "if" is perhaps to simplistic.

**Comment by andrius** [comment]
Yes, now it works with this suggested filename

**Comment by boredland** [comment]
We probably should at least make this behaviour more transparent in our support.md file.

Other ideas could be to make it more tolerant and consider all .conf files that have sth like "keyboard" in their filename an override.

**Comment by boredland** [comment]
@EmptyLungs or @andrius have you ideas as to 

1. how to make this behavior more transparent?
2. how to make this behavior more tolerant?

**Comment by Galbar** [comment]
I was just affected by this, I guess I didn't restart the computer in a week... Renaming the file to `01-keyboard.conf` worked.

How about doing something like `cat ~/.config/sway/config ~/.config/sway/config.d/* | grep -q xkb_` to detect custom keyboard configurations?

Small feedback: I am kind of annoyed that my config suddenly wasn't working after a reboot. All my configuration files looked right, yet it wasn't working. Maybe next time you could make it only enable once I do the `skel` thing to my config directory? That way I would at least expect some change and I would know how to roll it back if I don't have the time to debug it.

**Comment by boredland** [comment]
yes, thats good feedback. I had it in the "-git" package for weeks and didn't think about what this could mean for others.

**Comment by jagu-sayan** [comment]
It's because this commit https://github.com/manjaro-sway/desktop-settings/commit/c626e5d9107a61466a1f6d342c2ae03e3cc7db1e

If file `~/.config/sway/config.d/01-keyboard.conf` doesn't exist, the script apply the keyboard layout from localectl.

**Comment by andrius** [comment]
Received same error again after the update. Maybe it should be a `~/.config` in this place? https://github.com/manjaro-sway/desktop-settings/commit/85d4307acbf6a373429c08b6a6e5ab3af460443d#diff-05fe51b9391de93a07cc8931164310dcd2481c6870436a3fa5162b4b850a4b18R29

**Comment by andrius** [comment]
Received same error again after the update. Maybe it should be a `~/.config` in this place? https://github.com/manjaro-sway/desktop-settings/commit/85d4307acbf6a373429c08b6a6e5ab3af460443d#diff-05fe51b9391de93a07cc8931164310dcd2481c6870436a3fa5162b4b850a4b18R29

**Comment by boredland** [comment]
you are very right. damn me.

**Comment by boredland** [comment]
you might give the newest version a try

**Comment by boredland** [comment]
@all-contributors please add @andrius and @jagu-sayan and @Galbar and @EmptyLungs for reporting a bug

**Comment by boredland** [comment]
@all-contributors please add @jagu-sayan for reporting a bug

**Comment by boredland** [comment]
@all-contributors please add @Galbar for reporting a bug

**Comment by boredland** [comment]
@all-contributors please add @EmptyLungs for reporting a bug
