### ISSUE TITLE
bindsym broken after update?

### ISSUE THREAD

**Issue by kundex** [manjaro-sway/manjaro-sway#346]
I've put a bindsym in the configuration file _.config/sway/definitions.d/definitions.conf_, that worked well till the last update via pacman:

`bindsym $mod+p exec passmenu -p 'Passwords:' -b -i`

It still works via command line, but not as `$mod+p` any more. Any ideas? Thx!

**Comment by boredland** [comment]
I have no idea what could have changed there. But you can try if `$bindsym` or a combination with `$unbindsym` does the [trick](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-re-declare-shortcuts).

**Comment by hakanyi** [comment]
Commit https://github.com/manjaro-sway/desktop-settings/commit/e42c36e50b92095a325b7d72f5676a6318d67a87 assigned a `swayr` command to `$mod+p`. 
If you want to keep your keybinding, adding `$unbindsym $mod+p` before your `bindsym ...` should do the trick
