### ISSUE TITLE
Install Manjaro-sway-21.3.2-221106-linux515 Alongside Windows 10  boost.python error

### ISSUE THREAD

**Issue by eyes1971** [manjaro-sway/manjaro-sway#347]
[calamares log](https://termbin.com/4yca)
![Jytq](https://user-images.githubusercontent.com/46499928/200984763-c6854f6f-9637-4fe9-9910-00333103b853.png)

![7pH6](https://user-images.githubusercontent.com/46499928/200983717-ca8dedcb-a22f-468f-8cf6-7848e9c5de9b.png)

**Comment by feztix** [comment]
The same problem

**Comment by boredland** [comment]
Sway is not maintaining calamares and I fear I am not of much help there.

Perhaps you could head over to the Manjaro forums for this question?

**Comment by boredland** [comment]
I will trigger a new build in hopes of some upstream fixes that are paying into that. will keep you posted!

**Comment by boredland** [comment]
would you mind giving the [new iso](https://github.com/manjaro-sway/manjaro-sway/releases/tag/202211122038?notification_referrer_id=NT_kwDOAEcl3LI0ODE5MTk0MjQ4OjQ2NjI3NDg) a spin?

**Comment by boredland** [comment]
uncomment `GRUB_DISABLE_OS_PROBER=false` in `/etc/default/grub`.
then run `update-grub`.
