### ISSUE TITLE
manjaro-zsh-config not working

### ISSUE THREAD

**Issue by mioscape** [manjaro-sway/manjaro-sway#348]
I can't run manjaro-zsh-config in terminal, its always return command not found. Is there any fix?

**Comment by boredland** [comment]
I never used this, as I am quite happy with the default. Will have to have a look.

**Comment by boredland** [comment]
one moment. why do you think the command `manjaro-zsh-config` exists? this might be just a documentation issue.

**Comment by mioscape** [comment]
> one moment. why do you think the command `manjaro-zsh-config` exists? this might be just a documentation issue.

I've seen article how to configure this arrow, `manjaro-zsh-config` is used for configure the arrow.

I found command `p10k configure` its the same feature as `manjaro-zsh-config`.
![image](https://user-images.githubusercontent.com/43681888/200997620-4c9d6951-2038-4360-b258-1f714e0c0181.png)

**Comment by boredland** [comment]
In Manjaro sway this is pre- configured

**Comment by boredland** [comment]
closing as this is already enabled (and by the way not an executable afaik)

![image](https://user-images.githubusercontent.com/4662748/201492427-c7611fb8-501a-4315-9cb8-a0bc3d699dd9.png)
