### ISSUE TITLE
waybar sunset plugin doesn't work due to missing freegeoip.app api key

### ISSUE THREAD

**Issue by tve** [manjaro-sway/manjaro-sway#353]
The sunset plugin for waybar doesn't work out of the box 'cause freegeoip.app requires an API key:
```
~> curl -Ls https://freegeoip.app/json/
{
  "message":"No API key found in request"
}⏎                                                                                                  ~> 
```
Would be nice if either something in the docs stated one has to fill-in the lat/long in some config file or how to get an API key...

**Comment by boredland** [comment]
actually there is a [hint about setting a fixed location](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-set-a-fixed-geo-location-for-the-night-light-feature).

about the general problem: it new that you need an account & api key for that.

how do we progress with that? should we bake in an api key? should we remove the feature? should we use another geoip provider?

**Comment by boredland** [comment]
[this](https://ip-api.com/docs/api:json) one provides a similar api. will make the switch.
