### ISSUE TITLE
Pipewire rather than pulseaudio?

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#364]
I am seeing discussions about this all over, and arch itself defaults to pipewire as well now.
But here in the packages I saw that pulseaudio is still the default.
Have you looked into this topic already?

**Comment by boredland** [comment]
Hm, what packages of pulse are remaining?

**Comment by boredland** [comment]
So, the state is and has been: we're all in for pipewire (installed the manjaro-pipewire group). But you're right, pulseaudio-ctl was present and presumably unused.

**Comment by boredland** [comment]
re-opening: due to using pulsemixer in waybar, we still depend on pulse compatibility layers. we could probably get rid of it, if we found a pipewire native replacement for it. I don't know of one.

**Comment by boredland** [comment]
^^ googling this produces mainly hints that one should do exactly what we are doing: install the compatibility layer for pulse or alsa and go with their tooling.
