### ISSUE TITLE
Calamares Crash upon completion

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#365]
It was about to do all the installation, with an encrypted partition and bios-grub partition to a USB.
Suddenly it crashed, and when trying to relaunch it says "Calamares is already running, shutting down".
From the latest stable 202211200332 iso.

**Comment by boredland** [comment]
99% sure this is a duplicate with #366

**Comment by xeruf** [comment]
I got no error message, it just closed silently.
I suspect it was related to LUKS, but I won't test more anytime soon.

**Comment by boredland** [comment]
Well, very hard to actually know then, without a stack trace etc. I am using luks on all my devices, so at least at some point it worked just fine.

**Comment by xeruf** [comment]
One possible idea: I went back and resized the LUKS partition, thinking it would fold the steps down and only create it at the specified size, maybe that's where it got caught up.

**Comment by boredland** [comment]
I think I saw a recent [LUKS issue in the calamares issues](https://github.com/calamares/calamares/issues?q=is%3Aissue+is%3Aopen+luks) a these days, perhaps that helps?

**Comment by boredland** [comment]
Not much to go off here. I there are similar issues, please go to calamares directly, as this might not even be a manjaro topic specifically.
