### ISSUE TITLE
libgtk3-nocsd error messages with fresh install

### ISSUE THREAD

**Issue by jnslmk** [Manjaro-Sway/manjaro-sway#37]
I tried [the minimal testing release 202101161030](https://github.com/Manjaro-Sway/manjaro-sway/releases/download/202101161030/manjaro-sway-20.2.1-testing-minimal-210116-linux59.iso). After a fresh install the terminal displays the error message `ld.so: object '/usr/lib/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded` multiple times.

The reference file `/usr/lib/libgtk3-nocsd.so.0` does not exist. Installing [gtk3-nocsd-git](https://aur.archlinux.org/packages/gtk3-nocsd-git/) fixes the issue for me. It looks like you've removed the package via #27.

I don't know which packages depend on '/usr/lib/libgtk3-nocsd.so.0' and don't know for that reason if there is a better workaround than installing `gtk3-nocsd`.

**Comment by boredland** [comment]
hi @jnslmk ! sadly a super old version of the desktop settings got pulled into the image. please try again with the most recent one!

**Comment by boredland** [comment]
i
