### ISSUE TITLE
Handling Floating Windows

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#370]
For some reason, Emacs always starts floating.
Could it be related to this line in my sway config, and if yes, what's the alternative?

assign [class="Emacs"] workspace 1                                                                                                                                

Either way, even using SUPER+SPACE to toggle focus between tiling and floating windows does not work there for some reason.

And while we are at it, sometimes Right-click menus and Extension popups quickly popup before being covered by firefox itself (the latter more commonly, the former is not happening right now, seems to be primarily when a page is loading slowly), making them quite useless. This issue persist when moving Firefox to floating with Super+Shift+Space.

**Comment by boredland** [comment]
For me the keybind to make things float is super+shift+space, not just super+space.

**Comment by xeruf** [comment]
But the keybind to toggle focus between tiling and floating is C-S-SPC, which is what I was referring to - the other keybind works.

One example for the latter issue is the MasterPassword extension in Firefox: I click on it, the window pops up and immediately vanishes again, presumably covered by Firefox itself. Maybe the focus handling for pop-up windows does not work properly here?

**Comment by boredland** [comment]
Ah, well. Now I get it. I can't really tell why that happens in this particular case, as it works for regular Firefox UI elements. BUT I had the same issue for example with java applications, like [IntelliJ](https://www.reddit.com/r/swaywm/comments/q5uy12/intellij_popups_like_find_in_files_closing_when/) in the past.

**Comment by xeruf** [comment]
And how did you solve it?

The rightclick issue also comes back from time to time...

**Comment by boredland** [comment]
Not using IntelliJ anymore :dancing_men:

**Comment by xeruf** [comment]
I still can't use MasterPassword in the browser, which is quite annoying.

Leaving Intellij is bold, did you stop with Java/Kotlin or find an alternative?
I am still struggling with them as I just can't find an adequate replacement, even though I despise the keybindings not conforming to what I have in my Doom Emacs.

To get back to the original issue, I have this in my config:
```ini
assign [class="Emacs"] workspace 1
assign [app_id="firefox"] workspace 2
```
Let's say I already have a terminal open in workspace 2 and open Firefox.
Unlike what I thought, it does not actually start floating. What happens is that it weirdly coexists in a way that it is not accessible until I close the terminal.

![image](https://user-images.githubusercontent.com/13354331/205165767-6e4bd92e-9ea4-4012-a46c-bc56a13cb381.png)

Here you can see the same thing for Emacs - it opens in workspace 1, but I can't access it via CMD-TAB nor CMD-1

**Comment by boredland** [comment]
I can't test it right now, but this may be related to the renaming of workspaces, sworkstyle performs. Could you try if this changes anything for you?

```
assign [class="Emacs"] workspace number 1
```

**Comment by boredland** [comment]
I think this just works.

**Comment by xeruf** [comment]
Interesting, I had this exact thing in my config the whole time, but now it actually works ^^

**Comment by boredland** [comment]
I can't find anything about 'number' being deprecated in the manpage. Am I blind?

**Comment by xeruf** [comment]
not deprecated, but irrelevant ;)
