### ISSUE TITLE
Adding custom icons

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#371]
I saw neovim has a special config startup statement so it is recognized with an icon.
Can I do the same for emacs, including in tty mode? Is this handled by waybar itself, or part of the mansway config?

**Comment by xeruf** [comment]
I am guessing it is this?
https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-add-my-own-and-override-existing-sworkstyle-icons

But how do I find out the window class/name?

**Comment by boredland** [comment]
You should be able to find the app id using `smaymsg -t get_tree | grep app_id`.

Please report back useful bindings that you found, so we can add them to our default sworkstyle configuration.

**Comment by boredland** [comment]
We should add that hint for get_tee to the readme, that's for sure.
