### ISSUE TITLE
Language/Locale/Timezone settings at startup ignored in installer

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#372]
I thought I had seen this issue already some time ago, but just now I set the timezone to Europe/Berlin at the boot screen yet the installer had the wrong location preselected.

**Comment by xeruf** [comment]
Oh, and can I set the EurKEY layout (`eu`) in the installer? I did not find it anywhere, and it is very useful!

**Comment by boredland** [comment]
I don't even know how the boot-screen passes that to calamares. Anyway: calamares is the central piece we take from upstream manjaro. I am not sure what we can do about it, but if you find anything, I am more then happy to help with it.

**Comment by boredland** [comment]
Regarding EurKey: never tried to find it in calamares, but if it is missing, that could be a great little addition to the calamares [keyboard module](https://github.com/calamares/calamares/tree/calamares/src/modules/keyboard).

**Comment by boredland** [comment]
added a pr to add eurkey to the [grub menu](https://gitlab.manjaro.org/artwork/branding/grub-theme/-/merge_requests/11).

**Comment by boredland** [comment]
Won't add, don't think that is a big issue with a config-first setup like this.
