### ISSUE TITLE
Easily blur screenshots

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#373]
Spectacle has an option to do quick edits after making a screenshots to blur sensitive data.
Any chance for this with the current tool, maybe with a pipeline that pops the screenshot right into a quick editing tool (i.e. not gimp ^^)

**Comment by boredland** [comment]
[swappy](https://github.com/jtheoof/swappy) looks like a good fit, did you try it?

**Comment by boredland** [comment]
Just tried swappy. I think it is exactly what you search for:

![image](https://user-images.githubusercontent.com/4662748/204742660-d7a4081f-bd83-4905-b4d6-1d08d5b7215d.png)

IMO we could completely replace our screenshot mode with it, it would be a great new feature.
