### ISSUE TITLE
Every swaybar popup should be closeable with ESC

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#374]
This works for some, like the volume, bluetooth and wifi, but for CPU temperature and RAM Usage for example I have to resort to more complicated bindings, which is a bit annoying.
Ideally just clicking on another window would also close them, like a real pop-up :)

**Comment by boredland** [comment]
Interesting idea!

**Comment by boredland** [comment]
Thinking more about it. in the spirit of sway and it's settings: shouldn't all windows just close based on the configured keys instead of some internal tools shortcuts?
