### ISSUE TITLE
Broken cp alias?

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#375]
I already have `f` aliased to something and was wondering whether this alias for `cp` in zsh is from your config?
```sh
❯ which cp
cp: aliased to f(){fo=${1:--i}; shift; cp $fo $*};f
❯ cp
zsh: defining function based on alias `f'
zsh: parse error near `()'
```

**Comment by boredland** [comment]
Seems to be an upstream issue: https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/issues/4

**Comment by xeruf** [comment]
Oh what, there is _another_ directory with zsh startup files?
Well, that explains why zsh-vim-mode did not work on any Manjaro machine, it provides a conflicting config... Uninstalling it fixed it...

Makes me wonder though why you create a .zshenv and .zshrc in $HOME which end up additionally conflicting with my dotfiles, if there is already an established space for them?

**Comment by boredland** [comment]
The purpose, iirc, was to provide a zsh setup with the manjaro config + oh my zsh. But well, by now I don't know if thats worth it.

**Comment by tobip** [comment]
Same issue with possible solution in manjaro forum:
https://forum.manjaro.org/t/aliases-with-functions-in-zshrc-not-working/128237/21

**Comment by boredland** [comment]
not sure there currently is sth broken? can sb confirm this is fixed?

![image](https://user-images.githubusercontent.com/4662748/205515052-4a665a9e-cdfc-4647-a385-70dc149d59f7.png)

**Comment by tobip** [comment]
It is not broken per se, but as soon as I define an alias for `f` it will conflict with what happens in `manjaro-zsh-config` and `zsh-syntax-highlighting`.

**Comment by boredland** [comment]
not a manjaro sway issue.

**Comment by xeruf** [comment]
Fix is [committed](https://github.com/Chrysostomus/manjaro-zsh-config/commit/4ab3924476ace65a7067c26cbd733a9d8608dcf4) and [published](https://gitlab.manjaro.org/packages/community/manjaro-zsh-config/-/merge_requests/8) already :)
But I simply uninstalled manjaro-zsh-config for now ^^

**Comment by boredland** [comment]
Thx anyway!

**Comment by xeruf** [comment]
So, I would like to keep the neat suggestions to install a package when a missing command is found in a package, but without the rest of `manjaro-zsh-config`, can I do that?

**Comment by xeruf** [comment]
Because that package breaks zsh vim mode, tab completion in the middle of words and even overrides my HISTFILE location...

**Comment by xeruf** [comment]
oh whoops, I had a `source` statement for the manjaro-zsh-config in my zshrc, wut
