### ISSUE TITLE
oh-my-zsh outdated

### ISSUE THREAD

**Issue by tobip** [manjaro-sway/manjaro-sway#376]
I don't know where else to post this:

The `oh-my-zsh` package in the `manjaro-sway` repository seems to be terribly outdated. It says `Build Date: Mi 07 Jul 2021`.

**Comment by boredland** [comment]
oh, seems to be stuck since forever due to misconfiguration. good find!

@all-contributors please add @tobip for bug

**Comment by tobip** [comment]
> I've put up [a pull request](https://github.com/manjaro-sway/manjaro-sway/pull/377) to add @tobip! tada

yay! :-)
