### ISSUE TITLE
wrong notification if saving screenshot is aborted with ESC in desktop-settings v13.0.0

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#378]
*Steps to reproduce*

1. Toggle screenshot mode by pressing `Print`
2. Press `p`
3. Select an area of the screen
4. Press `Esc` when swappy (?) UI appears

*Expected result*

No screenshot should be saved.

Either no notification should be displayed or the notification should state that the screenshot has **not** been saved.

*Actual result*

Notification says: "screenshot saved in ~/Screenshots/..."

But when opening `~/Screenshots/` the folder is empty.

**Comment by boredland** [comment]
ya, that notification doesn't make sense. it saves only when clicking on the save button. I removed the notification, just didn't do a release yet.
