### ISSUE TITLE
integration of swappy in desktop-settings v13.0.0 breaks keyboard-only workflow

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#379]
*Steps to reproduce*

1. Toggle screenshot mode by pressing `Print`
2. Press `o`

*Expected result*

Screenshot should have been saved

*Actual result"

Some new UI (swappy?) appears, showing a preview of the screenshot and some menu to perform basic editing of the screenshot. That would be ok, but:

- it is not possible to move to or activate any functionality in the UI using `Tab`, for example
- if you press `Ctrl+s` to save the screenshot the screenshot is in fact saved but there is no corresponding notification. However, when you press `Esc` afterwards you receive a notification that the screenshot has been saved. This is confusing. I would expect `Ctrl+s` to save the screenshot, show the notification, and close the UI. If there is no feedback after `Ctrl+s` I assume that nothing has happened. And pressing `Esc` then I would assume that the whole process of creating a screenshot has been aborted. However, there still is a screenshot in `~/Screenshots`, which `Ctrl+s` quietly created.

*Preferred solution*

Allow to select between "Save or Upload screenshot without any intermediate UI" and "Open UI, then save or upload screenshot".

**Comment by boredland** [comment]
swappy has [tons of shortcuts](https://github.com/jtheoof/swappy#keyboard-shortcuts), would they work for you?

**Comment by boredland** [comment]
> notification that the screenshot has been saved

that should be solved in 13.0.1

**Comment by boredland** [comment]
Swappy has an `early_exit=true` config flag. With that I think the behavior is quite comprehensive: it closes once you decide to save to clipboard or file. Do you think with that we still should have a mode where it skips swappy?

**Comment by boredland** [comment]
> And I guess I can restore that behaviour by overriding the definitions

sure, but I would really like to try to get this in a state where it fits most. as I see it, a visual feedback after storing the image would suffice. Apparently swappy just recently removed such notifications for strange reasons. I asked [here](https://github.com/jtheoof/swappy/issues/58#issuecomment-1336166711).

**Comment by boredland** [comment]
would you like to try the newest `manjaro-sway-setting-git`? added notifications there via the workarounds from the thread at swappy.

**Comment by hakanyi** [comment]
`Do you think with that we still should have a mode where it skips swappy?`
Just adding my two cents here -- I think that'd be great. Perhaps we can "activate" swappy via `Ctrl` such that:
`p` picks and copies,
`Ctrl`+`p` picks and sends to swappy, and
`Ctrl`+`Shift`+`p` picks, sends to swappy and uploads the result

**Comment by hakanyi** [comment]
Also, just a note to say that the swappy version that allows `early_exit=true` has not made it to Manjaro stable yet

**Comment by boredland** [comment]
> Personally, I've never used the upload feature.

Same here.

> Is it a good idea then to add this tool as a default to the distro?

Well, I see swappy as a tool that adds more value for people like @xeruf who demanded something along the lines of swappy [here](https://github.com/manjaro-sway/manjaro-sway/issues/373).

There has to be compromise. I think Swappy took a strange decision with removing the notifications, but the workarounds are okay. Do you know another tool like it that works on sway?

**Comment by boredland** [comment]
I would like to close this issue for now, as IMO the current solution works. If sb wants to add a "skip swappy" shortcut to the screenshot mode, I would certainly accept a PR.
