### ISSUE TITLE
Manjaro Sway specific desktop wallpaper

### ISSUE THREAD

**Issue by AndreVallestero** [Manjaro-Sway/manjaro-sway#38]
I've made publicly available Manjaro Sway desktop wallpapers, feel free to use them if you want to:

- https://github.com/AndreVallestero/sway-art
- https://raw.githubusercontent.com/AndreVallestero/sway-art/master/manjaro-sway-small-wallpaper-3840x2160.png
- https://raw.githubusercontent.com/AndreVallestero/sway-art/master/manjaro-sway-small-wallpaper-edged-1920x1080.png

Also feel free to close this issue whenever.

**Comment by boredland** [comment]
uuuh, nice. I'll have a look and package it, okay?

**Comment by boredland** [comment]
In addition to the ones you made, I used your logo in the existing one:
![image](https://user-images.githubusercontent.com/4662748/105576846-e8030180-5d75-11eb-91ca-441a551eb9a0.png)

the whole package is assembled here:
https://github.com/Manjaro-Sway/manjaro-sway-wallpapers

**Comment by AndreVallestero** [comment]
Awesome! Although it might be better if it were color matched to the gruvbox color scheme. I'll see if I can work on it later tonight.

**Comment by boredland** [comment]
@all-contributors please add @AndreVallestero for the design of this wallpaper

**Comment by AndreVallestero** [comment]
> please add @AndreVallestero for the design of this wallpaper

Thanks! It's actually kinda funny how it all came around full circle. I was one of the first people using Manjaro + ARM + Sway back in 2019. I helped Xalius from the Pine64 team setup Sway on his PBP based on my config, and I believe his config was the inspiration of the official Manjaro ARM Sway build, which became the basis for the x86 build.

- https://github.com/AndreVallestero/masars
- https://twitter.com/thepine64/status/1201932519660277762
- https://www.reddit.com/e64elc
