### ISSUE TITLE
Disable pop-up on plugging in USB

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#380]
There is an automount function when I plug in an external medium which includes some kind of popup.
I would like to either disable the popup or the whole automount functionality as I do these kinds of things from the CLI :)

Maybe something to add to the FAQ as well, and I think the FAQ should also be linked from the organization readme: https://github.com/manjaro-sway

**Comment by boredland** [comment]
I guess this is an autostart of the pcmanfm daemon. Those aren't easy to disable yet.

**Comment by xeruf** [comment]
Thanks for the hint, I'll just try uninstalling, Emacs is my file manager ;)

**Comment by boredland** [comment]
please refer [here](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-remove-an-auto-starting-application).

in this case, this should be something like this in a `.config/sway/definitions.d/autostart.conf`:

```
set $mounting_daemon ""
```

**Comment by xeruf** [comment]
Related to https://github.com/manjaro-sway/manjaro-sway/issues/358
