### ISSUE TITLE
Clarify sleep icon

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#381]
There is a "zzz" in the swaybar, which says "deactivated" on hover and "activated" once clicked.
I am guessing that I can disable automatic sleep with it, but it would be good to clarify.

**Comment by boredland** [comment]
It's not about sleeping, but the tools that sets idle (screen light, lock screen).

**Comment by xeruf** [comment]
oh, so it is a "screen always on" function? Well I rarely care about that, I'd much prefer the option to enable and disable auto-sleep, as screen lock won't disturb any running processes either way.
