### ISSUE TITLE
Notification spamming by mako upon login (after latest stable update)

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#382]
Seeing this upon login. `mako` is using around 18% CPU.
Might be due to [this](https://github.com/manjaro-sway/desktop-settings/blob/9d5e9f402abb11b1ddd9753d5bce848a8a71e904/community/sway/etc/sway/definitions#L142) line.
![swappy-20221206_190833](https://user-images.githubusercontent.com/33870649/206053828-94091cbe-380a-4fb0-bd3e-3491d6f5b1b5.png)
Can someone confirm?

**Comment by syroezhkin** [comment]
Got the same issue. Just commented the [ line 171](https://github.com/manjaro-sway/desktop-settings/blob/63d63515c9a323b6113d9555d01c8810f07e1ea9/community/sway/etc/sway/modes/default#L171) in `/etc/sway/modes/default`.

**Comment by boredland** [comment]
sorry for the disruption, I wasn't aware inotify would be doing that, if the dir doesn't exist.

**Comment by boredland** [comment]
fix should be in 13.2.1, please tell me if this is gone!

**Comment by syroezhkin** [comment]
Looks like the last release fixed it for me. 

It's just not clear why the script checks the `~/Screenshots` directory, since I don't have it. And swappy on my machine saves images directly to the home directory.

**Comment by boredland** [comment]
Well, then the swappy config is missing. You can bootstrap the current skel using the `skel` command.

**Comment by syroezhkin** [comment]
Done. Everything works fine! Thank you!

**Comment by hakanyi** [comment]
Thanks! 
Turns out, I didn't even have `inotify-tools` installed..

**Comment by boredland** [comment]
But it should have added those to the dependencies of Manjaro sway settings this morning. Hope it is there now?
