### ISSUE TITLE
Escape key not working anymore

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#383]
Introduced in https://github.com/manjaro-sway/desktop-settings/pull/139
Had to temporarily unbind that key

**Comment by mwaltersva** [comment]
I'm also seeing this. Fixed when I reverted back to 12.1.3-21

**Comment by syroezhkin** [comment]
Got the same issue. Just commented the [ line 171](https://github.com/manjaro-sway/desktop-settings/blob/63d63515c9a323b6113d9555d01c8810f07e1ea9/community/sway/etc/sway/modes/default#L171) in `/etc/sway/modes/default`.

**Comment by boredland** [comment]
Ah, so setting that snitches the Escape key for all windows? Damn.

**Comment by boredland** [comment]
Sorry for the disruption! for future reference `--release` makes a bindsym not steal the key globally. Perhaps we have that problem unknowingly in other places.

**Comment by boredland** [comment]
I am not even sure the hack with `--release` is the right way to do this, as afaik is just makes the bindsym more specific (to the key release event, not the whole event).

**Comment by boredland** [comment]
fix should be in 13.2.1, please tell me if this is gone!
