### ISSUE TITLE
Saving screenshots triggers "copied to clipboard" notification

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#384]
Saving a screenshot (`Ctrl+s` in `swappy`) triggers the "Saved .." notification, but also an erroneous "copied to clipboard" notification for me:
![swappy-20221207_110308](https://user-images.githubusercontent.com/33870649/206229347-42730def-e6de-40f2-91a6-296f1ae6056f.png)

The new `swappy` pipeline is a welcome addition otherwise!

**Comment by boredland** [comment]
that is so confusing. It doesn't show the clipboard notification for me.

**Comment by hakanyi** [comment]
I'm not sure what happened in the meantime, but it's gone now -- sorry for the noise! 
`are you completely sure you didn't additionally copy it to the clipboard?` yes :)

**Comment by boredland** [comment]
Nice!
