### ISSUE TITLE
Yellowish tint screen

### ISSUE THREAD

**Issue by cavielles** [manjaro-sway/manjaro-sway#387]
My monitor shows a yellowish screen only in the sway(21.3.2 kernel 5.15) version, neither in mate nor i3wm nor xfce (all community versions) 
I have just try a clean install with unstable 6.0 kernel but the same issue
I have an Lenovo yoga 510 14ikb it has an Intel HD 620 graphics and I have never had anything like it. I have connected a TV via hdmi and it's just as yellowish.
As far as i know the only important difference with the other manjaro versions is that sway uses wayland, but i don't find any similar problem in wayland only with x11..

Any help or ideas will be appreciated! Maybe some xrandr command can help me but I'm not very fluent. I've always used managers for it and I'd like to learn
Thanks in advance

**Comment by boredland** [comment]
That's the night mode, wlsunset. You can disable it using the little light bulb our using the several ways outlined in support.md
