### ISSUE TITLE
skel updates of the manjaro-settings package override .zshrc and .profile

### ISSUE THREAD

**Issue by gregorbg** [manjaro-sway/manjaro-sway#388]
Hey! I hope this is the right place for support questions, I've tried searching `skel` and `zshrc` on closed issues to no avail.

Whenever there's a new version of the `manjaro-sway-settings` package, it asks to apply the update by invoking `skel`. I understand why this invocation is necessary, but it has the unpleasant side effect of overriding `.zshrc` and `.profile` every single time.

This affects stuff like environment variables (I want to set my own `EDITOR` and use `fcitx5` which requires certain env variables to be set in `.profile`) as well as custom `alias`es and the list of `oh-my-zsh` plugins. Is there a recommended / official way how to configure my shell and profile without having to re-type everything every single time a settings package update is released?

**Comment by gregorbg** [comment]
Nevermind, just found [the wiki](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-customize-sway-without-losing-my-customizations-after-an-upgrade). Sorry :sweat:

**Comment by boredland** [comment]
I don't think we have a section on zsh configuration, would you like to write a line or two so other perhaps will have a headstart?

**Comment by gregorbg** [comment]
Turns out I don't know how :sweat_smile: I tried to create some config files based on what's already in the Support file, but I don't know where to put them so zsh will pick them up.

Is there a recommended way or a convention for this?

**Comment by boredland** [comment]
Perhaps. Will take a look. Just realized the way I use it isn't working either :-)

**Comment by boredland** [comment]
let me know if [this](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-extend-the-zsh-configuration) does the trick for you. for me it did.

**Comment by gregorbg** [comment]
Cool, thanks! This does work for `zsh` indeed :smile: 
However, there's another use-case where I have to write values to `.profile` to use `fcitx5` for Japanese (aka `mozc`) input. These still get overwritten on each `skel` update. Is there another `.config` subdirectory that I'm missing?

**Comment by boredland** [comment]
Not yet, but we could make that a feature.

**Comment by boredland** [comment]
Wdyt we source `~/.config/profile.d/*` in .profile?

**Comment by boredland** [comment]
@all-contributors please add @gregorbg for having an idea

**Comment by gregorbg** [comment]
I somehow managed to overlook the initial reply to this PR. Now I got reminded because of the `@` mentions.
Thank you so much for implementing this, it works like a charm now :smiley:
