### ISSUE TITLE
Disable update notifications

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#391]
How can I disable the notification about package updates being available?
Didn't find anything corresponding in /etc/sway/definitions

**Comment by ishaanbhimwal** [comment]
disable "check for updates" in pamac-gui preferences

**Comment by boredland** [comment]
Okay, after some tinkering I would do the following:

1. disable the pamac-tray autostart
2. disable the pacmac-daemon

Not having gave me a well enough experience. I'll only be able to disable pamac-daemon for newly built images, so you'll have to run 
`systemctl disable --now pamac-daemon.service` on your own.

**Comment by boredland** [comment]
let me know/reopen if this isn't fixed and if we'd have to stop the pamac-daemon.

**Comment by xeruf** [comment]
Since I use yay anyways, I guess I can just remove pamac alltogether or at least pamac-gtk ^^

**Comment by boredland** [comment]
I guess so, but I was arguing for a sane default.

**Comment by xeruf** [comment]
Ideally there would just be a button on the dialogue like "Never ask again"
Or the dialogue only pops up when there hasn't been an update in like 2 weeks.

**Comment by boredland** [comment]
> I think it is not a bad idea to have this running by default though

We have the red "update" indicator in the waybar. IMO that is enough communication about that topic.
