### ISSUE TITLE
Add blur shadow for key help

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#394]
![image](https://user-images.githubusercontent.com/13354331/208269056-7c47d2ac-1702-471d-9b03-ee2d95b528b1.png)

Unfortunately, my background is rather bright at this position, maybe we can add a black blur to highlight the text?

By the by, do you know of a good way to set the system brightness depending on light sensors/camera or time of day at startup?

**Comment by ishaanbhimwal** [comment]
- try setting a more in dark font color for the text in conky's setting
- check out https://github.com/FedeDP/Clightd

**Comment by boredland** [comment]
It isn't conky, but [nwg-wrapper](https://github.com/nwg-piotr/nwg-wrapper). The default css resides [here](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/skel/.config/nwg-wrapper/style.css).
