### ISSUE TITLE
Bluetooth Swaybar item unintuitive

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#395]
Oftentimes it just closes when I select something by pressing enter, it seems shift-enter helps with that.
Still I was not able to pair my Logitech MX Ergo, which I was able to pair in seconds using `bluetuith`

**Comment by boredland** [comment]
Never heard of that tool. If it is better, I would be happy to get rid of rofi-bluetooth. For me it works, but pairing does seldomly work on the first try.

**Comment by xeruf** [comment]
Just discovered it, and it seems to work very well :)

**Comment by boredland** [comment]
Added `bluetuith` to our repos and will test it a few days.

**Comment by boredland** [comment]
Enabled bluetuith by default and remove rofi-bluetooth.

**Comment by boredland** [comment]
@all-contributors please add @xeruf for having a great idea
