### ISSUE TITLE
download link in https://manjaro-sway.download/ not working

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#396]
![image](https://user-images.githubusercontent.com/79986754/208707159-4a526e0d-b715-426f-99e9-939ad6eb771f.png)

* https://forum.manjaro.org/t/i-cant-download-manjaro-sway/129499
* https://forum.manjaro.org/t/sway-download-links-not-working/129603

**Comment by boredland** [comment]
Hm, yes, please then use the multipart download. From the [log](https://github.com/manjaro-sway/manjaro-sway/actions/runs/3723068859/jobs/6314350541#step:4:719), upload seems to have worked just fine.

**Comment by boredland** [comment]
@all-contributors please add @ishaanbhimwal for reporting a problem

**Comment by boredland** [comment]
https://github.com/all-contributors please add @ishaanbhimwal for reporting a bug

**Comment by boredland** [comment]
@all-contributors please add @ishaanbhimwal for reporting a bug
