### ISSUE TITLE
Make floating windows sticky 

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#398]
https://github.com/swaywm/sway/issues/2742
With `sticky toggle` one can make windows visible on all workspaces.
I think it might be sensible to enable this by default for floating windows, so that tools like `dragon-drop` (which I am also proposing to install by default, awesome for bridging terminal to GUI) and the screenshot tool are accessible across workspaces.
But I don't know how :c

**Comment by boredland** [comment]
To enable this for specific applications, refer [here](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/sway/config.d/98-application-defaults.conf#L17) for an example.

**Comment by boredland** [comment]
I assume this worked for you? Would you like to contribute contribute [additional](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/sway/config.d/98-application-defaults.conf) defaults?

**Comment by boredland** [comment]
feel free to reopen if you have suggestions.
