### ISSUE TITLE
Waybar / App Icons in Window Switcher

### ISSUE THREAD

**Issue by skunkfox** [manjaro-sway/manjaro-sway#399]
Hi, this isn't a bug per say but I was hoping you could help me out.

At some point in a previous version of Manjaro: Sway Edition there was a neat feature where in the window switcher at the top right, icons would be displayed (as unicode I believe) for whatever applications you currently had opened in that virtual desktop. There were icons for VSCode, Firefox, terminal. It was all pretty cool.

That feature got removed in a later revision of Manjaro: Sway Edition. But now that I'm on Arch Linux and configuring Sway from scratch, I wanted to bring that back. Unfortunately I haven't been able to figure out how that was done with Google. I was hoping someone could point me in the right direction. I figured it would be an option in waybar or something but apparently not.

**Comment by boredland** [comment]
The tool is called [swayest workstyle](https://github.com/Lyr-7D1h/swayest_workstyle)

**Comment by skunkfox** [comment]
You are the best!
