### ISSUE TITLE
Cursor appears in the screenshots

### ISSUE THREAD

**Issue by AdriandMartin** [manjaro-sway/manjaro-sway#400]
Since 12th December the cursor appears in my screenshots:
![imagen](https://user-images.githubusercontent.com/22200464/209941165-108e9bab-e2de-4daf-add2-4919d1df470a.png)

I'm completely sure that it didn't happen before, because I've been taking a lot of screenshots for a presentation. It doesn't seem to be a problem related to `swappy`, because the cursor also appears when just using the `grimshot` script

**Comment by boredland** [comment]
Iirc grimshot has a `--cursor` flag if one wants to explicitly enable those. Seems very strange that they suddenly occurred.

**Comment by boredland** [comment]
emersion [calls](https://todo.sr.ht/~emersion/grim/82) this a bug in wlroots.

**Comment by AdriandMartin** [comment]
I see, let's wait for emersion's response to your last comment

**Comment by boredland** [comment]
seems to have vanished in the new wlroots:
![image](https://user-images.githubusercontent.com/4662748/211141689-525f519f-1b17-49a7-8e22-077e5b3abedf.png)

**Comment by boredland** [comment]
damn, when creating a screenshot for a whole output, the cursors is still there:

![image](https://user-images.githubusercontent.com/4662748/212540982-43543d34-527b-4acd-9112-71813dba18f7.png)

**Comment by sefodopo** [comment]
I had the same issue, I just commented out a line in .profile and now the cursor is hiding correctly from the screenshots. I'll have to wait and see if this causes any other issues especially with virtualization.
```
# Disable hardware cursors. This might fix issues with
# disappearing cursors
# export WLR_NO_HARDWARE_CURSORS=1
```
This line was added in commit [3d19cd2](https://github.com/manjaro-sway/desktop-settings/commit/3d19cd2a7eaf67776d54e32fed66c47a0447ad2a) on the desktop settings repository.

**Comment by boredland** [comment]
will comment this out in the upcoming settings release.
