### ISSUE TITLE
Pop-ups sometimes hide behind their parent

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#402]
Follow-up to https://github.com/manjaro-sway/manjaro-sway/issues/370

For example in Firefox, the dict.cc and MasterPassword extensions are unusable as their pop-ups move behind the browser window right after opening.

**Comment by boredland** [comment]
I think this can only be solved on an application level. Searching through the mozilla issues, there are several ones related to this.

**Comment by boredland** [comment]
For me this just works :tm::

[recording_20230102-204934.webm](https://user-images.githubusercontent.com/4662748/210273418-2ff5561f-39c0-450e-bc6f-c8e3e64b70df.webm)

Disclaimer: Running sway 1.8 rn.

**Comment by xeruf** [comment]
It always works for me on non-sway setups. dict.cc extension works again, mpw never worked

**Comment by boredland** [comment]
Can you give me a link to the masterpassword extension you have been using? for [this](https://addons.mozilla.org/en-US/firefox/addon/masterpassword-firefox/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) one nothing hides. ffel free to reopen!

**Comment by xeruf** [comment]
yep, I am using that one, it keeps positioning behind firefox. Maybe related to my sway config?

    assign [app_id="firefox"] workspace 2

No permission to reopen ;)

**Comment by boredland** [comment]
> No permission to reopen ;)

sorry, overread that one.

**Comment by xeruf** [comment]
by the by, maybe you can give me triage permission on the repo so I can support actively :)

**Comment by boredland** [comment]
don't see how this fails. for me this just works:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/6346d6fd-9d86-47bb-ad55-b7dc75c4720b)

**Comment by xeruf** [comment]
works fine now, but with above line disabled

**Comment by boredland** [comment]
Nice!

**Comment by boredland** [comment]
I could imagine that `assign [app_id="firefox"] workspace 2` somehow "moves" the window to the workspace and thereby positions the additional window moves behind it. Perhaps also focus the window? does something like `assign [app_id="firefox"] workspace 2, focus`
