### ISSUE TITLE
incorrect positioning of the mouse in the terminal during selection

### ISSUE THREAD

**Issue by masteor** [Manjaro-Sway/manjaro-sway#41]
when I trying to select some text in the terminal (termit, kitty,...) - the mouse does not fall on the selected text, but selects the text a little higher than the one I need

**Comment by simon-bueler** [comment]
Are you running natively or in a virtual machine?

**Comment by boredland** [comment]
closed dueto no reaction and a likely interpretation.

**Comment by masteor** [comment]
> Are you running natively or in a virtual machine?

i ran this on kvm qemu virtual machine

**Comment by masteor** [comment]
> closed dueto no reaction and a likely interpretation.

sorry for the long answer - I had to delete Manjaro Sway since difficulties turned out to be more than desire and time to eliminate them
