### ISSUE TITLE
`source $HOME/.config/profile.d/*` does not work if there are multiple files in `profle.d`

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#410]
I think `source` does not work with a wildcard `*` if there are multiple files in `$HOME/.config/profile.d/`.

And I think I will have to add at least one other file if I want to extend `$HOME/.profile`. I cannot use `$HOME/.config/profile.d/example` for that because that will be overwritten again by `skel` with the next release of manjaro-settings, right?

*Steps to reproduce*

1. create file `$HOME/.config/profile.d/test`
2. add `export FOO=BAR` to the file
3. logout and login again
4. run `env | grep FOO`

*Result*

environment variable `FOO=BAR` does not exist

*Expected result*

environment variable `FOO=BAR` should exist

*Proposed solution*

```
for f in $HOME/.config/profile.d/*; do
  source $f
done
```

**Comment by boredland** [comment]
fixed in 14.0.1, thanks for the report!

**Comment by boredland** [comment]
@all-contributors please add @heapifyman for reporting a bug
