### ISSUE TITLE
Problem with zeit.db on different shells

### ISSUE THREAD

**Issue by theRoboxx** [manjaro-sway/manjaro-sway#413]
I get the error `open ~/.config/zeit.db: no such file or directory` when I try to execute `zeit` or hover over the icon on the waybar. 
Do I need to create the zeit.db by myself or am I missing something else?

**Comment by boredland** [comment]
I think so. Just `touch ~/.config/zeit.db` should do.

**Comment by boredland** [comment]
feel free to reopen

**Comment by theRoboxx** [comment]
I already tried that and also reinstalled the zeit package but unfortunately it doesn't solve the problem.
Are there any logs that I could use to debug the error?

**Comment by boredland** [comment]
I guess that best place would be [their repo](https://github.com/mrusme/zeit), but I am a bit hesitant: on my machine the zeit command just works, no matter if that file exists or not (it creates it). What does running `zeit track --project project --task task --begin -0:15` give you?

**Comment by theRoboxx** [comment]
I should mention that I don't use zsh but [clifm](https://github.com/leo-arch/clifm) as my shell. 
Bash and fish show the same error as clifm.
On zsh the `zeit` command works as expected. 
Is there some specific zsh-config for the zeit command?

**Comment by boredland** [comment]
not really, I think. The file path is [set](https://github.com/manjaro-sway/desktop-settings/blob/8a548b7881237363807c5d008e10c6c5f47f31fc/community/sway/etc/skel/.profile#L24-L25) in profile.

**Comment by theRoboxx** [comment]
Strange, I will take a closer look and update the issue if I find something.

So thanks for your help, I really like this project. :+1:
