### ISSUE TITLE
Problem logging in after update

### ISSUE THREAD

**Issue by dinkocar** [manjaro-sway/manjaro-sway#414]
After update today I can no longer login to GUI. I can still login to terminal and start sway manually, but when I login in tuigreeter, it always just starts tuigreeter again. Here is log from greetd service

sij 08 18:32:47 rade-tuxedoaura15gen1 systemd[1]: Started Greeter daemon.
sij 08 18:32:53 rade-tuxedoaura15gen1 greetd[1205]: pam_systemd_home(greetd:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
sij 08 18:32:53 rade-tuxedoaura15gen1 greetd[1205]: pam_unix(greetd:session): session opened for user greeter(uid=968) by (uid=0)
sij 08 18:32:53 rade-tuxedoaura15gen1 greetd[1231]: pam_systemd_home(greetd:auth): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
sij 08 18:33:00 rade-tuxedoaura15gen1 greetd[1231]: pam_unix(greetd:session): session opened for user rade(uid=1000) by (uid=0)
sij 08 18:33:01 rade-tuxedoaura15gen1 greetd[1231]: pam_unix(greetd:session): session closed for user rade
sij 08 18:33:02 rade-tuxedoaura15gen1 greetd[1314]: pam_systemd_home(greetd:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
sij 08 18:33:02 rade-tuxedoaura15gen1 greetd[1314]: pam_unix(greetd:session): session opened for user greeter(uid=968) by (uid=0)
sij 08 18:33:02 rade-tuxedoaura15gen1 greetd[1331]: pam_systemd_home(greetd:auth): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.

I have no idea how to start debugging this as there is no information why session is closed the moment it is opened.

**Comment by boredland** [comment]
hi there! 

1. which branch are you on? (in case you don't know: `pacman-mirrors --get-branch`)
2. can you recall what updated?

**Comment by boredland** [comment]
Overall this problem is not a lot to go with, would not know how to help here based on the information given.

**Comment by dinkocar** [comment]
I am on stable branch. I don't know what updates. There were just a few, I did it today. I know I run "skel" after the update, so the package that says to run skel was updated.

**Comment by dinkocar** [comment]
I don't think it tries to start sway. To me it looks like the problem is somewhere in greetd or tuigreeter, but I don't know how to check that.

**Comment by dinkocar** [comment]
When I try to start sway manually it starts with no problems, so this is why I have excluded sway as possible problem.

**Comment by boredland** [comment]
understood. there has been a greetd [update](https://git.sr.ht/~kennylevinsen/greetd/refs/0.9.0) recently, but for me this didn't cause any issues.

**Comment by boredland** [comment]
you could check `/var/log/pacman.log` for what recently got updated.

**Comment by boredland** [comment]
another idea: are you using nvidia drivers? if so, are you using proprietary drivers? if so: did you set that in tuigreet?

**Comment by dinkocar** [comment]
I don't have anything in profile.d. greetd and manjaro-sway-settings did get updated during todays update. I have checked it in pacman.log. I will try to downgrade, and see if it helps. Do I need some special switch to make sure no files are left from newer version?

**Comment by boredland** [comment]
> I don't have anything in profile.d. greetd and manjaro-sway-settings did get updated during todays update. I have checked it in pacman.log. I will try to downgrade, and see if it helps. Do I need some special switch to make sure no files are left from newer version?

I've got an idea! Give me a minute.

**Comment by dinkocar** [comment]
After downgrading greetd and manjaro-sway-settings it works again. So the problem is somewhere there.

**Comment by boredland** [comment]
To proof my theory: could you create an empty file in .config/profile.d/ ? I am guessing [yesterdays fix](https://github.com/manjaro-sway/manjaro-sway/issues/410) created a race condition.

**Comment by dinkocar** [comment]
Yes, it works with empty file.

**Comment by boredland** [comment]
Nice, I pushed a fix (that would require an update of the skel tho)

**Comment by boredland** [comment]
@all-contributors please add @dinkocar for reporting a bug
