### ISSUE TITLE
webseed of the torrent is causing memory leak in transmission-daemon

### ISSUE THREAD

**Issue by 2L3R4** [manjaro-sway/manjaro-sway#419]
when adding the torrent file from https://mirror.manjaro-sway.download/manjaro-sway/manjaro-sway.torrent after a few minutes transmission-daemon gets killed by OOM killer due to the system running out of RAM. 

I assume that that is caused by the web seed (as there are no other peers than me) 

I also raised a [issue on the transmission repo](https://github.com/transmission/transmission/issues/4595) in case it is a issue with my torrent client

**Comment by boredland** [comment]
Oh, wow. I wouldn't know how we could have an impact, as the mktorrent command [looks](https://github.com/manjaro-sway/manjaro-sway/blob/main/.github/workflows/mirror.yaml#L49) very basic.

**Comment by 2L3R4** [comment]
it downloads ~50MB from the webseed and then (allegedly) downloads for a few minutes at ~90MB/s (if internet is fast enough and no speed limit is set) while the progress bar doesn't move any further.

It then gets killed once the 1G of RAM gets full by transmission-daemon allocating memory at download speed

(it has only been the last 2 releases where the webseed even worked in some way, before then I downloaded the files from the github release page into the transmission downloads directory and then seeded for everyone else who would have wanted to download it via torrent)

**Comment by boredland** [comment]
> it has only been the last 2 releases where the webseed even worked

that is true, I just recently fixed the path for the webseed. sad this didn't work out so far. thanks for looking into it tho!

**Comment by boredland** [comment]
in qbittorrent for me it looks less like a memory leak, but after some seconds it is absurdly slow.

![image](https://user-images.githubusercontent.com/4662748/212537156-a49d3b19-1ace-4243-a7f6-ba8958c53c25.png)

in transmission, I can see the issue you describe. It starts with a high 9-11Mb/s but never progresses after having downloaded the small files. The .iso files remain at 0% while the download indicator stagnates around 10Mb/s

![image](https://user-images.githubusercontent.com/4662748/212537502-fba5ee3f-f7d1-4f8a-a048-d40398b2a2a7.png)

**Comment by boredland** [comment]
@all-contributors please add @2L3R4 for reporting a bug

**Comment by boredland** [comment]
I wonder if there is something about the file somehow "changing" between the local filesystem and after it is being uploaded to s3. For regular downloads I get top speed anyhow:

![image](https://user-images.githubusercontent.com/4662748/212544579-09f070f5-57d4-46ab-811d-d1ba71b458f5.png)

**Comment by boredland** [comment]
one more note: until this is clarifies, we could just decide to disable the torrent file link. I am serving the files via cloudflare r2 and will thus have [no](https://blog.cloudflare.com/introducing-r2-object-storage/) egress fees anyway. I always liked the idea of having a torrent option tho.

**Comment by boredland** [comment]
we dropped the whole torrent feature for now.
