### ISSUE TITLE
Issue after update:  [ARM Stable Update] 2021-02-26

### ISSUE THREAD

**Issue by fantomx69** [Manjaro-Sway/manjaro-sway#42]
When I open the terminal I get this error: 

thread 'main' panicked at 'unknown shell: "/bin/bash". Supported shells: bash, ion, powershell', src/main.rs:69:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

During updates, the following error occurred: "The print function does not exist. Choose between rprint or lprint".

Thanks for help.

**Comment by boredland** [comment]
I think this refers to the ARM edition - this is about the x86 one that is completely independent from it.
