### ISSUE TITLE
Add adaptive brightness functionality

### ISSUE THREAD

**Issue by boredland** [manjaro-sway/manjaro-sway#429]
[wluma](https://github.com/maximbaz/wluma) could be a great candidate for an easy to install and setup adaptive brightness solution, we could support it by including a waybar module and a default configuration for it.

1. allow to provide a default config, preferably not inside userspace (needs to be implemented upstream, https://github.com/maximbaz/wluma/pull/45). The minimal default configuration should use video0 (which should work on most notebooks and computers with a webpack) as a sensor and mostly stick to the example config otherwise.
2. provide waybar module on top of a little script:

- show only if wluma is installed
- read status from systemd unit
- click: toggle active status of systemd unit

3. Add wluma to the optional dependencies of our settings package
4. Add a hint to our support.md about how installing and configuring it

**Comment by cyrinux** [comment]
Hi @boredland, I did the PR to be able to support xdg dirs. For config and data. I hope this will help your integration in manjaro.
You can also find some inspiration @maximbaz and myself use in waybar, https://github.com/maximbaz/dotfiles/blob/master/.config/waybar/config#L119 and https://github.com/maximbaz/dotfiles/blob/master/.local/bin/waybar-movie

**Comment by maximbaz** [comment]
I've just cut the 4.2.0 release of wluma with the requested functionality - enjoy 🥳

**Comment by boredland** [comment]
thanks for the hints @maximbaz! for the waybar modules I did to not too different paths:

https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/usr/share/sway/scripts/wluma.sh#L1-L27

https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/usr/share/sway/templates/waybar/config.jsonc#L329-L342
