### ISSUE TITLE
Releases are absurd

### ISSUE THREAD

**Issue by mrusme** [Manjaro-Sway/manjaro-sway#43]
I initially subscribed to this repo's releases because I wanted to follow the process. However, since I was receiving so many notifications on GitHub I decided to check the details and, well, frankly speaking this is absurd:

<img width="917" alt="Screen Shot 2021-03-02 at 5 46 07 PM" src="https://user-images.githubusercontent.com/151967/109719674-6164ef80-7b7f-11eb-9acd-4115d71c9506.png">

All but the first two releases seem to only contain an updated downloads count in the documentation. I'd suggest to change the way your release procedure works and only release when there were release-worthy improvements made. Otherwise people (like myself) might lose interest in this very quickly.

**Comment by philmmanjaro** [comment]
@mrusme the releases are regular daily builds. The complete repository has only purpose to provide you with automatically built ISOs based on the [profiles](https://github.com/manjaro-sway/iso-profiles/tree/sway/community/sway) and [settings](https://github.com/manjaro-sway/desktop-settings/tree/sway/community/sway). See this repo more as an automatic quality check if the profiles are fine.

**Comment by boredland** [comment]
the release action defaults to the last commit as the release message. those are daily automated builds, as phil already explained.
