### ISSUE TITLE
weird weather icon display

### ISSUE THREAD

**Issue by boredland** [manjaro-sway/manjaro-sway#436]
![image](https://user-images.githubusercontent.com/4662748/213662692-c6414964-2f84-461b-b4e4-a403f552f2ce.png)

Should be `-3°C` and a light snow icon. May be an issue with the font and the weather script.

**Comment by AdriandMartin** [comment]
It seems to be written backwards, because in my case it appears as `weather-icon 1°C`

**Comment by boredland** [comment]
> It seems to be written backwards, because in my case it appears as `weather-icon 1°C`

As it should be. Really a little mystery I did not yet have the time to look into.

**Comment by boredland** [comment]
@AdriandMartin are you on manjaro-sway-settings or manjaro-sway-settings-git?

**Comment by AdriandMartin** [comment]
I'm in manjaro-sway-settings, the stable version

**Comment by AdriandMartin** [comment]
I could switch to the git version, is there something I had to take into consideration? Uninstalling another package or something similar

**Comment by boredland** [comment]
no, should just work. on the -git package I switched to the new `community/ttf-roboto-mono-nerd` instead of `manjaro-sway/nerd-fonts-roboto-mono`.

**Comment by AdriandMartin** [comment]
I've switched to the git version (and rebooted my laptop after), but it still works. Could it be a problem related to displaying subzero temperatures?
![imagen](https://user-images.githubusercontent.com/22200464/213925040-cfc28522-0925-41e3-9f2f-b46d767ee540.png)

**Comment by AdriandMartin** [comment]
Update: in my case it also works with subzero temperatures
![imagen](https://user-images.githubusercontent.com/22200464/213983069-53794e71-b772-4f2d-9b13-8ca78981a406.png)

**Comment by boredland** [comment]
for currently too. wth is going on...

![image](https://user-images.githubusercontent.com/4662748/213993962-0cb23f2f-a78a-4eaf-9eea-745666c7b91c.png)

**Comment by AdriandMartin** [comment]
It is really strange. I think the best is to keep the issue open for some time so that other users who could have the same problem can report it

**Comment by tofi1130** [comment]
same here 
![swappy-20230321_155358](https://user-images.githubusercontent.com/109919009/226585818-9a8ab646-2e6c-4c3b-97f2-28c3cb194182.png)

**Comment by boredland** [comment]
never happened to me again. perhaps got fixed upstream with wttrin?
