### ISSUE TITLE
Defaulting for V4L2 on x64 is a weird choice

### ISSUE THREAD

**Issue by xfalcox** [Manjaro-Sway/manjaro-sway#44]
https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/etc/skel/.profile#L7

I assume the above comes from Sway ARM edition, but it's a bad default.

Maybe we can try to auto-detect AMD/Intel/Nvidia and set the proper value?

https://wiki.archlinux.org/index.php/Hardware_video_acceleration#Configuring_VA-API

**Comment by boredland** [comment]
I guess we could instead just remove it without consequences - afaik that is merely an override for some devices.

**Comment by boredland** [comment]
removed as of manjaro-sway/manjaro-sway-settings@4.3.2

**Comment by xfalcox** [comment]
> removed as of manjaro-sway/manjaro-sway-settings@4.3.2

How do I update to that?

**Comment by boredland** [comment]
> > removed as of manjaro-sway/manjaro-sway-settings@4.3.2
> 
> How do I update to that?

`pacman -S manjaro-sway/manjaro-sway-settings` could work
