### ISSUE TITLE
Creating rofi config on the fly overrides custom config

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#440]
We might want to split the rofi config over [multiple files](https://davatorium.github.io/rofi/CONFIG/)

**Comment by boredland** [comment]
feel free to outline that plan a bit more, I am all ears.

**Comment by boredland** [comment]
we could make it very easy: just create the new file, if it doesn't exist already. Which would render updates impossible.

**Comment by boredland** [comment]
how about:

1. we dynamically update `~/.config/rofi/Manjaro.rasi`
2. we create a `~/.config/rofi/` if not exists:
```css
@theme "Manjaro"
```

This way, users would gain full opt-out capabilities, while we can keep updating Manjaro.rasi. Wdyt?

**Comment by boredland** [comment]
Well, seems to work just fine. I have no idea how to migrate users to it tho, as most of them will have a `.config/rofi/config.rasi` present, so it wont be overwritten. On the other hand, thats probably not too bad. If people ask, I'll add it to support.md
