### ISSUE TITLE
manjaro-sway.db failed to download

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#441]
`sudo pacman -Syyu` returns:

```
failed retrieving file 'manjaro-sway.db' from packages.manjaro-sway.download : The requested URL returned error: 404
```

**Comment by boredland** [comment]
I am on it. Currently I try to restructure our mirror so, that we can can provide manjaro-branch specific packages. All will be back soon, hopefully.

**Comment by superioq26** [comment]
No news?

**Comment by LucaBrockschmidt** [comment]
Apparently, something like this already happened 3 weeks ago: https://github.com/manjaro-sway/manjaro-sway/issues/408#issue-1522455937

Could you please explain, what's the issue here? Is there no testing environment? Do you expect this to happen regularly?

**Comment by boredland** [comment]
> Apparently, something like this already happened 3 weeks ago: https://github.com/manjaro-sway/manjaro-sway/issues/408#issue-1522455937
> 
> Could you please explain, what's the issue here? Is there no testing environment? Do you expect this to happen regularly?

You're free not to use it. I was about to create a testing environment and things did not go as planned, then I had to work at my paid job. Things like that happen. Feel free to march off to a distribution with premium support.

**Comment by boredland** [comment]
> Is there a temporary fix? Re-pointing url or downloading package manually? I'm a bit of newb to arch and manjaro...

yes, you can disable manjaro-sway in /etc/pacman.conf

**Comment by boredland** [comment]
And you're switching because the package repo isn't available for half a day :1st_place_medal:

**Comment by boredland** [comment]
Soo: it seems we're back again. Just a little typo.

**Comment by boredland** [comment]
I'll keep this open, as more changes are to come over the next days.

**Comment by 2L3R4** [comment]
confirm its back

**Comment by GeckoSplinter** [comment]
Fixed on my side too
Thanks a lot for your work :hugs:

**Comment by superioq26** [comment]
Solved on my side too. Thanks a lot for your work.

**Comment by andrius** [comment]
No unfortunately haven't solved it yet

**Comment by callumd789** [comment]
Back again, or rather not there again.

**Comment by boredland** [comment]
Should work again! Thanks for you patience. I promise, it will have been worth i - something [cool](https://github.com/manjaro-sway/mesa-nonfree) is about to come.

**Comment by worldofgeese** [comment]
@andrius unfortunately on a brand new install on the latest stable ISO today, `manjaro-sway-settings` failed to download when running any package update operation.

**Comment by boredland** [comment]
can you post some more information? for me it works like a charm.

**Comment by worldofgeese** [comment]
@boredland just woke up and went to do the same `sudo pacman -Syyu` operation I did last night: it now runs successfully!

**Comment by syroezhkin** [comment]
I managed to solve the problem with [this](https://manjaro.ru/how-to/oshibka-klyuchey-i-baz-pri-ochen-zapozdalom-obnovlenii-manjaro.html):
```
su
pacman-mirrors --fasttrack
rm -R /etc/pacman.d/gnupg
pacman-key --init
pacman-key --populate archlinux manjaro
pacman-key --refresh-keys  
pacman -Sc
cp -r /var/lib/pacman/sync/ /sync
rm -R /var/lib/pacman/sync/
pacman -Syyu
```

If everything works, delete the `/sync` directory -- the backup we made earlier

**Comment by AndrejGorodnij** [comment]
I had same error on `buildiso -p sway`

```
 --> Profile: [sway]
 --> detected: user-repos.conf
  -> parsing repo [manjaro-sway] ...
==> Start building [sway]
==> Cleaning up ...
  -> Deleting chroot [rootfs] (x86_64) ...
  -> Deleting isoroot [iso] ...
 --> Loading Packages: [Packages-Root] ...
==> Prepare [Base installation] (rootfs)
 --> mirror: https://mirror.alpix.eu/manjaro/stable/$repo/$arch
==> Creating install root at /var/lib/manjaro-tools/buildiso/sway/x86_64/rootfs
  -> Installing packages to /var/lib/manjaro-tools/buildiso/sway/x86_64/rootfs
:: Synchronizing package databases...
 core                                                                 163.5 KiB   427 KiB/s 00:00 [##########################################################] 100%
 extra                                                               1856.1 KiB  5.27 MiB/s 00:00 [##########################################################] 100%
 community                                                              7.6 MiB  6.33 MiB/s 00:01 [##########################################################] 100%
 multilib                                                             170.6 KiB  2.78 MiB/s 00:00 [##########################################################] 100%
 manjaro-sway.db failed to download
error: failed retrieving file 'manjaro-sway.db' from pkg.manjaro-sway.download : Failed to connect to pkg.manjaro-sway.download port 443 after 7602 ms: Couldn't connect to server
error: failed to synchronize all databases (download library error)
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
```

Also I can't open `manjaro-sway.download` without VPN, it's just endless page loading...

I'm from Ukraine, maybe your website has geo block, or something?
