### ISSUE TITLE
Signature from Jonas Strassel is invalid

### ISSUE THREAD

**Issue by willieseabrook** [manjaro-sway/manjaro-sway#443]
Hi,

Running `sudo pacman -Syyu`

gives:

`error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid`

I thought this might be related to #441 but not certain so posting a new issue.

P.S awesome distro and much thanks for sticking Sway and Manjaro together in such a smooth way, was exactly what I was looking for.

**Comment by boredland** [comment]
I don't think so. There probably is just sth broken in the signing process. Will try to recover that soon.

**Comment by boredland** [comment]
Should work again! Thanks for you patience. I promise, I will have been worth i - something [cool](https://github.com/manjaro-sway/mesa-nonfree) is about to come.
