### ISSUE TITLE
Make Brightness Keys more fine-grained at lower levels

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#444]
For example, when at 5, go down to 1, then 0.01, and only then to 0.
Currently I have to resort to the terminal to set absolute minimum brightness.

**Comment by boredland** [comment]
Just for reference the [discussion](https://github.com/manjaro-sway/manjaro-sway/issues/212) that lead to the current solution.

**Comment by boredland** [comment]
Hey! Created a little script that you can find in linked PR and would like to hear some feedback.

Be aware tho: 0.01 is not generally possible. The brightness devices in linux work with absolute numbers in a certain range. What I guess you want: from the last "big" step reduce brightness only in the smallest possible step. This, however, can be very different on various devices. On my xps13 screen, steps a 1-15, on another machine it is 1-1500. For the 1-1500 variant, single steps may still be much to small. My current solution would be to reduce the step size to relative 1% after hitting a threshold. Wdyt?

**Comment by xeruf** [comment]
My framework allows me to go down to .01, and in an environment without light, this does feel significantly different ;)

**Comment by boredland** [comment]
When you say `0.01`, you mean relative, I guess. Could you down to 0.01 and post the output of `light -rG`? I would guess it to be in the lower single digits. Also `light -rM` would be interesting.

**Comment by xeruf** [comment]
current increment = current value?

is the reduction by percentage or percentage points? Will this allow it to go down to 0.01?

**Comment by boredland** [comment]
Ya, wrong word.

Lets not talk about percentage for the "minimum non-0 value", because that, by convention, is absolute "1" on all machines afaik. You can try it: set it to 1 using `light -S 1`. I guess that is the lowest non-off brightness. On some devices there is a value "0" for off, but - some don't have a mode for no backlight.

**Comment by boredland** [comment]
Hi @xeruf did you have a chance to take a look? I think on one of my devices this breaks the brightness controls, but will have to test a bit more.

**Comment by boredland** [comment]
Will probably release that as is and try to debug if sb complains, as on my primary machine this works like a charm.
