### ISSUE TITLE
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

### ISSUE THREAD

**Issue by mioscape** [manjaro-sway/manjaro-sway#446]
> sudo pacman -Syyu
[sudo] password for ihya: 
error: GPGME error: No data
:: Synchronizing package databases...
 core                                                                        163,5 KiB   818 KiB/s 00:00 [##############################################################] 100%
 extra                                                                      1857,9 KiB  16,1 MiB/s 00:00 [##############################################################] 100%
 community                                                                     7,5 MiB  20,0 MiB/s 00:00 [##############################################################] 100%
 multilib                                                                    169,4 KiB  5,51 MiB/s 00:00 [##############################################################] 100%
 manjaro-sway                                                                110,9 KiB   834 KiB/s 00:00 [##############################################################] 100%
error: GPGME error: No data
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))

![image](https://user-images.githubusercontent.com/43681888/216930299-da7ae9fd-0435-4326-ac53-da6b56c52958.png)

**Comment by boredland** [comment]
I am on it. Perhaps a regression from my attempts to fix #445. Having a look.

**Comment by boredland** [comment]
--> https://github.com/manjaro-sway/manjaro-sway/issues/447
