### ISSUE TITLE
New package repository address

### ISSUE THREAD

**Issue by boredland** [manjaro-sway/manjaro-sway#447]
Even tho the new repository is symlinked to make the deprecated paths work, I want to urge all users to update to our new repository adress.

Added a little guide on how to update to the new repository addresses to the package repo [landing page](https://pkg.manjaro-sway.download/).

TODO:

- [x] add a "update repo" script to `manjaro-sway-settings`
- [x] add a update repo note to the postinstall hook of `manjaro-sway-settings`
- [x] add a note about switching branches to the `SUPPORT.md`

**Comment by xeruf** [comment]
Getting this now, even after executing the commands listed there:
```sh
❯ yay
 -> database already registered
❯ pacman
error: could not register 'manjaro-sway' database (database already registered)
error: no operation specified (use -h for help)
```

**Comment by boredland** [comment]
can you spot a gap in the logic [here](https://github.com/manjaro-sway/desktop-settings/commit/69b314056ce4c16b60f237c7d85c3d8103a2b0df)?

**Comment by boredland** [comment]
hm, I just reproduced it on my secondary notebook. apparently it isn't removing the old config. apparently escaping issue.

**Comment by boredland** [comment]
😂 well. That explains it.

**Comment by boredland** [comment]
> is directory /etc/pacman.d guaranteed to exist?

Yes, Manjaro stores the mirrors there.

The rest is valid, but probably we should find a POSIX variant of "root"-checking

**Comment by boredland** [comment]
hey @heapifyman wdyt about https://github.com/manjaro-sway/desktop-settings/pull/143 ?
