### ISSUE TITLE
system installation failure

### ISSUE THREAD

**Issue by ashkanaev** [manjaro-sway/manjaro-sway#448]
Hi, there!

Faced with failure while installing system (any drivers) on my huawei matebook WRT-W19. Installer crashes after clicking "Install Now".

Dist: manjaro-sway-22.0.1-230129-linux515.iso

Bootable usb done by etcher and rufus (same error)

> 2023-02-09 13:12:37 - (swaybg-1.2.0/main.c: 293] Found config * for output eDP-1 (Chimei Innolux Corporation P130ZFA-BA1)
> sed: can't read /usr/share/sway/templates/help.man: No such file or directory
> grep:/home/manjaro/.config/sway/config.d/x.conf:No such file or directoru
> + VISIBILITY SIGNAL=30
> + QUIT SIGNAL=31
> "[
> --toggle
> + pkill -f-31 nug-wrapper
> ** swaymsg -t get_outputs --raw
> ++ ja -r
> • [1. name
> failed to open file /home/manjaro/.config/kanshi/config: No such file or directory
> info: main.c:421: version: 1.13.1 +pgo +ime +graphemes -assertions
> info: main.c:428: arch: Linux ×86_64/64-bit
> info: main.c:440: locale: en US.UTF-8
> info: config.c:3003: loading configuration from /usr/share/sway/templates/foot.ini
> info: fcft.c:338: foft: 3.1.5 +graphemes +runs +svg(nanosvg) -assertions
> info: fcft.c:377: fontconfig: 2.14.1, freetype: 2.12.1, harfbuzz: 6.0.0, utf8proc: 2.8.0 (Unicode 15.0.0)
> + for output in $(swaymsg -t get_outputs
> -rau I ja -r
> aCl.name")
> + nwg-wrapper
> -0 eDP-1 -sv 30 -sq 31 -s help.sh -p left
> -a end
> info: feft.c:838: /usr/share/fonts/TTF/Roboto Mono Nerd Font Complete Mono.ttf: size=D.00pt/Bpx, dpi=75.00
> info: wayland.c:1353: eDP-1: 2168x1440+2x0@60Hz P138ZFA-BA1 13.10" scale=2 PPI=196x205 (physical) PPI=98x102 (logical), DPI=198.09
> info: server.c:572: accepting connections on /run/user/1800/foot-wayland-1.sock
> info: main.c:546: running as server; launch terminals by running footclient
> longitude: 37.6171 latitude: 55.7483
> {"alt": "off". "tooltip": "no gamma correction"]
> registru: adding output 44
> calculated sun trajectory: dawn 07:28, sunrise 08:34, sunset 16:52, dusk '17:58
> setting temperature to 6500 K
> Exception ignored in: ‹_io.TextIOWrapper name-'(stdout). mode='w
> encoding='utf-g'›
> BrokenPipeError: [Errno 32] Broken pipe
> [2023-02-09 13:12:40.222] [infol Using configuration file /usr/share/sway/templates/waybar/config. jsonc
> [2023-02-09 13:12:40.275] [info] Using CSS file /usr/share/sway/templates/waybar/style.css
> QStandardPaths: runtime directory
> /run/user/1000°
> QStandardPaths: runtime directory
> is not owned by UID D, but a directory permissions 0700 owned by UID 1000 GID 1000
> Event. WINDOW subscribed
> */run/user/1000° is not owned by UID @, but a directory permissions D7DD owned by UID 1800: GID 1000
> Event. MODE subscribed
> sh: line 1: gh: command not found
> No players found
> [2023-02-09 13:12:41.136] Iwarning] As using a timezone, some format args may be missing as the date library haven't got a release sinc
> e 2018.
> 2023/02/09 13:12:41 error in "list": opening db: please store something first
> 13:12:41 [6]: Calamares: :Settings: Settings(const QString&, bool)
> Using Calamares settings file at "/etc/calamares/settings.conf"
> Required settings.conf key hide-back-and-next-during-exec is missing.
> 13:12:41 [6] void Logger: :setupLogfile()
> Summary widget is larger than viewport, enlarge by 13 to QSize (B90, 671) éviceInfo*›&)outl*)ing&, const QStringList&, const QString
> HUAWEI

Manjaro Cinnamon works fine

Looking forward for your replay!

**Comment by boredland** [comment]
hi there! I tried installing using the latest "unstable" image in a Gnome Boxes machine. Seems to work just fine.

**Comment by boredland** [comment]
please try with the most recent image version, report back if it didn't work out.
