### ISSUE TITLE
Proton VPN issue

### ISSUE THREAD

**Issue by theRoboxx** [manjaro-sway/manjaro-sway#449]
I'm not sure if the problem is on my side or if it's an issue on wayland/sway.
[protonvpn-cli](https://github.com/ProtonVPN/linux-cli) cannot connect to a server and doesn't respond while trying to connect. 
But when I switch to KDE on the same machine it works like expected.
Could someone check, if it works for him/her? OpenVPN works fine.

```
$ protonvpn-cli c --cc nl
Setting up Proton VPN.
Connecting to Proton VPN on NL-FREE#912128 with UDP.

```

Unfortunately, `protonvpn-cli --get-logs` doesn't work either.
```
$ protonvpn-cli --get-logs

Generating logs...
Unable to generate logs: can't compare offset-naive and offset-aware datetimes
```

**Comment by boredland** [comment]
> But when I switch to KDE on the same machine it works like expected.

With KDE, do you mean the KDE edition of Manjaro or just the desktop environment installed on top of the same Manjaro installation ?

**Comment by theRoboxx** [comment]
I installed the KDE Edition of Manjaro first and sway+Manjaro-sway-edition packages on top of that. Therefore it works on the KDE edition of Manjaro.

**Comment by boredland** [comment]
I installed proton and can reproduce said behavior.

**Comment by boredland** [comment]
proton-vpn needs `network-manager-applet` to be installed and running, apparently.

you can start the applet by running `nm-applet`, optionally `nm-applet --indicator` if you need/want the tray icon.

**Comment by boredland** [comment]
Re-opened as reminder:

we probably should add Network-Manager-Applet to our iso profile and start it, if installed.

**Comment by theRoboxx** [comment]
> proton-vpn needs `network-manager-applet` to be installed and running, apparently.
> 
> you can start the applet by running `nm-applet`, optionally `nm-applet --indicator` if you need/want the tray icon.

That worked, thanks! :grinning:

**Comment by boredland** [comment]
please leave it open, as I'd like to add nm-applet in non-indicator mode eventually ;-)
