### ISSUE TITLE
sway: failed to create renderer/failed to create screen on install

### ISSUE THREAD

**Issue by Shinigamiixd** [manjaro-sway/manjaro-sway#450]
I wanted to install this alongside win10 to dual boot,
I tried proprietary and open source drivers same error (nvidia)

secure boot: disabled
iso: manjaro-sway-22.0.3-230213-linux515.iso (rufus)

The error appears for 0.5sec and then kicks me back to the manjaro:manjaro login screen

![IMG-20230214-025813](https://user-images.githubusercontent.com/78961147/218762851-131272ce-0492-4f3c-969e-f5a3569af9d5.jpg)

**Comment by boredland** [comment]
hm. thats strange. I created a USB and booted my p52s, wih the "unsupported-gpu" session and the proprietary drivers, as well as out of the box.

**Comment by Shinigamiixd** [comment]
> hm. thats strange. I created a USB and booted my p52s, wih the "unsupported-gpu" session and the proprietary drivers, as well as out of the box. I guess that could indicate this not being a driver thing.

im guessing thats my issue, how do i turn on the "unsupported-gpu" session?

**Comment by Shinigamiixd** [comment]
> In the greeter choose "F3/Choose Session". Not so sure this will help tho.

thank you, ill try it tonight

**Comment by Shinigamiixd** [comment]
i tried it again using "unsupported-gpu" option didn't work, still the same error

should i try the unstable iso?

**Comment by boredland** [comment]
Ya, that one could be more promising. Which device are you trying this with?

**Comment by Shinigamiixd** [comment]
> Ya, that one could be more promising. Which device are you trying this with?

Desktop (PC)

**Comment by Shinigamiixd** [comment]
just tried the unstable iso still the same error

**Comment by boredland** [comment]
This seems to be related:
 https://www.reddit.com/r/swaywm/comments/10yie3k/falling_to_start_on_nvidia_5258902/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by boredland** [comment]
You could also try to enable the DRM mode in the kernel settings: https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by boredland** [comment]
closing as to no feedback and nothing I can do from our side without it.
