### ISSUE TITLE
$mod+Shift+e doesn't open the confirmation prompt

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#453]
There's a no prompt and after clicking the shortcut to logouts after few seconds. The command works perfectly fine in the terminal though.

<code>#Exit sway (logs you out of your Wayland session)
bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'</code>

**Comment by boredland** [comment]
Are you using the arm edition? That menu doesn't sound like ours.

**Comment by ishaanbhimwal** [comment]
nope, x86_64 edition. Didn't change anything in `/etc/sway/config/`.

**Comment by ishaanbhimwal** [comment]
no sir. issue that i am facing is that on pressing `$mod+Shift+e` the session automatically logs out after few seconds. the ideal behaviour would have been to prompt the user for a confirmation.

**Comment by boredland** [comment]
I am sooo confused. Let's unwrap this a bit. By default manjaro sway ships [this](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/sway/modes/shutdown) mode on `$mod+Shift+e`.

If you want to replace this with swaynag, I suppose you first unbind the existing mode. To do this, create a new file `$HOME/.config/sway/config.d/06-swaynag.conf`:

```
$unbindsym $mod+Shift+e
$bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'
```

**Comment by ishaanbhimwal** [comment]
thanks a lot for your help. fixed the issue. i had removed `sway/mode` from waybar config because of which the `shutdown` mode seemed to be not working.
