### ISSUE TITLE
🐛 Need to press Ctrl+C twice to copy

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#454]
### branch

stable

### Architecture

x86_64

### Description

In the recent weeks I am getting the issue that I have to press Ctrl-C twice to copy something, at first press the old items stays in the clipboard.
I have tried removing cliphist, and it seems it is part of the issue but not completely.

For example, when I right-click an image on the web and select "Copy Image", this does not work at all most of the time now.
Meanwhile, copying screenshots from the tool works just fine.
I am confused.

Asked ChatGPT, maybe that can help in debugging :)
![image](https://user-images.githubusercontent.com/13354331/219982713-23431994-a5ac-4925-b3e7-eb6e32f1148e.png)

### Reproduction steps

```bash
Press Ctrl+C, Paste, content does not match.

Note that this mainly seems to happen when there is already something in the clipboard, not right after boot or after clearing it.
```

**Comment by boredland** [comment]
For me it works fine, with and without cliphist installed. No idea how to debug that tbh.

[recording_20230220-083727.webm](https://user-images.githubusercontent.com/4662748/220043480-563f9eaa-a963-49a9-9b01-1b272e440bbd.webm)

**Comment by boredland** [comment]
closing due to no reaction.

**Comment by xeruf** [comment]
Sorry, still having this issue with and without `cliphist`, but only on my Manjaro Sway Framework, no other machine whether it is running MSway or Arch. Maybe related to KDE Connect?

**Comment by boredland** [comment]
I am using KDEConnect rn. Didn't find something suspicious.

**Comment by boredland** [comment]
no idea how to track this down, as for me it works fine in all my setups... perhaps try if it works with with a live cd?

**Comment by xeruf** [comment]
Now this issue is starting to occur on my arch linux kde plasma machine as well, suspecting a package but no idea which...

**Comment by xeruf** [comment]
Somehow I seem to have two clipboard managers running, but I cannot figure out what this thing on the right is? Searched for `clip` and `hist` in my packages and only found `cliphist` all the time - any idea how to figure that out?
![image](https://github.com/manjaro-sway/manjaro-sway/assets/13354331/563e3124-e8db-429c-b881-8f21c338ba6e)

**Comment by xeruf** [comment]
This is getting really annoying, and I am kinda clueless how to debug :c

**Comment by boredland** [comment]
Does `ps -ef | grep -i clip` report something?

**Comment by xeruf** [comment]
```sh
❯ ps -ef | grep -i clip
janek       1517       1  0 20:56 ?        00:00:00 wl-paste --watch cliphist store
```

**Comment by xeruf** [comment]
Finally think I have found it:
```sh
sudo grep --recursive 'Clipboard Contents' /etc /usr
pacman -Qo /usr/share/plasma/plasmoids/org.kde.plasma.clipboard/contents/ui/clipboard.qml
```
The offending package was seemingly `plasma-workspace`. Will see after reboot :)
