### ISSUE TITLE
💡 Add a default system-wide monospace font

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#456]
### Summary

There's no default monospace font in manjaro sway. In many places `RobotoMono Nerd Font` is used but wherever it isn't there's this `/usr/share/fonts/gnu-free/FreeMono.otf` which is used as replacement or the actual default.

Examples:
bad - https://x0.at/MNxA.png and https://x0.at/nWea.png
good - https://x0.at/zS79.png and https://x0.at/Cnf7.png

### Drawbacks

A more uniformly themed system?

### Implementation idea

Adding this to  `/etc/sway/config.d/90-enable-gtk-theme.conf `:

```
gsettings set org.gnome.desktop.interface monospace-font-name "$term-font"
```

### Will you be able to contribute a PR for this?

- [X] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
Good catch!
