### ISSUE TITLE
🐛 Roboto font is not installed by default

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#457]
### branch

testing

### Architecture

x86_64

### Description

Roboto 11 is listed as default interface font almost everywhere but funnily enough it is not installed by default or fresh systems. Installing `ttf-roboto` instantly changes the look of the whole distro.

`/usr/share/sway/themes/matcha-green/definitions`

```
set $gui-font Roboto 11
```

### Reproduction steps

```bash
To verify if it is installed by default or not:


fc-list
```

Installation:

```
sudo pacman -S ttf-roboto
```
```


### Screenshots
```

bad - [https://x0.at/RaSL.png](https://x0.at/RaSL.png) and [https://x0.at/gcT6.png](https://x0.at/gcT6.png)
good - [https://x0.at/TD_f.png](https://x0.at/TD_f.png) and [https://x0.at/ZSUS.png
](https://x0.at/ZSUS.png
)
```

### Logs

_No response_

**Comment by boredland** [comment]
For some reason I seem to have [thought](https://github.com/Manjaro-Sway/manjaro-sway-settings/commit/91e6643e0fd4901c08d98ab6ca2749a3aac0fdfe) that it would be contained in `ttf-liberation`, which apparently it isn't. Will switch those out.
