### ISSUE TITLE
Sway user config theme definition

### ISSUE THREAD

**Issue by jza34** [Manjaro-Sway/manjaro-sway#46]
Hi,

First, thank you for this great distribution for my RaspberryPi 4!
Sadly I cannot figure how to customize the desktop theme...without modifying it in `/etc/sway` of course.

I have this in my `~/.config/sway/config`

```
include /etc/sway/definitions

set $mod Mod4
set $term xterm
set $theme /etc/sway/themes/matcha-green
set $background ~/wallpaper.jpg
set $gui-font DejaVu Sans 13
set $term-font Inconsolata 13
input * xkb_numlock enable

include /etc/sway/inputs/*
include /etc/sway/outputs/*
include /etc/sway/modes/default
include /etc/sway/modes/resize
include /etc/sway/config.d/*
```

Some of my values are applied : $mod, $term, $theme, input
But not these : $background, $gui-font, $term-font

I really had hard time to understand, I thought it will be a problem of ordering but I believe I almost tried every possible combination...without success

Any advice?

**Comment by Bashe** [comment]
For the $background variable I have noticed that the '~' symbol doesn't work, but the use of $HOME usually does work...
for the other variables, I think maybe the use of quotas will help...

**Comment by jza34** [comment]
Not better with $HOME sadly...
What do you mean by "the use of quotas"?

**Comment by boredland** [comment]
> you're likely not using this distro, but the manjaro arm sway edition. those are not really related. please refer to the manjaro forums!
