### ISSUE TITLE
🐛 Element-desktop crashes on startup

### ISSUE THREAD

**Issue by theRoboxx** [manjaro-sway/manjaro-sway#460]
### branch

stable

### Architecture

x86_64

### Description

`element-desktop` crashes on startup.
I tested it on a clean Manjaro Sway Edition installation and it crashed there aswell. On the other side Manjaro KDE Edition and Edeavour OS Sway Edition work as expected.

### Reproduction steps

```bash
Launch `element-desktop`
```

### Logs

```bash
$ element-desktop
/home/USER/.config/Element exists: yes
/home/USER/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
[9805:0302/175614.847277:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
```

**Comment by boredland** [comment]
I can absolutely reproduce this, with the packaged one, as well as with the aur -git package. BUT: `element-desktop-stable-bin` works.

**Comment by theRoboxx** [comment]
True, I forgot that the current official package version from manjaro is 1.11.20 which is 6 weeks behind the latest release on github. For me, the latest version 1.11.24 solves the problem.

**Comment by boredland** [comment]
Actually Manjaro is just syncing arch upstream there: https://archlinux.org/packages/community/x86_64/element-desktop/

**Comment by boredland** [comment]
closing as an upstream packaging issue.
