### ISSUE TITLE
🐛 Help with custom sway packages

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#461]
### branch

testing

### Architecture

x86_64

### Description

Suddenly a lot of sway packages are listed as AUR packages. It wasn't like that before.

### Reproduction steps

```bash
pacman -Qm
```

```
autotiling 1.8-1
bluetuith 0.1.3-1
cliphist 1:0.3.1-2
cloudflare-warp-bin 2023.1.133-1
flashfocus 2.2.4-2
google-chrome 110.0.5481.177-1
greetd 0.9.0-1
greetd-tuigreet 0.8.0-1
gtk3-nocsd r74.c153438-2
manjaro-sway-settings 14.7.0-29
manjaro-sway-wallpapers 1.0.2-3
nwg-wrapper 0.1.3-1
oh-my-zsh r6724.7ea8a93bb-2
poweralertd 0.2.0-4
rofi-wayland 1.7.5-2
spotify 1:1.1.84.716-13
swaycwd 1.1-1
swaylock-effects 1.6.10-4
swayr 0.24.0-2
sworkstyle 1.3.2-3
visual-studio-code-bin 1.76.0-1
wlay 0.0.0-2
wlsunset 0.2.0-3
wob 0.14.2-1
zeit v0.0.6-3
```

**Comment by boredland** [comment]
I guess that means that the manjaro-sway.db is not present locally. Will try on my machine.

**Comment by boredland** [comment]
I can't reproduce this. Perhaps you need to run `pacman -Syy` ?

**Comment by ishaanbhimwal** [comment]
Still the same. Give some time and I will get back. Tried this also but doesn't work.

* https://forum.manjaro.org/t/cant-update-manjaro-sway-db-failed-to-download/132407/3

**Comment by boredland** [comment]
Make sure the repo is set up. Perhaps sth. did go wrong in that department?

Refer [here](https://pkg.manjaro-sway.download/) for instructions.

**Comment by ishaanbhimwal** [comment]
Thank you! Those instructions fixed it. I wonder what caused that mess in the first place. If I remember correctly...there's was a new `pacman.conf.pacnew` which enabled `ILoveCandy` and changed parallel downloads to 4 instead of 5. Anyways, thank you for the support.

**Comment by boredland** [comment]
Uh, actually that explains it. The upstream pacman config does not have our repo configured.

**Comment by yochananmarqos** [comment]
@ishaanbhimwal 

> I wonder what caused that mess in the first place.

You blindly merged the pacnew without reviewing it. 

Please see: https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave
