### ISSUE TITLE
🐛 multilib.db: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid

### ISSUE THREAD

**Issue by hinricht** [manjaro-sway/manjaro-sway#463]
### branch

stable

### Architecture

x86_64

### Description

I can't do a `pamac update`anymore, it results in ` invalid or corrupted database`.
It happened out of the blue and I don't have any reproduction steps.

### Reproduction steps

```bash
* Run `pamac update`
```

### Logs

```bash
$ pamac update                
Preparing...
Synchronizing package databases...
Refreshing manjaro-sway.db...                                                                                                                                             
Error: multilib.db: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid                                                                     
Failed to synchronize databases
Error: Failed to prepare transaction: invalid or corrupted database

$ pamac update --force-refresh
Preparing...
Synchronizing package databases...
Refreshing manjaro-sway.db...                                                                                                                                             
Refreshing core.db...                                                                                                                                                     
Refreshing extra.db...                                                                                                                                                    
Refreshing community.db...                                                                                                                                                
Refreshing multilib.db...                                                                                                                                                 
Error: multilib.db: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid                                                                     
Refreshing manjaro-sway.files...                                                                                                                                          
Refreshing core.files...                                                                                                                                                  
Refreshing extra.files...                                                                                                                                                 
Refreshing community.files...                                                                                                                                             
Refreshing multilib.files...                                                                                                                                              
Failed to synchronize databases                                                                                                                                           
Refreshing AUR...                                                                                                                                                         
Error: Failed to prepare transaction: invalid or corrupted database  

```
```

**Comment by boredland** [comment]
Are you absolutely sure this wasn't just an interrupted http connection of sorts? For me it works like it should (`pacmac update`, `pacman -Syy`, `yay -Syy`)

**Comment by boredland** [comment]
without further info, I'd blame a network issue (on your side or cloudflare, idk)

**Comment by hinricht** [comment]
I tried multiple time, on 2 different devices. Now it's working again, don't know what that was. Thanks for responding quickly!

**Comment by hinricht** [comment]
I am bumping into this again: 

```
$ pacman update
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid
error: no operation specified (use -h for help)
``` 

``` 
$ gpg --homedir /etc/pacman.d/gnupg --list-keys Strassel
gpg: WARNING: unsafe permissions on homedir '/etc/pacman.d/gnupg'
pub   rsa3072 2021-07-07 [SC] [expires: 2023-07-07]
      A44C644D792767CED7941AFEABB2075D5F310CF8
uid           [  full  ] Jonas Strassel <info@jonas-strassel.de>
uid           [  full  ] Jonas Strassel <jonas.strassel@ioki.com>
uid           [  full  ] Jonas Strassel <jo.strassel@gmail.com>
uid           [  full  ] Jonas Strassel <jonas.strassel@manjaro.org>
sub   rsa3072 2021-07-07 [E] [expires: 2023-07-07]

$ ls -la /var/lib/pacman/sync/manjaro-sway*
-rw-r--r-- 1 root root 18225  8. Jun 11:25 /var/lib/pacman/sync/manjaro-sway.db
-rw-r--r-- 1 root root   438  6. Jun 09:16 /var/lib/pacman/sync/manjaro-sway.db.sig
-rw-r--r-- 1 root root 34422 25. Apr 13:41 /var/lib/pacman/sync/manjaro-sway.files

$ gpg --homedir /etc/pacman.d/gnupg --verify /var/lib/pacman/sync/manjaro-sway.db.sig 
gpg: WARNING: unsafe permissions on homedir '/etc/pacman.d/gnupg'
gpg: assuming signed data in '/var/lib/pacman/sync/manjaro-sway.db'
gpg: Signature made Di 30 Mai 2023 10:48:11 CEST
gpg:                using RSA key A44C644D792767CED7941AFEABB2075D5F310CF8
gpg: BAD signature from "Jonas Strassel <info@jonas-strassel.de>" [full]
```

I alread tried removing the entire `/etc/pacman.d/gnupg` and recreating it with 

```
pacman-key --init
pacman-key --populate
pacman -Su
``` 

without success. 

I'm kind of lost here...

**Comment by hinricht** [comment]
@boredland  Btw, your key key expires `2023-07-07`, it would be good to renew it soon.

**Comment by boredland** [comment]
Extended my expiry and sent the keys to the most common keyservers. For me `pamac update` runs just fine and I can verify the signature:

```
$ gpg --homedir /etc/pacman.d/gnupg --verify /var/lib/pacman/sync/manjaro-sway.db.sig
gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
gpg: assuming signed data in '/var/lib/pacman/sync/manjaro-sway.db'
gpg: Signature made Mi 07 Jun 2023 14:00:30 CEST
gpg:                using RSA key A44C644D792767CED7941AFEABB2075D5F310CF8
gpg: Note: trustdb not writable
gpg: Good signature from "Jonas Strassel <info@jonas-strassel.de>" [full]
gpg:                 aka "Jonas Strassel <jonas.strassel@ioki.com>" [full]
gpg:                 aka "Jonas Strassel <jo.strassel@gmail.com>" [full]
gpg:                 aka "Jonas Strassel <jonas.strassel@manjaro.org>" [full]
```

**Comment by hinricht** [comment]
I had a hard time solving this. These are my notes for everybody passing by and affected by the same (weird) issue:

    sudo rm -f /var/lib/pacman/sync/* /var/cache/pacman/pkg/* /etc/pacman.d/gnupg
    sudo pacman -Sy manjaro-keyring archlinux-keyring
    sudo pacman-key --init
    pacman-key --populate
    sudo pacman -Syy

This might be the sledgehammer approach, so use with caution.

@boredland Did you already cared to include your updated key in the `manjaro-keyring` package or how is this process triggered ?

**Comment by boredland** [comment]
> Did you already cared to include your updated key in the manjaro-keyring package or how is this process triggered

no, but asked them to update it for me

**Comment by peturgq** [comment]
I'm getting this now, doesn't seem to matter if I remove the key and re-add it, I even ran @hinricht's sledgehammer approach, but still I get:
`error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is marginal trust`

**Comment by peturgq** [comment]
Output of `sudo pacman-key -l jonas.strassel@manjaro.org`
                                                                                                                                                                                                              
```pub   rsa3072 2021-07-07 [SC] [expires: 2027-06-07]
      A44C644D792767CED7941AFEABB2075D5F310CF8
uid           [ unknown] Jonas Strassel <info@jonas-strassel.de>
uid           [marginal] Jonas Strassel <jonas.strassel@manjaro.org>
uid           [ unknown] Jonas Strassel <jonas.strassel@ioki.com>
uid           [ unknown] Jonas Strassel <jo.strassel@gmail.com>
sub   rsa3072 2021-07-07 [E]```

**Comment by unz3r0** [comment]
> Output of `sudo pacman-key -l jonas.strassel@manjaro.org`
> 
> ```
>       A44C644D792767CED7941AFEABB2075D5F310CF8
> uid           [ unknown] Jonas Strassel <info@jonas-strassel.de>
> uid           [marginal] Jonas Strassel <jonas.strassel@manjaro.org>
> uid           [ unknown] Jonas Strassel <jonas.strassel@ioki.com>
> uid           [ unknown] Jonas Strassel <jo.strassel@gmail.com>
> sub   rsa3072 2021-07-07 [E]
> ```

```
pub   rsa3072 2021-07-07 [SC] [expires: 2027-06-07]
      A44C644D792767CED7941AFEABB2075D5F310CF8
uid           [  full  ] Jonas Strassel <info@jonas-strassel.de>
uid           [  full  ] Jonas Strassel <jonas.strassel@manjaro.org>
uid           [  full  ] Jonas Strassel <jonas.strassel@ioki.com>
uid           [  full  ] Jonas Strassel <jo.strassel@gmail.com>
sub   rsa3072 2021-07-07 [E]
```

Nothing changed manually. Possibly fixed by running:

```
bash <(curl -s "https://notabug.org/megavolt/random-scripts/src/master/fix-gpg-pacman.sh") --aggressive
```
:notebook: I skipped refreshing keys from the internet, so said "N" when asking.
https://notabug.org/megavolt/random-scripts/src/master/fix-gpg-pacman.sh

**Comment by peturgq** [comment]
I was able to fix this with 
`sudo pacman-key --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8`
`sudo pacman-key --lsign-key A44C644D792767CED7941AFEABB2075D5F310CF8`

**Comment by hinricht** [comment]
Thanks for all these workarounds, but does anybody understand the underlying root cause for this ? I switch to Manjaro a few month ago, and am super happy *except* for this horrible package manager user experience, which can't be compared with other distribution package managers.

**Comment by hinricht** [comment]
(forgot to say that I get into this nasty situation once a month or so)

**Comment by boredland** [comment]
This particular issue was caused by a failed attempt of sb from the Manjaro team to update the signature of my gpg key to the current one. Instead of adding the new signature, my existing one got revoked, effectively stopping anyone from even receiving a new one... I suspect this isn't happening once a month, but was an ongoing issue since beginning of July.

**Comment by boredland** [comment]
As one can see [here](https://keyserver.ubuntu.com/pks/lookup?search=A44C644D792767CED7941AFEABB2075D5F310CF8&fingerprint=on&op=index) a update from the keyserver would have sufficed. But instead my key got revoked for all manjaro users, which lead into this great situation.

**Comment by hinricht** [comment]
Sorry for the trouble. Is there any upstream Manjaro issue / link that tracks this ? I wonder what happens becaue my initial report is from March, and now it hit others as well (again ?).

**Comment by boredland** [comment]
I think the issue from march was sth. entirely different when I switched hosting of the sway package repository to cloudflare. As soon as the signatures were downloading properly, the issue was gone.
