### ISSUE TITLE
💡 Rofi File Browser

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#464]
### Summary

`rofi-file-browser-extended-git` available in the AUR is a cool project to use rofi as a file browser.

* https://aur.archlinux.org/packages/rofi-file-browser-extended-git
* https://github.com/marvinkreis/rofi-file-browser-extended

```
set $rofi-file-browser rofi -show file-browser-extended -file-browser-resume -file-browser-follow-symlinks -show-icons -font "$gui-font" -lines 10 -width 35

bindsym $mod+Shift+a exec $rofi-file-browser
```

![](https://x0.at/9K4M.png)

### Drawbacks

No drawbacks really

### Will you be able to contribute a PR for this?

- [X] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I'm not entirely convinced. I guess this isn't supposed to replace pcmanfm, but to be an additional tool?

**Comment by ishaanbhimwal** [comment]
well pcmanfm does have many extra features and the given package is a third party AUR one...i'll close this.
