### ISSUE TITLE
🐛 Trigger of `swaylock` is delayed upon opening laptop lid

### ISSUE THREAD

**Issue by FlippingBinary** [manjaro-sway/manjaro-sway#466]
### branch

stable

### Architecture

x86_64

### Description

When opening the laptop lid, the screen is fully visible and unblurred for a second or two before `swaylock` locks the screen. If `swaylock` was already triggered by inactivity prior to closing the lid, this does not occur.

This [Reddit post](https://www.reddit.com/r/swaywm/comments/mtc11k/swaylock_trying_to_have_a_somewhat_nice_locker/), suggests the problem is a race between `swaylock` and the laptop's suspend. Since `swaylock` daemonizes immediately, the call to it returns immediately. This allows the laptop to suspend before `swaylock` has a chance to blur the screen. It does so as soon as it is able, which is after the laptop resumes.

The suggested work around involves adding a sleep instruction to the `before-sleep` argument of `swayidle` used to call `$locking`. I tried a one second sleep, but that wasn't enough for me. Five seconds wound up being enough. The author of the post uses `systemctl suspend` instead, but that doesn't work for me.

```
set $swayidle swayidle -w \
    timeout $idle_timeout 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout $locking_timeout 'exec $locking' \
    timeout $screen_timeout 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    before-sleep 'playerctl pause' \
    before-sleep 'exec $locking & sleep 5'
```

Would this be a reasonable change to make to this repository?

### Reproduction steps

```bash
Boot into Manjaro Sway on a laptop and close the lid. 
Wait a few seconds (or longer) for the laptop to fully go to sleep. 
Open the laptop lid. 
Observe the contents of your unblurred screen for a few seconds before `swaylock` blurs it.
```

**Comment by boredland** [comment]
I sadly can absolutely reproduce this and we have to do something about it.
