### ISSUE TITLE
Grub installation fails saying no space left on device

### ISSUE THREAD

**Issue by shubhindia** [Manjaro-Sway/manjaro-sway#48]
My grub installation is fails saying no space left on device. I don't know if this has something to do with manjaro sway but still posting this here to get help if someone else has solved it. Attaching the screenshot as well.
![install-error](https://user-images.githubusercontent.com/7694806/111877036-602d2280-89c7-11eb-8131-ed8e8c393aab.png)

As you can see, I don't have other boot entries as well. Only windows and my USB.

**Comment by simon-bueler** [comment]
Could you maybe provide some more information regarding what the environment is?

**Comment by boredland** [comment]
closing for now dueto no reaction.
