### ISSUE TITLE
💡 Shortcuts for moving windows/workspaces to another screen

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#481]
### Summary

When connecting an external monitor, I might want to move a workspace or window to another screen without putting it into another workspace.

### Drawbacks

-

### Implementation idea

Add shortcuts for moving workspaces across screens.

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
Do you mean sth. along the lines of this?

```
bindsym $mod+Control+Shift+Right move workspace to output right
bindsym $mod+Control+Shift+Left move workspace to output left
bindsym $mod+Control+Shift+Down move workspace to output down
bindsym $mod+Control+Shift+Up move workspace to output up
```

**Comment by xeruf** [comment]
yes, and as always include vi-like HJKL as well, please :)

**Comment by hakanyi** [comment]
I have these 
```
$bindsym $mod+Alt+$left_alt move workspace to output left
$bindsym $mod+Alt+$right_alt move workspace to output right
```
