### ISSUE TITLE
🐛 Keyboard layout reset to first position after entering TTY

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#482]
### branch

stable

### Architecture

x86_64

### Description

Not sure which component is the issue, but it is a bit annoying and I thought you might have an idea :)

### Reproduction steps

```bash
- configure multiple keyboard layouts, like this: https://code.ftt.gmbh/janek/dotfiles/src/branch/main/.config/sway/config.d/keyboard.conf
- switch to second one
- switch to tty and back, or execute `swaymsg reload`

Result: First keyboard layout is selected again.
```

**Comment by boredland** [comment]
We're using the vanilla [waybar language](https://github.com/Alexays/Waybar/wiki/Module:-Language) module. In my opinion that is an upstream issue: https://github.com/swaywm/sway/issues/5456

**Comment by boredland** [comment]
I'd say there are two issues:

1. `swaymsg reload` reloading the configuration and thus taking the first preference from the configured layouts
2. switching back from tty

**Comment by boredland** [comment]
I think it would be nice to persist the selected layout, but I guess we'd need a IPC daemon for that and I am not sure thats worth the effort...

**Comment by xeruf** [comment]
Well I guess this is something to be solved upstream in the linked issue, so we can close this here :)
