### ISSUE TITLE
💡 Cliphist shortcuts

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#483]
### Summary

How can I access a cliphist element via shortcut or from terminal?

### Drawbacks

-

### Implementation idea

An fzf-selector in the terminal like the one from the system menu would probably be ideal, or just a shortcut to trigger the popup.

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
Hi! I guess cliphist should "just work" :tm: with fzf: 

`cliphist list | fzf | cliphist decode | wl-copy`

**Comment by ishaanbhimwal** [comment]
How it this different from already existing rofi clipboard in manjaro sway? <kbd>Super+Shift+P</kbd>

**Comment by boredland** [comment]
As I understand it, he is seeking the same feature, but inside the terminal.

**Comment by xeruf** [comment]
thank you @ishaanbhimwal that was the shortcut I was looking for, thanks for the command too, maybe ship a default alias called something like `clip`?
