### ISSUE TITLE
💡 Timeout notifications

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#485]
### Summary

In KDE Plasma I could configure notifications to vanish after like 3 seconds, but here they just stay, meaning I have to move my mouse over and click a bunch of times, an absolutely worthless menial labor:
![image](https://user-images.githubusercontent.com/13354331/228504240-64ddea24-1d01-40e4-bc0e-11de7ad45de3.png)

### Drawbacks

might need to separate those that should persist to prevent relevant things from getting lost

### Implementation idea

idk what is used there

maybe also a keyboard shortcut to dismiss all notifications?

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I guess that's a bug. For me they vanish after a short while. We're using [mako](https://github.com/emersion/mako) for that.

**Comment by boredland** [comment]
[recording_20230423-203251.webm](https://user-images.githubusercontent.com/4662748/233858345-9c13f6c5-bf7a-455a-ab77-e9cc4495c00b.webm)

not reproducible for me, so not a lot to go with. but then: the notifications in the screenshot do not look a lot like the `mako` we're currently shipping...
