### ISSUE TITLE
Install instructions of pkg.manjaro-sway.download did not work for arm

### ISSUE THREAD

**Issue by stubbfel** [manjaro-sway/manjaro-sway#487]
### branch

stable

### Architecture

aarch64

### Description

The following steps from https://pkg.manjaro-sway.download/ didn't work for (my) aarch64 system.:

```sh
### install ###

## remove existing manjaro-sway repository configuration
sudo sed -i '/\[manjaro-sway\]/,+2 d'  /etc/pacman.conf

## include the repo configuration
sudo sed -i '/^\[core\]/i \Include = /etc/pacman.d/manjaro-sway.repo.conf\n' /etc/pacman.conf

## add or update the repo configuration
## additionally run this after switching manjaro lifecycle branches!
sudo sh -c "curl -s https://pkg.manjaro-sway.download/$(pacman-mirrors -G)/ > /etc/pacman.d/manjaro-sway.repo.conf"
```
The content of  looks like a HTML site and like a repo.conf file.

I think it didn't work on aarch64 system because `pacman-mirrors -G`  returns `arm-stable` instead `stable`

### Reproduction steps

```bash
1. Execute `pacman-mirrors -G` on aarch64 system.
2. The output will have following prefix `arm-`
3. But the package repo only have following folders:

* stable
* unstable
* testing
```

**Comment by boredland** [comment]
for the time being, just insert the name manually instead of the call to `pacman-mirrors`. Does that work for ya?

**Comment by boredland** [comment]
ya, aarch64 support by this project is more an ongoing beta project. nice that it works tho!

**Comment by boredland** [comment]
closing as we're not a aarch64 distro. nice that people can use our repo tho!
