### ISSUE TITLE
🐛 Never goes to sleep

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#492]
### branch

stable

### Architecture

x86_64

### Description

My framework laptop battery runs out from time to time, because manjaro sway does not automatically go to sleep. https://github.com/manjaro-sway/manjaro-sway/issues/261 seems to indicate otherwise, but I am not seeing that.
When I access my laptop after a while of inactivity, it is only blurred and locked, not sleeping.

### Reproduction steps

```bash
leave it alone
```

**Comment by xeruf** [comment]
Just confirmed today. Heard the Stretchly bell regularly.

**Comment by boredland** [comment]
I tested the fix and think it worked. Let me know if this didn't fix it.
