### ISSUE TITLE
🐛 iso broke my system...

### ISSUE THREAD

**Issue by memand** [manjaro-sway/manjaro-sway#494]
### branch

stable

### Architecture

x86_64

### Description

https://forum.manjaro.org/t/manjaro-sway-iso-broke-my-system/138192/2

### Reproduction steps

```bash
https://forum.manjaro.org/t/manjaro-sway-iso-broke-my-system/138192/2
```

### Screenshots

```https://forum.manjaro.org/t/manjaro-sway-iso-broke-my-system/138192/2```

### Logs

```bash
https://forum.manjaro.org/t/manjaro-sway-iso-broke-my-system/138192/2
```

**Comment by memand** [comment]
Some rancid mod got pisse he couldn't read, so in case he takes down the post on Manjaro forums here is the fail log again https://termbin.com/c6e0

**Comment by memand** [comment]
I am quite busy trying to get my system running again rn, but if i can be of further assistance pls let me know

**Comment by boredland** [comment]
You're not providing any context. When did that happen? What was the system like before? How did this break the system, as the use of calamares indicates that you probably were about to set it up?

**Comment by boredland** [comment]
I see. You made a rookie mistake of installing a rather experimental version of manjaro. You should be able to start from the usb?

**Comment by yochananmarqos** [comment]
> Some rancid mod 

Hi, Rancid Mod here. Keep up that attitude and you will get your wish to be banned. Show some respect, please.

**Comment by boredland** [comment]
creating such an urgent-sounding ticket with such a tone and not reacting...

**Comment by KevFrancisco** [comment]
Hi I'm in the same situation as op. See the fresh install logs here: https://termbin.com/b60x. Tried both 20230409 and 20230402. Same error
```
'NoneType' object is not iterable 
 File "/usr/lib/calamares/modules/services/main.py", line 102, in run
    r = systemctl(cfg.get("timers", []), "enable", ".timer")
```

**Comment by KevFrancisco** [comment]
Does anybody have info of the last good verified version of the ManjaroSway ISO?

**Comment by boredland** [comment]
That doesn't look like an issue related to Manjaro Sway, but something related to calamares.

**Comment by boredland** [comment]
There has been a recent update to the calamares PKGBUILD:

https://gitlab.manjaro.org/packages/extra/calamares/-/commit/993064a42bf7d83948cd28326c38ea5a1624a04b

You could try and older image. Sadly I am not near a computer and thus a bit helpless right now.

**Comment by boredland** [comment]
While the root cause needs to be addressed with Manjaro, I might patch it on our side (from my phone browser, outch..)

**Comment by boredland** [comment]
Rebuild is in progress: https://github.com/manjaro-sway/manjaro-sway/actions/runs/4649560210

**Comment by KevFrancisco** [comment]
Hey man, this is unexpected. Been trying march, feb, and jan build with no luck. Going to try the latest one just now. Thanks!

**Comment by boredland** [comment]
Many thanks to the whole Manjaro team - they all helped me understand what is going on in the background. In the end it was a tiny thing, that now even is fixed in Calamares: https://gitlab.manjaro.org/tools/development-tools/manjaro-tools/-/commit/8325693818b965525e24b482a91c26b1d8d6d6e0

So probably I should revert the workaround again.
