### ISSUE TITLE
Clock time is not updating with khal

### ISSUE THREAD

**Issue by cassc** [Manjaro-Sway/manjaro-sway#50]
System time is correct but sometimes the kha lclock shown  in the status  bar is not updating.

**Comment by boredland** [comment]
if its "in" the status bar, thats not an issue with khal. the status bar barely acts as a shortcut for khal. the actual display is done using a built-in extension of waybar: 
https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/etc/skel/.config/waybar/config#L69

can you describe this a bit more? how inaccurate is it? perhaps in the configured 60s update timeframe?

**Comment by boredland** [comment]
closing for now dueto no reaction.
