### ISSUE TITLE
🐛 Screensharing is black in Brave browser (Chrome also ?)

### ISSUE THREAD

**Issue by MaximizeRr** [manjaro-sway/manjaro-sway#500]
### branch

stable

### Architecture

x86_64

### Description

The screensharing is not working in Brave browser with the latest update.
 ([Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) unknown (64-bit)](https://brave.com/latest/)

To fix this i followed this post https://forum.manjaro.org/t/screensharing-stopped-working-after-stable-update-2023-04-11-with-chromium-wayland-pipewire/138687

You have to install the latest `xdg-desktop-portal-wlr-git` from AUR
```
aur/xdg-desktop-portal-wlr-git v0.3.0.r15.gefcbcb6-1 (+7 0.00) (Installed: v0.7.0.r0.g776113a-1)
```

### Reproduction steps

```bash
-> Share entire screen with Brave (maybe also with Chrome)
-> Get grey screen

You can try with this https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/
```

**Comment by boredland** [comment]
ah, I am on unstable, there it works and seemingly I didn't even realize it is broken. here you can track the packages progress into testing/stable: https://packages.manjaro.org/?query=xdg-desktop-portal-wlr

**Comment by boredland** [comment]
... for the record: it is fixed on all branches.
