### ISSUE TITLE
💡 shell script / hook prior the swaylock

### ISSUE THREAD

**Issue by andrius** [manjaro-sway/manjaro-sway#503]
### Summary

Background:

I use custom keyboard switcher through ~/.config/sway files, mainly because of the wayvnc; to get national languages working with the wayvnc, I had to add some workarounds. 

This works fine however if swaylock get triggered while I do use Lithuanian or Russian layout, I can't enter the password. 

So I want to call a shell script that switch keyboard to US English prior swaylock

### Drawbacks

I do not see any drawbacks for the users: no script, no action

### Implementation idea

Update swaylock script to call a shell file in some user directory (i.e. ~/.config/sway/scripts/before_swaylock.sh), if it exists

### Will you be able to contribute a PR for this?

- [X] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
> This works fine however if swaylock get triggered while I do use Lithuanian or Russian layout, I can't enter the password.

So swaylock does have a different layout then the currently selected one? I am a bit confused as to what is going on.

**Comment by boredland** [comment]
Do you have a discriminator key configured for switching the keyboard layout, like in our [example](https://github.com/manjaro-sway/desktop-settings/blob/d3efdc2132448183c71feaba29fd289b3359c9f6/community/sway/etc/skel/.config/sway/config.d/XX-keyboard.conf.example)? That isn't a fix, but could help you. I will take a look later at what is going on there.

**Comment by andrius** [comment]
The thing that I had to replace keyboard switching that you propose to the script based. Due to wayvnc, I wanted to get national languages working, for some reason the wayvnc does not allow to do the keyboard switch (there is issues about this topic in their repository).

 ~/.config/sway/config.d/01-keyboard.conf

```shell
# # Bindings made for wayvnc
# $bindsym $mod+Alt+1 input "type:keyboard" xkb_layout "us(euro)"
# $bindsym $mod+Alt+2 input "type:keyboard" xkb_layout "ru(phonetic_mac)"
$bindsym Ctrl+space exec /home/ak/.dotfiles/local/bin/sway-vnc-keyboard
$bindsym $mod+Ctrl+space exec /home/ak/.dotfiles/local/bin/sway-vnc-keyboard
```
cat ~/.dotfiles/local/bin/sway-vnc-keyboard

```shell
#!/bin/sh

FOCUSED_OUTPUT="$(swaymsg -t get_outputs --raw | jq -r '[.[] | select(.focused == true)][0] | .name')"
CURRENT_LAYOUT="$(swaymsg -t get_inputs --raw | jq -r '[.[] | select(.type == "keyboard")][0] | .xkb_active_layout_name' | awk '{print $1}')"
# KEYBOARD="$(swaymsg -t get_inputs --raw | jq '[.[] | select(.type == "keyboard")][0] | .identifier')"
KEYBOARD="*"

if [ "${FOCUSED_OUTPUT}" = "HEADLESS-1" ]; then
  if [ "${CURRENT_LAYOUT}" = "English" ]; then
    swaymsg input "${KEYBOARD}" xkb_layout "ru(phonetic_mac)"
  else
    swaymsg input "${KEYBOARD}" xkb_layout "us(euro)"
  fi
else
  swaymsg input "${KEYBOARD}" xkb_switch_layout next
fi
```

**Comment by boredland** [comment]
Couln't you just do both: configure the layouts in sway and use your custom switcher-script? that way layout-switching in swaymsg should just work - on my machine I can switch locales through the discriminator key then.
