### ISSUE TITLE
💡 Temporarily suspend sleep

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#505]
### Summary

It would be fantastic if a right-click on the Zzz-Tray button would open a menu with a few options of temporarily disabling sleep (such as 30mins, 2 hours, 8 hours). Today I disabled sleep, forgot to turn it back on before putting my laptop into my bag and now the battery is drained substantially :/

### Drawbacks

--

### Implementation idea

See above

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
Cool idea! Any idea how to implement that?

**Comment by ishaanbhimwal** [comment]
> Today I disabled sleep, forgot to turn it back on before putting my laptop into my bag and now the battery is drained substantially :/

My laptop suspends whenever the lid is closed, irrespective of the idle_inhibitor setting. Try going to `/etc/systemd/login.conf` and uncomment `HandleLidSwitch=suspend` and reboot.

**Comment by xeruf** [comment]
I am not a fan of suspend at lid close though, sometimes I just move a few meters and don't want my laptop to act by itself.

@boredland something like the Stretchly context menu, unfortunately the screenshot tool did not allow me to send you an illustration so far...

**Comment by boredland** [comment]
There already is an [option for the idle module](https://github.com/Alexays/Waybar/wiki/Module:-Idle-Inhibitor) to configure a timeout. I _guess_ most ppl want there to be a timeout, so we probably should make this configurable.

**Comment by xeruf** [comment]
yes there is, sometimes I start a long-running process in CLI or have syncthing do stuff and want it to continue running

**Comment by boredland** [comment]
I think we could create our own custom idle-lock module.

Adding a idle block that swayidle respects:

```
systemd-inhibit --what=idle --who=swayidle-inhibit --why=commanded --mode=block sleep 60 &
```

checking if an idle lock is set:

```
systemd-inhibit --what=idle --who=swayidle-inhibit --no-pager --no-legend | grep "block"
```

removing the block:

```
pkill systemd-inhibit
```

**Comment by boredland** [comment]
Added a little script and waybar module. Would you like to give it a spin (it is available through `manjaro-sway-settings-git`.

**Comment by boredland** [comment]
Also added a desktop file (for rofi) and shortcut.

**Comment by boredland** [comment]
The basics are there now, feel free to add to the script if you'd like that.l ;-)
