### ISSUE TITLE
🐛 After sleep, session manager start and can't log in

### ISSUE THREAD

**Issue by Inqb8tr-jp** [manjaro-sway/manjaro-sway#509]
### branch

stable

### Architecture

x86_64

### Description

After sleep on Manjaro sway, session manager, not swaylock, prompt password and can't login with errors like below.

amdgpu:  amdgpu_device_initialize failed.
libEGL warning: egl: failed to create dri2 screen
00:00:00.026 [wlr][EGL] command: eglInitialize, error: EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed"
amdgpu_device_initialize: AMDGPU_INFO_ACCEL_WORKING = 0
amdgpu: amdgpu_device_initialize failed.
libEGL warning: egl: failed to create dri2 screen
00:00:00.029 [wlr][EGL] command: eglInitialize, error : EGL_NOT_INITIALIZED (0x3001), message: "DRI2: failed"
00:00:00.029 [wlr][EGL] command: eglInitialize, error : EGL_NOT_INITIALIZED (0x3001), message: "eglInitialize...
00:00:00.029 [wlr][render/egl.c:264] Failed to initialize EGL
00:00:00.029 [wlr][render/egl.c:554] Failed to initialize EGL context
00:00:00.029 [wlr][render/gles2/renderer.c:679] Cloud not initialize EGL
00:00:00.029 [wlr][render/wlr_renderer.c:333] Could not initialize renderer
00:00:00.029 [sway/server.c:79] Failed to create renderer

The above error is momentary and immediately returns to session manager.

After clean installing Manjaro sway, still the problem has persisted.

I use MINISFORUM EliteMini HX90 https://store.minisforum.com/products/hx90 .

### Reproduction steps

```bash
Wait for sleep.
```

**Comment by boredland** [comment]
Hm, that is fishy. I have a not too different main PC, the think-centre m75q G2,  it wakes up from sleep with open sway lock, as it should.

**Comment by Inqb8tr-jp** [comment]
Yes, that is difficult to solve.
But before some update, there was no problem with Manjaro sway.
And I'm sorry not to be able to say which update cause the problem because I've reinstalled from the latest Manjaro sway installer.
The errors are GPU related but I don't think that GPU have problem because it works before sleep.

Sometimes even the session manager doesn't appear when I type keys but only black screen.

I'm still new to Manjaro sway, so I don't know where to start to diagnose. Which log files should I check?

**Comment by Inqb8tr-jp** [comment]
I misunderstood the difference between sleep and suspend.
Disabling suspend with `systemctl mask suspend.target` made swaylock work.
It doesn't solve the fundamental problem, but it save the rebooting.
