### ISSUE TITLE
swayidle package not installed

### ISSUE THREAD

**Issue by bhartshorn** [Manjaro-Sway/manjaro-sway#51]
Hi - my new installation of your Manjaro Sway edition doesn't seem to include the `swayidle` package. It looks to me like it's supposed to be included:

https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/etc/sway/definitions#L37

https://github.com/Manjaro-Sway/desktop-settings/blob/9b025a7616d399c9e26e28a5e4582062001c3a3a/community/sway/etc/sway/config.d/99-autostart-applications#L2

`pacman -Qs swayidle` returns nothing

**Comment by bhartshorn** [comment]
Sidenote: do y'all have a communication channel outside github?

**Comment by boredland** [comment]
added swayidle in newest settings package

**Comment by boredland** [comment]
@bhartshorn yes, we have a telegram channel and we're vaguely active in the manjaro forums

also @all-contributors please add @bhartshorn for finding a bug
