### ISSUE TITLE
Site 'manjaro-sway.download' is unavailable

### ISSUE THREAD

**Issue by rptrchv** [manjaro-sway/manjaro-sway#510]
### branch

stable

### Architecture

x86_64

### Description

Site 'manjaro-sway.download' is unavailable

### Reproduction steps

```bash
pacman -Syu or just open a browser
```

**Comment by boredland** [comment]
Seems to have been a local or temporary issue.. for me it's reachable.

**Comment by rptrchv** [comment]
Yes, checked through VPN - it's reachable. Very strange, if local authorities blocked your site, it worked a few days ago...
Sorry, I'm closing the issue.
