### ISSUE TITLE
🐛 sway new window split behavior

### ISSUE THREAD

**Issue by FlynCat** [manjaro-sway/manjaro-sway#521]
### branch

stable

### Architecture

x86_64

### Description

i've been using manjaro-sway for a few months now, after updating recently, the new window split behavior changed.
previously it is just toggling between vertical split and horizontal split. 
now i had to manually change the split with keybinds

i've tried running `skel` but the issue still persist

this is what i meant by toggling between vertical and horizontal
![image](https://github.com/manjaro-sway/manjaro-sway/assets/72902682/9f7dc575-08cb-40a9-8403-15dc1703c3bf)

im sorry if this is such a stupid question

### Reproduction steps

```bash
yay -Syu
```

**Comment by boredland** [comment]
Ah, can you try and install `autotiling-rs`?

**Comment by boredland** [comment]
some context: I switched from `autotiling` to its rust implementation `autotiling-rs`, but didn't realize that it is an optional dependency and "old" users wont get the new package. I will need think about if there is a neat solution for this (perhaps just setting `provides` in the package could help)...

**Comment by FlynCat** [comment]
Thanks, installing autotiling-rs solved the issue!

**Comment by l-j-g** [comment]
@boredland is there any tangible benefit from the rust implementation ? considering #522 - i also noticed other differences in behavior, personally ill be reverting to use autotiling

**Comment by boredland** [comment]
My personal hatred for the frequent breakage (need for re-packaging) in python-tooling when python versions change. Eventually I'd like to reduce the amount of python dependencies to a minimum.

**Comment by boredland** [comment]
@all-contributors please add @catlowlevel for reporting a bug
