### ISSUE TITLE
🐛 cannot switch back to "normal" window splitting after toggling window tabbing with autotiling-rs 

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#522]
### branch

stable

### Architecture

x86_64

### Description

After toggling window tabbing, opening a second application (like terminal), closing the application again, and then enabling window splitting again, there remains a kind of menu bar below the waybar - see screenshot.

![swappy-20230531_234146](https://github.com/manjaro-sway/manjaro-sway/assets/274236/28ea8ecf-24ab-467f-9788-63e5c9973afc)

Sway returns to window splitting mode but the menu bar remains, which is a bit annoying and occupies precious screen space.

Moving the application to another workspace gets rid of the menu bar.

This does not happen if you enable the "old" autotiling.

### Reproduction steps

```bash
1. Open terminal `Mod+Enter`
2. Toggle window tabbing `Mod+w`
3. Open another terminal `Mod+Enter`
4. Close second terminal `Ctrl+d`
5. Toggle window splitting `Mod+e`
```

**Comment by boredland** [comment]
since we're not doing anything but running it, I guess that might be an upstream issue? I surely can reproduce. Would you mind opening up an issue at https://github.com/ammgws/autotiling-rs ?

**Comment by boredland** [comment]
As there has been no feedback and this is still.unfixed, we probably should switch back to autotiling then...

**Comment by boredland** [comment]
Future ISOs will feature plain `autotiling` again. If you want to switch on existing installs, just install `autotiling` as it will take precedence.
