### ISSUE TITLE
🐛 Chinese symbols instead of emojis in waybar

### ISSUE THREAD

**Issue by unz3r0** [manjaro-sway/manjaro-sway#524]
### branch

stable

### Architecture

x86_64

### Description

After an update on the stable branch today, I get Chinese symbols on the waybar:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/33820044/5e81e46f-4eab-40f9-a6a7-a2d4f9c3cf1f)

### Reproduction steps

```bash
Just update the system.
```

**Comment by boredland** [comment]
Curious, I am on unstable and don't have it. We changed the font to Jetbrains mono a while ago - so probably running `skel` could help?

**Comment by e2m4n** [comment]
I'm getting missing unicode symbols here:
![image](https://github.com/manjaro-sway/manjaro-sway/assets/18171271/0a0b3c44-d405-43e7-8084-5153d17e9745)

(I already had Jetbrains Mono installed from using their IDEs - not sure if that makes a difference?)

**Comment by kemikoza** [comment]
I have the installation package 'ttf jetbrains mono nerd' in my system, but there is still garbled code
`extra/ttf-jetbrains-mono-nerd 3.0.2-1 (6.1 MiB 184.1 MiB) [nerd-fonts] (已安装)
    Patched font JetBrains Mono from nerd fonts library`
After switching from a stable branch to an unstable branch this morning and updating the system, the situation has not changed.
![image](https://github.com/manjaro-sway/manjaro-sway/assets/114063789/91a4279f-70bc-447e-aea2-c365f55fe27f)

**Comment by unz3r0** [comment]
> Curious, I am on unstable and don't have it. We changed the font to Jetbrains mono a while ago - so probably running `skel` could help?

@boredland I run skel and relogin, but it changed not much. I opened  `/usr/share/sway/templates/waybar/config.jsonc` looked at the problematic parts:

![grafik](https://github.com/manjaro-sway/manjaro-sway/assets/33820044/1d06da57-424f-414d-9073-b19cc241f0df)

![grafik](https://github.com/manjaro-sway/manjaro-sway/assets/33820044/bebb8af1-120a-4bc0-804c-f6760fcb4d84)

When I have time I will look a bit deeper, but at the moment it is just a minor issue, which doesn't bother much. Anyway, it would be nice if there would be offered a simple fix.

**Comment by boredland** [comment]
Probably I should try the stable iso tho. Will do in a few.

**Comment by boredland** [comment]
Same result for the current stable image.

**Comment by e2m4n** [comment]
> To me this kinda looks like it isn't using the proper font in the waybar (it looks like it is using the non-nerd-font version). just to make sure this isn't a font not being properly loaded: does `fc-list | grep -i "JetBrainsMono Nerd Font"` list the JetBrains font?

it didn't show up on `fc-list` so I installed the ttf-jetbrains-mono-nerd package to make it appear, and restarted sway, and then my computer, but the bar is still showing the unicode placeholder symbols

**Comment by boredland** [comment]
Hold on there. The fact that it hasn't been installed is in fact super weird, because our manjaro-sway-settings package should have pulled it as a dependency ([ref](https://github.com/manjaro-sway/manjaro-sway-settings/blob/master/PKGBUILD#LL27C6-L27C26)). 

What does `pacman -Qi manjaro-sway-settings` or `pacman -Qi manjaro-sway-settings-git` say which version you've got installed?

**Comment by boredland** [comment]
I'd assume that you fell off our repo migration - would you mind trying out the steps on [this](https://pkg.manjaro-sway.download) page?

**Comment by e2m4n** [comment]
> What does `pacman -Qi manjaro-sway-settings` or `pacman -Qi manjaro-sway-settings-git` say which version you've got installed?

version 14.8.0-30

I'll try following the steps you linked now...

**Comment by boredland** [comment]
Ya, then you're not on the current version. The current should be v15.0.0

**Comment by e2m4n** [comment]
ok I've followed the steps, the differences in the files are:
```
diff /etc/pacman.conf ./pacman.conf.original
78,79d77
< Include = /etc/pacman.d/manjaro-sway.repo.conf
<
```
and:
```
diff /etc/pacman.d/manjaro-sway.repo.conf ./manjaro-sway.repo.conf.original                                                                                                    1 
1,3d0
< [manjaro-sway]
< SigLevel = PackageRequired
< Server = https://pkg.manjaro-sway.download/stable/$arch
```
Then I tried to update with `pacman -Syyu`. It first printed a warning:
```
error: could not register 'manjaro-sway' database (database already registered)
```
And then it installed additional packages:
```
:: Synchronising package databases...
 manjaro-sway                                                                           17,8 KiB   133 KiB/s 00:00 [#####################################################################] 100%
 core                                                                                  143,6 KiB   957 KiB/s 00:00 [#####################################################################] 100%
 extra                                                                                1636,7 KiB  21,9 MiB/s 00:00 [#####################################################################] 100%
 community                                                                               7,0 MiB  33,8 MiB/s 00:00 [#####################################################################] 100%
 multilib                                                                              145,2 KiB  8,34 MiB/s 00:00 [#####################################################################] 100%
:: Starting full system upgrade...
warning: greetd: local (0.9.0-3) is newer than manjaro-sway (0.9.0-1)
warning: greetd-tuigreet: local (0.8.0-2) is newer than manjaro-sway (0.8.0-1)
warning: wlsunset: local (0.3.0-1) is newer than manjaro-sway (0.2.0-3)
resolving dependencies...
looking for conflicting packages...

Packages (5) autotiling-1.8-4  flashfocus-2.3.1-2  manjaro-sway-settings-15.0.0-33  manjaro-sway-wallpapers-2.0.0-3  nwg-wrapper-0.1.3-3
```

But after the update I've reloading with `swaymsg reload` and the bar looks a lot better than it did:
![image](https://github.com/manjaro-sway/manjaro-sway/assets/18171271/89c57c6d-08ac-4096-ba77-777d131b340d)

There are only four placeholder glyphs now which is an improvement

**Comment by boredland** [comment]
Well progress, at least.

**Comment by boredland** [comment]
I have no reason to assume that's the cause (as I booted up the stable image), but there are different versions for the font in stable vs unstable: https://packages.manjaro.org/?query=ttf-jetbrains-mono-nerd

**Comment by unz3r0** [comment]
@boredland Solution for me: Downgrade to 2.3.3-3. Anything starting with 3.0 doesn't work.

```
DOWNGRADE_FROM_ALA=1 sudo downgrade --ala-only ttf-jetbrains-mono-nerd
swaymsg reload 
```
This version works:
```
Name                  : ttf-jetbrains-mono-nerd
Version               : 2.3.3-3
Description           : Patched font JetBrains Mono from nerd fonts library
URL                   : https://github.com/ryanoasis/nerd-fonts
Licenses              : custom:OFL
Repository            : community
Installed Size        : 144.7 MB
Groups                : nerd-fonts
Depends On            : --
Optional Dependencies : --
Required By           : manjaro-sway-settings
Optional For          : --
Provides              : ttf-font-nerd
Replaces              : nerd-fonts-jetbrains-mono
Conflicts With        : nerd-fonts-jetbrains-mono
Packager              : T.J. Townsend <blakkheim@archlinux.org>
Build Date            : Fri Apr 28 01:15:15 2023
Install Date          : Fri Jun  9 05:37:07 2023
Install Reason        : Installed as a dependency for another package
Validated By          : Signature
Backup files          : --
```

![grafik](https://github.com/manjaro-sway/manjaro-sway/assets/33820044/273dae06-c13c-4875-a70c-44c2a2ef6d02)

These private symbols must have been removed in newer versions or the ID changed. No idea now, but at least we know that there was a breaking change at the font package.

**Comment by boredland** [comment]
But why doesn't it break for me and on a beging stable image then?

**Comment by unz3r0** [comment]
`ttf-jetbrains-mono-nerd` is not used here in first place and secondly exact the same version as mentioned is used:

![grafik](https://github.com/manjaro-sway/manjaro-sway/assets/33820044/2e56df2f-3afd-4544-9447-e73656d1aca6)

**Comment by andrius** [comment]
I also have this issue but I always used PragmataPro. After some update it start displaying 'chinese' letters. I've disabled PragmataPro to try with stock version - it did not helped.

```
pacman -Qi manjaro-sway-settings
Name            : manjaro-sway-settings
Version         : 15.0.0-33
```

**Comment by boredland** [comment]
As your waybar looks relatively pimped: do you have your own waybar config by any chance? That one might still contain characters deprecated by nerd fonts.

**Comment by andrius** [comment]
> As your waybar looks relatively pimped: do you have your own waybar config by any chance? That one might still contain characters deprecated by nerd fonts.

It is based on "yours". Basically the only difference that one of my laptops comes with a tiny screen (microsoft surface go2), I wanted to make waybar narrow.

To test it with stock font, I just commented out my font settings

` ~/.config/waybar/style.css` is below, the `~/.config/waybar/config.jsonc` also created similar way 

```css
@import "/usr/share/sway/templates/waybar/style.css";

/* Reset all styles */
* {
    border: none;
    border-radius: 0;
    min-height: 0;
    margin: 0;
    padding: 0;
    font-family: "PragmataPro Mono Liga", "RobotoMono Nerd Font", "Roboto Mono", sans-serif;
}

/* The whole bar */
#waybar {
    background: @theme_bg_color;
    color: @wm_icon_bg;
    font-size: 12px;
}

/* Each module */
#custom-pacman,
#custom-menu,
#custom-help,
#custom-scratchpad,
#custom-github,
#custom-clipboard,
#custom-zeit,
#bluetooth,
#battery,
#clock,
#cpu,
#memory,
#mode,
#network,
#pulseaudio,
#temperature,
#idle_inhibitor,
#backlight,
#language,
#custom-sunset,
#custom-playerctl,
#tray {
    padding-left: 4px;
    padding-right: 4px;
}

#custom-menu {
    padding-left: 4px;
    padding-right: 6px;
}


#workspaces button {
    padding-bottom: 2px;
    padding-left: 4px;
    padding-right: 4px;
}

#custom-wf-recorder {
    padding-right: 4px;
}
```

**Comment by boredland** [comment]
Your config doesn't contain JetbrainsMono Nerd Font, not even as a Fallback Font.

**Comment by boredland** [comment]
This could still work tho. Is "Roboto Mono Nerd Font" installed?

**Comment by andrius** [comment]
Yes, it is installed; I also tried to comment out my font settings in css and to use original css - with same result

**Comment by gregorbg** [comment]
Just want to drop a note that I'm also experiencing this issue. I did not install or configure any custom fonts and "simply" upgraded the settings, including running `skel`. The problem persists across my tower PC and laptop computer, who are both running `manjaro-sway`.

Fun fact: The symbol `零` that is being erroneously used for "power saving off" means "zero" in Japanese :D

**Comment by boredland** [comment]
I went through our source files another time and [found](https://github.com/manjaro-sway/desktop-settings/commit/68e2c503376418b0b6b8c2b7e567e55b9e0918cc) many more deprecations. No idea why they would not show on my machine and am very curious if this changes anything for all of you. Will push `manjaro-sway-settings-git` in an instant.

**Comment by andrius** [comment]
Installed `manjaro-sway-settings-git` and it's all-right now

![image](https://github.com/manjaro-sway/manjaro-sway/assets/26776/bebc86dd-9846-489a-b196-6f36e70bd5ef)

**Comment by boredland** [comment]
Nice, thats is great news! Will make a release of the regular settings instantly.
