### ISSUE TITLE
💡 Switch windows in fullscreen mode

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#531]
### Summary

When I have multiple windows in one workspace and enter fullscreen mode, is there a way to switch between them?

### Drawbacks

-

### Implementation idea

Additional shortcut, maybe Cmd-Ctrl-Arrows

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by ishaanbhimwal** [comment]
You can use <kbd>Alt+Tab</kbd> to switch to another window in the same workspace. However, this removes the original window from full screen. This behavior is similar to pressing just <kbd>Mod+F</kbd> again instead.

**Comment by ishaanbhimwal** [comment]
You can just use Tabbed mode with <kbd>Mod+W</kbd> to use as many windows in the same workspace in fullscreen mode.

**Comment by xeruf** [comment]
Thanks for the hints! However in tabbed mode, switching windows still exits fullscreen.
This is a no-go in my use-case, a presentation.

**Comment by boredland** [comment]
Would it be an option to open tabbed and hide the waybar (Ctrl+Shift+B)?

**Comment by xeruf** [comment]
no, that still shows the tabs. I need true fullscreen.

**Comment by boredland** [comment]
Just wondering - as that might be sth. for a presentation, if I get it right - if you could just move the different windows to different workspaces, make them fullscreen and switch using `Super + Tab`?

**Comment by xeruf** [comment]
I tried that but back then switching workspaces exited fullscreen. But it is also problematic because the presentation workspace is an external screen so I have to first switch there. And sometimes the second window is actually a pop-up during the presentation...

**Comment by boredland** [comment]
Not a manjaro issue, but a sway limitation.
