### ISSUE TITLE
🐛 nmtui (and similar popups) rather small

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#533]
### branch

stable

### Architecture

x86_64

### Description

when i open nmtui from the info area, sometimes the text is cut off and often only a small extract of the list of networks is shown because the windows is so small

### Reproduction steps

```bash
click on the network icon in the info area
```

### Screenshots

```bash
tried uploading multiple times, kept failing :/
```

**Comment by boredland** [comment]
This seems to depend on the DPI - see: https://github.com/manjaro-sway/manjaro-sway/issues/489

**Comment by boredland** [comment]
Seems I did not fix that correctly. Will try around for a bit.

**Comment by boredland** [comment]
Soo, added a width of 900px for the floating shell. Does that help for you too?

**Comment by boredland** [comment]
for nmtui it helped a lot on my machine:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/cb2122e8-c669-4a92-8b00-f00a89d1ba39)


Would you mind trying around what a good resolution would be for bluetooith to work? I guess it isn't too much more.

**Comment by xeruf** [comment]
seems you adjusted it now to be almost fullscreen, I see ^^

**Comment by boredland** [comment]
no, I didn't - it is at 900px wide iirc, by any modern standards, that isn't full-screen - that's just a cropped screenshot.

**Comment by xeruf** [comment]
Ah, if I apply a scaling factor of 2, it ends up like that. No problem though :)

![image](https://github.com/manjaro-sway/manjaro-sway/assets/13354331/041aa177-4af5-4a92-9e24-17af26b16fe4)

**Comment by boredland** [comment]
Hm, didn't think about that. Can you run `footclient -a floating_shell --window-size-chars 82x25 nmtui` (and bluetuith respectively) on your screen and check if that is better? if so, that could be the perfect solution.

**Comment by boredland** [comment]
Perhaps I don't understand it fully, but by the contrary "lines" are a scaling-dependent factor. Aren't they?

**Comment by xeruf** [comment]
true, that makes sense!
