### ISSUE TITLE
💡 Support users who like GUIs

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#537]
### Summary

My friend is giving Manjaro Sway another go, but he is inexperienced when it comes to configs, and I have to concur that reading up on them all the time before writing them is no faster than reaching for the mouse. So we should either preinstall some GUIs (they don't harm people who don't use them) or create really intuitive TUIs (which for some reason are rare, I dunno if everybody just writes his private helpers or if most people really type out those command sequences like `lsblk` + `mount` or `swaymsg -t get_inputs` + `swaymsg input ...` by hand...)

### Drawbacks

Potential confusion through conflicting configs.

### Implementation idea

So I would like to propose preinstalling these packages and adding .desktop-files with appropriate aliases so users find them:
- `sway-input-config` aka `Keyboard Layouts` aka `Mouse and Trackpad`
- `swaysettings-git` (would need config adjustments on includes: https://github.com/ErikReider/SwaySettings#install) aka `Sway System Settings` aka `Bluetooth Manager` aka `User Management` aka `Default Applications` aka `Wallpaper Configurion` (basically linking to every unique module not available otherwise, like on other desktop environments)
- `nwg-displays --outputs_path $XDG_CONFIG_HOME/sway/config.d/outputs.nwg-displays.conf` (using that filename so it takes precedence over a potential `outputs.conf`) aka `Display Management` aka `Monitor Screens`

Though we have to make sure to avoid confusion here - `sway-input-config` has more detailed keyboard settings, but `swaysettings-git` has a module for basic keyboard layout management as well.
I also just found https://github.com/nwg-piotr/nwg-shell-config which we should definitely check out.

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I like the idea. ngw-shell-config looks pretty nice - perhaps we could make a more detailed plan once you tried it out?

**Comment by xeruf** [comment]
good point, we will try when there is room again

**Comment by xeruf** [comment]
Maybe it is time for us to embrace nwg-shell completely and maybe even consider hyprland?
I for one are not married to sway ^^ https://nwg-piotr.github.io/nwg-shell/

**Comment by boredland** [comment]
If I wanted a full-fledged gnome-like session, why shouldn't I use Gnome? Hyperland looks interesting tho, but well, that probably is another distro.

**Comment by xeruf** [comment]
well, what I really like is the keyboard-first and tiling-first approach, which I do not think GNOME fulfills

**Comment by boredland** [comment]
We could explore installing hyprland in parallel. Has anyone got a basic config that we could use as a starting point? I could imagine we could try to rebuild the whole look&feel of manjaro sway relatively easily on hyprland, at least to doesn't look to differently and ppl seem to use mainly the same tools around it.

**Comment by xeruf** [comment]
Exploring hyprland sounds even more sensible now, I am not married to backwards-compatibility as apparently sway wants to be: https://github.com/swaywm/sway/issues/8241

**Comment by xeruf** [comment]
fair point - I also heard reports of people switching from hyprland to sway because of stability: https://www.reddit.com/r/swaywm/comments/1gt79nd/sway_more_stable_than_hyprland/
so maybe sway is a good choice for somebody who does not want updates to force him to tinker around and fix configs ;)

**Comment by kiil** [comment]
Maybe niri could also be part of the mix then :)

[YaLTeR/niri: A scrollable-tiling Wayland compositor.](https://github.com/YaLTeR/niri)
