### ISSUE TITLE
💡 Waybar Rearrangement

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#541]
### Summary

The info area is too crowded - it takes up a lot of space and displays so many things that I never bothered to actually explore it.

So maybe we can improve the arrangement and compactness:
- move (CPU) temperature to the left of the CPU usage
- two icons for clipboard? is the one between pamac-tray and activitywatch something I installed?
- different display modes for indicators, like omitting the percentage and maybe changing the icon, such as for brightness, or a circle like the battery setting on android
- hovering wifi without connection shows "():" for me, maybe change this to "no connection" or even differentiate between "known networks available", "networks available" and "no networks found"
- logical grouping (suggested order left to right):
  + toggles (keyboard layout, sleep, do not disturb, keyboard layout, missing: flight mode) - maybe all to the left
  + pop-ups: zeit, cliphist, wifi, bluetooth, volume
  + informational: brightness, battery (maybe this could pop up batstat on click)
  + sensors: CPU, RAM, Temp (auto-omit this group if screen size is tight, maybe with a setting to force show/hide it)

And then hide away non-essentials like in other desktop environments.
- I don't need the brightness indicator as I always use the shortcut keys of the keyboard
- the keyboard layout switcher should be pinned to overflow if no external keyboard is connected (at least for me, I keep accidentally clicking it)
- the temperature, zeit, CPU, RAM indicators should be optional

Last but not least, thank you for all the work invested here.
I am just now realising how rich this tray really is,
very different from anything I used before.

### Drawbacks

potential confusion

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
> move (CPU) temperature to the left of the CPU usage

sure, why not.

> two icons for clipboard? is the one between pamac-tray and activitywatch something I installed?

I don't know activitywatch, never used it. also pamac-tray isn't enabled by default, as we have a more lightweight icon in the tray for that.

>  omitting the percentage and maybe changing the icon, such as for brightness

- For temperature, ram and cpu we already have different icons / colors, so we could just remove the percentage.
- For sound volumes, this will a bit harder, as I don't even know how I'd do that visually

> hovering wifi without connection

The integrated waybar network modules  (https://man.archlinux.org/man/extra/waybar/waybar-network.5.en) can fulfill some of that, but "known networks available" etc. should proof hard.

> logical grouping

You could adapt the arrangement by editing your waybar config.json - if you came up with a more logical arrangement, feel free to share.

> hide away non-essentials 

Most waybar modules don't have "exec-if" switched, so even if we could determine the dpi, we couldn't just disable those.

> keyboard layout switcher should be pinned to overflow

I'd prefer if isn't shown if only one layout is configured or the default one is selected, but that depends on waybar [adaptions](https://github.com/Alexays/Waybar/issues/66#issuecomment-1007843003) that I neither have knowledge, nor time for at the moment.

**Comment by boredland** [comment]
Pushed a first iteration on this with the low hanging fruits, further feedback welcome.
