### ISSUE TITLE
🐛 Tray Popups can overlap

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#542]
### branch

stable

### Architecture

x86_64

### Description

When I click a tray icon on the swaybar, the new popup should replace the previous one, not cover it.

### Reproduction steps

```bash
click bluetooth tray icon twice, or any other with a popup
```

**Comment by boredland** [comment]
Added a little helper based on `flock` that ensures we run a command only once and hope I added it in all relevant places.

**Comment by boredland** [comment]
-> reading the title of this issue again - did you mean that none of the floating windows should overlap or none of the same windows? I only added exclusivity for each, not all of them. Best would be you give it a try and check if it fits your needs.

**Comment by xeruf** [comment]
exclusivity across all of them would be good
try opening bluetooth and network popup and then closing them again, rather annoying experience

**Comment by boredland** [comment]
added the once script to more places and made them mutex by killing holders of the lock. it doesn't yet include clipboard and zeit, but not sure we should include them in this.
