### ISSUE TITLE
🐛 Code duplication in 99-autostart-applications.conf

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#543]
### branch

testing

### Architecture

x86_64

### Description

The last lines of `community/sway/etc/sway/config.d/99-autostart-applications.conf` starting from [line 33](https://github.com/manjaro-sway/desktop-settings/blob/546b969f65fc813800d33406fb85f4fd1517b11b/community/sway/etc/sway/config.d/99-autostart-applications.conf#L33) are a duplicate of `/etc/sway/config.d/50-systemd-user.conf`, which is provided by package `sway`.

I think these lines can be removed from `community/sway/etc/sway/config.d/99-autostart-applications.conf`

### Reproduction steps

```bash
1. Compare `community/sway/etc/sway/config.d/99-autostart-applications.conf` and `/etc/sway/config.d/50-systemd-user.conf`.
```

**Comment by boredland** [comment]
Uh, I wonder how long that was there without anyone realizing. Thanks!
