### ISSUE TITLE
🐛 custom timeouts definitions for idle related tasks (lock, display off, sleep) are ignored

### ISSUE THREAD

**Issue by bdefore** [manjaro-sway/manjaro-sway#547]
### branch

stable

### Architecture

x86_64

### Description

I run Manjaro Sway on a desktop that I don't want to log out as quickly and always it on so that I can access it remotely. I don't see anything in the support doc.

### Reproduction steps

On a fresh install of Manjaro Sway, I've tried adding the following to `~/.config/sway/definitions.d/user_definitions.conf`, but the system still steps through lock, display off, and sleep corresponding to the default timings in `/etc/sway/definitions`

```bash
set $idle_timeout 999
set $locking_timeout 9999
set $screen_timeout 99999
set $sleep_timeout 999999
```

I also tried adding `set $swayidle echo "foo"` but there was no difference.

My `~/.config/sway/config` is unchanged from skel (` diff /etc/skel/.config/sway/config ~/.config/sway/config` is empty). It includes a section to load these definitions:

```
# global variables
include /etc/sway/definitions

# user variables
include $HOME/.config/sway/definitions.d/*.conf
```

Do the definitions for these work? How would one permanently disable sleep?

**Comment by unz3r0** [comment]
Since swayidle start as autostart, you would need to relogin so that your definitions take place. Reloading will not help, since it is already running.

Permanent:
Copy the file `/etc/sway/config.d/99-autostart-applications.conf` to `~/.config/sway/config.d/99-autostart-applications.conf` and comment out `$swayidle`.

If you don't want to re-login, kill it:
```
kill $(pgrep swayidle)
```
And nothing will happen.

**Comment by bdefore** [comment]
@unz3r0 Thank you. I can confirm that these options disable idle actions, which is the question I ultimately ended on. I believe the larger issue remains a bug, that custom timeout definitions are ignored.

**Comment by bdefore** [comment]
Following up on further testing. The first method of copying the base autostart config and overriding it with a commented out $swayidle does not have any effect even after a restart. The kill action does.

**Comment by l-j-g** [comment]
encountered this on my server - im pretty sure the problem is because in /etc/sway/definitions the variables are first set then swayidle configured (with those parameters) 

```
# /etc/sway/definitions
set $idle_timeout 240
set $locking_timeout 300
set $screen_timeout 600
set $sleep_timeout 900
set $sleep_delay 2

set $swayidle swayidle -w \
    timeout $idle_timeout 'light -G > /tmp/brightness && light -S 10' resume 'light -S $([ -f /tmp/brightness ] && cat /tmp/brightness || echo 100%)' \
    timeout $locking_timeout 'exec $locking' \
    timeout $screen_timeout 'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' \
    timeout $sleep_timeout 'swaymsg "output * dpms on"; sleep $sleep_delay; systemctl suspend' \
    before-sleep 'playerctl pause' \
    before-sleep 'exec $locking & sleep $sleep_delay'
```

if you change the swayidle configuration to your preference in ~/.config/sway/definitions.d/ it should work as intended

**Comment by boredland** [comment]
If anyone's got a good idea how we could split it so, that one can configure the values without having to re-declare the idle command, I am all ears.

**Comment by l-j-g** [comment]
the least disruptive way would be if we move the definition/configuration of swayidle to /etc/sway/config.d/*autostarts*.conf but keep the timeout definitions where they are - user customization will then overwrite the defaults before sway idle is configured

**Comment by boredland** [comment]
But would it still be possible to replace the sway idle configuration entirely then?

**Comment by l-j-g** [comment]
yes that's very true... wouldnt be able to replace

**Comment by boredland** [comment]
On `manjaro-sway-settings-git` (suppose you ran `skel`), you should now be able to override the autostart commands definitions independently from `$HOME/.config/sway/config.d/`, giving you the option to override `$swayidle` to your liking, while overrides in `$HOME/.config/sway/definitions.d/` should take precedence over the global definitions. Enjoy!
