### ISSUE TITLE
💡 Open nmtui in "Activate a connection" submenu

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#548]
### Summary

Because that is where a user expects to land, being immediately able to select a network. It is quite annoying always having to first reach for the keyboard and press down+enter.

### Drawbacks

other options are less discoverable, but they are anyways only for advanced users

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I am confused. Where is this submenu even? I feel we have very different workflows there.

**Comment by boredland** [comment]
Ah, I get it. You want it to start with "select network" straight away.

**Comment by xeruf** [comment]
thanks :)
