### ISSUE TITLE
🐛 GPG Key Expired? 

### ISSUE THREAD

**Issue by l-j-g** [manjaro-sway/manjaro-sway#553]
### branch

stable

### Architecture

x86_64

### Description

Cannot use pacman, seems @boredland key expired? 

```
❯ gpg --homedir /etc/pacman.d/gnupg --list-keys | grep strass  -A 3 -B 3
gpg: WARNING: unsafe ownership on homedir '/etc/pacman.d/gnupg'
gpg: Note: trustdb not writable

pub   rsa3072 2021-07-07 [SC] [expired: 2023-07-07]
      A44C644D792767CED7941AFEABB2075D5F310CF8
uid           [ expired] Jonas Strassel <info@jonas-strassel.de>
uid           [ expired] Jonas Strassel <jonas.strassel@ioki.com>
uid           [ expired] Jonas Strassel <jo.strassel@gmail.com>
uid           [ expired] Jonas Strassel <jonas.strassel@manjaro.org>

pub   rsa4096 2014-09-28 [SC]
      77DC01C9971AC3C39A0626F72C089F09AC97B894
```

### Reproduction steps

```bash
$ sudo rm -r /etc/pacman.d/gnupg
$ sudo pacman-key --init
$ sudo pacman-key --populate archlinux manajro
$ sudo pacman -S archlinux-keyring manjaro-keyring
...
❯ sudo pacman -S manjaro-keyring
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is unknown trust
error: database 'manjaro-sway' is not valid (invalid or corrupted database (PGP signature))
```
```


### Screenshots

_No response_

### Logs

_No response_

**Comment by l-j-g** [comment]
temp fix :

`sudo pacman-key --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8`
`sudo pacman-key --lsign-key A44C644D792767CED7941AFEABB2075D5F310CF8`

**Comment by boredland** [comment]
In Manjaro keyring, my signature has been switched out a long time ago (beginning of June), the package database was correctly signed yesterday. Not sure, but maybe you need to update your local signature store, let me check the command for that.

**Comment by boredland** [comment]
Ref.: https://github.com/manjaro-sway/manjaro-sway/issues/463#issuecomment-1584517395

**Comment by l-j-g** [comment]
Just to provide some context here as i've come across this on both of my machines. 

I noticed that the manjaro-sway repo was not in my package databases

```
❯ sudo pacman -S manjaro-sway-settings
error: target not found: manjaro-sway-settings
```

Then i added the repo following #447 , and encountered the error :

```
❯ sudo pacman -S manjaro-keyring
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is unknown trust
error: database 'manjaro-sway' is not valid (invalid or corrupted database (PGP signature))
```

**Comment by dinkocar** [comment]
I also get this error:
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is unknown trust

**Comment by boredland** [comment]
Apparently my key got [removed](https://gitlab.manjaro.org/packages/core/manjaro-keyring/-/commit/2f827130e33856586236dc60c6de5c05095807d5) from the keyring? I am confused... Perhaps @philmmanjaro can help us? My key didn't expire, I just re-signed to extend the validity.

**Comment by Galbar** [comment]
I have the same issue. Any updates or how to solve it?

**Comment by boredland** [comment]
No, just [trust](https://github.com/manjaro-sway/manjaro-sway/issues/553#issuecomment-1626973060) my key locally for now...

**Comment by boredland** [comment]
Guess with the lastest updates to the keyring, this is fixed. Until the next time, I guess :-D

**Comment by kiil** [comment]
I am getting this error today:

error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid

https://github.com/manjaro-sway/manjaro-sway/issues/463#issuecomment-1584517395

does not seem to help

**Comment by reniviech** [comment]
Since a few days I again have this problem with manjaro-sway. 

error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid

I tried to add the keys manually according to https://github.com/manjaro-sway/manjaro-sway/issues/553#issuecomment-1626973060, but this also didn't worked. Any other ideas?

**Comment by anhofmann** [comment]
> Ya, the new issue is caused by fixing the underlying issue of another one 😞 there was not good, non-breaking way to do that, sadly.

I'm also affected by this. How do I fix my machine, so that it can install updates again?

**Comment by boredland** [comment]
Have you tried [this](https://github.com/manjaro-sway/manjaro-sway/issues/644#issuecomment-1838440471)?

**Comment by boredland** [comment]
> I didn't see the pinned issue, since I came to this issue by a link somewhere on the internet. But I tried and it worked, thanks!

No problem, glad it helped!
