### ISSUE TITLE
🐛 empty manjaro-sway.repo.conf?

### ISSUE THREAD

**Issue by gdkrmr** [manjaro-sway/manjaro-sway#558]
### branch

stable

### Architecture

x86_64

### Description

On a fresh install the file `/etc/pacman.d/manjaro-sway.repo.conf` was empty. Is this intended?

### Reproduction steps

```bash
cat /etc/pacman.d/manjaro-sway.repo.conf
```

**Comment by boredland** [comment]
Initially, the repo should be set up inside the pacman.conf without an empty `/etc/pacman.d/manjaro-sway.repo.conf` - will take a look what might cause this.

**Comment by boredland** [comment]
That is mildly confusing. The pacman.conf contains the `include` line, so the `manjaro-sway-mirrors` script seems to run as postinstall, as intended. Why could it be empty tho.

**Comment by l-j-g** [comment]
this could possibly happen if the networking is not configured when the script is run - recreated it by disable my wifi and run `curl -s "https://pkg.manjaro-sway.download/$(pacman-mirrors -G)/"`

**Comment by boredland** [comment]
Curiously, I guess working internet connection should be needed to download the package itself... Probably I could just make it work offline and we're probably good to go.

**Comment by andrius** [comment]
I had it empty as well on newly re-installed system

**Comment by boredland** [comment]
You can fix it running `manjaro-sway-mirrors`, I'd hope.

**Comment by boredland** [comment]
The mirrors script should now work offline.
