### ISSUE TITLE
LiveCD won't run on a VM.

### ISSUE THREAD

**Issue by SuperZoops** [Manjaro-Sway/manjaro-sway#56]
Wanted to try this before installing it on bare metal.
Throws an error when logging in, instead of booting into desktop and throws you back into CLI log in screen. 
![image](https://user-images.githubusercontent.com/26927890/118403913-04061800-b671-11eb-9cd3-f29b2f0b3676.png)

Using mesa drivers in grub.
Tried on both VMware Workstation Pro 16 and VirtualBox.

**Comment by boredland** [comment]
there's multiple issues:

1. swayidle not on the live cd -> should be fixed
2. a bug in mesa when called by wlroots https://github.com/swaywm/wlroots/issues/2795

**Comment by simon-bueler** [comment]
Got it to work by enabling 3D acceleration for the video output of the virtual machine.
Not sure where to enable that for VMware but works for virtualbox and kvm/qemu

**Comment by simon-bueler** [comment]
swaywm/wlroots#1791 semmes to be the same or at least a comparable issue. It is too fixed through enabling the 3D acceleration.

**Comment by boredland** [comment]
we should

- [ ] add this hint about 3d acceleration to the readme

**Comment by FilBot3** [comment]
I am not sure how to enable 3D Acceleration for a libvirt instance. Since I don't have it installed yet, I cannot enable it in GNOME Boxes because SPICE isn't running yet. I don't see anything blatantly obvious that says 3D Acceleration in Virt-Manager either.

**Comment by boredland** [comment]
I can only tell you that in Gnome Boxes I can select 3d Acceleration right after creating the box - however I have other problems later with the cursor being turned around etc. If you find anything, please share - I think we'd all like to move this issue into any direction.

**Comment by boredland** [comment]
sway doesn't log in due to WLR_RENDERER_ALLOW_SOFTWARE not being enabled, I will add that to our default env and remove the hint from the readme.
