### ISSUE TITLE
How can I make everything a little bigger

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#560]
### branch

unstable

### Architecture

x86_64

### Description

Hello. I have been using the manjaro sway edition for around 6 months now and I really like the overall experience.

Recently I switched from a 15.6" 16:9 display to a 14" 16:10 display and everything looks so small. I know this can be fixed by playing with font sizes but the problem is that font configurations in Manjaro sway are a little messy. They are too many settings that have to be changed. 

This problem is probably due to 16:10 display as in a 14" 16:9 everything looks the right size. How can I fix the problem without a "hacky" solution. Something that effects everything without changing  100s of config files? For the time being I using Manjaro KDE and everything looks and works fine.

Thanks! 

### Reproduction steps

```bash
Use manjaro sway on a 14" 16:10 display.
```

**Comment by boredland** [comment]
Don't you really want to set a scaling in sway?

https://wiki.archlinux.org/title/Sway#HiDPI

**Comment by ishaanbhimwal** [comment]
Thanks a lot for the suggestion. Yes using the scaling "1.1" works great although foot's font gets too small somehow.

**Comment by boredland** [comment]
Hm, perhaps that's just a result from foot changing it's auto-dpi behavior from the other issue you opened?

**Comment by boredland** [comment]
1. making everything a bit bigger: via swaywm `scale`.
2. making foot font bigger relative to the swaywm scale: add `font=JetBrainsMono Nerd Font:size=8` to a [userspace](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-customize-the-foot-terminal-without-losing-my-customization-after-an-upgrade) foot.init.
