### ISSUE TITLE
Implement setting for a default monospace font

### ISSUE THREAD

**Issue by ishaanbhimwal** [manjaro-sway/manjaro-sway#561]
### branch

unstable

### Architecture

x86_64

### Description

Default monospace font on Manjaro sway looks so bad. There is no other way to put this. This is because universal fonts like "dejavu mono" are not installed. This can be easily solved by using a config file to specify the particular font.

```
~/.config/fontconfig/fonts.conf
```

```
<fontconfig>
<match target="pattern">
  <test name="family" qual="any">
    <string>monospace</string>
  </test>
  <edit binding="strong" mode="prepend" name="family">
    <string>JetBrainsMono Nerd Font</string>
  </edit>
</match>
</fontconfig>
```

### Reproduction steps

```bash
1. Grab the latest Manjaro sway image.
2. Open Firefox.
3. Go to any website that makes uses of the default monospace font, ex - any raw github file.
```

**Comment by boredland** [comment]
While I couldn't reproduce this on my day to day machine, I added this config as `community/sway/etc/fonts/conf.d/51-monospace.conf`.

**Comment by boredland** [comment]
This is now in `manjaro-sway-settings-git` - please report back!
