### ISSUE TITLE
🐛 Can't get default theme/look back

### ISSUE THREAD

**Issue by jd327** [manjaro-sway/manjaro-sway#564]
### branch

stable

### Architecture

x86_64

### Description

Sorry, I'm not sure where else to ask this, but I can't find much information on this. After a fresh install, I did `sudo pacman -Syu` and after doing `cp /etc/sway/config ~/.config/sway/config` + relaunching sway, the whole theme changed from dark green to blue and I got this:

<https://drive.google.com/file/d/10k_U5InJ8T5Lr8V89Q-pOJVXJ_L-Zh0l/view?usp=sharing>

I've tried `skel` which helped once, but then reverted to blue theme and now I can't get it back.

What did I do wrong? Should I have copied config files first before system update like it says [here](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#customizing)?

At this point I am not sure of how to manage updates + customize Sway.

I'm planning on doing a fresh install from ISO once again, but for the future - is there a section I can read on how to properly get updates + configure my Sway setup?

### Reproduction steps

```bash
1. Fresh install
2. sudo pacman -Syu
```

**Comment by boredland** [comment]
There is no need to copy over `/etc/sway/config` - instead you can use the user space config directories: https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-customize-sway-without-losing-my-customizations-after-an-upgrade

As for stock config back, you should just ensure your `~/.config/sway/config` is this one:  https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/skel/.config/sway/config

**Comment by boredland** [comment]
Hi there! 

1. yes, `skel` should have worked, if a) your `/etc/sway/*` dir is untouched by you and b) your local overrides are in `.config/sway/config.d/` and `.config/sway/definitions.d`
2. I think that is because you did override things you shouldn't have. The $waybar_position variable is part of the definitions.
