### ISSUE TITLE
Get gnome-control-center to work

### ISSUE THREAD

**Issue by Tamriel** [manjaro-sway/manjaro-sway#567]
### branch

stable

### Architecture

x86_64

### Description

I want to use gnome-calendar with my CalDAV server. For that I need to add my server in the `online-accounts ` section of the `gnome-control-center`. Sadly, `gnome-control-center` does not run at all.

### Reproduction steps

```bash
`sudo pacman -S gnome-control-center`
`gnome-control-center online-accounts`
```

**Comment by boredland** [comment]
`pacman -S gnome-control-center gnome-online-accounts`

`XDG_CURRENT_DESKTOP=GNOME gnome-control-center`
