### ISSUE TITLE
RTX 2070super can not install

### ISSUE THREAD

**Issue by kou18n** [Manjaro-Sway/manjaro-sway#57]
My graphics card is Nvidia 2070 super, using DisplayPort.I can not boot into the desktop with either an open-source driver or proprietary driver.

**Comment by simon-bueler** [comment]
Properitary driver for nvidia are not supported in sway(see [sway](https://github.com/swaywm/sway/wiki#insert-any-question-here-and-i-use-nvidia) wiki). As reported there also, the open source Nouveau driver is required instead. 
Since I do not have any way to test Nvidia graphics card I am not of a lot of help here.
Are you able to run the live environment?

**Comment by kou18n** [comment]
I cann‘t run the live environment.

**Comment by simon-bueler** [comment]
Could you try the latest ISO, as we had some issues it may work now.
If not let me know (if you get errors please post them)

**Comment by kou18n** [comment]
Thank you. It still can not work. Now use the open-source driver I can enter the live environment, but the mouse cursor disappears, and the system response is very slow. Also frequent screen flicker, I use a 4k monitor and DP cable.

**Comment by simon-bueler** [comment]
What you could try is install Manjaro-Sway if it is possible and then insall the Nouveau driver to see if that resolves the issues you have. On the other hand you could try another Manjaro version (like Gnome, KDE, etc.) and see if the experience is the same there.

**Comment by kou18n** [comment]
> What you could try is install Manjaro-Sway if it is possible and then insall the Nouveau driver to see if that resolves the issues you have. On the other hand you could try another Manjaro version (like Gnome, KDE, etc.) and see if the experience is the same there.
I used Manjaro KDE,i3,bspwm version last year, all worked. I'll try to install Nouveau driver, thanks.

**Comment by boredland** [comment]
I had mostly bad experiences using sway and nvidia cards (be it with forcing the proprietary driver or nouveau). Don't know how to help here...

**Comment by kou18n** [comment]
I solved the problem.Delete grub `apparmor=1 security=apparmor` and reboot use ctrl+x. Both proprietary driver and nouveau driver can enter to the live system,also can install the system to the disk. But I think sway is use nouveau driver and can not support CUDA. If do not use for deeplearning it can work.

**Comment by boredland** [comment]
> Delete grub `apparmor=1 security=apparmor` and reboot

Hm, I don't know a lot about apparmor, but from what I know, disabling it as a default does not sound like the best idea.

**Comment by kou18n** [comment]
> > Delete grub `apparmor=1 security=apparmor` and reboot
> 
> Hm, I don't know a lot about apparmor, but from what I know, disabling it as a default does not sound like the best idea.

This setting is for the live system, the manjaro kde and xfce also did not have this "apparmor=1 security=apparmor".

**Comment by boredland** [comment]
@kou18n thanks for clearing up, will take a look!

**Comment by boredland** [comment]
since I cant test this myself: @kou18n could you give this built a try: https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202106300817

**Comment by kou18n** [comment]
> since I cant test this myself, @kou18n could you give this built a try: https://github.com/Manjaro-Sway/manjaro-sway/releases/tag/202106300817
Thanks, I'll try the new built and reply.
