### ISSUE TITLE
🐛 skel script doesn't backup .profile , .zshenv

### ISSUE THREAD

**Issue by l-j-g** [manjaro-sway/manjaro-sway#571]
### branch

stable

### Architecture

x86_64

### Description

the skel script only backup files within .config, but manjaro sway skel overwrites .profile, .zshenv, 

its pretty common to put user configurations into .profile, so the default behavior should at least back up this file. 

i'd raise a pr myself but cant seem to find what repo it is being hosted in ?

### Reproduction steps

```bash
`cat /usr/bin/skel`
```

**Comment by boredland** [comment]
We already provide `.config/profile.d/` and `.config/zsh/config.d/` - from my point of view that is the better way to personalize those. Anyway raised a [PR](https://github.com/arcolinux/arcolinux-on-the-road/pull/1) to add this to the script, but really not a priority in my eyes.
