### ISSUE TITLE
🐛 manjaro-sway repo "Files" database inconsistent with "Sync / Packages" database

### ISSUE THREAD

**Issue by trinitronx** [manjaro-sway/manjaro-sway#578]
### branch

stable

### Architecture

x86_64

## Symptoms:

When querying the `pacman` files database, errors are output:

    error: manjaro-sway database is inconsistent: version mismatch on package autotiling
    error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git

## Details:

It's my understanding that the files and sync databases for `pacman` are separate, yet both can be updated via:

- `sudo pacman -Fyy`: Update Files database
- `sudo pacman -Syy`: Update Sync database

Although both have been updated, the versions of certain packages are inconsistent between the two:

- `manjaro-sway-settings-git`:
  - In Files DB: `r1861.64922c6e-1`
    - <details><summary>Queried via: <code>sudo pacman --machinereadable -Fl manjaro-sway-settings-git | tr '\0' '\t'</code><br/>(Expand for full output)</summary><p><pre>error: manjaro-sway database is inconsistent: version mismatch on package autotiling<br/>error: manjaro-sway database is inconsistent: version mismatch on package autotiling<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/fonts/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/fonts/conf.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/fonts/conf.d/51-monospace.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/Code - OSS/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/Code - OSS/User/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/Code - OSS/User/settings.json<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/Code/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/Code/settings.json<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/autostart/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/autostart/blueberry-obex-agent.desktop<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/autostart/blueberry-tray.desktop<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/autostart/pamac-tray.desktop<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/brave-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/calcurse/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/calcurse/conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/chrome-beta-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/chrome-dev-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/chrome-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/chromium-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/code-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/dconf/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/dconf/user<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/electron-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/electron12-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/electron18-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/electron20-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/flashfocus/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/flashfocus/flashfocus.yml<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/foot/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/foot/foot.ini.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/kanshi/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/kanshi/config.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/microsoft-edge-beta-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/microsoft-edge-dev-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/microsoft-edge-stable-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/nvim/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/nvim/init.lua<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/nwg-wrapper/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/nwg-wrapper/help.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/nwg-wrapper/style.css<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/profile.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/profile.d/.gitkeep<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/qt5ct/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/qt5ct/qt5ct.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/qt6ct/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/qt6ct/qt6ct.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/swappy/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/swappy/config<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/config<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/config.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/config.d/README.md<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/config.d/XX-keyboard.conf.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/definitions.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sway/definitions.d/README.md<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sworkstyle/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/sworkstyle/config.toml.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/user-dirs.dirs<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/vivaldi-stable.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/waybar/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/waybar/config.jsonc.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/waybar/style.css.example<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/youtube-music-flags.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/zsh/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/zsh/.zshrc<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/zsh/config.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.config/zsh/config.d/alias<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.profile<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/skel/.zshenv<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/90-enable-theme.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/95-generate-help.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/96-waybar-config.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/98-application-defaults.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/config.d/99-autostart-applications.conf<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/definitions<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/inputs/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/inputs/default-keyboard<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/inputs/default-touchpad<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/default<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/recording<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/resize<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/scratchpad<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/screenshot<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/modes/shutdown<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/outputs/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/sway/outputs/default-screen<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/xdg/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/xdg/swayr/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/xdg/swayr/config.toml<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/xdg/wluma/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	etc/xdg/wluma/config.toml<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/bin/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/bin/clipboard<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/bin/manjaro-sway-mirrors<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/bin/skel<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/applications/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/applications/mimeapps.list<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/brightness.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/first-empty-workspace.py<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/foot.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/help.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/keyboard.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/mako.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/once.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/recorder.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/sbdp.py<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/scale.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/scratchpad.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/screenshot-notify.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/sunset.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/waybar.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/weather.py<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/wluma.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/wob.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/scripts/zeit.sh<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/foot.ini<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/mako<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/waybar/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/waybar/config.jsonc<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/templates/waybar/style.css<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/themes/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/themes/matcha-green/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/sway/themes/matcha-green/definitions<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/wayland-sessions/<br/>manjaro-sway	manjaro-sway-settings-git	r1861.64922c6e-1	usr/share/wayland-sessions/sway-unsupported.desktop</pre></p></details>
  - In Sync DB: `r1901.9ad97a03-1`
    - <details><summary>Queried via: <code>sudo pacman -Ss manjaro-sway-settings-git</code><br/>(Expand for full output)</summary><p><pre>manjaro-sway/manjaro-sway-settings-git r1901.9ad97a03-1 (sway-manjaro)<br/>    Manjaro Sway Settings</pre></details>
- `autotiling`:
  - In Files DB: `1.8-2`
    - <details><summary>Queried via: <code>sudo pacman --machinereadable -Fl autotiling</code><br/>(Expand for full output)</summary><p><pre>error: manjaro-sway database is inconsistent: version mismatch on package autotiling<br/>error: manjaro-sway database is inconsistent: version mismatch on package autotiling<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git<br/>manjaro-sway	autotiling	1.8-2	usr/<br/>manjaro-sway	autotiling	1.8-2	usr/bin/<br/>manjaro-sway	autotiling	1.8-2	usr/bin/autotiling<br/>manjaro-sway	autotiling	1.8-2	usr/lib/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/PKG-INFO<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/SOURCES.txt<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/dependency_links.txt<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/entry_points.txt<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/requires.txt<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling-1.8-py3.11.egg-info/top_level.txt<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__about__.py<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__init__.py<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/__about__.cpython-311.opt-1.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/__about__.cpython-311.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/__init__.cpython-311.opt-1.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/__init__.cpython-311.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/main.cpython-311.opt-1.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/__pycache__/main.cpython-311.pyc<br/>manjaro-sway	autotiling	1.8-2	usr/lib/python3.11/site-packages/autotiling/main.py</pre></details>
  - In Sync DB: `1.8-4`
    - <details><summary>Queried via: <code>sudo pacman -Ss autotiling</code><br/>(Expand for full output)</summary><p><pre>manjaro-sway/autotiling 1.8-4<br/>    Script for sway and i3 to automatically switch the horizontal / vertical window split orientation<br/>extra/autotiling-rs 0.1.3-1 [installed]<br/>    Automatically alternates container layouts between horizontal and vertical</pre></details>

## Solution:

The `manjaro-sway` Repository Sync DB appears newer than the Files DB.

During the repo update process, the following should be run to update the Files DB:

    repo-add /path/to/repo/manjaro-sway.db.tar.gz --sign *.pkg.tar.xz

<details><summary>Resulting repo dbs should include an updated <code>manjaro-sway.files*</code> db set</summary>
<p>

```
ll manjaro-sway*

Permissions Size User       Date Modified Name
lrwxrwxrwx    22 exampleuser 23 Aug 05:28   manjaro-sway.db -> manjaro-sway.db.tar.gz
.rw-r--r--   17k exampleuser 23 Aug 05:28   manjaro-sway.db.tar.gz
lrwxrwxrwx    25 exampleuser 23 Aug 05:28   manjaro-sway.files -> manjaro-sway.files.tar.gz
lrwxrwxrwx    29 exampleuser 23 Aug 05:28   manjaro-sway.files.sig -> manjaro-sway.files.tar.gz.sig
.rw-r--r--  218k exampleuser 23 Aug 05:28   manjaro-sway.files.tar.gz
.rw-r--r--   566 exampleuser 23 Aug 05:28   manjaro-sway.files.tar.gz.sig
```

</p>
</details> 
 
### Reproduction steps

```bash
1. First update both databases:

    sudo pacman -Syy
    sudo pacman -Fyy

2. Query on Files database gives errors:

    pacman -Fx /etc/sway/config                                                                                                           
    
    error: manjaro-sway database is inconsistent: version mismatch on package autotiling
    error: manjaro-sway database is inconsistent: version mismatch on package autotiling
    error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
    error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
    error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
    error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git

    [...SNIP...]
```

### Logs

```bash
# Full output for Reproduction steps:

pacman -Fx /etc/sway/config

error: manjaro-sway database is inconsistent: version mismatch on package autotiling
error: manjaro-sway database is inconsistent: version mismatch on package autotiling
error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
error: manjaro-sway database is inconsistent: version mismatch on package manjaro-sway-settings-git
etc/sway/config.d/ is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/90-enable-theme.conf is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/95-generate-help.conf is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/96-waybar-config.conf is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/98-application-defaults.conf is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/99-autostart-applications.conf is owned by manjaro-sway/manjaro-sway-settings 15.3.3-34
etc/sway/config.d/ is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/90-enable-theme.conf is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/95-generate-help.conf is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/96-waybar-config.conf is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/98-application-defaults.conf is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/99-autostart-applications.conf is owned by manjaro-sway/manjaro-sway-settings-git r1861.64922c6e-1
etc/sway/config.d/ is owned by manjaro-sway/swayshot 2.7.3-4
etc/sway/config.d/swayshot.conf is owned by manjaro-sway/swayshot 2.7.3-4
usr/share/archuseriso/profiles/sway/airootfs/etc/sway/config.d/ is owned by extra/archuseriso 0.7.9-1
usr/share/archuseriso/profiles/sway/airootfs/etc/sway/config.d/touchpad.conf is owned by extra/archuseriso 0.7.9-1
etc/sway/config is owned by extra/sway 1:1.8.1-1
etc/sway/config.d/ is owned by extra/sway 1:1.8.1-1
etc/sway/config.d/50-systemd-user.conf is owned by extra/sway 1:1.8.1-1
```

**Comment by boredland** [comment]
Am I not already doing what you proposed?

https://github.com/manjaro-contrib/action-repo-add/blob/main/action.yml#L88

Also I don't get those errors following your reproduction steps:

```
pacman -Fx /etc/sway/config                                                                                                                                   ✔  8s  

etc/sway/config.d/ is owned by manjaro-sway/manjaro-sway-settings 15.5.1-34
etc/sway/config.d/90-enable-theme.conf is owned by manjaro-sway/manjaro-sway-settings 15.5.1-34
etc/sway/config.d/96-waybar-config.conf is owned by manjaro-sway/manjaro-sway-settings 15.5.1-34
etc/sway/config.d/98-application-defaults.conf is owned by manjaro-sway/manjaro-sway-settings 15.5.1-34
etc/sway/config.d/99-autostart-applications.conf is owned by manjaro-sway/manjaro-sway-settings 15.5.1-34
etc/sway/config.d/ is owned by manjaro-sway/manjaro-sway-settings-git r1905.e508ef6a-1
etc/sway/config.d/90-enable-theme.conf is owned by manjaro-sway/manjaro-sway-settings-git r1905.e508ef6a-1
etc/sway/config.d/96-waybar-config.conf is owned by manjaro-sway/manjaro-sway-settings-git r1905.e508ef6a-1
etc/sway/config.d/98-application-defaults.conf is owned by manjaro-sway/manjaro-sway-settings-git r1905.e508ef6a-1
etc/sway/config.d/99-autostart-applications.conf is owned by manjaro-sway/manjaro-sway-settings-git r1905.e508ef6a-1
etc/sway/config.d/ is owned by manjaro-sway/swayshot 2.7.3-4
etc/sway/config.d/swayshot.conf is owned by manjaro-sway/swayshot 2.7.3-4
usr/share/archuseriso/profiles/sway/airootfs/etc/sway/config.d/ is owned by extra/archuseriso 0.7.9-1
usr/share/archuseriso/profiles/sway/airootfs/etc/sway/config.d/touchpad.conf is owned by extra/archuseriso 0.7.9-1
etc/sway/config is owned by extra/sway 1:1.8.1-4
etc/sway/config.d/ is owned by extra/sway 1:1.8.1-4
etc/sway/config.d/50-systemd-user.conf is owned by extra/sway 1:1.8.1-4
```
