### ISSUE TITLE
More Concise Configuration Files

### ISSUE THREAD

**Issue by AbsenceFlintIvy** [Manjaro-Sway/manjaro-sway#59]
I know it's probably an issue that only I am having, but the configuration files are a bit hard to find. I think this could be fixed with cramming everything into the /etc/sway/config file or the ~/.config/sway/config file, and it would definitely help out the newbies to sway.

**Comment by simon-bueler** [comment]
We distributed the configs on purpose, it enables us to update certain configs with packages.
If you want to change anything you can override any config in your ~/.config/sway/config file.
