### ISSUE TITLE
🐛 way-displays broken

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#592]
### branch

stable

### Architecture

x86_64

### Description

```sh
❯ way-displays
way-displays: error while loading shared libraries: libyaml-cpp.so.0.7: cannot open shared object file: No such file or directory
```

Probably needs to be recompiled

### Reproduction steps

```bash
-
```

**Comment by boredland** [comment]
Maybe we just need to rebuild? Will trigger one before investigation...

**Comment by xeruf** [comment]
I think so too, I hope this can be automated?

**Comment by xeruf** [comment]
jup looking good :)
