### ISSUE TITLE
User Configs:Backgrounds and Workspace Naming

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#60]
Just a few things:
1) In ~/.config/sway/config
The include $HOME/.config/sway/config.d/* needed to moved below the definitions for the $background var to work as where it was the $background var is used before it is updated with my custom one image.

2. If you add:
set $ws1 "1:"   
Into definitions then users can change that var so they can customize the names of the workspaces if you change the bindsym in default modes file to.
bindsym $mod+1 workspace $ws1

**Comment by boredland** [comment]
1. would you be okay with me adding a line `include $HOME/.config/sway/definitions` below the definitions so we can override the definitions while allowing config overrides with the existing `$HOME/.config/sway/config.d/*` in the end of the file?
2. very nice idea

**Comment by Mathew-D** [comment]
That should work well and solve the problem.

**Comment by boredland** [comment]
so, I think this is what you wanted for pt 2, isn't it? https://github.com/Manjaro-Sway/desktop-settings/pull/3

**Comment by Mathew-D** [comment]
yes that is what I wanted.
