### ISSUE TITLE
🐛 python-xpybutil has been removed from arch repos but flashfocus depends on it

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#605]
### branch

testing

### Architecture

x86_64

### Description

```
$ sudo pacman -S flashfocus                                                                                                                                   
resolving dependencies...
warning: cannot resolve "python-xpybutil", a dependency of "flashfocus"
:: The following package cannot be upgraded due to unresolvable dependencies:
      flashfocus
```

`python-xpybutil` has been removed from manjaro package repos with latest testing update: https://gitlab.manjaro.org/-/snippets/933#LC1678

### Reproduction steps

```bash
1. `sudo pacman -Rsun flashfocus` - if you have `flashfocus` and `python-xpybutil` installed. Make sure to have a backup of `python-xpybutil` - probably there is one in `/var/cache/pacman/pkg/`.
2. `sudo pacman -S flashfocus`
```

**Comment by boredland** [comment]
That's sad.

**Comment by boredland** [comment]
I guess fixing up the pkgbuild and not installing python-xpybutil is fine for now. I would accept both, a PR switching to the minimal bash solution, as well as glimmer. It looks a bit different and I like it.

**Comment by boredland** [comment]
ah, damn. glimmer doesn't seem to be suported on sway: https://github.com/moustacheful/glimmer/pull/7

We could try that as a patch tho.

**Comment by boredland** [comment]
The patched version seems to work just fine.
