### ISSUE TITLE
Setting the default file chooser

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#609]
### Summary

When using the Slack desktop app and wanting to upload a file, it insists on using ranger even when that is not installed.
Also it does not work properly when installed.
Do you know how to change it?

**Comment by boredland** [comment]
Hm, I can say for sure that it isn't ranger for me. Perhaps that can help us track down how to change it for you? I assumed, that it should be enough to have the inode/directory "file type" set to pacman? For me, there is `inode/directory=pcmanfm.desktop` in the system wide mime types in `/usr/share/applications/mimeapps.list`. Is there probably an override in ` .config/mimeapps.list` containing ranger?

Ref.: https://wiki.archlinux.org/title/XDG_MIME_Applications#mimeapps.list

**Comment by xeruf** [comment]
Hm it was overridden to dolphin locally, which I uninstalled at some point, I will experiment a bit...

**Comment by xeruf** [comment]
This now also occurred in Signal, smells like some update

**Comment by boredland** [comment]
I don't have ranger installed, so probably a ranger update broke it?

**Comment by xeruf** [comment]
but I do not have it installed either :joy:

**Comment by boredland** [comment]
This still hasn't happened to me, I fear I don't know which package updates your mime settings...

**Comment by xeruf** [comment]
works fine for now
