### ISSUE TITLE
🐛 Terminal apps won't run from the pcmanfm context menu

### ISSUE THREAD

**Issue by mesmere** [manjaro-sway/manjaro-sway#619]
### branch

stable

### Architecture

x86_64

### Description

Any application with a `.desktop` file that has `Terminal=true` set, like neovim, does nothing when you click it from the pcmanfm context menu.

Apparently this issue is due to foot not being on the hardcoded (!) list of terminals that glib looks for when launching terminal applications.

### Reproduction steps

```bash
1. Install neovim on a fresh manjaro-sway system.
2. Right click a text file in pcmanfm.
3. Select the neovim option from the context menu.
4. Nothing happens.
```

### Screenshots

![swappy-20231109_224550](https://github.com/manjaro-sway/manjaro-sway/assets/95945959/85cc2b0e-aa25-43c7-98a7-de78516f2aef)

### Logs

```bash
~ $ gio launch /usr/share/applications/nvim.desktop lazyvim.json 
gio: Unable to launch application ‘/usr/share/applications/nvim.desktop’: Unable to find terminal required for application
```

**Comment by boredland** [comment]
Understood. So probably we should reopen this one to keep track of adding an appropriate .desktop file for foot.

**Comment by boredland** [comment]
I just removed `/usr/bin/xdg-terminal-exec` and installed `xdg-terminal-exec-git`. For me it seems to "just work" out of the box with the gio-command you posted earlier. Can you confirm?

**Comment by boredland** [comment]
Ah, I think I understand why it "just works": foot also listens to `foot -e [CMD]`. The only thing "foot.sh" achieves is picking up the default config when starting the foot server - so just starting foot via `foot -e` might be just fine afterwards.

**Comment by boredland** [comment]
Should land in 16.2.0
