### ISSUE TITLE
🐛 help.sh doesn't work with sway config that include env vars

### ISSUE THREAD

**Issue by tesseract241** [manjaro-sway/manjaro-sway#620]
### branch

stable

### Architecture

x86_64

### Description

The script used to serve nwg-wrapper the configuration to display on screen, sbdp.py, doesn't expand env vars.  
This results in sway configs that, for example, include $HOME, not to be parsed correctly.  
I've made a pull request that should fix it https://github.com/manjaro-sway/desktop-settings/commit/844d5e3e3894e9f2c26efeaabccd4456dfd6bb13
I've put the call to expand env vars within the include loop because the rootPath would have been expanded by the shell when launching sbdp.py, so this should cause the minimal fix.

### Reproduction steps

```bash
Have a sway configuration that includes env vars
```

**Comment by tesseract241** [comment]
I want to add that this is just a symptom of using an external script to emulate sway's internal behaviour, sbdp.py doesn't really understand the config so it misses things like `unbindsym`, rebinding and `bindgesture` and is in general fragile with regards to changes in how the sway config works.
The parsing also only happen at start time, so it doesn't respond to changes to sway config, as it doesn't have any way to know when they happen.  
The ideal solution here I think would be for `swaymsg` to provide a keybind dump option, which should solve all of the problems listed. Is there any chance that could happen?

**Comment by boredland** [comment]
Ya, having a tool like that inside `swaymsg` sounds much better. There has been an ongoing discussion and and experimental patch: https://github.com/swaywm/sway/pull/5561

**Comment by boredland** [comment]
Has been in the current release. Please report back if everything works as expected.

**Comment by tesseract241** [comment]
Working fine for me, but it was a given as I had switched the script in /usr/ with mine already, so the update made no changes.
