### ISSUE TITLE
Waybar cannot be displayed after startup

### ISSUE THREAD

**Issue by hnsylzg** [manjaro-sway/manjaro-sway#623]
### branch

stable

### Architecture

x86_64

### Description

After startup, the waybar cannot be displayed unless reloaded

### Reproduction steps

```bash
I uninstalled cliphist and the waybar works normally.
```

**Comment by boredland** [comment]
Very strange. I have cliphist and no issue starting the waybar...

**Comment by boredland** [comment]
I had it now too, but it just took quite a long time. Nothing interesting on the console either. Very strange indeed.

**Comment by hnsylzg** [comment]
I think the problem lies in
set $cliphist_watch '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch pkill -RTMIN+9 waybar'
set $cliphist_store '[ -x "$(command -v wl-paste)" ] && [ -x "$(command -v cliphist)" ] && wl-paste --watch cliphist store'

**Comment by boredland** [comment]
Maybe, but why would it work after a reload then?

**Comment by hnsylzg** [comment]
Is there any progress on this issue? I also have this problem when I do a fresh install

**Comment by hnsylzg** [comment]
waybar.log file is empty, content after reload

[2023-12-03 20:34:47.965] [info] Using configuration file /usr/share/sway/templates/waybar/config.jsonc
[2023-12-03 20:34:47.969] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2023-12-03 20:34:47.969] [info] Using CSS file /usr/share/sway/templates/waybar/style.css
[2023-12-03 20:34:48.002] [warning] No batteries.
[2023-12-03 20:34:48.050] [error] findCurController() failed: no bluetooth controller found
[2023-12-03 20:34:48.057] [warning] module backlight: Disabling module "backlight", No backlight found
No players found
[2023-12-03 20:34:48.232] [info] Bar configured (width: 1920, height: 30) for output: HDMI-A-1

**Comment by boredland** [comment]
> After startup，waybar.log file is empty

Oh wow, so the process is created but doesn't start, nor log anything? Very interesting.

Before you reload, could you check if the waybar process is alive or killed? (`ps -ef | grep -e 'waybar')

**Comment by hnsylzg** [comment]
ps -ef | grep waybar                                                                                                                                                                                                                                               ✔ 
lzg          740       1  0 20:53 ?        00:00:00 wl-paste --watch pkill -RTMIN+9 waybar
lzg          780       1  0 20:53 ?        00:00:00 sh -c [ -x "$(command -v playerctl)" ] && pkill playerctl; playerctl -a metadata --format {{status}} {{title}} --follow | while read line; do pkill -RTMIN+5 waybar; done
lzg          798     780  0 20:53 ?        00:00:00 sh -c [ -x "$(command -v playerctl)" ] && pkill playerctl; playerctl -a metadata --format {{status}} {{title}} --follow | while read line; do pkill -RTMIN+5 waybar; done
lzg         1102    1016  0 20:53 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox waybar

**Comment by boredland** [comment]
So waybar dead and we have to find out what killed it..

**Comment by boredland** [comment]
On the live image it just works. So something is different from the live-session (which sadly is quite a lot)..

**Comment by hnsylzg** [comment]
A problem was also reported. If the fcitx5 input method is installed, the pop-up htop and pulsemixer windows will flash and cannot be opened.

**Comment by boredland** [comment]
So. Waybar working in live session:

[recording_20231203-155212.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/b3d7e960-6954-40e8-a4ab-24d62f5719a7)

Thereafter in a freshly installed vm:

[recording_20231203-160054.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/24c955a8-9502-4f03-9e2f-3de37d7b6108)

Currently I am out of ideas as to where to look for the issue.

**Comment by hnsylzg** [comment]
My only solution now is to disable clipboard history, or reload after booting

**Comment by boredland** [comment]
Just had this - after a long time not seeing it at all - on my work-machine. There are no logs, as you already confirmed.

**Comment by boredland** [comment]
Changed it a bit so not only errors are written to `/tmp/waybar.log`. Can you check again if/what that contains while it fails?

**Comment by hnsylzg** [comment]
I reinstalled the latest version, waybar.log is still the same as before, empty, and the information after reload is also the same as before.
