### ISSUE TITLE
🐛 ttf-jetbrains-mono-nerd-3.1.0-1 breaks config

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#626]
### branch

testing

### Architecture

x86_64

### Description

`ttf-jetbrains-mono-nerd-3.1.0-1` seems to have renamed `JetBrainsMono Nerd Font` to `JetBrainsMono NF`, and now the config references a font that cannot be found.

### Reproduction steps

```bash
1. upgrade to `ttf-jetbrains-mono-nerd-3.1.0-1`
2. open foot
   => warning: DejaVu Sans: font does not appear to be monospace; check your config, or disable this warning by setting [tweak].font-monospace-warn=no
3. reload sway config
```

**Comment by boredland** [comment]
Yeah, a PR would be welcome!

**Comment by boredland** [comment]
Seems currently releases are broken due to an issue in our repo setup during build.

**Comment by boredland** [comment]
finally un-broke the release process. please check if everything works as expected. on a first glance it does on my machine.
