### ISSUE TITLE
🐛 "Unable to retrieve socket path" when upgrading manjaro-sway-settings

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#630]
### branch

testing

### Architecture

x86_64

### Description

During the upgrade to manjaro-sway-settings 15.6.0 I noticed the following error message:

```
...
(1/1) upgrading manjaro-sway-settings                                                                    [--------------------------------------------------------------] 100%
00:00:00.009 [ERROR] [swaymsg/main.c:491] Unable to retrieve socket path
## in order to update your user configuration, run: skel
...
```

### Reproduction steps

```bash
1. `sudo pacman -S manjaro-sway-settings`
```

**Comment by boredland** [comment]
Looks like a sway error when running `swaymsg reload`. No idea why tho.

**Comment by boredland** [comment]
Good catch! Do you know of a way to run a command during pacman install as the calling user?

**Comment by boredland** [comment]
As I don't think it is that important anyway: going with just the comment. Will be in the next release.
