### ISSUE TITLE
💡 Hide help menu initially

### ISSUE THREAD

**Issue by robin-thoene** [manjaro-sway/manjaro-sway#632]
### Summary

I think the help menu displayed on the desktop is pretty useful. I do not want to disable it entirely, but keep the option to toggle it on / off using the existing shortcut.

What I try is hiding it on boot. Currently it is displayed always after boot, so I quickly hit the shortcut once to hide it .

### Drawbacks

-

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
We could just store the state of the help menu in a file or something. This could be great place to implement that: https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/usr/share/sway/scripts/help.sh

**Comment by robin-thoene** [comment]
If you are okay with it, I would give it a try to implement this :)

**Comment by robin-thoene** [comment]
Could I define a var somewhere in the `.config/sway/definitions.d/...` like `set $hide-help-on-boot` and read it in the shell script you mentioned as initial value and then program something that keeps the behavior from there as it is now?

I just do not exactly know how this variables stuff works at the moment. How do I read a var I declared that way, or is it even possible to introduce a new variable this way?

**Comment by robin-thoene** [comment]
Yes indeed, works like a charm thank you very much.
