### ISSUE TITLE
🐛 Kernel header

### ISSUE THREAD

**Issue by randibprananda** [manjaro-sway/manjaro-sway#635]
### branch

unstable

### Architecture

x86_64

### Description

Please include the linux kernel header, because I am using an rtl8821ce whose driver must be installed manually due to kernel problems. I'm sure many applications have kernel headers.

### Reproduction steps

```bash
yay -S linux66-rt-headers
```

**Comment by boredland** [comment]
Without more information, I just don't know what to do here.
