### ISSUE TITLE
🐛 sworkstyle 

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#638]
### branch

stable

### Architecture

x86_64

### Description

it gives the error:
                                                                                                                                                                                                  
thread 'main' panicked at src/config.rs:164:65:
called `Result::unwrap()` on an `Err` value: ConfigError { message: "unexpected character found: `/` at line 47 column 1" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Reproduction steps

```bash
start the system or manual start sworkstyle
```

**Comment by boredland** [comment]
sorry for the inconvenience. Newest version should work.
