### ISSUE TITLE
💡 change the command for logout

### ISSUE THREAD

**Issue by Mathew-D** [manjaro-sway/manjaro-sway#639]
### Summary

I have moved my system to SDDM (wayland) as my greeter but the logout command we are using doesn't have it come back after you logout.  Could we switch the command to:
`swaymsg exit`
which sends a message to the running Sway instance to exit gracefully, which return me to the login manager.  Or is there a way I can override the command in /etc/sway/modes/shutdown

### Drawbacks

As I am not using the text greeter  I don't know how this command works with it.  Can someone try this command in a terminal and see if brings you back to the login.

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I would have thought, that a generic systemd command (`systemctl poweroff`) would shutdown sway gracefully and make sddm come back properly. You sure it works with `swaymsg exit`?

**Comment by boredland** [comment]
I tried swaymsg exit and it looks just as fine for me. I think we can just switch 🤷🏼

**Comment by Mathew-D** [comment]
The shutdown and restart commands worked fine, it was the logout command that didn't. So you could never switch users.

it was the loginctl terminate-user $USER that needed to be switched.

**Comment by boredland** [comment]
ah, oh well. didn't read that well enough. will mend it asap.

**Comment by boredland** [comment]
will land in 16.2.1
