### ISSUE TITLE
🐛 Cannot override definitions any more

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#640]
### branch

testing

### Architecture

x86_64

### Description

It used to be possible to override definitions in `/etc/sway/definitions` in a file `$HOME/.config/sway/definitions.d/definitions.conf`.

But since [this commit](https://github.com/manjaro-sway/desktop-settings/commit/6df239c0750cd04d6248f7962e2d530e9e9c33b4) some overrides are not applied anymore.

For example, if you override `$background` and `$calendar` only the change to `$background` will be applied.

In fact, most of the configuration options in [SUPPORT.md](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md) that refer to `$HOME/.config/sway/definitions.d/` won't work anymore - like [How can I disable the clipboard history?](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md).

### Reproduction steps

1. Create file `~/.config/sway/definitions.d/01-definitions.conf` and add the following content:

   ```   
   # Reset $calendar back to using khal
   set $calendar $term_float ikhal

   # Set desktop background
   set $background ~/Pictures/my-wallpaper.png
   ```
   
   Adjust `my-wallpaper.png` to an existing image.
2. Logout and login again
3. Click on the waybar's clock section in the upper right corner

**Result**

Desktop background image is changed.
calcurse opens in a floating foot terminal after step 3.

**Expected Result**

ikhal should open in a floating foot terminal after step 3.

**Potential Workaround**

Comment out the first `include $HOME/.config/sway/definitions.d/*.conf` in `~/.config/sway/config`, and reload sway. Now all overrides are applied as expected.
```


### Screenshots

_No response_

### Logs

_No response_

**Comment by boredland** [comment]
ya, guess we'll have to revert that one and offer some way to include "before" and "after" the global definitions..

**Comment by boredland** [comment]
I pushed a new version of `manjaro-sway-settings-git` which should be available in a few minutes. Could you give that one a try?

**Comment by boredland** [comment]
ah, well `set $background /usr/share/backgrounds/manjaro-sway/gruvbox-dark-manjarosway-3840x2160.png` in a file "x.conf" just worked fine. Guess I'll make a release of it soonish.
