### ISSUE TITLE
🐛 Signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid

### ISSUE THREAD

**Issue by kstiehl** [manjaro-sway/manjaro-sway#644]
### branch

stable

### Architecture

x86_64

### Description

# Problem

Updating with `pacman -Syyu` throws the error shown in the logs. 

I  tested it on multiple devices. and already tried to reinitialize pacman-keys by running 

```
sudo rm -fr /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --populate archlinux manjaro
sudo pacman-key --refresh-keys
```

But still get the same error

### Reproduction steps

```bash
Run `pacman -Syyu`
```

### Logs

```bash
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid
:: Synchronizing package databases...
 manjaro-sway                                                                                              19,4 KiB   132 KiB/s 00:00 [##################################################################################] 100%
 core                                                                                                     146,6 KiB   108 KiB/s 00:01 [##################################################################################] 100%
 extra                                                                                                      8,6 MiB  1829 KiB/s 00:05 [##################################################################################] 100%
 community                                                                                                 29,0   B  93,0   B/s 00:00 [##################################################################################] 100%
 multilib                                                                                                 145,0 KiB  2,48 MiB/s 00:00 [##################################################################################] 100%
error: manjaro-sway: signature from "Jonas Strassel <info@jonas-strassel.de>" is invalid
error: failed to synchronize all databases (unexpected error)
```

**Comment by pvlieres** [comment]
+1 same error on my machine

**Comment by DavidD344** [comment]
Is this the definitive solution? Or should I return here again later?

**Comment by jakubbortlik** [comment]
After running the command `sudo rm -f /var/lib/pacman/sync/manjaro-sway.db.sig` I'm still getting this error and am unable to run `sudo pacman -Syu` successfully:
```
error: xdg-terminal-exec-git: signature from "Jonas Strassel <info@jonas-strassel.de>" is marginal trust
:: File /var/cache/pacman/pkg/xdg-terminal-exec-git-r131.b269e8e-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: manjaro-sway-settings: signature from "Jonas Strassel <info@jonas-strassel.de>" is marginal trust
:: File /var/cache/pacman/pkg/manjaro-sway-settings-16.2.6-0-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: sworkstyle: signature from "Jonas Strassel <info@jonas-strassel.de>" is marginal trust
:: File /var/cache/pacman/pkg/sworkstyle-1.3.5-7-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```
Any ideas?

**Comment by boredland** [comment]
That seems to be a completely different issue. Can you try if manually trusting my key helps?

```
sudo pacman-key --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8
sudo pacman-key --lsign-key A44C644D792767CED7941AFEABB2075D5F310CF8
```

**Comment by jakubbortlik** [comment]
> That seems to be a completely different issue. Can you try if manually trusting my key helps?
> 
> ```
> sudo pacman-key --recv-keys A44C644D792767CED7941AFEABB2075D5F310CF8
> sudo pacman-key --lsign-key A44C644D792767CED7941AFEABB2075D5F310CF8
> ```
This solves my issue. Thank you!

Actually, I've tried this before (found the instructions elsewhere on the Web) but it didn't help because I ran it *before* running `sudo rm -f /var/lib/pacman/sync/manjaro-sway.db.sig`. Trusting your keys *after* purging the signature was the right way to do it.

**Comment by boredland** [comment]
> ### Why ?

While I can read and write French to some extent, let's please keep discussions mono lingual!

Your output doesn't look like something is wrong there, but like you installed greetd from our. If it works, there is nothing to worry about, we will catch up eventually.

**Comment by boredland** [comment]
> it's a fresh install, less 4 weeks max. I don't remember install greetd from aur.

Like is said: same error, different reasons. `greetd*` is in our repo in a slightly older version compared to manjaro-extra. You probably disabled our repo for a while for obvious reasons and then got the newer version, yielding that error. For `swayr` I guess you installed it from AUR, for example because you enabled "updates from AUR" in `pamac`.

**Comment by boredland** [comment]
yes, it is older then on aur. as already mentioned. but will fix both, greetd (pulling from our repo) and swayr (updating in our repo) soon.
