### ISSUE TITLE
🐛 timeshift-launcher is not working in fresh install

### ISSUE THREAD

**Issue by hyperion-ak** [manjaro-sway/manjaro-sway#647]
### branch

stable

### Architecture

x86_64

### Description

In a fresh install timeshift-launcher fails to open timeshift due to the missing optional package xorg-xhost.

### Reproduction steps

```bash
- New install of manjaro-sway
- Run timeshift-launcher
- Timeshift is not starting

- Solution: install missing optional deps xorg-xhost
```

**Comment by boredland** [comment]
Bust isn't the bug then, that Timeshift launcher has implicit dependencies that should be explicit? Or are those tools something that should always be installed?

**Comment by boredland** [comment]
Bust isn't the bug then, that Timeshift launcher has implicit dependencies that should be explicit? Or are those tools something that should always be installed?

**Comment by hyperion-ak** [comment]
xorg-host is required for authorization on Wayland. It should be an explicit dependency for timeshift in sway

**Comment by boredland** [comment]
I tried adding a [quick and dirty](https://github.com/manjaro-sway/desktop-settings/commit/bd6cd5e4256d944069a1d956346daa66487e5132) script for pkexec to work on manjaro sway. Not sure if s a great idea and not sure what to do about theming. Would you like to give it a try? It should land in `manjaro-sway-settings-git` soon.

**Comment by boredland** [comment]
I think my current version of that script works just fine. Would be great to hear, if this fixes the problem for you.

**Comment by hyperion-ak** [comment]
Hi boredland, thanks for the quick response. The fix solves the problem here as well. Thank you very much!
