### ISSUE TITLE
🐛 New install of manjaro sway is not including dex

### ISSUE THREAD

**Issue by hyperion-ak** [manjaro-sway/manjaro-sway#648]
### branch

stable

### Architecture

x86_64

### Description

Hi, I noticed that dex is used in /etc/sway/definitions:

`# autostarts
set $autostart_dex '[ -x "$(command -v dex)" ] && gdbus wait --session org.kde.StatusNotifierWatcher && dex --autostart'`

However, on my new Manjaro Sway installation I had to explicitly install the dex package as it was not present from the start.

Because dex is not installed, nm-applet is not starting. At the moment I am not sure if this affects any other functionalities.

### Reproduction steps

```bash
- Fresh manjaro sway install
- dex package is not installed
```

**Comment by boredland** [comment]
@all-contributors please add @hyperion-ak for fixing and reporting bugs
