### ISSUE TITLE
Why replace waybar config with the template?

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#65]
Hi, can you tell me why you have this in the 96-generate-waybar-config.conf 

    # waybar config changes will only be respected every other time

    'sleep 0.5 && cat $HOME/.config/waybar/config.template | sh /usr/share/sway/scripts/jsonreplace.sh .position $waybar_position >$HOME/.config/waybar/config'

With this code in the waybar will not load when I try and turn the num lock on by default when I add the code anywhere in the home config.  The code I am using to turn the num lock on is:
`input * xkb_numlock enabled
` 
But works great when I comment out the sleep section.

**Comment by boredland** [comment]
hi! this code is no longer present: https://github.com/Manjaro-Sway/desktop-settings/blob/sway/community/sway/etc/sway/config.d/96-waybar-config.conf

can you try to update the desktop-settings package from the manjao-sway repo?

**Comment by boredland** [comment]
It may be, that you could just have to remove `/etc/sway/config.d/96-generate-waybar-config.conf`

**Comment by Mathew-D** [comment]
This might have something to do with my settings not being up to date.  
warning: manjaro-sway-settings: local (4.3.2-5) is newer than community (1.0.0-1)
 there is nothing to do

**Comment by boredland** [comment]
Did you try `sudo pacman -Syyu manjaro-sway/manjaro-desktop`?

**Comment by boredland** [comment]
> This might have something to do with my settings not being up to date.  
> warning: manjaro-sway-settings: local (4.3.2-5) is newer than community (1.0.0-1)
>  there is nothing to do

This is because we're not an official community distro and did never update the package in the community repo. Which we definitely should.

**Comment by Mathew-D** [comment]
Also when I updated the config, the home definitions file was called "defintions"  so none of it worked until I renamed the file.

**Comment by Mathew-D** [comment]
Another change in the new config:  ~/.config/waybar/config
`    "position": "bottom",`
That overrides the $waybar_position setting in the definitions files.

**Comment by boredland** [comment]
yeah, that really is a problem. when we change things in the skeleton, those changes are not reflected in your home dir. this is how skeletons work and a problem across all distributions.
you can do that manually by copying the dotfiles from ` /etc/skel/.config` (waybar, sway) over the `.config` dir in your home directory. sorry for the inconveniences... this is basically the reason I tried to keep so much configuration in `/etc/sway` - so I can update stuff without issues like this.
