### ISSUE TITLE
💡 Sway-idle configuration

### ISSUE THREAD

**Issue by dinkocar** [manjaro-sway/manjaro-sway#651]
### Summary

Configure swayidle for baterry and AC. Below is my example of separate suspend configuration for battery, and AC. I like having long suspend period when my laptop is on AC. Also, there is no need to save current brightness in a file when light command supports saving it with light -O and the recalling with light -I. My example also has support for keyboard light "sysfs/leds/rgb:kbd_backligh", which is probably specific for my laptop, so it should not be used. Another thing is using acpi command to check if battery is discharging, so dependency on acpi package should be used, or something alternative (maybe inxi). Also, calling "dpms on" in "after resume", not before suspend, avoids screen being turned on before suspending, so it looks more "professional". I didn't see the need to call swaylock in "before-sleep", so I have removed that, as it is already locked when going to sleep (it stays locked when screen is turned on).
I have tried to reproduce power behavior from Gnome with this config, and I think it is close to that now :)

### Drawbacks

I don't think there are any.

### Implementation idea

```
set $idle_timeout 240
set $locking_timeout 300
set $screen_timeout 600
set $sleep_timeout_bat 900
set $sleep_timeout_ac 10800
set $sleep_delay 2

set $swayidle swayidle -w \
    timeout $idle_timeout 'light -O && light -S 10' \
    resume 'light -I' \
    timeout $locking_timeout 'exec $locking' \
    timeout $screen_timeout 'light -s sysfs/leds/rgb:kbd_backlight -O && light -s sysfs/leds/rgb:kbd_backlight -S 0 && swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on" && light -s sysfs/leds/rgb:kbd_backlight -I' \
    timeout $sleep_timeout_bat '[ "$(acpi -b | grep Discharging)" != "" ] && systemctl suspend' \
    timeout $sleep_timeout_ac '[ "$(acpi -b | grep Discharging)" = "" ] && systemctl suspend' \
    before-sleep 'playerctl pause' \
    after-resume 'swaymsg "output * dpms on" && light -I && light -s sysfs/leds/rgb:kbd_backlight -I'
```

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
ok, I think this would make sense. let's add this to the -git package and give it a try, shall we?
