### ISSUE TITLE
💡 Waybar features from CLI?

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#654]
### Summary

How would I go about things like enabling do not disturb or disabling sleep from the CLI, which I usually do from the waybar buttons?
Sometimes the waybar mysteriously vanishes, or I simply prefer not to use the mouse.

### Drawbacks

-

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I think we have to talk about the items individually, as most of them already are command line tools:

- [ ] rofi
- [ ] workspace switcher
- [ ] language switcher
- [ ] open github issues (`gh cli`)
- [ ] clipboard (`clipboard`)
- [ ] zeit (`zeit`)
- [ ] cpu (`htop`)
- [ ] temperature (`sensors`)
- [ ] memory (`htop`)
- [ ] battery
- [ ] network (`nmtui`)
- [ ] bluetooth (`bluetuith`)
- [ ] playerctl (`playerctl`)
- [ ] idle_inhibitor
- [ ] dnd
- [ ] pulseaudio (`pulseaudio`)
- [ ] backlight (`light`)
- [ ] adaptive light (`wluma`)
- [ ] sunset (`wlsunset`)
- [ ] pacman (`yay`,`pacman`,`pamac`)

**Comment by xeruf** [comment]
I guess the above list should be part of the documentation, makes it much easier to apply customization

**Comment by boredland** [comment]
Feel free to contribute ;-)
