### ISSUE TITLE
🐛 foot not starting

### ISSUE THREAD

**Issue by Mathew-D** [manjaro-sway/manjaro-sway#658]
### branch

stable

### Architecture

x86_64

### Description

After the last upgrade today in the testing breach  the foot daemon doesn't start.

### Reproduction steps

```bash
install upgrade
```

**Comment by Mathew-D** [comment]
Well it seems you added a: include /etc/sway/autostart to the config file which now overrides all the definitions.d i set in the home folder for:
$mako
$cliphist_store
$cliphist_watch

**Comment by boredland** [comment]
But shouldn't you be able to move them to config and be fine?

**Comment by Mathew-D** [comment]
after: include /etc/sway/autostart
there is no spot to override before the daemons are started in 
include /etc/sway/config.d/*
as you don't ready any other user configs until after the daemons are started with:
include $HOME/.config/sway/config.d/*.conf

**Comment by Mathew-D** [comment]
right now I am looking at adding a:
include $HOME/.config/sway/autostart_override
to the config file 
right after the include /etc/sway/autostart
so I can override those settings before it starts them

**Comment by Mathew-D** [comment]
I added the include $HOME/.config/sway/autostart_override to my config file so I can override those daemons and that seems to work for now

**Comment by boredland** [comment]
Hm, but I'd say there should be a "convention" for this. I honestly only added this to untangle https://github.com/manjaro-sway/manjaro-sway/issues/651. I'd be in favor of adding:

```
include $HOME/.config/sway/autostart_override.conf
```

to skel and a empty `$HOME/.config/sway/autostart_override.conf.example` that explains how to use it. Wdyt?

**Comment by Mathew-D** [comment]
That would do the trick but what would happen if we just switched:
include /etc/sway/config.d/*
and 
include $HOME/.config/sway/config.d/*.conf 
around as that holds the file to start the daemons and it doesn't look like there is anything in that folder that says it has to be run before the users configs.  Then you could override the daemons in the config.d folder

**Comment by boredland** [comment]
Well perhaps. The past sadly has shown that switching the order of things there breaks the workflow for somebody else. Perhaps we should make a `.d` directory per import in `.config/sway` so users are in full control and all people are happy and perhaps its a bit clearer what to do where...

**Comment by Mathew-D** [comment]
Before we go there, I would look at the /etc/sway/config.d folder.  We have moved most of the files out there in the last while so it only have 5 files in it. 
50-systemd-user.conf - which not one should touch there is nothing to override in there
90-enable-theme.conf - which uses user variables to set the themes which you really want to do last anyway
98-application-defaults.conf - which is only floating window defaults
99-autostart-applications.conf - which is the file that loads the daemons which is what we need at the end

**Comment by Mathew-D** [comment]
Another option would be to move this autostart file back to the /etc/sway/config.d and move the 99-autostart-applications.conf out and set it to run after include $HOME/.config/sway/config.d/*.conf
that would let us change any of daemons settings in the $home/.config.d/ folder before then run.  So please make sure you read my PS on the post above :+1:

**Comment by boredland** [comment]
I guess the biggest problem in that other issue is that ppl wanted to override some variables, but not the command generated to start the idle-process. So we had to have a possibility to "intercept" those vars inbetween. so yeah, ensuring the autostart cmds run last while their cmds are still overridable is the issue...

**Comment by Mathew-D** [comment]
the autostart file don't run the commands.. It only set the variables.  The 99-autostart-applications.conf starts all the commands with those variables.

**Comment by boredland** [comment]
yes, thus we need a way to include something after the autostarts file.

**Comment by boredland** [comment]
I think we should go back

**Comment by boredland** [comment]
@all-contributors please add @Mathew-D for reporting a bug
