### ISSUE TITLE
💡 file usage in script folder

### ISSUE THREAD

**Issue by Mathew-D** [manjaro-sway/manjaro-sway#659]
### Summary

There are a few scripts in the script folder that I can't seem to find were they are used.  I have checked all the sway config file I can find in both ~/.config/sway and /etc/sway/ and the waybar config in both ~/.config/waybar and /usr/share/sway/templates/waybar.  Can anyone tell me where they are used?

The names are:
autoname-workspaces.py 
inactive-windows-transparency.py 
sbdp.py

### Drawbacks

If we dont need the files why keep them.

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
> sbdp.py

is being used to generate the help text

for the other two, they are packaged by upstream into the sway package:

```
$ pacman -Qo /usr/share/sway/scripts/autoname-workspaces.py
/usr/share/sway/scripts/autoname-workspaces.py is owned by sway 1:1.8.1-4
$ pacman -Qo /usr/share/sway/scripts/inactive-windows-transparency.py
/usr/share/sway/scripts/inactive-windows-transparency.py is owned by sway 1:1.8.1-4
```
