### ISSUE TITLE
Theming without overwriting config files

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#66]
Instead of replacing the whole mako config file in ~/.config/mako/config each time to apply the theme couldn't you do the following:

`
sed -e '/border-color/c border-color=ACCENT_COLOR' -e '/text-color/c text-color=TEXT_COLOR' -e '/font/c font=TERM_FONT' -e '/background-color/c background-color=BACKGROUND_COLOR' $HOME/.config/mako/config  | sed -e $theme_template_script > $HOME/.config/mako/config'
`

That way if someone wants to change mako setup they don't have to go looking for the template as the only thing I believe you wanted the 92-enable-mako-theme to do was change the color to match the currently selected theme.

This could also be done for the other theming that is currently replacing config files.  This way you limit having to replacing users config files if they have customized it as you are only changing colors each time.

The one thing you would have to do is make sure all the config files are created the first time sway is installed or run an if statement to see if the file exist and make it if it doesn't.

**Comment by Mathew-D** [comment]
I got this working and put in a pull request.  Let me know what you think.
https://github.com/Manjaro-Sway/desktop-settings/pull/7

**Comment by boredland** [comment]
I think that was a direct copy from the manjaro arm edition - I like your solution more - thanks!
