### ISSUE TITLE
💡 consider laptop_mode_tools

### ISSUE THREAD

**Issue by l-j-g** [manjaro-sway/manjaro-sway#660]
### Summary

I just same across this : [laptop mode tools](https://wiki.archlinux.org/title/Laptop_Mode_Tools)

it seems to be a (mostly) zero config suite for laptop power-management. maybe we should include in the default packages (afaik it isnt already?) 

### Drawbacks

should only be enabled for laptops and im not sure how we would do that

### Implementation idea

add to packages / and or installer

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
looks nice. we could check if a battery device exists for example. or a lid.

**Comment by boredland** [comment]
Added the package to the repo.

**Comment by boredland** [comment]
I think this just looks like it would work fine with the defaults and we could just enable the system unit by default on new builds. Despite the name it is said to work just well for non-laptops.

**Comment by boredland** [comment]
added the tool to the iso, along with two dependencies so the UI works. I think we should add a little section about this to our FAQ. Would you mind contributing that @l-j-g ?

eitherway, @all-contributors please add @l-j-g for giving us a great idea.

**Comment by l-j-g** [comment]
Thank you guys, i will raise a PR to revise the FAQ over the weekend
