### ISSUE TITLE
Update db

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#67]
Hi, is there anyway we can update the main db on manjaro as there are a few version different on the manjaro-sway db.  Or you should move the manjaro-sway section above the community in pacman.conf so people can stay up to date with the changes.

warning: autotiling: local (1.4-1) is newer than community (1.2-1)
warning: flashfocus: local (2.2.2-2) is newer than community (2.2.2-1)
warning: greetd: local (0.7.0-2) is newer than community (0.7.0-1)
warning: greetd-tuigreet: local (0.2.0-2) is newer than community (0.2.0-1)
warning: manjaro-sway-settings: local (5.1.3-6) is newer than community (1.0.0-1)
warning: nerd-fonts-roboto-mono: local (2.1.0-3) is newer than community (2.1.0-1)
warning: oh-my-zsh: local (r5967.efcbd9f34-1) is newer than community (r5951.86f805280-1)
warning: sbdp: local (1.0.0-4) is newer than community (1.0.0-1)
warning: ttf-material-design-icons-webfont: local (5.8.55-2) is newer than community (5.8.55-1)
warning: wlogout: local (1.1.1-4) is newer than community (1.1.1-3)

**Comment by Mathew-D** [comment]
Also I know I have said this yet but you guys are doing great with the version and I really enjoy it.  If there is anything I can do to help let me know.

**Comment by boredland** [comment]
Hi! In fact I am already working on

1. reducing the amount of packages in our repo
2. Automatically aligning the packages with the community repo

I'd expect to be able to align all of that later today.

And thanks for your kind words :-)

**Comment by boredland** [comment]
> Or you should move the manjaro-sway section above the community in pacman.conf so people can stay up to date with the changes.

I'd have actually preferred that. But as I see it, this wouldn't work with buildiso out of the box. Will investigate that however.

**Comment by boredland** [comment]
Little update on this front:

There is not automated process for submitting packages to the Manjaro repos as of now. for that means that currently updates are done using a manual submission using the "box it" tooling.

For that reason I would ditch my high goals regarding Automation and draw this target picture for the near future

- [ ] sign everything in the Manjaro sway repo automatically
- [ ] add our signing key to the Manjaro Keyring
- [ ] request boxit access & upload all our packages using boxit manually

**Comment by boredland** [comment]
closing since it will be resolved alongside https://github.com/Manjaro-Sway/manjaro-sway/issues/69
