### ISSUE TITLE
🐛 swayidle configuration broken 

### ISSUE THREAD

**Issue by pschyma** [manjaro-sway/manjaro-sway#671]
### branch

stable

### Architecture

x86_64

### Description

swayidle does not turn off screen anymore.

It seems like the keyboard LED device that is used in the sway-idle callback is not a generic one (as mentioned by @dinkocar in #651).

This results in 
```
light -s sysfs/leds/rgb:kbd_backlight -O && light -s sysfs/leds/rgb:kbd_backlight -S 0 && swaymsg "output * dpms off"
We couldn't find the specified device target at the path "sysfs/leds/rgb:kbd_backlight". Use -L to find one.
```
and thus does not turn off the screen.

### Reproduction steps

```bash
Use most recent configuration that includes the changes from #651 and wait...
```

**Comment by dinkocar** [comment]
That is correct. It is for Tuxedo keyboard, and it should be removed from default config. It was just example and users should override $swayidle for their keyboard to work.

**Comment by boredland** [comment]
Currently not on my computer, would be happy if someone could open a fix pr!

**Comment by boredland** [comment]
`manjaro-sway-settings-git` now contains a little script to enable/disable keyboard backlight that greps for the keyboard backlights through a list of devices. @pschyma could you give it a try?

**Comment by pschyma** [comment]
@boredland the script itself works, but you have typo in the name, it should be `keyboard-backlight-switch.sh`.

**Comment by boredland** [comment]
Oh, good catch.

**Comment by boredland** [comment]
@all-contributors please add @pschyma and @dinkocar for fixing a bug
