### ISSUE TITLE
💡 Theme-browser

### ISSUE THREAD

**Issue by Mathew-D** [manjaro-sway/manjaro-sway#672]
### Summary

I was playing around with chatGPT and created a python program that allows use to browser the theme.conf files so you can see 
what they are and I wanted to share. Just change take the .txt off the file as this was the only way it would let me upload it.
[theme_browser.py.txt](https://github.com/manjaro-sway/manjaro-sway/files/13834209/theme_browser.py.txt)

### Drawbacks

none

### Implementation idea

import tkinter as tk
from pathlib import Path

class ThemeBrowser:
    def __init__(self, root):
        self.root = root
        self.root.title("Theme Browser")
        self.theme_folder = "/usr/share/sway/themes"  # Replace with the actual path to your themes folder

        self.theme_files = [file for file in Path(self.theme_folder).rglob('theme.conf')]

        self.current_theme_index = 0

        self.load_theme()

        # Create GUI components
        self.label = tk.Label(root, text=f"Theme Browser - {self.get_folder_name()}", font=("Helvetica", 16))
        self.label.pack(pady=10)

        # Create frames for color labels and variable labels
        main_frame = tk.Frame(root)
        main_frame.pack()

        color_frame = tk.Frame(main_frame)
        color_frame.pack(side=tk.LEFT)

        variable_frame = tk.Frame(main_frame)
        variable_frame.pack(side=tk.LEFT)

        # Color labels
        self.color_labels = []
        color_names = ["Background", "Text", "Selection", "Accent"]
        for i, name in enumerate(color_names):  # Include "Background" color
            label = tk.Label(color_frame, text=f"{name} Color", padx=10, pady=5, bg=self.colors[i], fg="white")
            label.pack(anchor="w")
            self.color_labels.append(label)

        for i in range(16):
            color_label = tk.Label(color_frame, text=f"Color {i}", padx=10, pady=5, bg=self.color_set[i], fg="white")
            color_label.pack(anchor="w")
            self.color_labels.append(color_label)

        # Variable labels
        self.variable_labels = []
        self.variable_names = [
            "$gtk-theme", "$icon-theme", "$cursor-theme", "$gui-font",
            "$term-font", "$gtk-color-scheme", "$kvantum-theme", "$background-color"
        ]
        for i, name in enumerate(self.variable_names):
            value = self.variables[i] if i < len(self.variables) else "N/A"
            label = tk.Label(variable_frame, text=f"{name}:", padx=10, pady=5, wraplength=150, anchor="e")
            label.pack(anchor="w")

            # Display variable name beside its value
            value_label = tk.Label(variable_frame, text=f"{value}  ", padx=10, pady=5, wraplength=150, anchor="w")
            value_label.pack(anchor="w")

            self.variable_labels.extend([label, value_label])

        self.prev_button = tk.Button(root, text="Previous", command=self.prev_theme)
        self.prev_button.pack(side="left", padx=5)

        self.next_button = tk.Button(root, text="Next", command=self.next_theme)
        self.next_button.pack(side="right", padx=5)

        # Center the information on the screen
        screen_width = root.winfo_screenwidth()
        screen_height = root.winfo_screenheight()
        root.geometry(f"{screen_width}x{screen_height}+{int((screen_width - root.winfo_reqwidth()) / 2)}+{int((screen_height - root.winfo_reqheight()) / 2)}")

        self.update_display()

    def load_theme(self):
        theme_file = self.theme_files[self.current_theme_index]
        with open(theme_file, 'r') as file:
            theme_content = file.readlines()

        # Define keywords to look for in the theme file
        color_keywords = ["$background-color", "$text-color", "$selection-color", "$accent-color"]
        self.colors = []

        for keyword in color_keywords:
            color_value = None
            for line in theme_content:
                if keyword in line:
                    color_value = line.split()[2]
                    if color_value.startswith('$'):
                        # If color value is a variable, resolve it
                        color_value = self.resolve_variable(color_value, theme_content)
                    break

            if color_value is not None:
                self.colors.append(color_value)
            else:
                # Handle the case where the keyword is not found in the theme file
                self.colors.append("#000000")  # Default to black

        # Extract and display set $color values, excluding $background
        self.color_set = [line.split()[2] for line in theme_content if line.startswith("set $color") and "$background" not in line]

        # Extract and display additional variables, excluding $background
        variable_keywords = [
            "$gtk-theme", "$icon-theme", "$cursor-theme", "$gui-font",
            "$term-font", "$gtk-color-scheme", "$kvantum-theme", "$background-color"
        ]
        self.variables = []

        for keyword in variable_keywords:
            value = None
            for line in theme_content:
                if line.startswith(f"set {keyword}"):
                    value = line.split(maxsplit=2)[2]
                    if value.startswith('$'):
                        # If variable value is a variable, resolve it recursively
                        value = self.resolve_variable(value, theme_content)
                    break

            if value is not None:
                self.variables.append(value)
            else:
                # Handle the case where the keyword is not found in the theme file
                self.variables.append("N/A")

    def resolve_variable(self, variable, theme_content):
        for line in theme_content:
            if line.startswith(f"set {variable}"):
                value = line.split(maxsplit=2)[2].strip()
                if value.startswith('$'):
                    # If variable value is a variable, resolve it recursively
                    value = self.resolve_variable(value, theme_content)
                elif value.startswith('#'):
                    # If the value is a hexadecimal color code, use it directly
                    return value
                elif value.startswith('"') and value.endswith('"'):
                    # If the value is a quoted string, remove the quotes
                    return value[1:-1]
                return value
        return variable  # Return the variable itself if not found

    def get_folder_name(self):
        return Path(self.theme_files[self.current_theme_index]).parent.name

    def update_display(self):
        self.label.config(text=f"Theme Browser - {self.get_folder_name()}")

        for i in range(4):  # Include the "Background" color
            self.color_labels[i].config(bg=self.colors[i])

        for i in range(16):
            self.color_labels[i + 4].config(bg=self.color_set[i])

        for i, name in enumerate(self.variable_names):
            value = self.variables[i] if i < len(self.variables) else "N/A"
            self.variable_labels[i * 2 + 1].config(text=f"{value}  ")

    def prev_theme(self):
        self.current_theme_index = (self.current_theme_index - 1) % len(self.theme_files)
        self.load_theme()
        self.update_display()

    def next_theme(self):
        self.current_theme_index = (self.current_theme_index + 1) % len(self.theme_files)
        self.load_theme()
        self.update_display()

if __name__ == "__main__":
    root = tk.Tk()
    app = ThemeBrowser(root)
    root.mainloop()

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
Interesting idea!

**Comment by boredland** [comment]
We also could just not exit the theme picker after choosing a theme.
