### ISSUE TITLE
🐛 no background image in live session or after fresh install

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#679]
### branch

stable

### Architecture

x86_64

### Description

The current live image [manjaro-sway-22.1.2-240114-linux61.iso](https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240114-linux61.iso) does not display any background image, even though `$HOME/.config/sway/generated_background.svg` does exist.

After a fresh install from that live image there is still no background image.

Updating manjaro-sway-settings does not help (and the image should already contain the latest version 16.12.0-5, anyway).

Overriding `$background` with a custom image, as described in [the support document](https://github.com/Manjaro-Sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-change-the-wallpaperbackground-image) also does not show any background - neither in the live session nor in the installed version.

### Reproduction steps

```bash
1. start up live session [manjaro-sway-22.1.2-240114-linux61.iso](https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240114-linux61.iso)
```

**Comment by hnsylzg** [comment]
Need to install waybg

**Comment by boredland** [comment]
I may have removed that by accident. Will check later...

**Comment by boredland** [comment]
next image should have it again, made it dependency of the desktop-settings package.

**Comment by boredland** [comment]
yay:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/7363b4c2-a9b8-4979-bb0c-63903946d503)
