### ISSUE TITLE
🐛 manjaro-sway-settings post update instructions break waybar and gtk theme

### ISSUE THREAD

**Issue by heapifyman** [Manjaro-Sway/manjaro-sway#680]
### branch

testing

### Architecture

x86_64

### Description

The following instructions are displayed after updating `manjaro-sway-settings`:

> in order to update your user configuration, run: skel
> in order to apply your user configuration, run: swaymsg reload

After I do that the theme seems to be broken. This is most visible in the waybar, but apps like firefox are also affected.

Strangely, I have to reboot the machine to "fix" the theme. It is not enough to just logout and login again.

This also happens in the current live image [manjaro-sway-22.1.2-240114-linux61.iso](https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240114-linux61.iso)

### Reproduction steps

```bash
1. Start live image [manjaro-sway-22.1.2-240114-linux61.iso](https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240114-linux61.iso)
2. Open foot
3. Run `skel`
4. Run `swaymsg reload`
```

### Screenshots

Some screenshots after running `swaymsg reload`

waybar:

![waybar](https://github.com/manjaro-sway/manjaro-sway/assets/274236/a2e12dd8-95a0-46ab-b60b-82de5a893e9e)

timeshift:

![timeshift](https://github.com/manjaro-sway/manjaro-sway/assets/274236/dd7e0ed0-38e1-45dc-a1dd-6357b725b5d4)

remmina:

![remmina](https://github.com/manjaro-sway/manjaro-sway/assets/274236/744555bc-738d-471b-b84a-5b59da3a659f)

**Comment by boredland** [comment]
I can reproduce this, but I don't fully understand why that happens. Perhaps something is still in `exec` not `exec_always`, but on first sight, it looks fine. Does the same happen for you if you use the theme-switcher (`manjaro-sway-theme`)?

That being said: you don't have to always do this all the time. I try to keep changes that require `skel` to a minimum.

**Comment by boredland** [comment]
Funny enough: running `manjaro-sway-theme` after `skel` seems to fix it again. So we probably should take at look at what the theme-script odes that `swaymsg reload` alone doesn't.

**Comment by l-j-g** [comment]
usually i can fix this by reloading the sway configuration a few times and after a few minutes... it get fixed.. agree it is a mystery

**Comment by boredland** [comment]
For me this currently "just works" and I can recall if there was anything on our side that could have fixed it. Could one of you give it a try again to see if it also magically is fixed?
