### ISSUE TITLE
🐛 How to set keyboard layout for login screen?

### ISSUE THREAD

**Issue by RKCZ** [manjaro-sway/manjaro-sway#682]
### branch

stable

### Architecture

x86_64

### Description

Hi,
I am trying to set my keyboard layout to czech(qwerty) for login screen but I can't figure it out. I followed this forum thread https://forum.manjaro.org/t/how-to-change-keymap-for-login-in-sway/90296
but the login screen is still using default us layout.
I am using the default tuigreet greeter that came installed with manjaro-sway.
I am sorry if I overlooked some obvious answer in the README, but I think I looked everywhere.

### Reproduction steps

```bash
boot the system, tui greeter is showm with last logged user preselected. When I try to type password according to my wanted layout, I get an "authentication failed" message. When I type the password in "us" keyboard layout, I get logged in.
```

**Comment by hnsylzg** [comment]
https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-add-more-keyboard-layouts-to-sway

**Comment by boredland** [comment]
not 100% sure, and a bit hard to test, but does tuigreet respect the system-settings (e.g. via `manjaro-settings-manager`)?

**Comment by RKCZ** [comment]
Thank you for a suggestion.
I looked at tuigreet and found similar question https://github.com/apognu/tuigreet/issues/121. Based on the forum topic I linked above I thought configuring sway is enough to propagate the keyboard settings to greetd, but it seems it is not. 
I also found out that us keyboard is used by other tty consoles by default and that I can change it there with `sudo loadkeys cz`, but it is not persisted after reboot. The man page for loadkeys mentions some files, where default setting might be stored but I didn't find any of those files on my system.

**Comment by boredland** [comment]
Well, the forum link is for the `arm` edition, which basically starts sway to log in into sway 🧠, thus the sway settings may help for that. In the x86 case we use `tuigreet`, which has not relation to sway on its own. You can probably change the tty locale in `/etc/vconsole.conf`, afaik.

**Comment by RKCZ** [comment]
oh I missed that it is for ARM edition. I already tried to look into `/etc/vconsole.conf` but there was already set czech keyboard, probably by localectl. I will probably try to dig more at weekend.

**Comment by boredland** [comment]
What ever comes out of it: we should add it to the FAQ ;-)

**Comment by RKCZ** [comment]
Found it! It is really `/etc/vconsole.conf`, but I had only xkblayout set and KEYMAP variable was unset. relevant documentation from arch linux: https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration#Persistent_configuration
