### ISSUE TITLE
Document configuration peculiarities

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#690]
### Summary

- this tripped me up for months, always misplacing popups (https://github.com/manjaro-sway/manjaro-sway/issues/402) until I realized the cause: https://github.com/Lyr-7D1h/swayest_workstyle#sway-configuration and fixed it in https://github.com/xeruf/dotfiles/commit/99a13ed12ab184116a5b9bb991d7d73816b82937
- where to find waybar tools: https://github.com/manjaro-sway/manjaro-sway/issues/654

by the by, package vencord-desktop-bin (https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#recommended-tools) does not exist

### Drawbacks

-

### Implementation idea

Document them in FAQ

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
regarding your first bullet point, I am a bit unsure what to write into the readme. we already have examples for setting binds, don't we?

**Comment by boredland** [comment]
Closing this for now, feel free to add to the SUPPORT.md tho!
