### ISSUE TITLE
Waybar - pacman off by 1 

### ISSUE THREAD

**Issue by Mathew-D** [Manjaro-Sway/manjaro-sway#70]
Has anyone else noticed that when waybar shows there is a package to update that it is always 1 more then the packages there are to update?

**Comment by boredland** [comment]
This could be easily due to line feeds combined with wc.. will have a look.

**Comment by boredland** [comment]
yeah, as expected, but even on two layers:

1. dependency for `checkupdates` script missing (fakeroot) in default - so the script got executed all the time
2. `pamac checkupdates` returns a line "Your system is up-to-date" when there is no updates - resulting in "1" for `wc -l`
