### ISSUE TITLE
🐛 PCManFM could not select path anymore + Java applications freeze the system upon selecting text

### ISSUE THREAD

**Issue by m-1tZ** [manjaro-sway/manjaro-sway#701]
### branch

stable

### Architecture

x86_64

### Description

Hi guys,

sorry to bother you but I do have a system-breaking issue on my side and I am curious whether this applies to your systems as well. My system lags while using Java-based applications and also freezes the system when selecting more than 2 sentences of text within the application by mouse (when the selection is done via keyboard, everything is fine). I tested it with BurpSuite and https://github.com/skylot/jadx/wiki/jadx-gui-features-overview. Furthermore, my PCManFM can not select any text anymore (e.g. the path to a file). I feel this is related to this issue. I tested several combination with themes and Java versions, etc.

Do you know something about that or even face any similar issues?

Thank you in advance!

### Reproduction steps

```bash
1. Open Java-based app such as BurpSuite or JADX-Gui.
2. Open a view with more than 2 sentences of text and select them.

or

1. Open PCManFM
2. Try to select the path with the mouse
```

**Comment by boredland** [comment]
The qt version of pcmanfm seems to work fine, so probably this is something affecting GTK mostly. I think it affects both, gtk4 (tried with pamac) and gtk3 (pcmanfm)

**Comment by boredland** [comment]
It starts working as soon as I kill `wl-clip-persist`. Also found an issue on their side: https://github.com/Linus789/wl-clip-persist/issues/3

Will go to "regular" clipboard only, which should solve the immediate problem.
