### ISSUE TITLE
💡 Screensharing with Pipewire?

### ISSUE THREAD

**Issue by 825i** [manjaro-sway/manjaro-sway#708]
### Summary

How is screensharing with pipewire? Is it integrated into Manjaro Sway? I can't find existing packages, but maybe I am blind.

If we aren't including this in the default packages, I think we should. It would be great to have screen sharing OOTB for manjaro sway.

### Drawbacks

None that I could think of.

### Will you be able to contribute a PR for this?

- [X] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
WebRTC screensharing works out of the box, what specific things don't work?

**Comment by boredland** [comment]
No response.
