### ISSUE TITLE
🐛 kvantum manager starts after login since kvantum-theme-matcha update to 20191119-1

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#709]
### branch

testing

### Architecture

x86_64

### Description

Yesterday I got an update for kvantum-theme-matcha: `upgraded kvantum-theme-matcha (20190810-3 -> 20191119-1)`

Now kvantum manager starts after every login (or sway reload).

It appears that theme `Matcha-Dark` (which is set in `matcha-green/theme.conf`) does not exist any more. kvantum manager only finds `Matchama-Dark`.

Overriding `$kvantum-theme` with `set $kvantum-theme Matchama-Dark` seems to fix it.

Is something wrong with the kvantum-theme-matcha package or is desktop-settings just not updated yet?

### Reproduction steps

```bash
1. upgrade kvantum-theme-matcha to current release `20191119-1`
2. logout
3. login
```

**Comment by boredland** [comment]
Yes, seems the package in the manjaro gitlab is not what is in the manjaro repos. Will revert that by hand.

**Comment by boredland** [comment]
Update has been pushed, I guess its fixed?
