### ISSUE TITLE
login in virtualbox not working

### ISSUE THREAD

**Issue by TheYoctoJester** [Manjaro-Sway/manjaro-sway#71]
on build 20210707 i can't log in when the iso is booted in a generic virtualbox setting.
are the credentials in the readme still correct?

**Comment by boredland** [comment]
Without being able to try anything right now: this could be an overlap with https://github.com/Manjaro-Sway/manjaro-sway/issues/56

**Comment by TheYoctoJester** [comment]
Yup, sounds very likely. Will give it a try later to verify.

**Comment by TheYoctoJester** [comment]
So. Enabling 3d actually solves the problem of not being able to log in. However, the mouse cursor is not visible, unless some thing applies, and I don't know what exactly. In a nutshell:
- wdisplay running: visible
- wdisplay not running: invisible
But it almost certainly is something that wdisplay does in the background.

**Comment by TheYoctoJester** [comment]
seems to be https://github.com/swaywm/sway/issues/3814

**Comment by boredland** [comment]
I have been using gnome boxes / qemu since forever, would this be a viable alternative?

**Comment by TheYoctoJester** [comment]
Unfortunately not - this is actually just the test driving situation at the moment to get a feel for sway, daily driver at the moment is Windows. But I think its fair enough to call this closed. Might sense to add a note to the README, though.

**Comment by boredland** [comment]
Left a note in the readme.
