### ISSUE TITLE
🐛 Chrome reports "unsupported command line flag"

### ISSUE THREAD

**Issue by gregorbg** [manjaro-sway/manjaro-sway#711]
### branch

stable

### Architecture

x86_64

### Description

When launching Chrome, there is a popup at the top of the screen right below the URL bar that reads
"You are using an unsupported command line flag `--enable-unsafe-webgpu`. This affects stability and security."

It doesn't actually have any noticeable impact on my browsing experience, apart from the fact that the banner is so large that it obstructs the view.

### Reproduction steps

```bash
Open google-chrome-stable.
```

### Screenshots

(sorry for localized screenshot in German. Translation is under "Description" above.)
![image](https://github.com/manjaro-sway/manjaro-sway/assets/6136469/858dc814-03d1-40aa-af10-e1af6217823e)

**Comment by gregorbg** [comment]
The flag is defined here: https://github.com/manjaro-sway/desktop-settings/blob/4a5a1037d2bb61e49e423252397f65e7308c9a30/community/sway/etc/skel/.config/chrome-flags.conf

I would be happy to submit a PR removing it, if that helps.

**Comment by gregorbg** [comment]
Thanks for the prompt PR, but the issue persists.
Very recent I installed v16.19.2 and ran `skel`. The flag is back again and I had to remove it manually with `nano ~/.config/chrome-flags.conf`

**Comment by boredland** [comment]
Then something is off. The desktop-settings don't contain that flag anymore for chrome-flags:
https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/skel/.config/chrome-flags.conf
