### ISSUE TITLE
power management is dysfunctional on Acer Swift 3

### ISSUE THREAD

**Issue by davidthewatson** [manjaro-sway/manjaro-sway#715]
### branch

stable

### Architecture

x86_64

### Description

I installed manjaro sway from USB a few days ago. Everything seems great as it was when I ran manjaro sway last year,  except power management now seems broken on my acer swift 3 with Ryzen CPU. 

The behavior I've observed is that I boot, login, do some work, walk away to get coffee, and when I come back the machine has shut down completely and worse, when it boots, all my work is gone and we're in a freshly booted clean state. 

I've run laptop mode tools (https://github.com/manjaro-sway/manjaro-sway/issues/660) and I see that there are some things that are enabled by default, but what can I disable to turn off this over-reaching power management that's killing my beloved manjaro sway when I walk away? Do I need to do the ACPI switches at boot or something similar? I've not seen this particular problem on any modern linux on this box before, i.e. fedora, ubuntu, and even other arch-derivatives. I suspect it may be the Ryzen chipset, but that's purely speculative.

Thanks!

### Reproduction steps

```bash
Install manjaro sway on acer swift 3 with Ryzen processor. Boot, login, wait for power management to take over.
```

**Comment by davidthewatson** [comment]
Overnight, the behavior changed.

Root cause remains a mystery but it seems better now. I had done `pamac update` and `sudo pacman -Syyu manjaro-sway-settings` yesterday so it's difficult to be sure which may have tweaked the behavior for sure, but you can close this as it seems fine now. Thanks!

**Comment by davidthewatson** [comment]
I was premature in closing this issue. 

Worked on the box this morning, left it sit to make coffee and it powere off completely when I was away.  When it came back after a key press, all the pre-reboot state was gone, i.e. terminals, tmux, firefox, etc.

@boredland Do you want me to actually remove Laptop-Mode-Tools? I didn't believe that was causal here. Thought it was just GUI displaying the state, shouldn't have any impact on the state without interaction. Correct?

**Comment by boredland** [comment]
I think there are just two tools influencing power-management: poweralertd and laptop-mode-tools. Both have been installed for quite some time by default. My bets are on laptop-mode-tools.

**Comment by davidthewatson** [comment]
Thanks for your response.

I tested this by removing laptop-mode-tools as you suggested and rebooting. Same problem. Walked away for a while, system powered off, all state was gone upon touch of a key after it booted. That leaves poweralertd from your list. In the meantime, I did the following:

```
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target                                      
Created symlink /etc/systemd/system/sleep.target → /dev/null.
Created symlink /etc/systemd/system/suspend.target → /dev/null.
Created symlink /etc/systemd/system/hibernate.target → /dev/null.
Created symlink /etc/systemd/system/hybrid-sleep.target → /dev/null.
```

so that I could function without issue. Happy to pursue any further debugging. I'm just not sure where to go from here since I understand poweralertd may be the source of the eventing but I don't have much more mental model than that outside the quick workaround I did here.

**Comment by boredland** [comment]
> Happy to pursue any further debugging. I'm just not sure where to go from here

Sadly: me neither. Just pointers coming to mind for tools, that mingle with the power management:

- [swayidle](https://github.com/manjaro-sway/desktop-settings/blob/64314b9efc17bf365f5bbc771a9b6efad3ddcaa0/community/sway/etc/sway/autostart#L26)
- [idlehack](https://github.com/manjaro-sway/desktop-settings/blob/64314b9efc17bf365f5bbc771a9b6efad3ddcaa0/community/sway/etc/sway/autostart#L25)

I have no particular idea how they might interfere.

**Comment by davidthewatson** [comment]
Thanks for the update.

Let me know if you'd like me to document the workaround:

    sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target                                      
    Created symlink /etc/systemd/system/sleep.target → /dev/null.
    Created symlink /etc/systemd/system/suspend.target → /dev/null.
    Created symlink /etc/systemd/system/hibernate.target → /dev/null.
    Created symlink /etc/systemd/system/hybrid-sleep.target → /dev/null.

In the FAQ. 

My system has functioned great with this in place for several days now. 

I've seen no issues with power since masking sleep, suspend, hibernate, and hybrid-sleep.

**Comment by boredland** [comment]
I think having this issue and ppl finding it in case of a similarly weird issue is enough.
