### ISSUE TITLE
🐛 Weather shown in Fahrenheit even though I'm using a none US locale

### ISSUE THREAD

**Issue by TheSimpleZ** [manjaro-sway/manjaro-sway#717]
### branch

stable

### Architecture

x86_64

### Description

The weather is shown in Fahrenheit in the waybar. I would expect it to be Celcius according to my locale settings. 

### Reproduction steps

```bash
Install Manjaro-sway. Choose language en_US and locale sv_SE.
```

### Screenshots

![image](https://github.com/manjaro-sway/manjaro-sway/assets/2884929/b73abd52-c463-45fa-a71b-69b21764d2bb)

**Comment by boredland** [comment]
That is a regression from https://github.com/manjaro-sway/desktop-settings/pull/188, I think.

**Comment by boredland** [comment]
Ya, think I got it. Would you mind switching to `manjaro-sway-settings-git` to give it a try?

**Comment by TheSimpleZ** [comment]
Yeah, seems to be working now. Thanks for the quick response!

**Comment by boredland** [comment]
Cool, will make a release!
