### ISSUE TITLE
🐛 Scrolling with touchpad does not work in the default file manager

### ISSUE THREAD

**Issue by TheSimpleZ** [manjaro-sway/manjaro-sway#718]
### branch

stable

### Architecture

x86_64

### Description

I can't use my touchpad to scroll in the default file manager (PCManFM). Dragging the scrollbar works fine. Using the touchpad to scroll in any other app works fine. 

I don't know what logs would be relevant here, so please tell me what you need to debug this and I'll gladly update the issue.

### Reproduction steps

```bash
Clean install of manjaro-sway. Open File Manager. Attempt a 2 finger scroll.
```

**Comment by boredland** [comment]
That seems to be an upstream issue in pcmanfm-gtk3: https://sourceforge.net/p/pcmanfm/bugs/1131/

**Comment by boredland** [comment]
Alternatively we could switch to the qt-version of pcmanfm. Sadly, the qt6 version is not yet in the repos and I wouldn't want to bake in support for qt5 anymore.

**Comment by TheSimpleZ** [comment]
Alright, I've installed Thunar for now and it works perfectly fine.

**Comment by boredland** [comment]
I think now we could switch to `pcmanfm-qt`. Looking at the non-maintenance done at the regular `pcmanfm`, switching might be a good idea anyway.

**Comment by boredland** [comment]
Please install `pcmanfm-qt` after the next update. IMO it should fix the issue at hand.
