### ISSUE TITLE
🐛 Wifi icon appears twice in waybar

### ISSUE THREAD

**Issue by TheSimpleZ** [manjaro-sway/manjaro-sway#719]
### branch

stable

### Architecture

x86_64

### Description

There are 2 slightly different wifi icons in the waybar. When clicked, one opens a context menu, the other opens a terminal window where wifi settings can be changed.

### Reproduction steps

```bash
Clean install of manjaro-sway. This appears even during the installation process.
```

### Screenshots

![image](https://github.com/manjaro-sway/manjaro-sway/assets/2884929/bc968afa-f213-4666-9c73-5288a7e79c1b)

**Comment by boredland** [comment]
I think the one on the right isn't waybar, but somehow the nm-applet sneaks around being masked.

**Comment by TheSimpleZ** [comment]
Probably... I don't know which one of them you'd like to have there by default, but I managed to get rid of the left one by creating a file called `~/.config/waybar` with this content:
```json
{
  "include": [
    "/usr/share/sway/templates/waybar/config.jsonc"
  ],
  "modules-right": [
    // informational
    "sway/language",
    "custom/github",
    "custom/clipboard",
    "custom/zeit",
    "cpu",
    "temperature",
    "memory",
    "battery",
    // connecting
    //"network", // <-- Comment out this line
    "bluetooth",
    "custom/valent",
    // media
    "custom/playerctl",
    "custom/idle_inhibitor",
    "custom/dnd",
    "pulseaudio",
    "backlight",
    // system
    "custom/adaptive-light",
    "custom/sunset",
    "custom/pacman",
    "tray",
    "clock"
  ],
}

```

**Comment by boredland** [comment]
Could you try if this is fixed in `manjaro-sway-settings-git`?

**Comment by boredland** [comment]
nevermind, it still starts the indicator.

**Comment by boredland** [comment]
please `skel` after the next update!
