### ISSUE TITLE
🐛 PCManFM's underlying file associations include *.txt -> command line text editors, which don't work on right-click, launch

### ISSUE THREAD

**Issue by davidthewatson** [manjaro-sway/manjaro-sway#723]
### branch

unstable

### Architecture

x86_64

### Description

I was looking at a directory of text files in PCManFM and right-clicked to launch a viewer, but found that none of the viewers registered by default launched. I assume this is because the listed viewers were things like vi that require a terminal. 

It occurred to me that the default association for *.txt in PCManFM would likely work more reliably if it were simply something pre-installed and lightweight, like `pango-view`.

Hence, I tried this:

`pango-view --font="monospace 20" ~/Downloads/whatever.txt`

and discovered that it worked great.

I couldn't quite tell if the pango-view dependencies were there from installation time even though I see pango in the package list, since I use other similar tools in my work stack.

Regardless, it seemed like it would improve the UI/UX to just add a simple association and script to render text in sway this way. Happy to provide a pull request with a little "where to look for linkages" help in the stack I've described here.

### Reproduction steps

```bash
0. populate a directory with text files *.txt
0. [Super-D] "File Manager"
0. Right-click any text file
0. Observe the drop-down options: helix, neovim, and vim (on my system)
0. Observe that none launch upon click; effectively a no-op given the message flow
```

**Comment by boredland** [comment]
I think pango is installed as a direct dependency of sway (used to create `modes` etc.

**Comment by boredland** [comment]
Honestly, I think there must be a bug. Opening text file using nvim/helix and the like "should" work.

**Comment by boredland** [comment]
Oh, you can set the default terminal in pcmanfm like so and everything starts working:

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/28544223-921e-4067-868c-a79bb80bf4c2)

Now we have to figure out how to set that in the profile.
