### ISSUE TITLE
🐛 Waybar module "custom/pacman" not synced across monitors

### ISSUE THREAD

**Issue by hakanyi** [manjaro-sway/manjaro-sway#724]
### branch

testing

### Architecture

x86_64

### Description

This is obv low priority, but I'd appreciate a pointer on this: Whenever I see updates signaled by the waybar pacman module, I usually update via `yay` in the terminal. At this point, I'd expect the pacman module to disappear which does not happen. 
In addition, when I manually click the module, it'd disappear on the currently active monitor, but not the other. 
Thanks! 

### Reproduction steps

```bash
See above
```

**Comment by boredland** [comment]
well, when you run it by clicking in waybar, it updates the waybar module afterwards, otherwise it is just updating on a schedule. one could let the pacman-module accept a signal, if it doesn't yet. is there a pacman hook we could configure to run after every pacman run?

**Comment by boredland** [comment]
I have an idea to at least make it more graceful and sync state.

**Comment by boredland** [comment]
in `manjaro-sway-settings-git`, waybar is signalled to update the pacman module in a pacman-hook. I am testing it myself right now, but would glad about some feedback.

**Comment by boredland** [comment]
I am quite happy without, but don't have a multi-monitor setup to test your case. I'll leave that for you to close (hopefully).
