### ISSUE TITLE
🐛 What is the preferred way to set environment variables ?

### ISSUE THREAD

**Issue by l-j-g** [manjaro-sway/manjaro-sway#725]
### branch

stable

### Architecture

x86_64

### Description

Possibly PEBKAC and not a bug:

I've struggled with this issue for a while; for some reason my profile configuration at `.config/profile.d/` does not seem to be sourced at startup. I remember this working at some point but doesn't anymore for me (could be my own configuration issue) :
 
- running skel overwrites .profile and .bashrc
- FAQ suggests profile modifications to `$HOME/.config/profile.d`
- after manually running `source ~/.profile` my alias below work, otherwise they dont
 
```
alias autotiling-rs=autotiling
alias cf='cd $HOME/.config/'
alias ls='lsd'
alias vim='nvim'
export PATH='$PATH:$HOME/.config/emacs/bin'
```

### Reproduction steps

```bash
I want to know if other people experience this issue or if its just me
```

**Comment by boredland** [comment]
I think this bug is tackled throughout https://github.com/manjaro-sway/manjaro-sway/issues/721. Can you give the current `manjaro-sway-settings-git` a try?

**Comment by boredland** [comment]
nevermind, it only works in foot, even as a login-shell, for the thing set in .profile, not in .config/profile.d

**Comment by boredland** [comment]
Tested this myself a bit more. Apparently creating an alias in `profile.d` doesn't work in foot, exporting variables works however.

**Comment by boredland** [comment]
I think the likely useful answer to your question is, if this is about foot & the zsh shell (both are the defaults):

set your alias in e.g. a file `.config/zsh/config.d/alias` and thats it. This is sourced with every new instance of zsh.
