### ISSUE TITLE
contributors

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#73]
update the list of contributors from all our repos

**Comment by boredland** [comment]
@all-contributors please add @AntonPicetti for finding a bug and writing code

**Comment by boredland** [comment]
@all-contributors please add @Mathew-D for finding bugs, having ideas and writing code

**Comment by boredland** [comment]
@all-contributors please add @xfalcox for writing code that allows us to screenshot areas using grimshot

**Comment by boredland** [comment]
@all-contributors please add @Chrysostomus for giving us tons of ideas to get started

**Comment by boredland** [comment]
@all-contributors please add @appelgriebsch for given us tons of ideas and code from the arm edition

**Comment by boredland** [comment]
added back the position since without it, it defaulted to "top". IMO the sway bar.position has no effect when using waybar.

**Comment by boredland** [comment]
thank you very much for this! the old icon script had some major downsides. would you mind just removing it entirely?

@all-contributors please add @FallenChromium for writing configurations that allow for dynamic workspace naming

**Comment by boredland** [comment]
@all-contributors please add @FallenChromium for writing code that allow for dynamic workspace naming

**Comment by boredland** [comment]
@FallenChromium fyi just for future reference as this belongs to the legwork section of https://github.com/Manjaro-Sway/desktop-settings/pull/15

**Comment by boredland** [comment]
@all-contributors please add @MuratovAS for finding and fixing a bug

**Comment by boredland** [comment]
> Also, not sure why sink_volume and source_volume are set in modes/default. Don't they belong in definitions? Happy to change that, too.

Hi! That was me thinking, that defining sth. thats being used in exactly one place in another place is strange. But since we do that everywhere else, I'd appreciate if you could move it 🎉 

@all-contributors please add @hakanyi for finding and fixing a bug in our code

**Comment by boredland** [comment]
@all-contributors please add @vncsna for fixing a bug with the default sunset being very late

**Comment by boredland** [comment]
@all-contributors please add @Zeioth for the idea to add a weather module

**Comment by boredland** [comment]
I believe that the basic support for all languages will be enough, no real need for Adobe Source Han then. As far as I understand, there is a difference in the font format between microhei and Source Han, so you may also want to check how it works in LibreOffice and other apps which use font selection interface. The other difference is that MicroHei is Sans Serif, while Adobe fonts are either Sans or Serif. That said, if MicroHei doesn't work properly in document apps, it may be worth it to add full-fledged support with Adobe Han packages, for our asian users.

**Comment by boredland** [comment]
@all-contributors please add @hakanyi for fixing a bug

**Comment by boredland** [comment]
@all-contributors please add @xeruf for maintenance

**Comment by boredland** [comment]
Oops

**Comment by boredland** [comment]
did you want me to rebase onto the current version of iso-profiles? good idea 🍡

**Comment by boredland** [comment]
> did you want me to rebase onto the current version of iso-profiles? good idea 🍡

Wdym?

**Comment by MuratovAS** [comment]
> did you want me to rebase onto the current version of iso-profiles? good idea dango

It's not very clear what you specifically want to change :)
What will change? What problems can we face?

**Comment by boredland** [comment]
I was wondering what this PR could have been about, and thought that it perhaps was about getting our iso profile on top of the others and probably fetch some changes in the area of root packages. So I rebased and don't think there were notable changes for us.

**Comment by boredland** [comment]
It was accidently opened while I was working this repo to make a stable iso, but I didn't managed to do that, could you please build a stable iso support

**Comment by boredland** [comment]
what do you mean with a "stable iso"?

**Comment by boredland** [comment]
@all-contributors please add @fraunos for writing code to support swaycwd

**Comment by boredland** [comment]
@all-contributors please add @nnuel for fixing up some documentation

**Comment by boredland** [comment]
> what do you mean with a "stable iso"?

Low ram usage and less laggy

**Comment by boredland** [comment]
I (and I suppose a lot more people) use manjaro sway on a daily basis without it being laggy or sth.

this is my machine with a heavy vscode project open, two firefoxes, a chrome window with teams, slack open:

![image](https://user-images.githubusercontent.com/4662748/149135442-24c17a9b-2863-4719-9439-57d17f495ef0.png)

According to my system info, sway itself takes like 100Mb. Waybar we tried to streamline towards lower ram usage. So without further pointers I'd say whatever problem you face is a bug on your machine. Without further information that is really hard to do. In general: Manjaro has no such things as stable releases. "Stable" refers to the usage of the stable package repository. We offer images that point to the stable package repo. There is nothing more "stable" in a rolling release distro than that. If you download a Gnome ISO for example, it will update to the latest stable repo, as soon as you run pacman.

**Comment by boredland** [comment]
Just to rule that out: are you on a nvidia card?

**Comment by boredland** [comment]
> Just to rule that out: are you on a nvidia card?

No, I am on 4GB laptop using Manjaro Cutefish

**Comment by boredland** [comment]
So.. this isn't about sway?

**Comment by boredland** [comment]
> So.. this isn't about sway?

Nope

**Comment by boredland** [comment]
@all-contributors add @aboettger for fixing a bug

**Comment by boredland** [comment]
@all-contributors please add @fraunos for fixing multiple bugs

**Comment by boredland** [comment]
@all-contributors please add @AdriandMartin for code

**Comment by boredland** [comment]
@all-contributors please add @Lyr-7D1h for writing code that makes use of upstream changes

**Comment by boredland** [comment]
@all-contributors please add @xeruf for fixing a bug

**Comment by boredland** [comment]
@all-contributors please add @ishaanbhimwal for writing code to support qt6

**Comment by boredland** [comment]
@all-contributors please add @cmeessen for fixing a bug around the tuigreet cmd

**Comment by boredland** [comment]
@all-contributors please add @varac for fixing a bug around the weather module

**Comment by boredland** [comment]
@all-contributors please add @trinitronx for writing code

**Comment by boredland** [comment]
@all-contributors please add @oxmj for writing code to improve security of the sworkstyle service

**Comment by boredland** [comment]
@all-contributors please add @crackersamdjam for writing code to fix passing long/lat to the wlsunset wrapper

**Comment by boredland** [comment]
@all-contributors please add @andrius for having the idea to add an unlimited idle-timeout and writing code to implement it

**Comment by boredland** [comment]
@all-contributors please add @varac for writing code to make the weather script more resilient

**Comment by boredland** [comment]
@all-contributors please add @trinitronx for enhancing the sway wrapper to allow passing on arguments to it

**Comment by boredland** [comment]
@all-contributors please add @trinitronx for writing code enhancing the sway wrapper to allow passing on arguments to it

**Comment by boredland** [comment]
@all-contributors please add @juleslink for implementing the nordic theme
