### ISSUE TITLE
🐛 swaymsg reload kills all foot terminals

### ISSUE THREAD

**Issue by pschyma** [manjaro-sway/manjaro-sway#732]
### branch

stable

### Architecture

x86_64

### Description

I just updated my system including manjaro-sway-settings 16.18.0-7. After merging my configuration files and reloading sway to adapt the changes, every foot terminal was killed.

### Reproduction steps

```bash
Open a foot terminal and reload sway.
```

**Comment by boredland** [comment]
Ya, this annoys me too. Not doing it would result in theme adaptions not being reflected, as the foot server wouldn't restart. Not sure which way is less annoying, but tend to agree that restarting the foot server manually would be less of a pain than the windows being closed.

**Comment by pschyma** [comment]
Another observation I just made: 
![grafik](https://github.com/manjaro-sway/manjaro-sway/assets/2489928/f677623d-d973-4d14-bfca-fba63aea139c)
foot terminal does not exit anymore since the last update.

**Comment by pschyma** [comment]
I didn't notice any theme adaption issues in foot in previous updates - maybe it's just because I don't care if there are small updates to foot (or my own customization just prevent any visible change to me). 

I only see theme issues after updates, when I start meld to review skel changes for the first time. Then the theme there is always light and after starting meld again it becomes dark again.

For me the foot issues are more annoying then any theme inconsistencies.

**Comment by boredland** [comment]
> Another observation I just made: ![grafik](https://private-user-images.githubusercontent.com/2489928/313162480-f677623d-d973-4d14-bfca-fba63aea139c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTk5OTEsIm5iZiI6MTcxMDQ5OTY5MSwicGF0aCI6Ii8yNDg5OTI4LzMxMzE2MjQ4MC1mNjc3NjIzZC1kOTczLTRkMTQtYmZjYS1mYmE2M2FlYTEzOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMTA0ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YxMGMyNzIzNjI5MTVlZDY4OTg3ZDMzZjJhMzI2MDc2MmZmNWI4NmRmOTM2NzI4ZWQ1ZTEwYzVlZjBhMTdkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nA9PmXW-zotAzFioCIBZqggH1698DMlMLkrTQTYsRVY) foot terminal does not exit anymore since the last update.

yes, that is probably due to the spawned window being a a client only. is that something we "need" to fix? I always kill them via ctrl+q..

**Comment by pschyma** [comment]
I'd prefer to have the previous behavior as from my side it's a rather surprising change that the terminal does not close when the shell exits. 

The explicit `exit` in the screenshot was just a test as I noticed that another window did not disappear after hitting `ctrl-d` (that's my usual way to exit any shell and finally terminal).

**Comment by boredland** [comment]
Seems this in fact was a tiny error on my end. Fix is on its way!

**Comment by boredland** [comment]
both problems should be solved soon, report back if the issues persist. 

https://github.com/manjaro-sway/desktop-settings/compare/16.18.0...16.19.0

**Comment by pschyma** [comment]
I've upgraded to 16.19.0 now. The terminal works now as expected, but I'm still having issues since my upgrade to 16.18.0.

I'll create another issue for this.
