### ISSUE TITLE
🐛 cannot set custom background any more by overriding $background variable

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#734]
### branch

testing

### Architecture

x86_64

### Description

According to [SUPPORT.md](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-change-the-wallpaperbackground-image) setting `$background` to a new value should set a different background image.

But since commit https://github.com/manjaro-sway/desktop-settings/commit/feaf7ee8268605cd393cff9f99d218f6210198f7 this does not seem to work anymore.

I think because `$apply_background` is set before the user defined `$background` is evaluated. So it always uses the `$background` from `/etc/sway/definitions`.

### Reproduction steps

```bash
1. Update to manjaro-sway-settings 16.19.0-7
```

**Comment by boredland** [comment]
Sorry for the inconvenience. I had to add the logic for `$apply_background`, as to my knowledge there it no way to "unset" a `output` definition - rendering tools like `swww` non working. It is always a compromise... Amended the docs to reflects that tiny extra-step.

**Comment by olivercoad** [comment]
@boredland  Just curious, what was the motivation behind that breaking change?  
Previously you could configure the background using the normal sway/i3 `output` configuration without even needing to know about special variables for `manjaro-sway`. I just think it would be good to keep things compatible with existing configuration where possible, or at least have an explaination for when there is differences.

**Comment by boredland** [comment]
Sadly sway doesn't allow to unset a `output` configuration. So 3rd party tools to configure the background can't really be used, if they don't use the sway mechanism. In particular `swww` couldn't be used.
