### ISSUE TITLE
🐛 Clifm crashes after update

### ISSUE THREAD

**Issue by theRoboxx** [manjaro-sway/manjaro-sway#735]
### branch

stable

### Architecture

x86_64

### Description

I use this terminal file manager: https://github.com/leo-arch/clifm
Since the last update it crashes and somehow doesn't have access to the path variables in foot and alacritty.
Fish and bash work as expected. The issue appeared before and after running `skel`

Version: 16.19.2-7

### Reproduction steps

```
- set /bin/clifm as shell in foot.ini
- launch foot. 
- commands like htop or ls don't get recognized and create new files.
```

**Comment by boredland** [comment]
Could you check what happens when you call the foot binary directly or via `/usr/share/sway/scripts/foot.sh`? I could imagine that this is somehow related to removing a bug that didn't properly make use of the foot server instance... (when just calling foot/the foot script, instead a new terminal window is spawned).

**Comment by theRoboxx** [comment]
> Could you check what happens when you call the foot binary directly or via `/usr/share/sway/scripts/foot.sh`? I could imagine that this is somehow related to removing a bug that didn't properly make use of the foot server instance... (when just calling foot/the foot script, instead a new terminal window is spawned).

This works without the bug

**Comment by boredland** [comment]
Hm. I installed clifm and started it from the terminal - I have $PATH and htop starts without a problem. So the maybe isn't an issue with `footclient` after all?

**Comment by theRoboxx** [comment]
> What does `ps -ef | grep foot` yield?
```
<0> $ ps -ef | grep foot
tloop        1574    1171  0 12:40 ?        00:00:00 sh /usr/share/sway/scripts/foot.sh --server=3
tloop        1577    1574  0 12:40 ?        00:00:03 foot -c /home/tloop/.config/foot/foot.ini --server=3
tloop       10373       1  0 15:34 ?        00:00:00 footclient
tloop       10453       1  0 15:34 ?        00:00:00 foot
tloop       11309   10375  0 15:55 pts/2    00:00:00 clifm -c ps -ef | grep foot
tloop       11404   10458  0 15:55 pts/3    00:00:00 bash -c ps -ef | grep foot
tloop       11406   11404  0 15:55 pts/3    00:00:00 grep foot
```
I did more troubleshooting and found out that if I run **_drun Foot (Terminal)_** in the $mod+d menu it works without problems but if I use $mod+Return or the **_drun Foot Client (Terminal)_** option the bug appears. (see screenshot below)
Did $mod+Return change in a recent settings update? 
![swappy-20240319_122406](https://github.com/manjaro-sway/manjaro-sway/assets/63428105/5ea0673c-b013-4616-a94f-90f44df91c5d)

$mod+Return opened, the bug appears: 
`tloop       10048       1  0 15:32 ?        00:00:00 footclient -D /home/tloop`

$mod+d menu and **_drun Foot (Terminal)_** works without problems:
`tloop       10792       1  3 15:40 ?        00:00:00 foot`

**Comment by boredland** [comment]
> Did $mod+Return change in a recent settings update?

Like I said earlier: yes, it now actually uses the foot-server (via footclient), not a separate instance. starting foot via rofi starts a new instance of foot - where the problem isn't present. I can't explain why tho and on my machien :tm: it just works. You could override $foot in you userspace config, if you like.

**Comment by theRoboxx** [comment]
> ```
> set $term /usr/share/sway/scripts/foot.sh
> set $term_cwd $term -D "$(swaycwd 2>/dev/null || echo $HOME)"
> ```

Thanks, that worked. :+1: 

I'm still trying to figure out what causes this issue. 
Is it intended that editing ~/.config/foot/foot.ini doesn't change behaviour of the new foot-server version?

**Comment by boredland** [comment]
> doesn't change behaviour of the new foot-server version?

You have to restart the service for changes to take effect.

**Comment by boredland** [comment]
Has this been clarified? Can this be closed?
