### ISSUE TITLE
🐛 swayrd keeps on spamming the logs with warnings

### ISSUE THREAD

**Issue by pschyma** [manjaro-sway/manjaro-sway#742]
### branch

stable

### Architecture

x86_64

### Description

I upgraded another machine to the latest manjaro sway including running `manjaro-sway-align` and `skel`. Now I see many warnings from swayrd (every 3 seconds).

This doesn't happen on other machines. The affected one is a rather pure manjaro sway one without any customizations to configs or extra programs installed. 

I wonder if there is something missing in the tools installed by default that is required by swayrd. 

### Reproduction steps

```bash
Start sway and watch the logs.
```

### Logs

```bash
Mär 23 10:03:59 endeavour swayrd[3765]: [2024-03-23T09:03:59Z WARN  swayr::daemon] Error while receiving events: failed to fill whole buffer
Mär 23 10:04:02 endeavour swayrd[3765]: [2024-03-23T09:04:02Z WARN  swayr::daemon] Resetting!
Mär 23 10:04:02 endeavour swayrd[3765]: [2024-03-23T09:04:02Z WARN  swayr::daemon] Error while receiving events: failed to fill whole buffer
Mär 23 10:04:05 endeavour swayrd[3765]: [2024-03-23T09:04:05Z WARN  swayr::daemon] Resetting!
Mär 23 10:04:05 endeavour swayrd[3765]: [2024-03-23T09:04:05Z WARN  swayr::daemon] Error while receiving events: failed to fill whole buffer
Mär 23 10:04:08 endeavour swayrd[3765]: [2024-03-23T09:04:08Z WARN  swayr::daemon] Resetting!
Mär 23 10:04:08 endeavour swayrd[3765]: [2024-03-23T09:04:08Z WARN  swayr::daemon] Error while receiving events: failed to fill whole buffer
Mär 23 10:04:11 endeavour swayrd[3765]: [2024-03-23T09:04:11Z WARN  swayr::daemon] Resetting!
Mär 23 10:04:11 endeavour swayrd[3765]: [2024-03-23T09:04:11Z WARN  swayr::daemon] Error while receiving events: failed to fill whole buffer
```

**Comment by boredland** [comment]
> This doesn't happen on other machines.

On other machines with swayr running or just in general?

**Comment by boredland** [comment]
On my machine this warning is logged only early on during systemd boot.

**Comment by pschyma** [comment]
> On other machines with swayr running or just in general?

On other machines running swayr. Restarting swayr seems to fix the warning. 

Maybe this is still related to the recent sway start changes. I was so focused on this warning that I didn't even notice that there were no app icons in waybar until I restarted it and that also the terminal did not start using the `win + enter` hotkey.

This is with the "sway" session.

Waybar service logged:
```
journalctl /usr/bin/waybar
Mär 23 09:26:35 endeavour waybar[4618]: cannot open display: :0
Mär 23 09:26:37 endeavour waybar[4671]: cannot open display: :0
Mär 23 09:26:40 endeavour waybar[4710]: cannot open display: :0
Mär 23 11:36:24 endeavour waybar[37378]: cannot open display: :0
Mär 23 11:36:26 endeavour waybar[37427]: cannot open display: :0
```

Is this a kind of race condition starting the different services?

**Comment by boredland** [comment]
> This is with the "sway" session.

So not the sway-service session?
