### ISSUE TITLE
🐛 manjaro-sway database broken

### ISSUE THREAD

**Issue by clemensjur** [manjaro-sway/manjaro-sway#760]
### branch

stable

### Architecture

x86_64

### Description

Greetings!

I just installed Manjaro Sway Edition from the ISO-File at [https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240331-linux66.iso](https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-240331-linux66.iso) and the manjaro-sway database seems to be broken currently (or at least the link to it).

When trying to update my system I always get the following error:
![Result of "sudo pacman -Syyu"](https://github.com/manjaro-sway/manjaro-sway/assets/16306561/eebaf4de-6f93-4b21-abd4-b7d3aef467fb)

As far as I could find out the problem seems to be that the file [https://packages.manjaro-sway.download//stable/x86_64/manjaro-sway.db](https://packages.manjaro-sway.download//stable/x86_64/manjaro-sway.db) is not gzip-compressed data but a plain text file with the content:
![Result of "cat /var/lib/pacman/sync/manjaro-sway.db"](https://github.com/manjaro-sway/manjaro-sway/assets/16306561/885c403e-a342-4837-9778-e8fda4a811dc)

### Reproduction steps

```bash
- Freshly install Manjaro Sway Edition from the newest ISO-File
- Run "sudo pacman -Syyu"
- Error appears
```

### Screenshots

![Result of "sudo pacman -Syyu"](https://github.com/manjaro-sway/manjaro-sway/assets/16306561/5cf082e6-57f8-49f2-863e-b143fa86ccef)
![Result of "cat /var/lib/pacman/sync/manjaro-sway.db"](https://github.com/manjaro-sway/manjaro-sway/assets/16306561/1771338a-9746-4247-b23d-36098c4b5c63)

**Comment by boredland** [comment]
I exceeded the limits of free github lfs.  Sorry, will take a look tomorrow.

**Comment by RPwnage** [comment]
Same problem here, tried to install multiple times, and tried various workarounds i found.

**Comment by boredland** [comment]
I think I worked around this problem. Please check if everything works again!

**Comment by boredland** [comment]
I think that means while Manjaro sway was disabled you updated it from our and now the version diverges. It's not the only package I am lagging a tiny bit behind.

**Comment by clemensjur** [comment]
> I think I worked around this problem. Please check if everything works again!

Thanks for the quick fix @boredland everything seems to work.


I am closing this issue because the initial problem is now fixed.

Have a great day!
