### ISSUE TITLE
🐛 sworkstyle privacy leak

### ISSUE THREAD

**Issue by oxmj** [manjaro-sway/manjaro-sway#763]
### branch

stable

### Architecture

x86_64

### Description

sworkstyle, while trying to match rules, prints web page titles of all open browser windows to syslog 

### Reproduction steps

```bash
- open few browser windows
- check journalctl/syslog
```

### Logs
dub 06 22:20:47 inara sworkstyle[40102]: 2024-04-06T20:20:47.006Z WARN  [sworkstyle::config] No match for "brave-browser" with title "Leek Spin - YouTube - Brave"
_No response_

**Comment by oxmj** [comment]
i think sworkstyle should log on error, not info, which leaks all web page titles.
if someone goes to debug his sworkstyle config -  matching rules, he should change it by hand/run sworkstyle with different option....

just a small change in sworkstyle systemd config -  log level  

/etc/systemd/user/sworkstyle.service
ExecStart=/usr/bin/sworkstyle -d -l **error**


```
[Unit]
Description=Renames workspaces to the icons configured
Documentation=https://github.com/Lyr-7D1h/swayest_workstyle
PartOf=sway-session.target
After=sway-session.target

[Service]
ExecStart=/usr/bin/sworkstyle -d -l error
NonBlocking=true
ExecReload=kill -SIGUSR2 $MAINPID
Restart=on-failure

[Install]
WantedBy=sway-session.target
```

**Comment by boredland** [comment]
Absolutely correct. Would you like to raise a PR in `desktop-settings`?

**Comment by oxmj** [comment]
[done](https://github.com/manjaro-sway/desktop-settings/pull/195)

thanks!

**Comment by boredland** [comment]
should have laded by now.
