### ISSUE TITLE
🐛 .local/bin folder missing from PATH

### ISSUE THREAD

**Issue by dinkocar** [manjaro-sway/manjaro-sway#764]
### branch

stable

### Architecture

x86_64

### Description

I have noticed that my $HOME/.local/bin folder is missing from path (since recently, I am not sure about exact time when it disappeared.) When I manually source /etc/profile.d/home-local-bin.sh it works. But I didn't have to do this manually. Also other functionality in /etc/profile.d might be effected, I haven't checked.

### Reproduction steps

```bash
Create $HOME/.local/bin folder if it is missing
logout/login or reboot
$HOME/.local/bin sholuld be in $PATH but it is not.
```

**Comment by boredland** [comment]
I think for that to work, we'd have to start foot as a login-shell, which caused other problems. But some things may have changed and probably we could give it another try (original issue: https://github.com/manjaro-sway/manjaro-sway/issues/721)

**Comment by dinkocar** [comment]
This is not only foot related. I have some sway bindings that call some scripts from my local bin folder (I don't use full path, just script name), and they don't work also.

**Comment by boredland** [comment]
Probably we just need to start sway from a login-shell then. Will do a little experiment.

**Comment by boredland** [comment]
Would you like to give `manjaro-sway-settings-git` a try?

**Comment by dinkocar** [comment]
My shortcuts are working, but still no local bin folder in PATH in foot.

**Comment by boredland** [comment]
Could you share your ` /etc/profile.d/home-local-bin.sh`?

**Comment by dinkocar** [comment]
Sure, here it is:

case ":${PATH}:" in
  *:"$HOME/.local/bin":*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac

And /etc/profile.d/home-local-bin.sh is owned by filesystem 2024.01.19-1

**Comment by boredland** [comment]
is that posix? I did just use `sh`, not `bash` or `zsh` to load sway.

**Comment by dinkocar** [comment]
I have no idea what that is. I have not used posix. It comes from core/filesystem package, and I guess it is installed in all Manjaro installations.

**Comment by boredland** [comment]
Seems that service unit never came to a final conclusion regarding /etc/profile and honestly I am on the fence here, as I personally don't even use it, but I know this caused issues in that past.

https://github.com/xdbob/sway-services/issues/13
