### ISSUE TITLE
🐛 chromium 124 does not accept flag --ozone-platform-hint any more

### ISSUE THREAD

**Issue by heapifyman** [manjaro-sway/manjaro-sway#770]
### branch

testing

### Architecture

x86_64

### Description

[Today's testing update](https://forum.manjaro.org/t/testing-update-2024-04-14-kernels-kde-frameworks-6-1-xorg-server-inputplumber/159909) upgraded chromium to version 124.

Afterwards, chromium would only display an empty window.

Seems that `--ozone-platform-hint=wayland` is not supported any more.

Changing to `--ozone-platform=wayland` seems to fix it.

### Reproduction steps

```bash
1. Upgrade chromium to version 124.
2. Start chromium
```

**Comment by boredland** [comment]
This is like the 4th time chrome has renamed that flag. Super annoying and I don't get why they don't leave it with one flag (like firefox does) until at some point they just switch automatically.

**Comment by boredland** [comment]
Just checked that regular chrome starts with the current flags. Will we need to have different (non symlinked) flags for them or is there something that works for both?

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/7a0c9e01-ab57-4692-8d60-84d819dbfb34)
