### ISSUE TITLE
🐛  way-displays  && scale.sh bugs

### ISSUE THREAD

**Issue by l-j-g** [manjaro-sway/manjaro-sway#786]
### branch

stable

### Architecture

x86_64

### Description

connected external TV - scale function would not work. i found a couple of issues:

1. /etc/systemd/user/way-displays.service 
the redirection of the output to the logs does not work correctly. it can be confirmed with systemctl status way-displays --user

it should be changed to something like 
```
[Service]
NonBlocking=true
ExecStart=way-displays --log-threshold debug
ExecReload=kill -SIGUSR2 $MAINPID
Restart=on-failure
StandardOutput=file:/tmp/way-displays.log
StandardError=file:/tmp/way-displays.log
``` 

2. `scale.sh` extracts the display name from `swaymsg -t get_outputs`.  this was selecting the wrong name (XXX Beyond TV (DP-1)) way-display github suggest use the desc field from their log. i.e 'XXX Beyond TV 0x00010000 (DP-1 via HDMI)'

but also just the 'name' field can be used..  suggest that we just take the name field from sway-msg because that will be easier. here's an example `cfg.yaml`:
```
ARRANGE: ROW
ALIGN: TOP
SCALING: TRUE
AUTO_SCALE: FALSE
AUTO_SCALE_MIN: 1
AUTO_SCALE_MAX: -1
SCALE:
  - NAME_DESC: Chimei Innolux Corporation 0x14D2 (eDP-1)
    SCALE: 1
  - NAME_DESC: XXX Beyond TV (DP-1) // Added by scale.sh, doesnt work.
    SCALE: 1.75
  - NAME_DESC: DP-1 // Manually added (or way-displays -s SCALE 'DP-1'  2 && way-displays -w)
    SCALE: 2
VRR_OFF:
  - eDP-1
  - DP-1
LOG_THRESHOLD: INFO
```
                                                 

3. closing the lid would not deactivate the display 

this one was described on their [github page](https://github.com/alex-courtis/way-displays/wiki/Troubleshooting#laptop-lid-not-detected---permission-denied) 

is was resolved by adding the user to the input group: 
`sudo usermod -a -G input "${USER}"`

### Reproduction steps

```bash
described above
```

### Logs

```bash
way-display log (abridged)

I [12:54:19] DP-1 Arrived:
I [12:54:19]   info:
I [12:54:19]     name:      'DP-1'
I [12:54:19]     desc:      'XXX Beyond TV 0x00010000 (DP-1 via HDMI)'
```

**Comment by boredland** [comment]
Those are all good findings. Would you be willing to open PRs for that?

**Comment by l-j-g** [comment]
sure ill be happy to do that just give me a couple of days

**Comment by boredland** [comment]
Hi there! Did you have a chance to look into it?

**Comment by boredland** [comment]
The docs by way-displays state: 

> Using a regex is preferred, however partial string matches of at least 3 characters may be used.

This IMO means we can do partial matching with only make and model and are just fine - so you can use the same config on multiple devices where the connection-name (like eDP-1) may change.
