### ISSUE TITLE
💡 make bindings keyboard-layout-agnostic

### ISSUE THREAD

**Issue by cgbarros** [manjaro-sway/manjaro-sway#788]
### Summary

Hey! I normally use a latin and a russian keyboard layout, and, at least in the ARM version, when I'm on the `ru` layout, the navigation bindings don't work. There is a fix for that, described [in the Arch Wiki](https://wiki.archlinux.org/title/sway#Keybindings_and_keyboard_layouts), which is adding `--to-code` after the `bindsym` command, like so:

```
bindsym --to-code {
  $mod+$left focus left
  $mod+$down focus down
  $mod+$up focus up
  $mod+$right focus right
}
```

 I tested locally and works great. Maybe we could make this the default.

### Drawbacks

This might require some extra testing and we need to be careful if we want to map special keys (like media playback) like this (I didn't test that). Maybe there are some keyboard layouts that will not work as well, but seems fairly safe)

### Implementation idea

I think the cleanest way is to create a variable `$bindtocode` with value `bindsym --to-code` and replace `bindsym` for this variable where it is relevant.

### Will you be able to contribute a PR for this?

- [X] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
I think in the non arm version we're already doing that. It's more about syncing that up finally, which I only started working on a few weeks ago (you can check status in the releases of our GitHub project. Sadly there were issues with calamares last time I checked).

**Comment by cgbarros** [comment]
Oh yeah, I'm seeing it. I tested on my x86_64 machine and indeed it works with other layouts. I guess I didn't notice it before because it just worked. Do you need help with this? Seems like the changes needed are already there in the codebase, but let me know. Otherwise I'll close this request.

**Comment by boredland** [comment]
Which arm device do you own? Currently I am only building an image for >=rpi4, but if you like to test and iron out stuff, I would add another device.

**Comment by boredland** [comment]
That's the same devices I have. As soon as that looks ok, I'll ping ya. Didn't find the time lately. The rpi4 image (works on rpi5 too) is already included in the weekly builds (https://manjaro-sway.download) - but those likely are still broken due to calamares/glibc issues.

**Comment by boredland** [comment]
You can, however, also add the repo and install the new `manjaro-sway-settings`, if you'd like:
https://packages.manjaro-sway.download
