### ISSUE TITLE
🐛 System font reset to monospace

### ISSUE THREAD

**Issue by Juliosh422** [manjaro-sway/manjaro-sway#798]
### branch

stable

### Architecture

x86_64

### Description

Got an update of manjaro-settings using pacman -Syu and all my system fonts got reset to monospace, I managed to set the foot client font to JetBrainsMono font but I'm struggling to find where are rofi and other applications picking the default fonts. 
I read in manjaro forums about /etc/sway/themes/ being wrongly configurated but I can't find that directory on my machine.

### Reproduction steps

```bash
Run a system update using 'pacman -Syu' or 'paru -Syu'
```

**Comment by boredland** [comment]
I could swear I had this issue once, but it was a long time ago. Will have to skim through the gir history, perhaps I can recall the problem that was

PS: I am a bit surprised you had an update, as I didn't create a release in a while?

**Comment by boredland** [comment]
Just a shot into the dark, but could you try: `fc-cache -f -v` to regenerate the font-cache?

**Comment by boredland** [comment]
No reaction.
