### ISSUE TITLE
installer doesn't boot on latest ISOs 🐛

### ISSUE THREAD

**Issue by erikh** [manjaro-sway/manjaro-sway#807]
### branch

stable

### Architecture

x86_64

### Description

After getting into sway from the live ISO, starting the installer from the launcher nothing happens.

### Reproduction steps

Using virtualbox, display has 3d support enabled (which without, it doesn't even boot to the GUI). After getting into sway, starting the installer from the launcher nothing happens. Checking journalctl, seems this is a compositor issue related to DRM allocating buffers. This might work on actual hardware, but the end result is that I cannot install anything from the live ISO. This happens both in the stable and unstable release.

**Comment by boredland** [comment]
Can you share the name of the iso you downloaded?

**Comment by erikh** [comment]
After an all day trial session, this is definitely somehow in the middle of full disk encryption, EFI, and probably initrd. It's not only related to sway; the GNOME installer bricks too. Turning off encryption makes the system work.

**Comment by erikh** [comment]
Sorry, same as my other ticket #808. This comment was actually meant to go there too; I guess I got my wires crossed. Pretty much all the installers on manjaro.org result in boot failure if the encrypted system is selected.

**Comment by boredland** [comment]
That's sad. All my systems use luks, so maybe this either is a new issue or related to VMs.

**Comment by boredland** [comment]
So: I didn't try virtualbox, as I personally don't like it/Oracle very much. But: With Gnome Boxes (a KVM/qemu/libvrt UI), I just have been able to install with encryption enabled on `manjaro-sway-24.0.0-unstable-240523-linux69.iso`. So likely this is an issue specific to virtuabox. I don't know what your host system is, but for most Linux Distributions there's a wide range of kvm-based Solutions (a popular one is [virt-manager](https://virt-manager.org)) - not sure about windows/mac tho.

**Comment by boredland** [comment]
The installer start in Gnome Boxes. I did nothing else but enable Hardware Acceleration. This doesn't seem like a Manjaro, nor a Manjaro Sway issue, but a problem with VirtualBox.

![image](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/5d5f19d4-7bee-48ca-a5ea-8c7c24f1076e)

**Comment by gczgcz2015** [comment]
> The installer start in Gnome Boxes. I did nothing else but enable Hardware Acceleration. This doesn't seem like a Manjaro, nor a Manjaro Sway issue, but a problem with VirtualBox.
> 
> ![image](https://private-user-images.githubusercontent.com/4662748/334195652-5d5f19d4-7bee-48ca-a5ea-8c7c24f1076e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTMzNzEsIm5iZiI6MTczMzExMzA3MSwicGF0aCI6Ii80NjYyNzQ4LzMzNDE5NTY1Mi01ZDVmMTlkNC03YmVlLTQ4Y2EtYTVlYS04YzdjMjRmMTA3NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMDQxNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjI1ZTY1MDNkN2RjZWEzYmE4ZWRjNWEwNWFiYmI0NTA2NTQ5ZDUxMDUyN2I3MWFhOTVjYTM3MTk5MTc4OGFkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MxSfx6iJgOqO6VKpNONNdh0DhfO-Vnp0UvENUbwqkpU)

same issue. I'm using vmware to install manjaro-sway. ios file is [manjaro-sway-24.1.1-241110-linux66.iso 2.562 GB].  After getting into sway, starting the installer from the launcher nothing happen too. And if I run "sudo -E calamares"  it shows
![屏幕截图 2024-12-02 122528](https://github.com/user-attachments/assets/8e08da5a-007b-437c-be06-e48a19b4b73e)
