### ISSUE TITLE
🐛 latest unstable build bricks at boot

### ISSUE THREAD

**Issue by erikh** [manjaro-sway/manjaro-sway#808]
### branch

unstable

### Architecture

x86_64

### Description

Installed with an encrypted system; tried both f2fs and ext4 as backing filesystems. Both efforts caused no output after the boot logo. System is a system76 thelio, radeon card amd 5900x

### Reproduction steps

```bash
Install it
```

**Comment by erikh** [comment]
stable also bricked; not sure what's going on here. I'm trying a GNOME install now to see if it's related to the install with this ISO or the kernel/initrd in general. I was using the proprietary drivers in the livecd. Not sure if that matters.

**Comment by boredland** [comment]
Can you share the name of the iso you downloaded?

**Comment by erikh** [comment]
manjaro-sway-24.0.0-240523-linux66.iso

**Comment by erikh** [comment]
sorry; the unstable was manjaro-sway-24.0.0-unstable-240526-linux69.iso

**Comment by erikh** [comment]
I'm downloading 240526 stable now, to see if it works.

**Comment by erikh** [comment]
Ok, this is definitely directly related to encryption settings in manjaro. If I select an encrypted system and enter the password, the system is rendered unbootable.

If I were to guess, it has something to do with the encrypted boot partition or initrd setup, but even trying to repair the partitions with the tools provided in the manjaro GNOME installer post-install didn't even detect a linux system.

I know at this point this isn't just the sway dist; I verified it on Manjaro GNOME as well, so I guess it might have to be bubbled up. Hoping someone more connected to the community can do that.

**Comment by erikh** [comment]
just to confirm, installing without full disk encryption got my system booting just fine with the stable sway iso. looks wonderful and the default settings are really great and I hope you all are proud of the work you're doing here.

**Comment by boredland** [comment]
Did you read my [other](https://github.com/manjaro-sway/manjaro-sway/issues/807#issuecomment-2132155482) comment? As is worked for me instantly with Gnome Boxes, I suspect this to be an issue around manjaro + full disk encryption + virtualbox.

**Comment by erikh** [comment]
no worries! I've provided more than enough information here to help you resolve the problem on your own and I just want to use the software.

I'll close this issue and if you want to fix it, be my guest.

**Comment by boredland** [comment]
I just installed Manjaro Sway in Gnome Boxes with Hardware Acceleration enabled and with the encryption setting during install:

[recording_20240527-212854.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/06b9a7d6-ab3e-4f27-ae45-473f2daa7913)

**Comment by boredland** [comment]
What might be interesting for you: I couldn't start the live ISO for Ubuntu 24.04. where VirtualBox even has a preset when I select the ISO. I won't look into this further, as I don't even like VirtualBox and don't understand why people are using it when there's nicer software around.
