### ISSUE TITLE
VirtualBox live ISO does not allow persistent installation

### ISSUE THREAD

**Issue by Zero-33** [manjaro-sway/manjaro-sway#817]
### branch

stable

### Architecture

x86_64

### Description

When running the current Manjaro Sway edition ISO, manjaro-sway-24.0.1-240602-linux66.iso (and unstable version) initially within VirtualBox, it loads and displays as you would assume an OS iso would. However, the Manjaro Installer does not appear and installation CLI commands to start the installation process do not work.

Commands tried to initiate persistent installation:- 
sudo setup
sudo -E calamares
meta+d > "Manjaro Installer"

When using the exact same ISO within Gnome Boxes, the Manjaro Installer shows and pops up immediately after initial startup - works as fully expected.

### Reproduction steps

```bash
- Create new VM using ISO within VirtualBox
- Load using open source drivers
- Desktop appears as you'd expect
- No Installer available or functioning using various means
- If you use Gnome Boxes instead, installer pops up and functions as expected
```

### Logs

```bash
Please note this is the first issue I have submitted, so unsure if you need anything more. Let me know if you need any further information/testing.
```

**Comment by boredland** [comment]
I tried a recent version of VirtualBox and could neither get Ubuntu running there, nor any version of Manjaro. If that's the case for you too, I suppose this isn't a Manjaro Sway issue. Can you try another VM, like Gnome Boxes?

**Comment by Zero-33** [comment]
Thanks for your quick response @boredland :)

Other Manjaro Editions do actually work under my version of VirtualBox.

Sorry, I should of mentioned that I had already successfully tried two other ISOs before I posted - Manjaro i3 and BunsonLabs. Both worked as expected within VirtualBox.

I've done some more tests and added more info if it will help:


Host Device     -  System76 Lemur Pro
Host Graphics  -  Mesa Intel® Graphics (RPL-U)
Host OS           -   Pop! OS 22.04 LTS
VirtualBox         -  7.0.10_Ubuntu r158379

All Manjaro ISOs were booted with open source drivers selected

| ISO                                             | VirtualBox 7        | Gnome Boxes       |
| ----------------------------------------------- | ------------------- | ----------------- |
| manjaro-i3-23.0.1-230921-linux65.iso            | Installer Success   |                   |
| boron-1-240123-amd64.hybrid.iso                 | Installer Success   |                   |
| manjaro-sway-24.0.1-240602-linux66.iso          | No installer  | Installer Success |
| manjaro-sway-24.0.1-unstable-240602-linux69.iso | No installer  |                   |
| manjaro-gnome-24.0.1-240529-linux69.iso         | Installer Success   |                   |

_I've only tried Sway in Gnome Boxes, not the others._
Note - Sway showed signs of screen tearing when running under Gnome

Screenshots of the VirtualBox settings for Manjaro Editions (Gnome, i3 and Sway) are attached.

Let me know if I can try anything else :smile: 

![i3 Screenshot from 2024-06-09 07-44-09](https://github.com/manjaro-sway/manjaro-sway/assets/39703619/c3714bf8-c899-4b9d-adf8-cba64bf178c6)
![Sway Screenshot from 2024-06-09 07-44-02](https://github.com/manjaro-sway/manjaro-sway/assets/39703619/a4649d96-408a-41d9-a6a7-0fdbfb1fa2f9)
![Gnome Screenshot from 2024-06-09 07-43-51](https://github.com/manjaro-sway/manjaro-sway/assets/39703619/d14246ce-3c8f-40ac-8ba0-683f8ddb9701)

**Comment by Zero-33** [comment]
Was just going to try something else and noticed a new version of the iso out today (manjaro-sway-24.0.1-240609-linux66.iso)

So using this new iso, the same process as above and on the same machine:

1. Installer does not appear
2. Run `sudo -E calamres` and no installer appears
3. Error shown in the terminal = `[destroyed object] : error 7: importing the supplied dmabufs failed`

Next test was on a completely different computer, using the new iso installed onto a usb stick, to then carry out a proper installation:

1. Booted from USB, selected open source drivers
2. Sway booted fine, can see desktop etc
3. No installer window though, just as previous tests above
4. Carried out `sudo -E calamares`
5. Installer window DOES appear and seems to function correctly

The terminal was showing some 'errors' (if they are errors):
`Authorization required, but no authorization protocol specified`
`Cannot open display ":0"`

**Comment by boredland** [comment]
installer starts in unstable (manjaro-sway-24.0.1-unstable-240609-linux69.iso): 
[recording_20240609-131155.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/1397f77a-daa6-4488-bdb7-3d2828a21920)

installer starts in stable (manjaro-sway-24.0.1-240609-linux66.iso): 
[recording_20240609-134611.webm](https://github.com/manjaro-sway/manjaro-sway/assets/4662748/f10dacb1-7685-4b53-924d-2ffdc5bb11aa)

However, I updated the iso-profiles repo to be based on the current state of what manjaro has, just to avoid some differences to account for there. new ISOs should be uploaded withing the next minutes. I don't feel comfortable testing out virtualbox again, as I neither like it a lot, nor feel like it will lead anywhere. If I can confirm it not working, I'd be googling the same errors, that you probably already googled before me.

**Comment by SilverTux** [comment]
Hi!
I've experienced the same problem as @Zero-33. I've planned to try out Manjaro sway and i3 editions inside VirtualBox and based on that decide which one will I use in the future. Sadly I couldn't start the installer nor with running calamares using sudo nor with the "Manjaro Installer".

I've tried to run calamares as a root with these env variables:
```
export QT_LOGGING_RULES=qt.qpa.*=true
export QT_DEBUG_PLUGINS=1
export QSG_INFO=1
export QT_QPA_EGLFS_DEBUG=1
export XDG_RUNTIME_DIR=/run/user/$(id -u)
```

and the output was:
```
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
loaded library "/usr/lib/qt/plugins/platforms/libqwayland-generic.so"
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
loaded library "/usr/lib/qt/plugins/platforms/libqxcb.so"
Authorization required, but no authorization protocol specified

qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

**Comment by boredland** [comment]
Whats stopping you to just use Gnome Boxes or any other KVM/Qemu/libvrt based tool? In my experience that works fine, at least for getting a first glance..

**Comment by SilverTux** [comment]
Back then I started to use VirtualBox for virtualization and since then I'm using it if I need some vm (very rarely), so no reason why I didn't use Gnome Boxes.
Writing the ISO to a bootable USB, the installer works, but I expected that there won't be any problem trying it in real action. Now I can say that it is a VirtualBox specific problem as you mentioned and @Zero-33 proved with using Gnome Boxes. Do you have any ideas why sway is problematic inside VirtualBox?

**Comment by Zero-33** [comment]
> VirtualBox has been a problem with sway from the very first ISO I built and I eventually gave up.

Thanks @boredland , I've just arrived into _this_ world and didn't know that


> As for your issue @SilverTux: seems `sudo -E calamares` should do the trick for you. At least it did for @Zero-33.

yes it did on a bare metal install, which after all is likely to be the favorite situation for most. For those that it isn't and need it in a VM, Sway works in VirtualBox in a 'non-persistent way, so that is great for an eval and Gnome Boxes works for a more permanent eval or more.

Happy to close this off as close as not planned
(let me know if this isn't the right thing to do here.....remember, just arrived.... :wink: )

**Comment by Zero-33** [comment]
Happy to close this off as close as not planned
_(let me know if this isn't the right thing to do here.....remember, just arrived.... :wink: )_
