### ISSUE TITLE
💡 Shortcut to switch back to tiling

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#827]
### Summary

How do I switch back to tiling when I switched to stacking or tabbed layout?

### Drawbacks

-

### Implementation idea

shortcut in help texts

### Will you be able to contribute a PR for this?

- [ ] Yes I will be able to get that feature a *lot* quicker.

**Comment by boredland** [comment]
This is actually there, but phrased differently, making it hard to find:

```
## Action // Toggle window splitting ##
$bindsym $mod+e layout toggle split
```

I will change it to

```
## Action // Switch to window splitting ##
$bindsym $mod+e layout toggle split
```
