### ISSUE TITLE
add a clipboard manager

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#83]
just saw it should be pretty straightforward to add one using[ wl-clipboard](https://github.com/bugaevc/wl-clipboard):

```bash
exec wl-paste -t text --watch clipman store --max-items=60 --histpath="~/.local/share/clipman.json"
bindsym $mod+h exec clipman pick --tool="wofi" --max-items=30 --histpath="~/.local/share/clipman.json"
```

**Comment by Mathew-D** [comment]
clipman breaks pcmanFM'd copy and paste.   A better choice is CopyQ

**Comment by boredland** [comment]
oh thanks for the feedback, having a look.

**Comment by Mathew-D** [comment]
I know you have [ -x "$(command -v clipman)" ] in the autostart to make it so if clipman isn't installed it will not load but now it must be installed as manjaro-sway-settings 5.3.0-7 depends on it.  

Can you please remove the dependencies for this so I don't have to either stop taking updates for sway-settings and remove clipman from 99-autostart-applications.conf or go into /usr/bin/ and remove the clipman so the autostart will not run.

**Comment by boredland** [comment]
> I know you have [ -x "$(command -v clipman)" ] in the autostart to make it so if clipman isn't installed it will not load but now it must be installed as manjaro-sway-settings 5.3.0-7 depends on it.  
> 
> Can you please remove the dependencies for this so I don't have to either stop taking updates for sway-settings and remove clipman from 99-autostart-applications.conf or go into /usr/bin/ and remove the clipman so the autostart will not run.

Oh, yeah, sure.

**Comment by boredland** [comment]
should be optional in pkgrel 8

**Comment by Mathew-D** [comment]
Thank you very much. I hate having to copy twice with PCmanFM which clipman forces you to do.

**Comment by boredland** [comment]
Could you elaborate a bit more what breaks? Not entirely sure what happens and if we shouldn't open a bug with clipman/pcmanfm then 👯‍♂️

**Comment by Mathew-D** [comment]
Sure, when you try and use copy with clipman on it shows up as file:// in clipman and PCmanFM doesn't see that as a file anymore.  You then have to copy the same file again before you can paste.
It is basicly https://github.com/yory8/clipman/issues/59
It is also basicly in the known issues:
"By default, we continue serving the last copied item even after its owner has exited. This means that, unless you run with the --no-persist option, you'll always immediately lose rich content" and in this case the rich content seems to be what we you need to copy and paste in PCmanFM.  This is why I ended up switching to CopyQ which takes all text, image, etc and doesn't seem to get in the way.

**Comment by boredland** [comment]
Thanks for the explanation. Seems there is no way around it then.

**Comment by Mathew-D** [comment]
What about this clipboard manger... https://github.com/sentriz/cliphist

**Comment by boredland** [comment]
That looks really minimal. Did you try it? How was your experience so far?

**Comment by Mathew-D** [comment]
I have play with it a bit. So far it hasn't broken the clipboard copy and paste in PCmanFM and as has let me see a history of my clipboard with rofi and select the old values. Which in the end is really all it needs to do I think.

**Comment by Mathew-D** [comment]
Right now I have it on waybar with:
"custom/clip": {
        "format": "",
        "on-click": "swaymsg -q exec \\$clip",
        "tooltip": false
    }
and 

set $clip cliphist list | rofi -dmenu  -theme-str "* {lightbg: $background-color; background: $background-color; lightfg: $accent-color; foreground: $text-color; ac: $accent-color;}" | cliphist decode | wl-copy
in my definitions.d/00-user-define.conf

**Comment by boredland** [comment]
added cliphist to our packages
