### ISSUE TITLE
🐛 The webcam LED flashes continuously.

### ISSUE THREAD

**Issue by unz3r0** [manjaro-sway/manjaro-sway#834]
### branch

unstable

### Architecture

x86_64

### Description

The webcam LED, i.e. the indicator for a recording in progress, flashes continuously. Something in the background triggers the webcam continuously, but I don't know what it could be. It is not a laptop, but a mini PC. Could it have something to do with the backlight?  The flashing starts straight after I'm logging into SwayWM.

### Reproduction steps

```bash
When I connect the webcam via USB, it flashes incessantly and is always busy.
```

### Screenshots

https://github.com/user-attachments/assets/796d12c6-548c-4253-96c5-5270e23b62cc

**Comment by boredland** [comment]
That is wluma, a tool to adjust the display brightness based on ambient brightness. You can disable it by uninstalling it or pressing the 🔅 button in the waybar, so it doesn't contain an "A".

**Comment by unz3r0** [comment]
I cannot see it here:
![image](https://github.com/user-attachments/assets/811e2703-152e-4070-9a63-e1bc649c52d0)

Although it is there, and I disabled by customizations plus reloaded sway and restarted waybar:
```
    ~  grep -B10 -A2 "wluma" /usr/share/sway/templates/waybar/config.jsonc                                                                                                                                                                ✔ 

    "custom/adaptive-light": {
        "interval": "once",
        "tooltip": true,
        "return-type": "json",
        "format": "{icon}",
        "format-icons": {
            "on": "󰃡",
            "off": "󰃠"
        },
        "exec": "/usr/share/sway/scripts/wluma.sh",
        "on-click": "/usr/share/sway/scripts/wluma.sh toggle",
        "exec-if": "/usr/share/sway/scripts/wluma.sh check",
        "signal": 12
    },
    ~  ls .config/waybar/                                                                                                                                                                                                                 ✔ 
config.jsonc.bak  config.jsonc.example  style.css.example
```

That is strange.

Anyhow. Thanks for pointing to wluma. I followed this : https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-configure-adaptive-brightness, commented out:

```
#[als.webcam]
#video = 0
#thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }
```
and restarted it:
``` 
systemctl --user restart wluma.service
```

No more flashing LED. Thanks.
