### ISSUE TITLE
🐛 Superkey on keyboard not recognized by OS

### ISSUE THREAD

**Issue by JohnZ03** [manjaro-sway/manjaro-sway#845]
### branch

stable

### Architecture

x86_64

### Description

Installed on a Lenovo laptop made in about 2021.
I tested with one of those online keyboard tester, and found out that the superkey inputs are not registered by the OS. How should I proceed to fix this? Do I need to find an appropriate dirver?
I used default option for all the install/language settings.
Thanks for the help.

### Reproduction steps

```bash
N/A
```

**Comment by simon-bueler** [comment]
Could you verify, that it is not a hardware problem (broken key) by installing a different OS or connecting a keyboard? Normally it should just work.

**Comment by JohnZ03** [comment]
> Could you verify, that it is not a hardware problem (broken key) by installing a different OS or connecting a keyboard? Normally it should just work.

It's not a hardware problem. I even tested with installing the KDE version of Manjaro, and the superkey is registered correctly.

Also during the installation process of Manjaro Sway, the Z key is being register as Y key. I tried with different keyboard layout/languages and it is still incorrect. And the superkey remain unfunctional.

**Comment by boredland** [comment]
> I tried with different keyboard layout/languages and it is still incorrect. And the superkey remain unfunctional.

In the calamares installer of manjaro? That one isn't actually having an effect on Sway. In sway, you [configure the keyboard differently](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-add-more-keyboard-layouts-to-sway). I can assure you, that _normally_ the super key just works. I have working installs on a desktop computer, several thinkpads and even a framework 13 as of now. None of them have issues with the super key.

**Comment by JohnZ03** [comment]
> > I tried with different keyboard layout/languages and it is still incorrect. And the superkey remain unfunctional.
> 
> In the calamares installer of manjaro? That one isn't actually having an effect on Sway. In sway, you [configure the keyboard differently](https://github.com/manjaro-sway/manjaro-sway/blob/main/SUPPORT.md#how-can-i-add-more-keyboard-layouts-to-sway). I can assure you, that _normally_ the super key just works. I have working installs on a desktop computer, several thinkpads and even a framework 13 as of now. None of them have issues with the super key.

Thanks for the info, I'll give it couple more tires and see where the issue comes from.

**Comment by boredland** [comment]
Very nebulous issue.
