### ISSUE TITLE
Link to download ISOs on https://manjaro-sway.download/ are all dead

### ISSUE THREAD

**Issue by lemoinem** [manjaro-sway/manjaro-sway#846]
### branch

stable

### Architecture

x86_64

### Description

Links to ISO to install majaro-sway on manjaro-sway.download are dead.
I've looked around for an alternative source for the ISOs, but couldn't find any...

### Reproduction steps

```bash
1. Go to https://manjaro-sway.download/
2. Click on either manjaro-sway-24.0.1-240908-linux66.iso or manjaro-sway-24.0.1-unstable-240908-linux610.iso
3. Get 404 Not Found
```

**Comment by boredland** [comment]
For some reason the build process for the jekyll page failed, so those are the old urls. Will have a look! 👀
