### ISSUE TITLE
add a "dnd"-button to waybar

### ISSUE THREAD

**Issue by boredland** [Manjaro-Sway/manjaro-sway#85]
mako accepts modes from https://github.com/emersion/mako/releases/tag/v1.6 on - this should allow us to add a little snooze-icon to waybar so we can disable notifications.

**Comment by boredland** [comment]
since we don't release mako ourselves (yet), we should wait for it to land in the repos.

**Comment by Mathew-D** [comment]
You mean use: makoctl set-mode do-not-disturb 
The testing version of manjaro just updated mako to 1.6

**Comment by Mathew-D** [comment]
I am looking at this but right now there but isn't a way to find out which mode is active without a script.  
https://github.com/emersion/mako/issues/367
I found someone script that tells us which mode is active: https://github.com/emersion/mako/issues/159#issuecomment-875886026

**Comment by boredland** [comment]
Ok, buts an active discussion however.

**Comment by flipflop133** [comment]
For those who can't wait, here is how I managed to do it until official release:
https://github.com/flipflop133/Dotfiles/blob/master/.config/scripts/bash/notifications_status.sh
https://github.com/flipflop133/Dotfiles/blob/master/.config/waybar/config#L153
Hope it'll help 😀

**Comment by Mathew-D** [comment]
An interesting idea but with your script you killall mako instead of putting it into dnd mode.  This stops mako but when you restart it you lose all the settings we pass to it on start. 

mako --font "$term-font" --text-color "$text-color" --border-color "$accent-color" --background-color "$background-color" --border-size 3 --width 400 --height 200 --padding 20 --margin 20 --default-timeout 15000

**Comment by flipflop133** [comment]
Why don't you use the config file instead? But of course it's not the best solution, it's just temporary, another solution would be using a loop, so we can keep track of the current mode though with this solution I'm afraid to encounter a case where we could lose track of the current mode. Anyway, I'll not implement this as a get mode feature is near to be implemented I think.

**Comment by boredland** [comment]
> Why don't you use the config file instead?

so we can put in theme variables from sway

**Comment by boredland** [comment]
since there is no movement upstream, I think adding a script should be an option. if sb would like to pick it up.

**Comment by FallenChromium** [comment]
It could be that [dnkl/fnott](https://codeberg.org/dnkl/fnott/issues/20) will implement this feature faster than mako, if you have any valuable input for this project, it will be great if you'll share your thoughts.

**Comment by Mathew-D** [comment]
Looks like we might get lucky on this:

https://github.com/emersion/mako/pull/382

**Comment by boredland** [comment]
has been implemented upstream via https://github.com/emersion/mako/pull/433
