### ISSUE TITLE
🐛 Unable to communicate with way-displays systemctl unit

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#852]
### branch

stable

### Architecture

x86_64

### Description

Way-displays is running via systemd, but I can neither send signals not find its logs anywhere.
Starting another instance that I can communicate with leads to funny conflicts (flickering).

### Logs

```bash
❯ ps aux | grep way-dis
janek       1959  0.0  0.0  10752  6996 ?        Ss   Sep26   0:00 way-displays --log-threshold debug
❯ sudo pacman -Qo /etc/xdg/systemd/user/way-displays.service
/etc/systemd/user/way-displays.service is owned by manjaro-sway-settings 16.30.0-9
❯ way-displays -s ARRANGE_ALIGN COLUMN middle
ERROR: way-displays not running, check $XDG_VTNR
❯ echo $XDG_VTNR
2
❯ journalctl -u way-displays
-- No entries --
❯ systemctl --user status way-displays
● way-displays.service - Auto Manages Your Wayland Displays
     Loaded: loaded (/etc/xdg/systemd/user/way-displays.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-09-26 17:38:46 CEST; 3 days ago
 Invocation: 06b12ba9f9d0400a92d9ea636737e7be
       Docs: https://github.com/alex-courtis/way-displays
   Main PID: 1959 (way-displays)
      Tasks: 1 (limit: 76802)
     Memory: 1.8M
        CPU: 155ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/way-displays.service
             └─1959 way-displays --log-threshold debug

Sep 26 17:38:46 frog systemd[1386]: Started Auto Manages Your Wayland Displays.
```

**Comment by boredland** [comment]
can't you just stop the system unit and start it then? Perhaps that reveals something...?

**Comment by xeruf** [comment]
I can start it either way, and if I stop the systemd unit before starting it it works indeed without issues. But that's not really a solution ^^

**Comment by alex-courtis** [comment]
Alex from way-displays:

**Brief:** It looks like `$XDG_VTNR` is not set when way-displays starts.

**Testing:**
* river
* copied `/etc/systemd/user/way-displays.service`
* changed `WantedBy=graphical-session.target` as `wayland-session.target` does not exist
* `systemctl enable --user way-displays`
* `systemctl --user start way-displays`

**Following are present:**
```
:; ll /run/user/1000 | grep way-displays
srwxr-xr-x 1 alex users   0 Oct 28 10:39 way-displays.sock
:; ll /tmp | grep way-displays
-rw-r--r-- 1 alex users 5.4K Oct 28 10:39 way-displays.log
-rw-rw-rw- 1 alex users    5 Oct 28 10:39 way-displays.pid
```
The files are expected to be named `way-displays.${XDG_VTNR}...`

**Issue:**
`way-displays -g` etc will find the way-displays process by looking for `/tmp/way-displays.${XDG_VTNR}.pid` which is not found, hence `ERROR: way-displays not running, check $XDG_VTNR`

`$XDG_VTNR` is used to allow multiple sessions

**Proposed Solution:**
Ensure that `$XDG_VTNR` is present when running the systemd unit.

**Workaround:**
```sh
:; unset XDG_VTNR
:; way-displays -g

Client sending request: get

Server received request: get

Active configuration:
  Arrange in a ROW aligned at the BOTTOM
 ...
```

**Comment by alex-courtis** [comment]
Once we resolve this: I'll add a service template to way-displays based on this one, along with some documentation.

**Comment by xeruf** [comment]
Thanks, added a drop-in like this as a workaround:
```sh
[Service]
Environment=XDG_VTNR=2
```
Maybe you can utilize $TTY in that case?

**Comment by boredland** [comment]
Couldn't we add this environment dependency to [our](https://github.com/manjaro-sway/desktop-settings/blob/sway/community/sway/etc/systemd/user/way-displays.service) service unit?

**Comment by alex-courtis** [comment]
Thanks @boredland

**Comment by xeruf** [comment]
though of course that only solves it for manjaro-sway where you can assume the main instance running in TTY 2

**Comment by alex-courtis** [comment]
> though of course that only solves it for manjaro-sway where you can assume the main instance running in TTY 2

If we genuinely cannot evaluate $XDG_VTNR at startup time, that is indeed a problem.

As an alterative solution I could make a change to way-displays:

Try to fall back to `/tmp/way-displays.pid` when `way-displays.${XDG_VTNR}.pid` not found.

**Comment by xeruf** [comment]
alternatively, substitute XDG_VTNR for TTY when not present - the last digit of TTY seems to always be the number of XDG_VTNR which makes sense
