### ISSUE TITLE
🐛 Waybar Pacman hook incomplete

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#859]
### branch

stable

### Architecture

x86_64

### Description

The hook in `/etc/pacman.d/hooks/waybar.hook` has two issues:
- it is missing a description
- it executes and fails when running in a TTY session, producing a confusing and meaningless error message

### Reproduction steps

```bash
Run pacman package install in a tty
```

**Comment by boredland** [comment]
> TTY session

What is a `tty session`?

**Comment by boredland** [comment]
I guess you mean you started into a tty without sway (and thus without waybar). The script called by that hook indeed doesn't check if waybar is running.

**Comment by xeruf** [comment]
thanks, that was fast, saw the update before your comment ^^!
