### ISSUE TITLE
Can't change the theme and wallpaper 

### ISSUE THREAD

**Issue by MuratovAS** [Manjaro-Sway/manjaro-sway#86]
Good day.
My attempts to change the topic of registration, and the wallpaper ended with the failure.
Configuration prescribed in _00-user.conf_. The theme was applied only to Waybar.
```
set $theme $HOME/.config/sway/themes/matcha-blue
set $background $HOME/Изображения/background/1.png
```
The problem was solved by the transfer of strings, at the end of the _config_ file.
```
include /etc/sway/inputs/*
include /etc/sway/outputs/*
```
This happened because in _/etc/sway/outputs_, the variables that we override are used.

**Comment by simon-bueler** [comment]
If I remember correctly we have a $HOME/.config/sway/definitions file were you can adjust settings we have in /etc/sway/definitions. This includes changing the modifier key, background image, theme and waybar position.
All in 00-user.conf will be appended to the configuration. 
If you have not updated or maybe changed too much it can help to start fresh by updating all packages (sudo pacman -Syuu) and copying the configs from /etc/skel/ to $HOME.

**Comment by MuratovAS** [comment]
I apologize. Used outdated assembly. 
On the site manjaro.org 
The latest version of MANJARO-SWAY-21.0-210428 .....
