### ISSUE TITLE
🐛 <title>404 Error Trying to Download ISO from manjaro-sway.download </title>

### ISSUE THREAD

**Issue by aarRJaay** [manjaro-sway/manjaro-sway#860]
### branch

stable

### Architecture

x86_64

### Description

This object does not exist or is not publicly accessible at this URL. Check the URL of the object that you're looking for or contact the owner to enable Public access. 

### Reproduction steps

```bash
Click on Manjaro Sway link on the Manjaro homepage - select any of the ISO links, taken to a 404 error.
```

**Comment by boredland** [comment]
Should be fixed now. Apparently on Cloudflare workers, running `jekyll build` is not too great, `bundle exec jekyll build` did the trick.

**Comment by xor** [comment]
This is still happening again. :(

**Comment by boredland** [comment]
Not exactly sure why that happend (and isn't anymore, it seems..)
