### ISSUE TITLE
🐛 Notification Do not Disturb not working

### ISSUE THREAD

**Issue by xeruf** [manjaro-sway/manjaro-sway#869]
### branch

stable

### Architecture

x86_64

### Description

I don't know what just happened, but the appearance of notifications changed and do not disturb does not make a difference anymore:

![image](https://github.com/user-attachments/assets/901f58b8-f1b1-472f-958a-74cbed3e69a7)

### Reproduction steps

```bash
unsure
```

related to https://github.com/manjaro-sway/manjaro-sway/discussions/814

**Comment by xeruf** [comment]
and for some reason, notifications are also sticky now

**Comment by boredland** [comment]
Your notifications don't look like the themed mako that is installed by default.

[recording_20241110-192339.webm](https://github.com/user-attachments/assets/477d5c03-5a44-46cb-8768-c3360fa620d7)

**Comment by boredland** [comment]
No reaction, no support.

**Comment by xeruf** [comment]
I guess it was a transient issue, thanks anyway :)
