### ISSUE TITLE
Terminal opens slowly

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#88]
Hello! I've been following this project for a while and yesterday I decided to give it a try. One of the problems that I've faced is the time it takes from pressing Mod+Enter to seeing the terminal window - it's absurdly long for my machine (i7-8650U, 16GB RAM). 

I suppose the problem may be a rather slow script terminal.sh which checks OpenGL version EVERY time I open a terminal, which in Sway happens a lot more than in a conventional DE. This of course is unnecessary.
 
I have a suggestion to make it a one-time execution script, either in the installation session or when opening terminal for the first time. The other option would be to use a baseline terminal which is not dependent on graphics support, which makes sense if you think of Manjaro Sway not only as a Sway showcase, but as an option for low-end machines. 

May we have a poll or something along those lines about the default terminal emulator? For example, [foot](https://codeberg.org/dnkl/foot) may be a good fit, considering its' speed and lack of GPU acceleration, which is a pro in this context.

**Comment by boredland** [comment]
Good point. I think the current solution is a result of

1. Me wanting to have compatibility on older hardware without OpenGL 2.1 support (termite)
2. Image Previews in ranger not working on wayland (kitty)

If foot meets both of those requirements, I thing we don't even need a poll, since it would objectively be the better solution for everyone.

**Comment by andrius** [comment]
I used foot with manjaro sway previously, OSC 52 support with mosh works better with kitty from my experience (but it works with foot in any case). At all, I'm more comfortable with kitty.

**Comment by boredland** [comment]
> At all, I'm more comfortable with kitty.

if we stay with kitty, I'd go with @FallenChromium proposal to make terminal selection a "one-time execution script, either in the installation session or when opening terminal for the first time".

**Comment by boredland** [comment]
tbh if everything works nicely in foot, I'd like that more. Never tried it though.

**Comment by dnkl** [comment]
> I used foot with manjaro sway previously, OSC 52 support with mosh works better with kitty from my experience (but it works with foot in any case). At all, I'm more comfortable with kitty.

@andrius honest question: in what way did it work better? Kitty's implementation is a non-backward compatible variant of the original OSC-52 protocol. Perhaps mosh isn't aware of this?

**Comment by Mathew-D** [comment]
For me I just overwrote the $term in the ~/.config/sway/definitions to the one I wanted to use.  Everyone likes there own terminal. The only time the script gets run for me is when I click on something in my waybar.

**Comment by andrius** [comment]
Some scripts could be executed once (with system bootstrap/install or after the user login. For instance, my .zsh files are complex (due to environments setup, some encryption etc, so I create a flag in the /tmp and check it, if it exists, then business logic get executed already and these files won't be executed again

**Comment by andrius** [comment]
> > I used foot with manjaro sway previously, OSC 52 support with mosh works better with kitty from my experience (but it works with foot in any case). At all, I'm more comfortable with kitty.
> 
> @andrius honest question: in what way did it work better? Kitty's implementation is a non-backward compatible variant of the original OSC-52 protocol. Perhaps mosh isn't aware of this?

Yes, kitty's implementation is a bit different, I've googled and updated my dotfiles (I think this in kitty.conf: `clipboard_control write-clipboard write-primary no-append`). But in overall it's clipboard management + mosh/ssh + OSC52 works better, I spent a lot of my time in terminals (my laptop is just a thin clirnt with browser and messengers; I do code in neovim on vps)

**Comment by boredland** [comment]
> Everyone likes there own terminal.

while this is true, this discussion is more about: "what will work best for most?"

While I spend most of my time in the terminal, I seem to be using it much differently from you people. I mostly use the terminal in vscode, since I'm programming all day. So the choice of the "regular" terminal doesn't really impact me that much.

**Comment by FallenChromium** [comment]
Hey, I'm glad this issue has attention :)

>     1. Me wanting to have compatibility on older hardware without OpenGL 2.1 support (termite)
As far as I am aware termite is discontinued in favor to Alacritty, and though I know the requirement for Alacritty is OGL3.3, it doesn't seem future-proofing to support a terminal which may be removed from official packages at any moment due to it's abandoned state (though for now it works very well)

>     2\. Image Previews in ranger not working on wayland (kitty)

I have also thought about that, image previews in ranger are awesome, but no tool seems to work properly on wayland except terminal protocols. That said, foot supports sixel, and there is an utility to output images to terminal, img2sixel. I do not know if this utility can be used to preview images in ranger, but if it can, we will have working image previews.

 

> I create a flag in the /tmp and check it, if it exists, then business logic get executed already

Sounds less efficient than sed-ing the terminal launch script into not checkning OGL support and straight-up launching a terminal supported by the machine, but the thing is, user's hardware configuration can change while on the same OS, if it is a priority to support that edge-case, then a /tmp file to indicate OGL supports sounds like a good middle-ground.

**Comment by Mathew-D** [comment]
I notice you have a pull to remove termite, does that mean you have decided to go to with foot or are you just leaving it at kitty.  If we go with foot we will have to add it to the manjaro-sway db as right now people have to built it from the AUR.

**Comment by boredland** [comment]
> I notice you have a pull to remove termite, does that mean you have decided to go to with foot or are you just leaving it at kitty.  If we go with foot we will have to add it to the manjaro-sway db as right now people have to built it from the AUR.

No, I removed termite, because it is already removed from the Manjaro repos and therefore our build is broken.

**Comment by Mathew-D** [comment]
Well if we are going to leave it as just one terminal then we don't need the script.  We can just set the $term, $term_float and $term_float_portrait directly in the definition file

**Comment by boredland** [comment]
you're right - wanted to wait what we discuss here.

**Comment by boredland** [comment]
added foot and its dependencies to our repo. we should probably adapt it to the theme a little. I'll merge the termite removal first, so we have a clear starting point.

**Comment by simon-bueler** [comment]
From my side it would make sense to have only one terminal application. If this should be foot or kitty or any other one should depend on these points:
- future proof support from maintainer/community
- supported features match our requirements
- effort to integrate as low as possible

**Comment by boredland** [comment]
I honestly think that foot checks all the boxes.

1. it allows to disable the window decorations
2. it super fast
3. it has a nice configuration file that we can convert our kitty conf to: https://www.mankier.com/5/foot.ini
4. the maintainer updates the pkgbuilds himself
5. ranger image previews using sixel are on their way https://github.com/ranger/ranger/pull/2234

**Comment by andrius** [comment]
I have installed foot and it works fine, the only thing I had to consider is `dpi-aware=yes/no` property in the config. Interesting that fonts rendering is different than with kitty and with my contrast white themes, I'd have to tune up scaling for my monitor to remove white gap at the bottom of terminal

**Comment by dnkl** [comment]
Foot is one of very few applications that tries to use your monitor's actual DPI.

It'd recommend reading through both https://codeberg.org/dnkl/foot/src/branch/master/README.md#user-content-dpi-and-font-size, and https://codeberg.org/dnkl/foot/src/commit/931595bda573588d8529565869aafa3574179011/doc/foot.ini.5.scd#L148-L166 before making a decision.

Also, please note that there are **three** possible values for `dpi-aware`: no, yes and auto, with auto being the default.

Unless you've already done so, in which case I apologize :)

Also feel free to join #foot on libera.chat

**Comment by boredland** [comment]
has anybody got some nice foot.ini that would fit into manjaro at hand already? and: I'm wondering if we should drop the blue manjaro theme from the sway config. If people want to theme their stuff, thats fine. Just wouldn't like to maintain that and its actually just stolen from the arm profile.

**Comment by FallenChromium** [comment]
I have made a quick test: foot + [ranger-sixel from AUR](https://aur.archlinux.org/packages/ranger-sixel/). It does work, though the speed and memory usage are in question right now, it works good enough, but it isn't blazing fast. Also, it is unknown when the sixel PR will be merged to the original project, it seems like it's in a final stage, and only tests are required, but what do we do now then?
![2021-07-16T16:59:28,835371759+03:00](https://user-images.githubusercontent.com/43214067/125960013-d3247194-450e-4a07-b6b0-8d88bd9a42bf.png)

P.S: I have a foot.ini for the Matcha Blue, ported it from kitty.conf just now, also I love that theme btw :). 
But I agree, maintaining two themes... Sounds out of scope for this project. We could integrate wpgtk \ pywal to the Sway setup, I believe templates for foot, sway, gtk and other apps exist already, it will be a unique feature of this Manjaro flavor then and it will ease the maintenance of themes. But it's just a wild suggestion, not sure yet if it's a good idea to make such an opinionated default setup. 
[foot.txt](https://github.com/Manjaro-Sway/manjaro-sway/files/6831196/foot.txt)

**Comment by boredland** [comment]
> ranger-sixel from AUR

my personal opinion would be, that this is fine and could add the sixel configuration bit as soon as that is available in regular ranger. I guess having image previews in ranger isn't that big of a dealbreaker for most users and at least I personally lived without it for years because I didn't care.

> We could integrate wpgtk \ pywal to the Sway setup

that actually sounds amazing! as long as we give users an opt-out (for example uninstalling) I don't see big issues with having such a defaut.

**Comment by FallenChromium** [comment]
Great, then we can proceed to do the following:
1. A PR to switch terminals. Basically delete the terminal.sh, rebind the $term and $term_float to foot, add the default matcha-green foot.ini, add foot to the config.toml of sworkstyle. Because I've already kind of did it on my own machine I'll probably send a PR later today
2. We need an issue to discuss wpgtk+pywal integration, and if we will do it, which components will be themed.
3. I totally agree about the opt-out idea, and actually it reminded me about one small problem with default sway configs in /etc/sway - the binds. I can't override some of them, such as $mod+d, because they are defined in the main config. Technically I can change these files, but I feel like it's undesirable (it will probably change after package update). Should I create a separate issue for this?

**Comment by boredland** [comment]
regarding 3: yes please. I think its mostly a "sorting" issue as to which config is being loaded before another. when its not overrideable, isn't it?
