### ISSUE TITLE
it won't recognize encrypted partition

### ISSUE THREAD

**Issue by andrius** [Manjaro-Sway/manjaro-sway#90]
If you'll install a manjaro-sway with default encryption settings, it won't boot, it can't find a partition. Nor sure is that sway related or that's an installer issue

**Comment by simon-bueler** [comment]
Could you provide more information on your configuration and hardware you tried to setup and maybe provide some errror message or where in the boot process you get stuck?

**Comment by andrius** [comment]
It is not hardware-related I think, I have been tried with both Dell 7490 and Microsoft Surface Go 2 (arch/manjaro works there with default kernel). I've follow all the standard setup, and selected an encrypted partition option. Setup went right, but after reboot, it did not found a partition.

With Ubuntu it worked well.

Next week I will reinstall manjaro-sway on Dell 7490 and will take a photo of the screen

**Comment by boredland** [comment]
just installed todays built freshly on my x200 and it is prompting for the encryption password as it should.

**Comment by FallenChromium** [comment]
One thing to add though: with default Calamares btrfs + luks setup and swap partition (with hibernation, so around 17GB) added, every time my laptop boots it says "Key file not found" and "resume from partition UUID bla-bla", with the uuid being my swap. The thing is that hibernation doesn't work, when I have opened some windows and chose to hibernate in wlogout menu, my laptop turned back on to the "clean slate" state. 🤷🏻‍♂️

That said, I haven't encountered the original issue. I have formatted my drive, chose btrfs as root partition and encrypted it with a password.

**Comment by boredland** [comment]
Ah, I am on ext4. So perhaps it's a very specific setting that fails.

**Comment by andrius** [comment]
WIP on manjaro-sway progressing so fast. With the fresh iso that is released today, everything works. Previously I used to try ~2 months old ISO downloaded from the manjaro website

**Comment by boredland** [comment]
I have no idea who added that image on the manjaro website tbh. Perhaps @philmmanjaro can refer to a newer one?
