### ISSUE TITLE
Keyboard layouts setup

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#91]
Hi there! While checking the default config files I've stumbled upon /usr/share/sway/scripts/setkeyboard.sh, a script that is supposed to grab xkb settings from X11 and apply them to Sway, for compatibility purposes as far as I understand. The idea is neat, especially for newbies in Wayland, though I have some suggestions and I think this is a good topic for discussion.
1. The script doesn't parse xkb_options which is used mainly to setup a hotkey to switch layouts, without it the user would have to dive into sway configs anyway.
2. That said, I think this behavior can be very confusing and non-educating for some users, for example users may assume that Sway is compatible with XKB, and, therefore, with all the tools made for XKB. A better solution might be to add documentation (or a [link to ArchWiki](https://wiki.archlinux.org/title/Sway#Keymap)) to educate users on how to setup keyboard layout through ~/.config/sway/config.d/10-layout.conf, for example

**Comment by FallenChromium** [comment]
For documentation purposes, I will leave my own config for layouts which I placed at ~/.config/sway/config.d/10-layout.conf. It adds two layouts, Caps Lock is the shortcut to switch between them (to use Caps, you have to press Shift+Caps Lock). Caps LED is used as an additional indicator for a layout.
```
input * {
    xkb_layout us,ru
    xkb_options grp:caps_toggle,grp_led:caps
    xkb_capslock disable
}
```

**Comment by boredland** [comment]
1. i really like this capslock-setting and am wondering if we shouldn't add that to our default. wdyt?
2. isn't both possible?

**Comment by FallenChromium** [comment]
1. This might be a counter-intuitive experience for many users, and it only makes sense to someone who uses 2 layouts or more (in case of 3+ I don't think the Caps LED setting will make a lot of sense), but yeah, it would be cool to introduce this feature to the multilingual users. But for that we have to make a separate UI for configuring layouts and stop relying on X11. Using environmental variables such as `XKB_DEFAULT_LAYOUT`, `XKB_DEFAULT_VARIANT` and `XKB_DEFAULT_OPTIONS` might be an option, but it has to be set before sway launches, doesn't look good to me.

2. I brought up this issue exactly because I had problems with it, so yeah, isn't possible unless we either check if X11 config isn't default or introduce a special file in ~/.config to set up layouts and will check it's existence, and do nothing in case it exists. 

The problem I had: I didn't use X for anything for a long time, so when I transferred my keyboard settings from my old config and reloaded Sway, I was surprised that it didn't work. Apparently because there are no layout settings for X11 (on my machine), the script pulled up defaults from X11, which is US layout only, and on reload all my changes were dead. I had to delete the script from my machine so I could setup keyboard within sway. 

It's a good question if we shall prioritize the "idiomatic" way to do this (via Sway config) or the "friction-less experience" (the X11 compatibility), but it may be confusing for someone who already tried Sway and understood it cannot be controlled via XKB. It is unlikely that Calamares will gain support for setting up layouts in any Wayland compositor, so it's up to you. 

P.S Honestly I think that someone who decided to try a distribution with Window Manager should be teached on how to set it up, after all many Manjaro users end up trying Arch, where no such conveniences exist, it will be nice if they will be ready for this.

**Comment by boredland** [comment]
Yeah, I'm a bit out of ideas here. We had a lot of people complaining about a lot of settings from calamares having no effect (https://github.com/Manjaro-Sway/manjaro-sway/issues/36), but all your arguments basically apply to me too, but didn't come into effect (I have some per keyboard configurations that take precedence). One "middle ground" could be, that we add a file check for `~/.config/sway/config.d/10-layout.conf` and if its given, we don't run the keyboard scipt. Otherwise I'd be in favor of removing it again or adding it on the live image only.

**Comment by boredland** [comment]
@FallenChromium would running this on the live-iso be fine with you? if yes, I think the PRs I opened should cover most bases.

**Comment by FallenChromium** [comment]
Yep, running it on live-cd sounds good to me! Though I'd clarify the documentation on setting the keyboard. 

First, it looks like a necessary step that you have to apply the same way it's presented. So I'd paraphrase it like 'If you use any keyboard layout other than US, add your keyboard settings, for example 'something-something'. It will save people from accidentally making their keyboard German :D

For 2 and more layouts it will be nice to add a link to ArchWiki right to the point about setting keyboard layout on first boot, so people can get more knowledge on how to set it up. Actually, it might be better to rewrite the example from echo to "paste this to the file", it's worse than a one-liner in terms of convenience, but it's more understandable.

Btw, is "swaymsg" part supposed to be in `echo "swaymsg input type:keyboard xkb_layout de" > ~/.config/sway/config.d/01-keyboard.conf`? Looks like a typo to me.

With all that said, thanks for ironing out one more pain point from Manjaro Sway! I love using it so far, it's a way more polished experience than I had on bare Sway with bare Arch, I was too lazy to set it up properly tbh 🤣

**Comment by boredland** [comment]
> Btw, is "swaymsg" part supposed to be in echo "swaymsg input type:keyboard xkb_layout de" > ~/.config/sway/config.d/01-keyboard.conf?

oh. copy pasta.
