### ISSUE TITLE
Warnings when overriding binds

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#95]
One of the things which confused me a lot while transitioning my old Sway config to Manjaro Sway was inability to override a keybind, $mod+d or $mod+s, for example. I use W\A\S\D for focusing on windows (sorry, but really got used to this Doom-like style :D ), and doing `bindsym $mod+$down focus down` in ~/.config/sway/config.d/00-user.conf, for example, raises a warning. Override works, but the warning appears every time I launch\reload sway, which is a bit infuriating. One of the things that can be done is to move the binds from normal mode to dotfiles folder, so users could change binds themselves, but if there are any reasons against that, or if there's a better solution, it will be very useful for me, because this solution is definitely less than ideal.

**Comment by boredland** [comment]
Yeah, I'd be fine with moving the key bindings into `.config`.

**Comment by Mathew-D** [comment]
Instead of having to move all the bindings you can remove the binding with that you didn't like:
unbindsym $mod+$down

Then rebind it to the setup you want.

**Comment by boredland** [comment]
I honestly did not know of `unbindsym`. Perhaps that's another hint for our Readme?

**Comment by FallenChromium** [comment]
Woah, this is interesting, I didn't know it's possible 🤣 . I will try and report it soon.

Well, there's one more thing to consider about binds: I suggest doing bindsym --to-code rather than bindsym, this way binds will work no matter which layout you use. Right now when I use other keyboard layout which doesn't have latin symbols, I can't control Sway

**Comment by FallenChromium** [comment]
It does work like a charm, thanks @Mathew-D! Before closing this issue I will just post a reference so that anyone who's searching for it could find an example. My current `~/.config/sway/config.d/00-user.conf` looks like this:
```
##These unbinds are requirered because I overwritten up\left\right\right to WASD
#Unbind stacking
unbindsym $mod+s
#unbind menu
unbindsym $mod+d
#unbind tabs
unbindsym $mod+w
#unbind focus parent
unbindsym $mod+a

#bind fot tab mode
bindsym $mod+t layout tabbed

#bind for menu
bindsym Mod1+space exec $menu

#Binds to focus windows with WASD
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right
bindsym $mod+$left focus left

```
