### ISSUE TITLE
Upgrading theming support

### ISSUE THREAD

**Issue by FallenChromium** [Manjaro-Sway/manjaro-sway#99]
As @boredland recently mentioned, it's becoming hard to maintain /usr/share/sway/themes scripts and color themes as Manjaro Sway evolves and apps used are changing. A possible solution to that problem is to use a theme manager\generator that changes config files on-the-fly, it will be described below. 

It's not the only solution, so we can as well discuss a static theming approach with one source of truth on colors(. Xresources, .Xdefaults, sway variables for colors, etc.) to set up everything else, it's actually preferable, but I doubt we can easily do this. Suggestions and discussions are welcome.

The most mainstream solutions are [`pywal`](https://github.com/dylanaraps/pywal) and [`wpgtk`](https://github.com/deviantfero/wpgtk) (which also uses pywal under the hood). wpgtk is a GUI-first utility and pywal is a CLI application. Both provide default templates for the most popular applications and allow the use of custom templates. They will enable the user to customize appearance of the whole OS easily and consistently, it is a very neat feature to have (for example, it may enable us to create a shortcut to switch between light and dark themes on-the-go), but of course, there are caveats.

Let me describe the tools briefly first: Both tools take a wallpaper picture as an input, generate a color scheme based on it and confugure the rest of the system to be consistent with it. Changing color schemes without changing wallpapers is supported.  Pywal is officially available in Arch (and thus Manjaro) repos as `python-pywal`. It generates  a fair amount of theme settings for different apps such as `kitty`, `sway`, `rofi`, `waybar` and `vim`, also it generates escape sequences to dynamically theme any shell, even tty. It allows making custom templates, the caveat being everything is generated to the `~/.cache/wal`, which is neat because it's non-intrusive, but useless for apps which do not have import/include directives in their configuration.

The main reason why I have even mention wpgtk here is, as its' name may have already suggested, it generates a GTK theme and in general allows dynamic GTK theming. In addition to that, it also allows creating custom templates the same way as pywal does, but wpgtk uses symlinks to deliver configs to any directory, which is a solution for any app which doesn't support includes, though I don't know yet how symlinks are supposed to work within /etc/skel. and what will happen if wpgtk will be deleted. Overall I'd like to use pywal only, but it looks like wpgtk significantly eases GTK configuration and allows to control pywal via GUI, which can be nice for beginners. 

Now to the implementation problems
1. Again, as @boredland said, it should totally be either an opt-out or opt-in experience. That creates following challenges:
1.1 We have to either make a config file architecture to tolerate deletion of pywal \ wpgtk, so user will be left with a working config with the default matcha-green color palette...
1.2 ...or to create includes in such a way that it'll be an opt-in experience (as it is with qutebrowser, for example). Both of these ways will result in a big PR with significant efforts, so if I will actually start this after discussion, I'd be happy if anyone would elaborate and help me.

For now, the safest solution I see for this problem is to maintain fully static configuration in `/usr/share/sway/themes/matcha-green` and define startup commands for all apps in the definitions file to use configs from that directory. Next to it, we can create `wal` directory, which will contain a definitions file for sway that instructs apps to use configs which include theme data from `~/.cache/wal`
If you have any thoughts on this, I would love to hear it. It is very hard for me to get full understanding of these changes, it will be good if we will construct the full picture together :)

**Comment by FallenChromium** [comment]
For now, we have this list of apps installed that should be themed, in braces I will indicate how can we achieve that (apart from dynamically sed-ing these on launch or symlinking (including custom templates in wpgtk), which are valid, but since we're using a theme manager it's probably better to use their capabilities)

- [ ] gtk (wpgtk + FlatColor theme)
- [ ] kvantum (have no idea for now)
- [ ] sway (has include directive, pywal-generated template with colors)
- [ ] waybar (has include directive, config can be declared at launch time, pywal-generated .css with colors)
- [ ] rofi (has include directive, config can be declared at launch time, pywal-generated .rasi with full theme properties)
- [ ] foot (has include directive, so custom pywal template can be used. Shells can also be themed dynamically (by cat-ing escape sequences from ~/.cache/wal, but for now it's undesirable because I don't know how to not use this file if wal folder exists but default theme is chosen)
- [ ] mako (config can be declared at launch time, also can be fully configured by arguments, so either pywal custom template or sway variables can be used)
- [ ] wob (isn't themed now, it's a script, so cat can be conditionally used (if file exists) to get color value from ~/.cache/wal)
These will be nice-to-haves:

- [ ] firefox (actually uses GTK theme by default, so probably no need to)
- [ ] neovim (pywal-generated vimscript with colors can be used, but probably unnecessary, termguicolors are used by default in neovim)
- [ ] zathura ([Zathura-Pywal](https://github.com/GideonWolfe/Zathura-Pywal) as a pywal plugin)
- [ ] telegram ([telegram-palette-gen](https://github.com/agnipau/telegram-palette-gen) as a pywal plugin)

One workaround on these difficulties on supporting both static and dynamic theming can be to use just wal, with match-green color scheme by default, but then pywal becomes a hard dependendy 🤷🏻‍♂️ . It's up to you to decide then.

**Comment by Mathew-D** [comment]
Right now I use sed to change the colors that mako uses each time sway configs loaded.  All it does is replace some key worlds in your mako config file with colors declared in the theme files. If wpgtk gives uses the colors somewhere the same sed commands can be used to replace them in mako config.

**Comment by boredland** [comment]
This all sounds pretty amazing! I think we could even implement it incrementally, one theme-able application after the other.

**Comment by FallenChromium** [comment]
Things to discuss then:
0. The list of apps. This also includes merging PRs to change apps (right now I am able to do a PR with lbonn's rofi fork to replace wofi, but it's an open discussion right now so I'm not sure if it will get approved. Also foot PR depends on the launcher PR)
1. Which dotfiles structure we pursue (main settings at skel, main settings at /etc or /usr or definable by sway variables)
2. Which ways of theming are more preferable than others. Currently we can: 
2.1. use CLI flags to theme apps (we can use sway env then, but what if the user wants to redefine colors for exactly one app?)
2.2 load configs at launch time (we have to have matcha-green, wal and maybe a "custom" folders for configs then to either use matcha-green colors, include pywal config or to use config from ~/.config)
2.3 include theme config from the main config (blends with the above, I suppose)
2.4 use templating (wpgtk or sed). Overrides files and in case of wpgtk uses symlinks. Is a bit dangerous, but flexible.

The main criteria to choose architecture are those: easy to maintain for us, easy to change to their liking for users. For me it sounds like using pywal's includes and ~/.config includes is the best thing we can do, and for apps which do not support config includes it's probably easier to use CLI flags, let me know what do you think.

**Comment by Mathew-D** [comment]
I tried wpgtk with rofi template but it seems to be out of date and rofi config has changed.

**Comment by Mathew-D** [comment]
For mako it would be very easy to use the sway variables and sed to update the mako.conf file on start.

**Comment by FallenChromium** [comment]
Yes, wpgtk template is very old, but pywal's (wpgtk uses pywal anyway) include template in ~/.cache/pywal is recent and working perfectly

As for mako, yes, it would be easy to do so, but it looks like we can also just use sway variables in the exec for mako to set it up without a config at all

**Comment by Mathew-D** [comment]
If we do that they people can't change any of mako's settings.  For example I change the timeout and the width in the config file.

**Comment by Mathew-D** [comment]
Unless we make variables for those options in /etc/sway/definitions which can be overwrite by ~/.config/sway/definitions so people can still change the looks.

**Comment by FallenChromium** [comment]
Hmm... That's a valid point. But, I mean, mako config sed-ing is made somewhere in the /etc/sway/config.d directory, so it's problematic to disable that. What if I want to change the appearance itself? Besides, as far as I understand, mako's CLi flags have higher priority than config file, but config file isn't discarded, all the other values are read from it anyway

**Comment by FallenChromium** [comment]
I've just tested it and yes, CLI flags are only overriding the flags mentioned in the CLI, not the whole config. So, for example, when I run mako --border-radius 7, all the other options from ~/.config/mako/config are in effect. Which means that we can use sway colors from the command line, leave the config file where it is, and if the user decides to use only the config \ use other colors from the CLI flags, user can do it by only overriding, say, $notification_daemon variable if we'll do this

**Comment by Mathew-D** [comment]
That sounds like a great idea. It gives us the best of both worlds.

**Comment by Mathew-D** [comment]
So that does:

- mako -> cli and config file
- sway -> vars in ~./cache/wal
- foot ->auto done when you hit set in wpgkt
- rofi -> the dark / light in ~/.cahce/wal right was what we wanted right?
- waybar -> colors-waybar.css in ~/.cahce/wal 
- wob -> I can't find where it starts but in  wob.sh import sway vars and change the line a bit

Did I miss anything?

**Comment by Mathew-D** [comment]
For rofi what I think we need is:  ln -s ~/.cache/wal ~/.config/rofi 
Then on the $menu just add -theme colors-rofi-dark or colors-rofi-light.rasi
Rofi reads all the themes from ~/.config/rofi so with the link we don't have to do anything to else to it as long as we make a default theme.

**Comment by FallenChromium** [comment]
>     * foot ->auto done when you hit set in wpgkt doesn't it? as I know my gnome-terminal was.
Not precisely. wpgtk (actually pywal beneath pygtk) broadcasts escape sequences to ttys, to change colors of all terminals, but that will work in new terminal windows only if in .zshrc we will add these escape sequences `$(cat ~/.cache/wal/sequences)` It is a solution, but it's less than ideal, because if the user will delete python-pywal, then user also has to delete that line from .zshrc, and we didn't decide yet if we will make a static matcha-green and make it default, or we will do it with wal. Theming foot may be a better solution than using escape sequences for shell, because it's easier to understand and reconfigure by non-savvy users (after all, theming probably IS targeted to these kind of users)



>     * I can't find where it starts but in  wob.sh import sway vars and change the line a bit
Yep, that was my intention too.



> Did I miss anything?

Kvantum. I don't know if there's actually a need in Kvantum at all (is that a Qt theme engine?), but it is included into all Manjaro flavors. I don't know the format of Kvantum themes and what they are used for, so I would like to know more about it

**Comment by FallenChromium** [comment]
Though you know what, both options are fine, actually. Especially if the user decides to use 3rd-party terminal and wal theme, it makes sense to make zsh use these escape sequences by default

**Comment by FallenChromium** [comment]
>  ln -s ~/.cache/wal ~/.config/rofi
There is no need, actually. You can pass a path to the theme, not only a name. 
A little over-engineered architecture of configs would look like this: we will have a default config for rofi somewhere at /usr/share/sway. In the theme definitions file `/usr/share/sway/themes/(matcha-green|wal)` $menu will be redefined to use a theme from either ~/.cache/wal or /usr/share/sway/themes/matcha-green
